### ISSUE TITLE
kitchen login should create image if it hasn't been

### ISSUE THREAD

**Issue by drrk** [test-kitchen/test-kitchen#1005]
Currently if you run kitchen login on an uncreated machine you get the following error:

> > > > > > ------Exception-------
> > > > > > Class: Kitchen::UserError
> > > > > > ## Message: Instance <default-ubuntu-1404> has not yet been created
> > > > > > 
> > > > > > Please see .kitchen/logs/kitchen.log for more details
> > > > > > Also try running `kitchen diagnose --all` for configuration

It should instead follow the principle of least surprise and do what kitchen converge or kitchen verify do and create the machine.

**Comment by cheeseplus** [comment]
This seems reasonable given existing behaviour
