### ISSUE TITLE
AWS Windows AMI adjustment needs a graceful error

### ISSUE THREAD

**Issue by Kgirthofer** [test-kitchen/test-kitchen#1021]
## Description

When launching an windows AMI through test-kitchen, if AWS rotates the ami you get a very non-descriptive error message. 
"Message: Failed to complete #create action: [undefined method `[]' for nil:NilClass]"

## Kitchen Version

```ruby
Test Kitchen version 1.7.2
```

## ChefDK Version

```ruby
Chef Development Kit Version: 0.13.18
chef-client version: 12.9.36
berks version: 4.3.2
kitchen version: 1.7.2
```

## Ruby Version

```ruby
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```

## Platform Version

Ubuntu 14.04

## Replication Case

Add an old Windows AMI in the ec2 drvier of .kitchen.yml in image_id: (example ami-3586ac5f) then run chef exec kitchen converge

## Kitchen Output

```ruby
https://gist.github.com/Kgirthofer/a89b91e9721703bdd7f325e65cdb92fd
```

**Comment by cheeseplus** [comment]
This issue needs to go under the EC2 driver - https://github.com/test-kitchen/kitchen-ec2

Could you close this one and open there? That is where any and all EC2 related bits live and where this would be addressed.

**Comment by Kgirthofer** [comment]
Moved - thanks
