### ISSUE TITLE
Test Kitchen now uses local profile and gives no option to use berks

### ISSUE THREAD

**Issue by mhedgpeth** [test-kitchen/test-kitchen#1036]
## Description

When I run kitchen with the chef_zero provisioner it will try to read a local policyfile, even when I want to use the berksfile for kitchen. We use berksfile for kitchen to use local resources and want to test it that way.
## Kitchen Version

1.8
## ChefDK Version

0.14.25
## Platform Version

Windows 7
## Replication Case

Run test kitchen from a cookbook where there is a berksfile and policyfile. Before 1.8 it would use the berksfile. After 1.8 it uses the policyfile and doesn't allow you to switch back.
## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

Output: https://gist.github.com/mhedgpeth/188190d5d02bd70084cb0cb643e2824a
## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

Diagnose Gist: https://gist.github.com/mhedgpeth/7ed5a01ad744f9e4d54cf3db1d2c6f8f
## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by cheeseplus** [comment]
Is this still an issue? I see we had 3 related PRs, one of which is still open but this may have been fixed.

**Comment by cheeseplus** [comment]
Closing due to lack of response, please re-open if this is still an issue.

**Comment by mhedgpeth** [comment]
Sorry this went through the cracks. Thanks for closing it; it's not an issue for us anymore.
