### ISSUE TITLE
kitchen test -c will always return 0, even when failing

### ISSUE THREAD

**Issue by billietl** [test-kitchen/test-kitchen#1051]
When running ```bash kitchen test -c```, all tests are run but the error code will always be 0, even when some tests are failing.
The problem is continuous integration platforms rely on this error code in order to determine wether the test is successful or not.

**Comment by smurawski** [comment]
@billietl What version of test-kitchen?  Could you supply the log output from a run that should have failed?

**Comment by billietl** [comment]
test-kitchen version 1.8 (I can't run 1.9 because of a scp bug, can't find the related issue).
Concerning the logs, I'll have to truncate because it concerns a private project at work. The interesting part is : 
```
-----> Verifying <run playbook-debian-7-21>...
       [Serverspec] Verify on instance=#<Kitchen::Instance:0x000000017896b8> with state={:port=>32924, :username=>"kitchen", :password=>"kitchen", :ssh_key=>"/home/gitlab-runner/[CENSORED]", :image_id=>"ef824398bdd7", :container_id=>"c1b7beca1d4ad936b8e5ba71986eed562931d84e01af1c4b60d09095c2c9c221", :hostname=>"localhost", :last_action=>"setup"}
       Environment variable KITCHEN_PORT value 32924
       Environment variable KITCHEN_USERNAME value kitchen
       Environment variable KITCHEN_PASSWORD value kitchen
       Environment variable KITCHEN_SSH_KEY value /home/gitlab-runner/[CENSORED]
       Environment variable KITCHEN_IMAGE_ID value ef824398bdd7
       Environment variable KITCHEN_CONTAINER_ID value c1b7beca1d4ad936b8e5ba71986eed562931d84e01af1c4b60d09095c2c9c221
       Environment variable KITCHEN_HOSTNAME value localhost
       Environment variable KITCHEN_LAST_ACTION value setup
       Installing ruby, bundler and serverspec remotely on server
       Running Serverspec
       /usr/local/bin/rspec
       
       [TRUNCATED]
       
       Process "[CENSORED]"
         should be running
         count
           should eq 3 (FAILED - 1)
       
       Failures:
       
         1) Process "[CENSORED]" count should eq 3
            Failure/Error: its(:count) { should eq 3 }
              
              expected: 3
                   got: 2
              
              (compared using ==)
              /bin/sh -c ps\ aux\ \|\ grep\ -w\ --\ [CENSORED]\ \|\ grep\ -v\ grep\ \|\ wc\ -l
              2
       
            # ./spec/generic_spec.rb:25:in `block (2 levels) in <top (required)>'
       
       Finished in 0.26012 seconds (files took 0.78886 seconds to load)
       9 examples, 1 failure
       
       Failed examples:
       
       rspec ./spec/generic_spec.rb:25 # Process "[CENSORED]" count should eq 3
```
A serverspec test for this build fails and the tests goes on (as expected), but the error code returned is 0 (which is not expected), so gitlab marks the build as passed. I ran the build on my workstation. It fails on the same serverspec test and the error code is also 0, so I guess the problem doesn't come from gitlab.

**Comment by smurawski** [comment]
On the plus side, we should have a release out that fixes the scp bug today.  

When you try to replicate locally, does kitchen verify exit with a non-zero error code?

**Comment by billietl** [comment]
```kitchen verify -c``` returns 20 after finishing all the tests. Looks like it's specific to the "test" subcommand. Just after that I ran ```kitchen test -c``` and it returned 20. That is pretty strange :/
I'll investigate further on why kitchen test returned 0 then and 20 now...

**Comment by smurawski** [comment]
@billietl Cool.. If you have a consistent repro, please provide a gist of the output of `kitchen diagnose --all` from project that consistently fails.  If it's intermittent, I'd like to hear that as well, just makes it harder to replicate.

**Comment by billietl** [comment]
Of course ! So far, my guess is that kitchen verify/test will return 0 if suite invocation succeeded and at least 1 suite succeeded. I'll try to pin it down as soon as i can.

**Comment by billietl** [comment]
Comming back with some fresh news : I really can't reproduce the issue on my workstation (I created a project here to do some tests : https://github.com/billietl/kitchen_sample) but the builds on gitlab-ci keeps being problematic, so I guess the problem did not come from test-kitchen.

**Comment by smurawski** [comment]
@billietl Thanks for the update.  If you find anything kitchen related, please open another issue.
