### ISSUE TITLE
Add documentation for elevated transport

### ISSUE THREAD

**Issue by vinyar** [test-kitchen/test-kitchen#1054]
## Description

A new feature for transport has been introduced and shipped, however it lacks any documentation.
https://github.com/test-kitchen/test-kitchen/pull/1012#issuecomment-216685606

```
transport:
  name: winrm
  elevated: true
```
## Kitchen Version

TK 1.9.1
## Expected outcome

The feature is documented (ideally as part of shipping criteria) and easily accessible via search/

**Comment by cheeseplus** [comment]
Re-opening and unlocking this one now that docs are merged into the same repo.

**Comment by cheeseplus** [comment]
Oops, looks like we did close this one in https://github.com/test-kitchen/kitchen-docs/pull/75
