### ISSUE TITLE
Docs on https://docs.chef.io/ have not been kept up to date

### ISSUE THREAD

**Issue by drrk** [test-kitchen/test-kitchen#1060]
Specifically https://docs.chef.io/config_yml_kitchen.html#chef-client-settings is not up to date for the log_level changes.

**Comment by SolverDude** [comment]
I'm trying to get a report handler to work in test-kitchen, and followed the doc mentioned here, and it doesn't work.  @drrk could you elaborate on what you've found to CHANGE?  You reference log_level, but I'm hoping it might help me, before I have to dig into test-kitchen code and lose an hour of my life finding out why it isn't working as advertised.

**Comment by jjasghar** [comment]
@SolverDude yeah the harsh reality with all  software project is that the docs always lags behind the project. Chef open sources all our docs, if you are willing to help we'd love contribs! 

https://github.com/chef/chef-web-docs

/cc @davidwrede

**Comment by cheeseplus** [comment]
Looks like this one got taken care of on the docs side, closing.
