### ISSUE TITLE
Reboot resource with new 'reboot and try again' feature

### ISSUE THREAD

**Issue by jonathanmorley** [test-kitchen/test-kitchen#1062]
## Description

I have a reboot resource in my chef cookbook, and when it gets executed, the chef-client does reboot the box, but I don't get any notification of an exit code, such that I can use it to restart the converge (as per #1055).

## Kitchen Version

1.10.0

## Kitchen Output

```ruby
         * reboot[reboot for .NET] action reboot_now


           Running handlers:
           Running handlers complete
           Chef Client finished, 7/9 resources updated in 01 minutes 33 seconds
       [2016-06-20T06:45:15-07:00] WARN: Rebooting server at a recipe's request. Details: {:delay_mins=>0, :reason=>".NET installation", :timestamp=>2016-06-20 06:45:14 -0700, :requested_by=>"reboot for .NET"}
$$$$$$ C:/opscode/chef/embedded/lib/ruby/2.1.0/x64-mingw32/dl.so: warning: already initialized constant DL::RUBY_FREE
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/authentication/pageant.rb:16: warning: previous definition of RUBY_FREE was here
$$$$$$ DL is deprecated, please use Fiddle
D      Cleaning up local sandbox in /var/folders/xq/krg4l8qj2t9gcw48k255vrndpyb1wk/T/policyfile-windows-7-sandbox-20160620-53096-jxciu1
       Finished converging <policyfile-windows-7> (3m1.00s).
-----> Kitchen is finished. (4m51.46s)
D      [WinRM] closing remote shell FEEE352C-AA32-451F-9CF1-84EFBFB0B651 on http://127.0.0.1:5985/wsman
D      [WinRM] remote shell FEEE352C-AA32-451F-9CF1-84EFBFB0B651 closed
```

**Comment by smurawski** [comment]
@jonathanmorley Is the node being tested using Chef 12.11 or newer?  And do you have `exit_status :enabled` in the client.rb on the node being tested?

**Comment by jonathanmorley** [comment]
I am running against Chef 12.11.18, but did not have exit_status :enabled in the client.rb.

Adding this in made kitchen exit with an exit code of 20, and even adding '20' to a list of exit codes to restart on, does not cause kitchen to restart

**Comment by smurawski** [comment]
@jonathanmorley kitchen would exit with '20' if a run failed and it wasn't retryable.  Can you share your `kitchen diagnose` and the output of the run? (perhaps in a gist?)

**Comment by jonathanmorley** [comment]
https://gist.github.com/jonathanmorley/4a95a30626825cb2002796a73bf43bdc

**Comment by smurawski** [comment]
@jonathanmorley  - you'll need to add `retry_on_exit_code` to the provisioner configuration block.

```
provisioner:
  retry_on_exit_code: 
    - 35
```

It shows an empty array currently.
https://gist.github.com/jonathanmorley/4a95a30626825cb2002796a73bf43bdc#file-kitchen_diagnose-L74

**Comment by jonathanmorley** [comment]
Yes, I had added that with an entry of 20. I was wanting to use the output of the kitchen converge command to determine what number to use there, I see that the exit codes are available in https://github.com/chef/chef-rfc/blob/master/rfc062-exit-status.md though.

I added that block and the output didn't change much, updated the gist above.

**Comment by smurawski** [comment]
@jonathanmorley the underlying error did change - could you add the kitchen log (`.kitchen/logs/kitchen.log `) to the gist?

**Comment by smurawski** [comment]
@jonathanmorley Thanks for helping troubleshoot this by the way.

**Comment by jonathanmorley** [comment]
that file is empty

```# jmorley at hqjmorley901 in ~/Code/cvent/workup on git:update-chefdk ✖︎ [16:27:46]
→ cat .kitchen/logs/kitchen.log

# jmorley at hqjmorley901 in ~/Code/cvent/workup on git:update-chefdk ✖︎ [16:51:14]```

**Comment by smurawski** [comment]
That's odd.  There's two things that I can think of that may be happening - one, something in the policyfile provisioner attempts to upload something after the run (which https://github.com/test-kitchen/test-kitchen/pull/1064 will fix) or there isn't enough of a wait and kitchen tries to run the next command too soon (before the node reboots).

The latter is easy to test - you can increase the 'wait_for_retry` setting on the provisioner to 45 or 60 (it's in seconds and defaults to 30).

**Comment by jonathanmorley** [comment]
C:\Users\vagrant\Local\Temp\kitchen\cache\chef-stacktrace.out shows a trace starting with

```
Chef::Exceptions::Reboot: Rebooting server at a recipe's request. Details: {:delay_mins => 0, :reason => "Reboot by Chef", ...
```

Trying increasing that now

**Comment by jonathanmorley** [comment]
Increased the wait_for_retry to 60, and I noticed that the restart does take a while because of Windows Update; kitchen waited until just after the reboot finished to error out, so I am increasing the wait to 100, to make sure that it isnt _just_ missing the window it needs.

.kitchen/logs/kitchen.log is now full of logs (probably was empty above because I had run kitchen diagnose?) I am updating the gist with this log information now

**Comment by jonathanmorley** [comment]
Same error with wait_for_retry = 100.

**Comment by smurawski** [comment]
@jonathanmorley trying to repro now.  Thanks!

**Comment by smurawski** [comment]
@jonathanmorley I can replicate it.  Will debug it tonight and try to get a fix out soon.  I think that winrm-elevated isn't returning the proper exit code or isn't responding nicely to the session close.

**Comment by jonathanmorley** [comment]
I just isolated it to winrm-elevated too

**Comment by mwrock** [comment]
yup thats it. We just had a similar issue with file uploads and needed to make the same fix for the elevated runner. That is now added to [this PR](https://github.com/test-kitchen/test-kitchen/pull/1064). 

You could quickly validate that this fixes you by editing `/Users/jmorley/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb`. It should be about line 92 just inside the `close` method and change the ensure block to look like this:
```
        ensure
          @file_transporter = nil
          @session = nil
          @elevated_runner = nil
        end
```
