### ISSUE TITLE
Release 1.10.1 contains Windows newline characters

### ISSUE THREAD

**Issue by RoboticCheese** [test-kitchen/test-kitchen#1066]
## Description

Was seeing some assorted new errors (see below) after updating to 1.10.1.

After some poking around, the 1.10.1 release seems to have included a change to Windows newlines in many (all?) of the source files. I guess Ruby is smart enough to figure this out, but it causes the shellouts to steps like installing Busser to fail in unusual ways.

The new newlines aren't present when pulling TK from GitHub instead of RubyGems, nor are they present in 1.10.0, so I'm guessing something happened during the most recent gem build/push.

```
$ grep -R "\r" test-kitchen-1.10.0 | wc -l
       0

$ grep -R "\r" test-kitchen-1.10.1 | wc -l
   35417
```

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.10.1
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

## Platform Version

Mac OS X El Capitan 10.11.6 Beta (15G19a)

## Replication Case

Install TK 1.10.1 from Rubygems and do a `kitchen verify` for any cookbook with a set of tests. Or do `:verbose setl ff?` in Vim and it'll show `fileformat=dos`.

## Kitchen Output

```
I, [2016-06-23T14:49:50.896432 #60251]  INFO -- default-ubuntu-1604: sh: 13: cannot create /dev/null^M: Permission denied`
```

```
>>>>>>     Failed to complete #converge action: [scp: /tmp/kitchen: Not a directory
```

Note:
```
$ ls -la /tmp/

-rw-r--r--  1 vagrant vagrant   637 Jun 23 21:32 kitchen
drwxrwxr-x  2 vagrant vagrant  4096 Jun 23 21:31 kitchen?
```

**Comment by coderanger** [comment]
I am also seeing this. To show data directly from the gem downloads:

```
$ file ~/Downloads/test-kitchen-1.10.1/data/support/busser_install_command.sh
/Users/coderanger/Downloads/test-kitchen-1.10.1/data/support/busser_install_command.sh: ASCII text, with CRLF line terminators
$ file ~/Downloads/test-kitchen-1.10.0/data/support/busser_install_command.sh
/Users/coderanger/Downloads/test-kitchen-1.10.0/data/support/busser_install_command.sh: ASCII text
```

**Comment by mwrock** [comment]
diving in to look. may need to push a 1.10.2

**Comment by coderanger** [comment]
Thanky :) I'm not sure 1.10.1 is functional on any Linux platforms currently and pre-release testing wouldn't catch this because git usually fixes line endings. We should add to the release checklist to not push the gem from a windows machine probably :)

**Comment by mwrock** [comment]
ok 1.10.2 released. Thanks for reporting!!
