### ISSUE TITLE
Run chef-solo in legacy mode for chef_solo provisioner under Chef 12.11+

### ISSUE THREAD

**Issue by SaltwaterC** [test-kitchen/test-kitchen#1070]
## Description

Starting with Chef 12.11.x chef_solo provisioner essentially runs in chef_zero mode. To enable the previous behaviour, one needs to pass --legacy-mode argument to the chef-solo command. This argument is backwards incompatible i.e can't be baked into chef_solo provisioner and expect old Chef versions to work.

We would be using chef-client in local mode (aka chef_zero provisioner), but as you can see below, the performance of the local mode is rubbish.

I'd send a pull request, but I don't know which solution you'd accept out of these three:

 * do version detection and pass --legacy-mode for Chef 12.11+
 * legacy_mode config for the chef_solo provisioner
 * add the possibility to pass arbitrary arguments to the chef-solo command via a config option

## Kitchen Version

```ruby
Test Kitchen version 1.10.0
```

## ChefDK Version

```ruby
Chef Development Kit Version: 0.15.15
chef-client version: 12.11.18
delivery version: 0.0.23 (bf89a6b776b55b89a46bbd57fcaa615c143a09a0)
berks version: 4.3.5
kitchen version: 1.10.0
```

## Replication Case

```ruby
provisioner:
  name: chef_solo
```

## Kitchen Output

```ruby
# chef_solo with default local mode behaviour with Chef 12.11.18
Chef Client finished, 9/345 resources updated in 01 minutes 14 seconds
Finished converging <default-centos-68> (1m31.17s).
-----> Kitchen is finished. (1m31.70s)
```

```ruby
# chef_solo convinced to use --legacy-mode by injecting the argument
# with log_file: '/dev/null --legacy-mode' in kitchen.yml
Chef Client finished, 9/345 resources updated in 28 seconds
Finished converging <default-centos-68> (0m43.60s).
-----> Kitchen is finished. (0m43.95s)
```

**Comment by mwrock** [comment]
If you wanted to send a PR, I personally like option 2 the most and think its a reasonable approach.

**Comment by SaltwaterC** [comment]
Please review. Thank you.

**Comment by cheeseplus** [comment]
Closing as it's been merged.

**Comment by lamont-granquist** [comment]
reopening because this is a bit problematic.

does the chef-solo provisioner on chef >= 12.11 where chef-solo invokes chef-zero actually work at all without either having legacy mode passed to chef-solo or switching to use the proper chef-zero provisioner in TK?  because that prompts the question of what the different codepaths are doing in the chef-zero provisioner vs the chef-solo one...

**Comment by lamont-granquist** [comment]
option #1 (version detection and adding the legacy flag automatically to chef >= 12.11) would probably have been the more correct way to fix this

**Comment by lamont-granquist** [comment]
unless all the extra code in the chef_zero provisioner is unnecessary in which case someone should clean it up by deleting that code and just inheriting from the chef-solo one and overriding only the command line to invoke chef-zero...

**Comment by lamont-granquist** [comment]
although for chef-13 we need to delete the chef-solo legacy mode code in core, and that implies removing this functionality from TK as well -- which most likely means literally aliasing chef-solo to chef-zero.  we'd need a deprecation warning in there, which is what i came to try to add, but i'm not sure what it should be now.

**Comment by thommay** [comment]
Yes, the chef-solo provisioner works properly - after all, that's exactly the behaviour we expect to have from chef-solo in zero mode.

**Comment by SaltwaterC** [comment]
> does the chef-solo provisioner on chef >= 12.11 where chef-solo invokes chef-zero actually work at all

It works in zero mode, but with the significant overhead of launching the local server. As stated in OP, the reason behind having legacy mode enabled in TK is performance. Hopefully this will be addressed in future Chef releases.

The zero mode of chef-solo used to be affected by a ChefFS issue (see chef/chef#5051), but TK generates a solo.rb file that overrides the defaults. TK wasn't affected.

**Comment by thommay** [comment]
We've shipped a bunch of fixes to the performance of chef-zero, so hopefully that's no longer an issue.

**Comment by SaltwaterC** [comment]
I see that with latest ChefDK / Chef 12.13.37 is bit better:

```
Chef Client finished, 126/2360 resources updated in 25 seconds

Finished converging <default-centos-72> (0m27.29s). (chef-solo --legacy-mode)
Finished converging <default-centos-72> (0m48.55s). (chef-solo)
```

It still has some 20 odd seconds of overhead compared to pure serverless mode.

**Comment by lamont-granquist** [comment]
nevermind @thommay cleared it up for me this morning....
