### ISSUE TITLE
test_base_path is weird

### ISSUE THREAD

**Issue by tyler-ball** [test-kitchen/test-kitchen#1077]
## Description

In `kitchen-inspec` we are trying to change the `test_base_path` from `test/integration` to `test/recipes` (see [this](https://github.com/chef/chef-dk/pull/934#issuecomment-232551108) for reasons why). It turns out this config value (as well as a few others like, `log_level`) are read in off the command line or defaulted long before the driver/provisioner/verifier gets created. They are also ignored when trying to be set in the `.kitchen.yml`.

I propose the following acceptance criteria for fixing this:
1. If specifying `test_base_path` via the CLI, that takes highest precedence
2. If it is not specified on the CLI but is specified in the `.kitchen.yml` then that takes second highest precedence
3. If it is not specified in either of those places it should default to the current location
4. We should not be populating this config into the `provisioner`, `transport` or `driver` configs. It should only be populated into the `verifier` config. See the [data_munger](https://github.com/test-kitchen/test-kitchen/blob/85474866a2d0f8d9c6a6602b94aac6dc5d0ac268/lib/kitchen/data_munger.rb#L62)

What do people think of these AC?

\cc @tylercloke @test-kitchen/maintainers

**Comment by tyler-ball** [comment]
If the community thinks this is a good idea, there is some cleanup work to do:

1. Update the ChefDK generator to add `test_base_path` to the `.kitchen.yml`
2. Remove the `finalize_config!` method added to `kitchen-inspec`

**Comment by mwrock** [comment]
:+1:

**Comment by tylercloke** [comment]
👍

**Comment by drrk** [comment]
👍 The data_munger is quite complex and make setting options less intuitive than you might like in some cases.  So we might want to look into the config stuff in more general, but this seems a good start.

**Comment by 4-20ma** [comment]
Also reported via #377.

**Comment by chris-rock** [comment]
Is there any reason why we require `test_base_path` at all? Why not just share the root path with the verifier and all verifier implementations can decide on their own. That would require:

**all options are defined as part of the verifier yaml part**
```
suites:
  - name: default
    verifier:
      options:
        root: 'recipes'
```

**pass cli options to verifier**

we could just use a prefix eg. `--verifier-root recipes` would end up in a hash object as part of the options.

**Comment by cheeseplus** [comment]
I am in agreement with this thread generally and specifically with @chris-rock suggestion if we can achieve with minimal caveats (I presume there is potential with that one we may break back compat) then let's do it.

**Comment by coderanger** [comment]
-1 on changing the test base overall. If you want to make some special mode for Automate that's up to you all but consistency with other Test Kitchen stuff should stay the default.

**Comment by cheeseplus** [comment]
Given the command line option added and change up product directions, closing this one since this doesn't seem critical any longer.
