### ISSUE TITLE
SSH Transport: Bastion proxy results in broken pipe error

### ISSUE THREAD

**Issue by yoshiwaan** [test-kitchen/test-kitchen#1079]
## Description

When using a bastion as TCP forwarding proxy for SSH the error returned when a machine is just booting and is listening on port 22 but not responding correctly from the bastion is a broken pipe.

This happens reliably when spooling up EC2 instances. When the kitchen run verifies that the node has transitioned to a ready state it starts to check for SSH availability. From what I can tell the bastion host will accept the connection on port 22 and forward to the spooling instance, which may be listening on port 22. The remote host seems to close the connection to the bastion as it's not ready and the bastion returns a broken pipe to the client.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.10.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 0.15.15
chef-client version: 12.11.18
delivery version: 0.0.23 (bf89a6b776b55b89a46bbd57fcaa615c143a09a0)
berks version: 4.3.5
kitchen version: 1.10.0
```

## Platform Version

Linux slave 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

## Replication Case

* Use ssh as the transport option
* Use the kitchen-ec2 driver and set it to create an ec2 instance in a VPC without public accessiblity
* Set up a bastion box it with access to the subnet you will deploy your test ec2 instance into
* Set up your ~/.ssh/config to route through the bastion box for the subnet that you will deploy your test ec2 instance into, with a command like:
```
Host <cidr of private subnet, e.g. 10.1.1.*>
StrictHostKeyChecking no
UserKnownHostsFile /dev/null
ProxyCommand ssh -W %h:%p <bastion user>@<bastion ip>
```
* You may need to set up another entry in your ssh config file to gain access to the bastion host itself, such as something like
```
Host <bastion ip>
        IdentityFile ~/.ssh/<private key for bastion>
        User <ssh user for bastion>
```

## Kitchen Output

```ruby
yoshiwaan@slave:~/code/pulse-aem-env$ KITCHEN_YAML=.kitchen_jenkins.yml kitchen test author
<truncated>
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

       Instance <i-d1f00745> requested.
       Polling AWS for existence, attempt 0...
       Attempting to tag the instance, 0 retries
       EC2 instance <i-d1f00745> created.
       Waited 0/300s for instance <i-d1f00745> to become ready.
       Waited 5/300s for instance <i-d1f00745> to become ready.
       Waited 10/300s for instance <i-d1f00745> to become ready.
       Waited 15/300s for instance <i-d1f00745> to become ready.
       Waited 20/300s for instance <i-d1f00745> to become ready.
       EC2 instance <i-d1f00745> ready.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Broken pipe] on author-ubuntu-1404
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by yoshiwaan** [comment]
PR https://github.com/test-kitchen/test-kitchen/pull/1078

**Comment by cheeseplus** [comment]
Fixing as the above PR is merged.

**Comment by yoshiwaan** [comment]
Thank you. Looking forward to the next release :)
