### ISSUE TITLE
inspec "not found in load path" when used as verifier

### ISSUE THREAD

**Issue by davidcpell** [test-kitchen/test-kitchen#1090]
## Description

I have a cookbook that was generated with `berks` rather than `chef generate cookbook` and would like to use inspec rather than serverspec in my kitchen setup (kitchen was set up with `kitchen init`). However, I'm also having this problem when using `chef generate cookbook` which initializes Kitchen and defaults to inspec as the verifier.

When adding it as the verifier I get an error that it can't be found in the load path despite having it in in my `Gemfile`. 

Error message:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'inspec' verifier from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
```

My `Gemfile`:

```
source 'https://rubygems.org'

gem 'kitchen-vagrant'
gem 'inspec'
gem 'pry'
gem 'test-kitchen'
```

other:

```
➜  cic-zabbix-agent git:(feature_CIC-371) ✗ bundle list inspec
/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-0.28.0
```

## Kitchen Version

```ruby
Test Kitchen version 1.10.2
```

## ChefDK Version

```ruby
Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
delivery version: 0.0.23 (bf89a6b776b55b89a46bbd57fcaa615c143a09a0)
berks version: 4.3.5
kitchen version: 1.10.2
```

Other:

```
➜  cic-zabbix-agent git:(feature_CIC-371) ✗ bundle list inspec
/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-0.28.0
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
```

## Platform Version

Mac OSX 10.11.5

## Replication Case

1. create cookbook with berks
2. `$ kitchen init`
3. Add this to `.kitchen.yml`:

```
verifier:
  name: inspec
```

3. `$ kitchen test default-ubuntu-1404`

OR 

1. `chef generate cookbook <name>`
2. `kitchen list`

## Kitchen Output

https://gist.github.com/davidcpell/da0b0a2637522733f3f2264fee7d0b76

## Kitchen Diagnose

https://gist.github.com/davidcpell/d15d39444f273bf45bbaf2dc2e27c9e3

**Comment by cheeseplus** [comment]
Are you loading kitchen-inspec?

**Comment by mwrock** [comment]
right. Based on your Gemfile, kitchen-inspec would not get loaded. You need to add it.

**Comment by davidcpell** [comment]
Thanks for the replies. I was familiar with having a "kitchen-"-prepended gem for the drivers but not a verifier (i.e. just "serverspec").

Anyway, I've added kitchen-inspec to my `Gemfile` but am still getting the load error:

```
# Gemfile

source 'https://rubygems.org'

gem 'kitchen-vagrant'
gem 'kitchen-inspec'
gem 'pry'
gem 'test-kitchen'
```

```shell
➜  cic-zabbix-agent git:(feature_CIC-371) ✗ kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'inspec' verifier from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Anything else I might be missing? I'm checking out the readme at the GitHub repo that @cheeseplus shared but installation seems pretty standard...

**Comment by mwrock** [comment]
Hmm. Looking again at your initial bug report info, I see you are not using `bundle exec` for your `kitchen` commands so the Gemfile is not used. However, if you have chefdk installed, that shouldn't matter because it comes with kitchen-inspec.

Usually what this means is you have a gem conflict somewhere and nuking ~/.chefdk usually fixes that. Altrnatively, you could also leverage your Gemfile which *should* also work:
```
bundle install
bundle exec kitchen list
```

**Comment by davidcpell** [comment]
update: I switched from Ruby 2.3.1 back to 2.2.2 and everything worked

**Comment by mwrock** [comment]
OH. yes. If you are not using the ruby bundled with chef-dk its "swim at your own risk".

**Comment by davidcpell** [comment]
I also recently found that Berkshelf was having trouble with Ruby >= 2.3.0. Check out this issue:

https://github.com/berkshelf/berkshelf/issues/1513

> I've tracked down the problem here. Berkshelf can't parse config.json using ruby >= 2.3.0 because of a clash involving Hash.dig

No idea if that is relevant but it just popped into my head after getting this to work on 2.2.2.

As to your point, sorry for the totally newb question but do you know how can I ensure I am using the ruby bundled with chef-dk if I manage my rubies with rbenv? It sticks executables in its shims directory. just installed ChefDK and I've just been rolling with `rbenv global 2.3.1`. I don't think I even realized that chef-dk came with its own ruby.

**Comment by mwrock** [comment]
Yes thats one of the main conveniences of chef-dk (at least for those who dont care to manage multiple rubies). You need to run the `shell-init` command to fully leverage the chef-dk path and its ruby:
```
eval "$(chef shell-init bash)"
```

**Comment by davidcpell** [comment]
Thanks @mwrock and @cheeseplus! Sorry for the trouble here. I'll close out the issue. One last thing: I know this is the wrong repo for specific drivers but any chance one of you guys know how I can get some eyes on [this PR](https://github.com/test-kitchen/kitchen-ec2/pull/259) for kitchen-ec2? It's been there for a while so I'm wondering if I should take it as a sign that it's not wanted or just find out how to do the right nudging.
