### ISSUE TITLE
sometimes TK doesn't mount shares

### ISSUE THREAD

**Issue by vinyar** [test-kitchen/test-kitchen#1093]
## Description

I've noticed that sometimes (maybe 5%) on create, TK will not mount share. Vagrant reload or tk destroy;create fixes it
## Kitchen Version

$ chef -v
Chef Development Kit Version: 0.17.5 (dk from current)
chef-client version: 12.12.15
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.10.2
## Platform Version

osx 10.11.4
## Replication Case

Create / destroy boxes, one in a while notice that custom share (not current front, but additional mount) have not been mounted.

**Comment by cheeseplus** [comment]
Closing this one - this is more likely than not Vagrant and the VM tooling itself more so than test-kitchen (or even kitchen-vagrant)
