### ISSUE TITLE
Allow force override of chef attributes

### ISSUE THREAD

**Issue by jorhett** [test-kitchen/test-kitchen#1094]
## Description

Kitchen instances sometimes don't have access to a number of resources a normal node would (provider metadata services, for instance) and thus a lot of environment analysis/setup fails. At the current time this requires the maintainer of the environment analysis code running in production to insert code specific to evaluating test kitchen (bugs in testing code can affect production!) and also prevents more complex testing scenarios (multiple regions, etc)

## Kitchen and ChefDK Version

```ruby
Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
delivery version: master (921828facad8a8bbbd767368bfc72f19bd30e7bd)
berks version: 4.3.5
kitchen version: 1.10.2
```

## Platform Version

MacOS El Capitan

## Replication Case

```
suites:
  - name: default
    run_list:
      - recipe[my_test::default]
    attributes:
      region: 'us-west-1'
```

## Kitchen Output

Results of `node.debug_value('region')`

```ruby
   [["set_unless_enabled?", false],
       ["default", :not_present],
       ["env_default", :not_present],
       ["role_default", :not_present],
       ["force_default", :not_present],
       ["normal", "us-west-1"],
       ["override", :not_present],
       ["role_override", :not_present],
       ["env_override", :not_present],
       ["force_override", :not_present],
       ["automatic", "unknown"]]
```

## Suggestion

Allow force_override attributes in kitchen and use code similar to this so that kitchen can optionally override environment-specific values, and thus avoid the need to put testing-specific code into production. For a limited example, this code would allow for providing an array of kitchen-supplied attributes which "win"...

```
# kitchen-supplied force attributes
force_attributes.each do |attribute_name|
  if node[attribute_name] != node.normal[attribute_name]
   Chef::Log.warn("Overriding attribute #{attribute_name} with value supplied by Test Kitchen")
   node.automatic_attrs[attribute_name] = node.normal[attribute_name]
 end
end
```

**Comment by coderanger** [comment]
Chef does not offer a way to set per node attributes at anything but normal.

**Comment by jorhett** [comment]
My writeup above assumes they are normal level. We're using code similar to the above to do this today. My thought was that generalizing this idea would have widespread value.
