### ISSUE TITLE
More verbose kitchen verify output?

### ISSUE THREAD

**Issue by daxgames** [test-kitchen/test-kitchen#1097]
## Description

Is it possible to get 'inspec exec --format=documentation' output in a kitchen verify run?

When I use inspec with kitchen I get:

````
..
Finished in 0.03486 seconds (files took 0.59776 seconds to load)
2 examples, 0 failures
````

I want to see:

````
inspec exec --format=documentation test/integration/default/inspec --target=ssh://vagrant:vagrant@127.0.0.1:2222

File /app/bin/test.conf
  should exist
  should be file

Finished in 0.02091 seconds (files took 0.73959 seconds to load)
2 examples, 0 failures
````

## Kitchen Version

Test Kitchen version 1.8.0

## ChefDK Version

Chef Development Kit Version: 0.14.25

**Comment by mwrock** [comment]
This is possible with the following in your `.kitchen.yml`:
```
verifier:
  name: inspec
  format: documentation
```

**Comment by daxgames** [comment]
Thanks Matt.
