### ISSUE TITLE
Ability to change tk- prefix to another optionally.

### ISSUE THREAD

**Issue by bartanxas** [test-kitchen/test-kitchen#1101]
## Description

It very important for us to have ability change "tk-" prefix.  It will help us correspond our naming convention.

## ChefDK Version
Chef Development Kit Version: 0.13.21
chef-client version: 12.9.41
berks version: 4.3.2
kitchen version: 1.7.3

```ruby
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]
```

## Platform Version

Centos 6.7

## Replication Case

Create any instance in google cloud and you will see hostname eg. "tk-..."
## Kitchen Output

-----> Creating <activemq-centos-67>...
       Creating GCE instance <tk-activemq-centos-67-369c25> in project ......................, zone ...............
       Zone operation ................................. created. Waiting for it to complete...
       Current status: PENDING
       Current status: RUNNING
       Current status: DONE

**Comment by bartanxas** [comment]
It will be great if default prefix stay like "tk-" and will be changed over some additional attribute in one of sections like:
platforms:
suites:

**Comment by coderanger** [comment]
This would be a function of the driver plugin you are using, not Test Kitchen itself. Probably https://github.com/test-kitchen/kitchen-google but there could be another I'm not aware of.
