### ISSUE TITLE
 [[WinRM::FS::Core::FileTransporter] Upload  failed (exitcode: 1) - In Windows 2012RTM only

### ISSUE THREAD

**Issue by sandeepmendiratta** [test-kitchen/test-kitchen#1106]
## Description

Converge fails with Windows 2012 RTM with following message:
 #converge action: [[WinRM::FS::Core::FileTransporter] Upload
 failed (exitcode: 1)
## Kitchen Version

Test Kitchen version 1.10.0
## ChefDK Version

Chef Development Kit Version: 0.15.16
chef-client version: 12.11.18
delivery version: master (444effdf9c81908795e88157f01cd667a6c43b5f)
berks version: 4.3.5
kitchen version: 1.10.0
## Ruby Version

ruby 2.1.8p440 (2015-12-16 revision 53160) [i386-mingw32]
## Platform Version

Windows 2012 RTM
## Kitchen Diagnose

[w12rtm_fail.txt](https://github.com/test-kitchen/test-kitchen/files/431154/w12rtm_fail.txt)
## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by mwrock** [comment]
@ChrisAWalker and @sandeepmendiratta I'm unable to repro but that may be that my 2012 vm is way behind in patches (as in maybe never been patched). I see that both of you are using the `elevated` transporter and I'm curious if the issue repros if you do not set `elevated` to `true`. In the meantime, I'm patching my 2012 VM and will give it another go when that completes.

**Comment by sandeepmendiratta** [comment]
@mwrock and @ChrisAWalker  After changing transporter elevated to false, I am able to run without errors and able to converge now.

**Comment by ChrisAWalker** [comment]
I reconverged with elevated: false and it appears that things are working.  I'm going to dig further into this to perform additional validation.

Thanks!

**Comment by mwrock** [comment]
Interesting. Still a broken experience in my opinion but good info thanks!

**Comment by ChrisAWalker** [comment]
I've confirmed that it is working properly.  I'd be interested in hearing what your experience is...

**Comment by mwrock** [comment]
So I was never able to reproduce this error even on a patched win 2012. When running elevated I was getting a very strange error about a powershell assrmbly not found from the command that runs the scheduled task. Googling it I found a couple [vagrant issues](https://github.com/mitchellh/vagrant/issues/4688) of users with the same problem.

Anyways, out of curiosity I then modified my Gemfile to use all the new (unreleased) [winrm-v2](https://github.com/WinRb/WinRM/pull/191) gems by adding this to it:
```
  gem 'kitchen-inspec', :github => "mwrock/kitchen-inspec", :branch => "winrm-v2"
  gem "test-kitchen", :github => "test-kitchen", :branch => "winrm-v2"
  gem "train", :github => "chef/train", :branch => "winrm-v2"
  gem "winrm", :github => "winrb/winrm", :branch => "winrm-v2"
  gem "winrm-fs", :github => "winrb/winrm-fs", :branch => "winrm-v2"
  gem "winrm-elevated", :github => "winrb/winrm-elevated", :branch => "winrm-v2"
```

With this I was able to run without a problem with elevated set to `true`.  I'd be curious to know if either of you have similar experiences.

**Comment by jkerry** [comment]
@mwrock I had this happen to me on the latest DK when attempting to run elevated: true while also setting retry_on_exit_code in order to reboot after .net 4.6.2 install on a windows 2008 r2 image. It only happens when the retry on reboot is in progress.  convergence before and after the reboot have no issues.

**Comment by mwrock** [comment]
ok thanks. Well the next dk is going to have fundamentally different winrm code so we'll see if this re-emerges. Please give a hollar if it does.

**Comment by jkerry** [comment]
actually it looks like this was a race condition with my reboot timer.  kitchen retried to connect at a minute and my reboot resource fired at one minute.  The transport probably forced closed after the second run started.
