### ISSUE TITLE
failed to converge on OSX 10.11.6

### ISSUE THREAD

**Issue by wcpan** [test-kitchen/test-kitchen#1122]
## Description
Hi, I am new to chef, I follow the instruction and use following config to converge, but failed.

```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    attributes:
```
## Kitchen Version
```ruby
Test Kitchen version 1.13.0
```

## ChefDK Version
```ruby
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 5.1.0
kitchen version: 1.13.0
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

## Platform Version
Tell us which Operating System distribution and version test-kitchen is running on.
```
OSX 10.11.6
```

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.
https://gist.github.com/6c880b5924ffd5f3ce377d9d2aef064e

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

https://gist.github.com/b6c488022578d28f85d27c479ad23e9d

**Comment by mwrock** [comment]
Yes this is due to a bad mixlib-install 1.2.1 which has since been yanked. Please `gem install mixlib-install -v 1.2.2` to fix your environment and my apologies that you had to deal with this in the first place.
