### ISSUE TITLE
tar.gz transport for chef provisioners

### ISSUE THREAD

**Issue by lamont-granquist** [test-kitchen/test-kitchen#1123]
- For all chef 11.x/12.x omnibus installs on the target machine
- The chef-solo/legacy/zero providers should support .tar.gz transport to speed up file transfers
- There must be no additional configuration required and the perf bug must be fixed by default for all users
- Other provisioners are out of scope, but must not be broken
- The solution needs to be "pluggable" or "configurable" so that other provisioners can implement fixes if anyone cares to (if nobody cares to it doesn't get fixed and does not block improving the chef provisioners).

We can leverage:
- We have an omnibus-chef install on the box
- We have a ruby on the box
- We have archive-tar on the box

We cannot leverage:
- The mixlib-archive gem on the target (that was done fairly recently -- dropping chef 11 support wouldn't help us)
- The --recipe-url option (pretty certain I only ported that to chef-zolo fairly recently -- dropping chef 11 support wouldn't help us)
- A tar utility being installed on the target (windows, minimal docker, blah, blah, blah)

It looks like TK should ship a script up to the target that uses archive-tar to `tar xvf` the files.  We may be able to make TK depend on mixlib-archive and ship the guts of that up to the target, but the more complicated mixlib-archive becomes the more files may need to be shipped in order to bootstrap it and I can think of a huge pile of edge cases (in general I see a huge risk of software developers acting like software developers and layering powerful abstractions on top of mixlib-archive that completely screw up this use case we have here).  It may be simpler to copypasta the mixlib-archive code into a standalone script which is shipped to the target.  See the appbundle-updater gem which has a short mixlib-archive embedded in it that works fine when you control both ends of the problem.

Don't let the Perfect be the Enemy of the Good
KISS

**Comment by coderanger** [comment]
Not sure what you think this will speed up? SFTP already supports good connection multiplexing (as I think does WinRM but less sure there). SSH does compression already too, and I think we compress data before shipping it in winrm-fs (or at least we could, since we are already blobbing it ourselves).

**Comment by kamaradclimber** [comment]
@lamont-granquist we've implemented such improvement for transport and results are really great: https://github.com/criteo/kitchen-transport-speedy

**Comment by lamont-granquist** [comment]
net-ssh bogs down on lots-of-files for unknown reasons, its the tar which is important.

and @kamaradclimber you do `which tar` which is a full on no-go showstopper for windows or any other box which doesn't have a tar executable (probably docker) which cannot be accepted.  there's a bunch of those plugins -- i'd like them all to go away and get replaced by core TK getting better, but none of them do the work to be portable enough.

**Comment by kamaradclimber** [comment]
you're right indeed. I'll be happy to contribute

**Comment by coderanger** [comment]
@lamont-granquist `net-scp` bogs down, I've not seen that with `net-sftp`. It's just that Kitchen uses literally the worst possible file transfer system in SSH :)

**Comment by lamont-granquist** [comment]
can we use sftp without having special configuration on the daemon side?  i recall at one point it needed sshd_config changes, but that was literally more than a decade ago...

**Comment by coderanger** [comment]
It's been by default in every sshd_config for a very long time. The only thing I know of that disabled it was our own `ssh` cookbook :) I think that got fixed though.

**Comment by lamont-granquist** [comment]
yeah i may be thinking of a time before internal-sftp when you had to setup sftp-server.

okay that'd work.

it'd be kind of nice to see how tar+sftp compares to sftp and how tar+winrm compares to winrm on the windows side as well though.

**Comment by coderanger** [comment]
Yeah, I defer to @mwrock on if he thinks that would be faster for Windows. My understanding was the PSRP upgrade should fix most of those stuffs.

**Comment by mwrock** [comment]
Yeah this would have been undoable prior to the PSRP work without incurring multi hour uploads of the client.

**Comment by cheeseplus** [comment]
Any updates on this front in terms of code/PR? Would love to get this in as at least an option for linux hosts to see if this can alleviate some of the weirder issues folks seem to have with Net:SSH
