### ISSUE TITLE
Guest hostname does not get set if converge times out during vagrant VM boot

### ISSUE THREAD

**Issue by fooshards** [test-kitchen/test-kitchen#1128]
## Description

If a box is slow to boot up, and kitchen aborts the first time, the VM still continues to boot in the background.  I am guessing that it terminates the vagrant process (which would have set the hostname after boot) but the VM itself continues.  On a subsequent kitchen converge, if the VM is now responding, the post-provision config is skipped, and then the rest of kitchen lifecycle happens as normal.
## Kitchen Version

1,11,1
## ChefDK Version

```
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1
```
## Platform Version

Windows 7 host, OEL6.5 guest
## Replication Case

1) In your kitchen.yml specify 

```
driver:
  name: vagrant
  vm_hostname: "foo.bar.com"
```

2) Select a box that is either slow to boot, or artificially create a timeout by setting the following in kitchen.yml

```
platforms:
  - name: yourbox
    driver:
      boot_timeout: 1
```

2) Run kitchen converge. (Timeout fail.)
3) Upon kitchen failure, allow the VM that is starting in the background to boot naturally.
4) Run kitchen converge.  (Normal op.)
5) SSH to your VM 
6) Check `hostname -f`
## Kitchen Diagnose

https://gist.github.com/fooshards/568f8805b02eff6fff2da8dc3132e54c
## Expected behavior

I would assume the a kitchen converge failing to start the vm, and terminating vagrant, would also funnel down and terminate the VM launch.  If it doesn't, kitchen should be instructing vagrant (or doing it itself) any post-provision steps that may have been missed.

**Comment by cheeseplus** [comment]
This is something that is a bit outside the scope as we, for better or worse, rely on Vagrant doing mostly the correct things here. If this is a continuing problem please open an issue on the `kitchen-vagrant` project.
