### ISSUE TITLE
kitchen has wrong exit code for chef-solo failure on windows (winrm)

### ISSUE THREAD

**Issue by b-dean** [test-kitchen/test-kitchen#1134]
## Description

With Kitchen versions that use winrm gem 2.x, when chef-solo exits with a non-zero exit status, kitchen exits with a `20`, which is the "unexpected error" exit status. Previous versions of kitchen (`< 1.8` for sure, maybe others) returned the "expected error" exit status of `10` for chef-solo errors.
## Kitchen Version

1.13.2
## Ruby Version

2.3.0
## Platform Version
- Host: Ubuntu 14.04.5
- Guest: Windows 2012 R2
## Replication Case

I created [b-dean/winrm-issue-229 ](https://github.com/b-dean/winrm-issue-229) to reproduce WinRb/WinRM#229 and if you edit the `Gemfile` to say 

```
gem 'winrm', '~> 2.0.3'
```

then the winrm bug is fixed and kitchen has the wrong exit code.
## Kitchen Output

Here's the output of running `bundle exec kitchen test -l debug`
https://gist.github.com/b-dean/7d7f5798ef9a4f35ab2b3aa67ef63ece#file-default-windows-log
## Kitchen Diagnose

https://gist.github.com/b-dean/7d7f5798ef9a4f35ab2b3aa67ef63ece#file-kitchen-diagnose-yaml

**Comment by cheeseplus** [comment]
Given the age on this one and a significant amount of fixes on several of the related repos, closing this one out. Please do open a new issue with current versions if still experiencing this behaviour but this works pretty well now.
