### ISSUE TITLE
Kitchen converge fails, doesn't install omnibus,  [[WinRM::FS::Core::FileTransporter] Upload failed

### ISSUE THREAD

**Issue by cosmincucu** [test-kitchen/test-kitchen#1150]
## Description

I'm running the tutorial at : https://learn.chef.io/tutorials/local-development/windows/virtualbox/get-set-up/

before i did the tutorial for hyperv, that worked fine, but i can't rename a host easily when deploying , which brings all sort of issues. More than that, most the examples i can find online are about vagrant. Then i uninstalled hyperv and tried Vagrant, when nothing worked anymore.

i just downloaded a couple of premade boxes of hashicorps website. When i try to converge kitchen the first time, it builds the vm, but when copying the files it throws a lot of errors , looking like : 

https://gist.github.com/cosmincucu/4cd435468b5a576c89c8320287ce014f

And a lot more powershell errors that look similar.

When i log on to the VM, in the C:\tmp folder i find a file named kitchen, not folder. If i try to reconverge, the same error happens. If i delete the file and create a folder named kitchen, it converges, but nothing is installed, ie no recipes are applied. When i check that folder i can see files are copied now, but they are not executed. I also noticed omnitruck is not installed. 

Am i missing anything?

## Kitchen Version

kitchen version: 1.13.0

## ChefDK Version

Chef Development Kit Version: 0.18.26
chef-client version: 12.14.89
delivery version: master (d86679335580be3de22996ef294b20d525889d8d)
berks version: 5.1.0
kitchen version: 1.13.0
 
## Platform Version

Windows 10 enterprise

## Replication Case

I just installed chefdk, virtual box and vagrant via chocolatey, and tried to follow the tutorial at https://learn.chef.io/tutorials/local-development/windows/virtualbox/get-set-up/

## Kitchen Diagnose

---
https://gist.github.com/cosmincucu/05d7e928f86865c5c2a9c039066dde7f

**Comment by smurawski** [comment]
@cosmincucu 

Here's the problem - https://gist.github.com/cosmincucu/05d7e928f86865c5c2a9c039066dde7f#file-gistfile1-txt-L67

Kitchen thinks you have a unix system and so is trying to issue bash commands to the system.

There is an `os_type` parameter to platform that you can set to say windows (which will change the default shell to powershell).  We default the OS type to windows if the name of the platform starts with "win".

Either change the platform name

```
platforms:
  - name: windows2012r2
    driver:
      box: mwrock/windows2012r2
```

or add the `os_type`
```
platforms:
  - name: mwrock/windows2012r2
    os_type: windows
    shell_type: powershell 
```
