### ISSUE TITLE
inspec works, but kitchen verify fails

### ISSUE THREAD

**Issue by noloc** [test-kitchen/test-kitchen#1154]
I am a newbie to inspec and I am encountering an issue I don't seem to be able
to "see" where the problem is and how to resolve it.  8(

I am using inspec compliance control profiles: 
linux-patch-benchmark (suspect, issues encountered)
tests-os-hardening (functional)
tests-ssh-hardening (functional)
ssl-benchmark (functional)

When running inspec via command line, linux-patch-benchmark works flawlessly (note that I have isolated my issue to this specific control profile).
 Bundle inspec version:  inspec (1.5.0)

inspec exec test/integration/linux-patch-benchmark -i .kitchen/kitchen-vagrant/kitchen-zero-default-centos-72/.vagrant/machines/default/parallels/private_key -t ssh://root@192.168.33.3
WARN: Unresolved specs during Gem::Specification.reset:
      winrm (~> 2.0)
      docker-api (~> 1.26)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

Profile: Linux Patch Benchmark (linux-patch-benchmark)
Version: 0.1.0
Target:  ssh://root@192.168.33.3:22

  ✖  verify-patches: All patches should be installed (
     expected: 0
          got: 94
     
     (compared using ==)
     )
     ✖  94 should eq 0
.......
Profile Summary: 0 successful, 2 failures, 0 skipped

kitchen --version = Test Kitchen version 1.13.2

Bundle list kitchen versions:
kitchen-vagrant (0.20.0)
test-kitchen (1.14.0))
kitchen-inspec (0.16.1)

My current ChefDK versions are:  chef --version
Chef Development Kit Version: 0.18.30
chef-client version: 12.14.89
delivery version: master (d86679335580be3de22996ef294b20d525889d8d)
berks version: 5.1.0
kitchen version: 1.13.2

My development environment is on Mac OS X Sierra 10.12.1

The following is the contents of my .kitchen.yml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  host: 192.168.33.3
  port: 22
  sudo: true
  sudo_command: 'sudo'

platforms:
  - name: centos-7.2
    driver:
      provider: parallels
      box: parallels/centos-7.2
      box_url: parallels/centos-7.2
      network:
      - ["private_network", {ip: "192.168.33.3"}]
      synced_folders:
      - ["~/chef-repos/chef-sync-dir", "/chef-repo" ]
#
# Second VM type we can generate... 
#
  - name: ubuntu-16.04
    driver:
      provider: parallels
      box: parallels/ubuntu-16.04
      network:
      - ["private_network", {ip: "192.168.33.4"}]
#
# Third VM type we can generate... 
#
  - name: bcentos-7.2
    driver:
      provider: virtualbox
      box: bento/centos-7.2
      box_url: bento/centos-7.2
      network:
      - ["private_network", {ip: "192.168.33.5"}]

suites:
  - name: default
    run_list:
      - recipe[zero::default]
      # - recipe[apache2]
      # - recipe[os-hardening]
      # - recipe[ssh-hardening]
      # - recipe[yum]
      # - recipe[yum-centos]
    verifier:
      inspec_tests:
        - test/recipes
        - test/integration/default
    attributes:

## Replication Case
The following content is located in my mock cookbook called "zero", in: test/integration/default
├── LICENSE
├── README.md
├── controls
│   ├── hardening.rb
│   ├── patch.rb
│   └── ssl.rb
└── inspec.yml

Inspec.yml content (note that the %suite% is located in test/integration/linux-patch-benchmark):
name: inspec-profile
title: Meta profile for Compliance as Code
maintainer: Christoph Hartmann
copyright: Christoph Hartmann
copyright_email: chris@lollyrock.com
license: Apache 2.0
summary: This profile demonstrates compliance as code analysis
version: 0.1.0

depends:
  - name: linux-patch-benchmark
    path: ../linux-patch-benchmark

Items in the controls/*.rb are commented out for hardening.rb and in patch.rb the windows-patch-benchmark is also commented out, leaving only the linux-patch-benchmark control as the only valid control to run

Kitchen verify fails with the following output:

kitchen verify default-centos-72
-----> Starting Kitchen (v1.13.2)
WARN: Unresolved specs during Gem::Specification.reset:
      octokit (~> 4.0)
      winrm (~> 2.0)
      docker-api (~> 1.26)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
-----> Verifying <default-centos-72>...
       Using `/Users/noloc/chef-repos/chef-CaaS/cookbooks/zero/test/recipes/default` for testing
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [nil can't be coerced into Fixnum] on default-centos-72
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

Kitchen diagnose all output contained in the following gist:  https://gist.github.com/noloc/35bea899e4e4159cad7203f26937876a

Kitchen diagnose loader output contained in the following gist:
https://gist.github.com/noloc/fd5a8254fd3f013c3f65dc3e922c91fe

**Comment by noloc** [comment]
nil fix #4 provided by @chris-rock results in this issue being resolved.  I am closing this item out accordingly.

**Comment by chris-rock** [comment]
The original issue is tracked here: https://github.com/dev-sec/linux-patch-benchmark/issues/3 and was not related to test-kitchen
