### ISSUE TITLE
Deployment of cookbooks do differ from berks package

### ISSUE THREAD

**Issue by EugenMayer** [test-kitchen/test-kitchen#1158]
## Description

When using kitchen to converge a box, the cookbooks are put under /tmp/kitchen/ - since `berks` is used and the general folder structure looks like `berks package` has been used, it suprises, that the result is different.

For example `berks package` would include data_bags from cookbooks which have been referenced like

```
cookbook A
```
in the Berksfile of the cookbook we are testing.

Kitchen thus does not include those, actually excludes more then that.

## Kitchen Version

```ruby
Test Kitchen version 1.13.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 0.19.6
chef-client version: 12.15.19
delivery version: master (802e801d920ea6b6d48db735aa7c6e7a6194bea4)
berks version: 5.2.0
kitchen version: 1.14.0
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
chef exec ruby --version                                               1 ↵
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin13]
```

## Platform Version

OSX El Capitan

## Replication Case

1. create a cookbook A with a data_bags
2. create a other cookbook B, add A as a dependency in the `Berksfile`
3. run `kitchen converge`
4. check `/tmp/kitchen/cookbooks/a/data_bags` on the box, it should be missing

**Comment by cheeseplus** [comment]
Explained this on IRC, closing.
