### ISSUE TITLE
ssh port forwarding

### ISSUE THREAD

**Issue by directionless** [test-kitchen/test-kitchen#1159]
## Description

Hi! I find I often want to interactively poke some process running in a test kitchen. This usually means I want an ssh port forward. I don't see one available in https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/ssh.rb it would be awesome if there was an option.

The workarounds I have are configuring a port at vagrant create time, via the driver:network block, though this runs into port conflicts. Or using bare ssh with values pulled from the kitchen host files.

**Comment by cheeseplus** [comment]
Kitchen-vagrant already allows you to configure port forwarding and as this would be down to driver specifics, it doesn't sound to me like this something that belongs in core. The implementation would be hyper-specific to local or remote virtualization (cloud).

**Comment by directionless** [comment]
I don't know how kitchen thinks of it's internals, so forgive me if I'm off base.

From what I can tell, there's an option to create it VM _create_ time, presumably by kitchen-vagrant. I'm finding that runs into a couple of issues:

* I often find I have some sprawling cookbook, with a long converge time. By the time I realize I need a port forward, I'm loath to go through a `destroy` &  `create` cycle. (1 hour plus on some of my role cookbooks)
* I think this only allows a given set of ports, per .kitchen file, which means if there are multiple suites they're going to conflict. Which isn't fatal, but is confusing.
* I need to manually manage ports across my kitchen instances, which gets hard if I leave them running
* I feel weird pushing this to CI infrastructure, since concurrent runs will have port conflicts 

Instead, I'd love something that worked at `login` time. That way port forwards would only need to be unique across active login sessions, and I'd be able to apply them to an existing VM. I would imagine this would pass the `-L...` option to ssh, analogous to how `:forward_agent` works

**Comment by cheeseplus** [comment]
So this still is highly specific to kitchen-vagrant - the limitation for port forwards is one of Vagrant, not really tk itself and if you want to enumerate them you can do so arbitrarily. The default mode of kitchen is sequential as well so again not really a problem. If you need to manually manage ports across kitchen instances, kitchen is the wrong tool.

In short: this isn't really something supportable widely and is hyper specific to Vagrant. The problems are really not kitchen problems but simply it mirroring the underlying mechanics of what it's abstracting, in this case Vagrant.
