### ISSUE TITLE
a link on kitchen.ci/blog is broken (very minor)

### ISSUE THREAD

**Issue by kernelsmith** [test-kitchen/test-kitchen#1161]
## Description

I didn't see the source for the blog on github, tho I admit I didn't look too hard, so I'm putting the issue here, otherwise I would have created a PR for it.  At http://kitchen.ci/blog, the first blog entry at the top:

```
Test Kitchen Windows Test Flight with Vagrant
Tuesday, April 28 2015

As mentioned in the 1.4.0 release notes...
```
the link to the release notes points to http://kitchen.ci/test-kitchen-1-4-0-release-notes but I believe the correct url is http://kitchen.ci/blog/test-kitchen-1-4-0-release-notes (adds "blog" in the middle)

## Kitchen Version

n/a 

## ChefDK Version

n/a

## Ruby Version

n/a

## Platform Version

n/a

## Replication Case

n/a

**Comment by kernelsmith** [comment]
especially minor given how old 1.4 is

**Comment by cheeseplus** [comment]
We've completely redone the site and all that text is gone anyway but if there are still issues please open them up at https://github.com/test-kitchen/kitchen-docs
