### ISSUE TITLE
Possible to specify a custom bootstrap template?

### ISSUE THREAD

**Issue by joestump** [test-kitchen/test-kitchen#1162]
## Description

We use `knife` and we have custom bootstrap template to bootstrap template. I've looked high and low for how I could plug that into `kitchen converge` and I've come up empty. Is this not supported or possible?

## Kitchen Version

```ruby
Test Kitchen version 1.14.0
```

## Platform Version

All? We use Ubuntu LTS.

**Comment by coderanger** [comment]
Test Kitchen doesn't use knife bootstrap so no. If you want to customize the provisioner you can subclass it and make your own plugin.
