### ISSUE TITLE
Getting message: "Expected array default value for '--driver'; got "kitchen-vagrant" (string)" with every operation

### ISSUE THREAD

**Issue by eyalzek** [test-kitchen/test-kitchen#1163]
## Description

I started getting the following message with every `test-kitchen` operation, whether it's `--help`, `--version`, `converge`, `verify`, etc..
I'm pretty sure it started happening with the last version, but I can't find the changed that introduced it, or figure out where this is coming from.

## Kitchen Version

```ruby
~$  kitchen --version
Expected array default value for '--driver'; got "kitchen-vagrant" (string)
Test Kitchen version 1.14.0
```

## Ruby Version

```ruby
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```

## Platform Version

Ubuntu 16.04

## Replication Case

With every `kitchen` operation

## Kitchen Output

```ruby
Expected array default value for '--driver'; got "kitchen-vagrant" (string)
```

## Kitchen Diagnose
It isn't specific to one `.kitchen.yml`, it happens without that file as well.

**Comment by szymonpk** [comment]
It's due to [thor 0.19.2](https://github.com/erikhuda/thor/blob/master/CHANGELOG.md#0192-release-2016-11-26) - *Ensure that default option values are of the specified type (e.g. you can't specify "foo" as the default for a numeric option), but make symbols and strings interchangeable*.

**Comment by eyalzek** [comment]
Huh, so I guess it isn't `test-kitchen` related. Thanks!

**Comment by szymonpk** [comment]
Well it's, because `--driver` is defined in test-kitchen. You should re-open this.

**Comment by szymonpk** [comment]
Only place where I found `kitchen-vagrant` is [here](https://github.com/test-kitchen/test-kitchen/blob/28b1f04b5467e4229140e4772c75b270568e3806/lib/kitchen/generator/init.rb#L37). But it's an array. Can test-kitchen maintainer look at this?

**Comment by szymonpk** [comment]
Sorry @eyalzek, looks like @coderanger [fixed this](https://github.com/test-kitchen/test-kitchen/commit/53a0eaf452985fa3facdc8f9059cdad012696144). It just isn't released yet.

After all, I think you can close it.

**Comment by eyalzek** [comment]
:)
