### ISSUE TITLE
Changelog was not updated for the 1.15.0 release

### ISSUE THREAD

**Issue by pgporada** [test-kitchen/test-kitchen#1183]
## Description

[CHANGELOG.md](https://github.com/test-kitchen/test-kitchen/blob/master/CHANGELOG.md) still points at the 1.14.2 release even though 1.15.0 is out.

**Comment by tduffield** [comment]
https://github.com/test-kitchen/test-kitchen/pull/1181 should fix this issue.

**Comment by pgporada** [comment]
Hooray! Thank you!
