### ISSUE TITLE
Chef omnibus pin warning from busser setup

### ISSUE THREAD

**Issue by matschaffer** [test-kitchen/test-kitchen#1185]
## Description

The omnibus pin warning on what I'm pretty sure is a fairly default setup is somewhat distracting.

Is there a good way to suppress that?

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.15.0
```

## ChefDK Version

None, using kitchen-ansible

## Ruby Version

```ruby
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
```

(via rvm)

## Platform Version

macOS 10.12.2 (16C67)
vagrant version 1.9.1 (via homebrew)

## Replication Case

Just a basic case in a new dir can replicate the output.

```
> kitchen init
> kitchen test
```

## Kitchen Output

```ruby
...
    WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       You are installing an omnibus package without a version pin.  If you are installing
       on production servers via an automated process this is DANGEROUS and you will
       be upgraded without warning on new releases, even to new major releases.
       Letting the version float is only appropriate in desktop, test, development or
       CI/CD environments.

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
...
```

**Comment by cheeseplus** [comment]
This is more a problem of how busser works as it really shouldn't need to install Chef if you're not using it as the provisioner, something that newer plugins like kitchen-inspec completely sidestep. The mechanism is designed so that If you don't pin a version via `require_chef_omnibus` you get the warning but as stated above, the underlying mechanism is of more concern.

This probably is more a busser issue than anything. What busser-plugin is being used here?

**Comment by matschaffer** [comment]
I don't specifically have any busser plugins in my Gemfile.

I tried both bats and serverspec tests and both yielded the same output.

**Comment by cheeseplus** [comment]
Busser is the default so if BATS or ServerSpec are being called they are being executed via their respective busser-* plugins so that does answer my question.

**Comment by matschaffer** [comment]
Gotcha. It's a greenfield so guess I'll try out inspec to see if it eliminates the extra steps & warnings.

**Comment by cheeseplus** [comment]
Closing this one as the output is a side effect of expected behaviour as described.
