### ISSUE TITLE
pull or push in a docker registry with kitchen

### ISSUE THREAD

**Issue by mahmoudmahdi24** [test-kitchen/test-kitchen#1186]
How to pull or push an image with kitchen ? 
I don't want to do it with an sh or bash command.
Thanks

**Comment by cheeseplus** [comment]
tl;dr you don't

Test-kitchen can make use of several drivers, like kitchen-docker, and those will automatically pull certain images or let you specify which images to pull from the Docker Hub a la https://github.com/test-kitchen/kitchen-docker#image. Kitchen itself is an isolated testing framework and as such has no push facility although one could be added to any driver under the `package` command that is stubbed out in core for drivers to use.

I'm going to close this questions as answered but if you have further questions please do ask.

**Comment by mahmoudmahdi24** [comment]
Actually, it's not what i am looking for.
I am totally aware that I can choose the images (platforms) where my tests will run, but it's not what i am looking for.
My problem is, that i am testing an infrastructure with a private docker registry.
I want to test with kitchen if i can pull an image, and push it to the private docker registry.
Now, i am using bats tests now, but it would be great to use kitchen.

**Comment by cheeseplus** [comment]
kitchen is centered around testing the cookbook/playbook/module artifacts in isolation and as such this functionality is a bit out of scope and the implementation would be highly specific to the driver being utilized. It can be done but you'd probably want to start with forking an existing driver and see if it's feasible. At present this is both out of scope and doesn't feel generally useful across drivers to belong in core.

I'm not sure how the BATS test overlap here either, that is for verification of the cookbook/etc and not for the infrastructure underlying.

If you'd like to enhance kitchen-docker/dokken (and core if necessary) then I'd suggest working out a PR/issue that describes how this functionality would work.

**Comment by mahmoudmahdi24** [comment]
Can i contribute to the project ?

**Comment by cheeseplus** [comment]
Of course! Contributions are always welcome but I will note that just because kitchen _could_ do something doesn't mean it _should_. You have a very specific use case and one that as described doesn't seem generally useful to kitchen users from my experience. We try to balance new features with the maintenance cost and general benefit to all users of kitchen hence why we don't just bolt on everything it _could_ do.
