### ISSUE TITLE
kitchen busser verifier fails on windows if file path case differs from case used when navigating

### ISSUE THREAD

**Issue by coderjoe** [test-kitchen/test-kitchen#1190]
## Description

On windows, if I navigate into a cookbook directory using a different file-path case than the actual directory on the filesystem then kitchen fails with the following error:

```
-----> Setting up <default-ubuntu-1404>...
       Finished setting up <default-ubuntu-1404> (0m0.00s).
-----> Verifying <default-ubuntu-1404>...
       Preparing files for transfer
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Invalid argument @ dir_s_mkdir - C:/Users/JOSEPH~1.BAU/AppData/Local/Temp/default-ubuntu-1404-sandbox-20170203-26696-hglx0c/suites/C:] on default-ubuntu-1404
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I believe the problem has been narrowed down to `lib/kitchen/verifier/busser.rb#252` in test-kitchen where it does a substitution string of the base path using a case sensitive match. The `config[:test_base_path]` gets whatever value the user used when navigating to the path, but the `helper_files` are generated using Dir.glob which seems to produce the correct OS case resulting in the match failing due to case sensitivity.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.14.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
chef --version
Chef Development Kit Version: 1.1.16
chef-client version: 12.17.44
delivery version: master (83358fb62c0f711c70ad5a81030a6cae4017f103)
berks version: 5.2.0
kitchen version: 1.14.2
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]
```

## Platform Version

Windows 8.1 

## Replication Case

1. Open the ChefDK console
2. `mkdir C:\TestCase`
3. `cd C:\testcase`
4. `git clone https://github.com/miketheman/nginx.git` (or any other cookbook with tests)
5. `cd nginx`
5. `kitchen test example-ubuntu-1404` (or any test from your selected cookbook)
6. Note that it fails with the above error.
7. `cd C:\TestCase\nginx` (note correct casing)
8. `kitchen test example-ubuntu-1404` (or any test from your selected cookbook)
9. Note that it no longer fails.

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

See gist: https://gist.github.com/coderjoe/68c54b0e9860557ab82ff83d94b89d9e

## Kitchen Diagnose

See gist: https://gist.github.com/coderjoe/68c54b0e9860557ab82ff83d94b89d9e

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by cheeseplus** [comment]
I think we could make this better but I have reservations about ignoring the fact that "Folder" != "folder" as this is only an issue specific operating systems committing a cardinal sin with respect to case sensitivity. That is to say, I think the failure is entirely appropriate but if we could make this easier to determine (via an error message) I'd be amenable to merging.

**Comment by coderjoe** [comment]
Closing as the linked merged PR seems to have resolved my original problem.
