### ISSUE TITLE
Add a constraint for minimal required kitchen version

### ISSUE THREAD

**Issue by coredump** [test-kitchen/test-kitchen#1193]
## Description

Currently there's no way on `.kitchen.yml` to specify what version is the lowest required one to run the tests/tools correctly. 
That causes issues where new functionality are added to kitchen and used in the YAML but are ignored or return errors because someone is trying to run it on a kitchen version that doesn't support the new stuff.

## Kitchen Version

```ruby
Test Kitchen version 1.15.0
```

## ChefDK Version

```ruby
Chef Development Kit Version: 1.3.6
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 2017-02-13T12:28:45.811234 8804] 2017-02-13T12:28:45.811394 8804] 2017-02-13T12:28:45.811504 8804] 2017-02-13T12:28:45.811603 8804] 2017-02-13T12:28:45.852202 8804] 2017-02-13T12:28:45.852492 8804] 5.6.0
kitchen version: 1.15.0
chef -v  3.01s user 0.71s
```

## Platform Version

MacOS 10.11.6

## Replication Case

* Create a kitchen YAML config using the `policyfile`  directive under `provisioner`.
* Run the config using test-kitchen version 1.6.0

Kitchen will ignore policyfiles and try to converge an empty run list.

**Comment by cheeseplus** [comment]
I think this would be fairly non-invasive and could just be a warning. Something like:

```
---
kitchen_min_version: 1.14.0
```
