### ISSUE TITLE
Option for bootstrap_run_list to run before the actual run_list

### ISSUE THREAD

**Issue by joerg** [test-kitchen/test-kitchen#1195]
I think it is quite common to have something like a bootstrap cookbook (or base cookbook or whatever else you might want to call it) and it would be great to have this available as a kitchen feature.
In my specific case the problem is that we have no access to the internet from our servers, so we have to set up our internal gem and yum repos plus certificates before we can start doing anything. The docker cookbook for example tries to install the docker-api gem from a library and thus it doesn't even help if we have our configs placed at converge time in a recipe like we do now ( cookbook_file '/etc/gemrc' do; end.run_action(:create) ).
Having some option like "bootstrap_run_list" or so would have several benefits:
* A naked base system image can be used without any modifications
* The approach would resemble the use of "knife bootrstrap ... -r base" or similar
* Simply two chef runs would be triggered after each other, so the implementation should not be too hard I guess

Does this make sense? Any further suggestions?

**Comment by cheeseplus** [comment]
We've actually considered doing this at the chef-client level recently where there is a 'boostrap' run_list to do the same types of operations described here. 

At present this can often be accomplished via unique functionality of downstream drivers, i.e. custom Vagrantfiles with shell provisioner in kitchen-vagrant etc. but if we don't add it to the client itself this may be something viable. We also have plans to do multiple converge passes as a first class feature but that is somewhat bound up with multiple node support.

**Comment by joerg** [comment]
I considered doing it in the Vagrantfile/Dockerfile but that just duplicates the work I do in my bootstrap/base cookbook and even worse, everything will be statically in those cookbooks and any updates will require me to update every cookbook. So this is not really a viable option.
Doing it in the chef-client also sounds like something useful, but I actually considered a very straight-forward approach in kitchen where there could simply be a second chef-run before the actual run with an --override-runlist (don't know if this also works with solo, apply etc. but should work with zero).
Or for a more complete implementation this bootstrapping could/should be done in an additional phase between create and converge.

I am actually myself not sure if this would be a good idea and/or implementation. I was just looking for a way to bootstrap in kitchen and found that the only way to do this is by creating a custom image which in my eyes would just duplicate the work most people already do in some bootstrap/base cookbook.

**Comment by cheeseplus** [comment]
This will be covered by multi-node/multi-converge https://github.com/chef/chef-rfc/blob/master/rfc084-test-kitchen-multi.md so I'm closing it as this will inherently be covered there as described OR belongs as a feature of chef-client itself.
