### ISSUE TITLE
Can test-kitchen be used for black-box testing

### ISSUE THREAD

**Issue by guettli** [test-kitchen/test-kitchen#1200]
## Description

This is a question, not a bug or feature request. If off-topic here, please guide me to the right direction.

How can I use test-kitchen for black-box testing:

My use case:
 

1.  VM gets created
1. Salt States get applied
1. Test the http-API which the VM provides (black-box only, these tests don't look into the box)

AFAIK step 1 and 2 can be done by test-kitchen.

What is the common way to do step 3 for test-kitchen gurus?

**Comment by nvtkaszpir** [comment]
run custom verifier, for example trigger jmeter on local machine to verify converged hosts?

**Comment by cheeseplus** [comment]
Re-reading the original question I guess for black box you'd be looking at the custom verifier suggested by @nvtkaszpir - both inspec and serverspec are oriented around machine state, not necessarily application/API testing even though they can be bent that way (but still not black box exactly)

**Comment by cheeseplus** [comment]
Closing this one given the answers and no further discussion.

**Comment by alexpop** [comment]
`kitchen-inspec`'s target is the hostname+port used by kitchen for converging. e.g. 127.0.0.1:2222

You can override this from the kitchen config:
```yaml
verifier:
  name: inspec
  host: 192.168.56.40
  port: 22
```

Resources can grab the target, like the `ssl` resource here: https://github.com/chef/inspec/blob/v1.19.2/lib/resources/ssl.rb#L51
