### ISSUE TITLE
concurrency between multiple KITCHEN_YAML

### ISSUE THREAD

**Issue by juju4** [test-kitchen/test-kitchen#1207]
## Description

when having multiple kitchen config in same directory, for example with different providers, kitchen doesn't differentiate the provider and execute command on existing platform if existed.

## Kitchen Version

```
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ kitchen --version
Test Kitchen version 1.16.0
```

## Platform Version

Ubuntu trusty

## Replication Case

Create a test for anything, for example an ansible role.
Have generic .kitchen.yml (lxd for me) and alternative .kitchen.vagrant.yml, .kitchen.docker.yml
Do a kitchen verify with first one
Try to do a verify with alternate config, it will verify on previous provider.

```
$ kitchen verify default-ubuntu-1604
$ KITCHEN_YAML=".kitchen.vagrant.yml" kitchen verify default-ubuntu-1604
```

can do the same between docker, vagrant or whatever provider so I suppose it's a core issue which doesn't differentiate execution platform depending on provider.

It's useful to have multiple provider as containers are fast but may trigger specific bugs compare to a full VM.

**Comment by smurawski** [comment]
@juju4 

Kitchen has several lifecycle events:

* Create
* Converge
* Verify
* Destroy

(There's `test` too, but that just runs Destroy, Create, Converge, Verify, Destroy in series.)

Pretty much everything after create is driver independent and uses the state persisted in the `.kitchen` directory to connect to the instance (the system under test).  If an instance of the same name (suite-platform) exists and has gotten past the create stage, changing the provide will have limited to no effect until you go through the `create` phase again.

If you are going to change what KITCHEN_YAML points at, a good practice would be to `kitchen destroy` existing instances.

You can hit similar problems by changing the suites or platforms (or some other settings) in your current .kitchen.yml (or whatever you are pointing to for config).  For example, if you are using the kitchen-azurerm provider and create some instances (e.g. default-ubuntu-1604), then change the suite name before destroying (e.g. and the instance becomes testing-ubuntu-1604), test-kitchen will lose any idea of the pre-existing instance (default-ubuntu-1604 will be left running in Azure until you manually clean it up from their portal or with the Azure CLI).
