### ISSUE TITLE
Syncronzing Cookbooks fails to sync root files

### ISSUE THREAD

**Issue by lioramilbaum** [test-kitchen/test-kitchen#1213]
## Description

A json file placed in the cookbook root folder is not synced to the instance when 'Syncing Cookbooks' is performed 

## Kitchen Version

Test Kitchen version 1.15.0

## ChefDK Version

Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 5.6.1
kitchen version: 1.15.0

## Platform Version

OS-X 10.12.4

## Replication Case

place a json file in the cookbook root folder and run kitchen converge. 

.kitchen.yml file:

---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[core::default]
      - recipe[depy-jenkins::default]
    attributes:

## Kitchen Output

The json file is not synced

**Comment by cheeseplus** [comment]
This isn't a bug, this behaviour is as designed as we _explcitly_ don't copy arbitrary non-cookbook files.

**Comment by coderanger** [comment]
You can change this via the `cookbook_files_glob` provisioner setting (though make sure you copy over the entire current value).

**Comment by lioramilbaum** [comment]
Thanks. Will check that.
