### ISSUE TITLE
kitchen converge ssl error on windows

### ISSUE THREAD

**Issue by akankshajain** [test-kitchen/test-kitchen#1216]
I am facing SSL verify error when trying to run kitchen converge on Windows 7

Here are versions used for various components:

Chef Development Kit Version: 1.3.40
chef-client version: 12.19.36
delivery version: master (69bfa4a76959a8d093511a90fddd7a1f7e43e354)
berks version: 5.6.4
kitchen version: 1.16.0

When I do a kitchen converge I get
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [SSL_connect returned=1 errno=0
state=error: certificate verify failed] on default-ubuntu-1404
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

And this because of the following line in berksfile
`source 'https://supermarket.chef.io'`

If I change https to http it moves ahead and try to download the cookbook but fails with 301 error as http url tries to redirect to https url.

My workstation is Windows 7 ,  chef server is ubuntu 14.04

**Comment by cheeseplus** [comment]
We'd need a full log to troubleshoot this one properly. The error is related to connecting to a host with self-signed or invalid certs. This can also pop up when using a proxy. Going to close this one given the time elapsed but feel free to open a new one with the complete log and .kitchen.yml and we'd be happy to work out what is breaking here.
