### ISSUE TITLE
[QUESTION] Verifier Retry Options

### ISSUE THREAD

**Issue by pantocrator27** [test-kitchen/test-kitchen#1217]
## Question

I am running some integrated testing that may occasionally fail and may need a retry.  I have been trying to use gems like https://github.com/NoRedInk/rspec-retry along with inspec testing and this does not appear to work.  What I am looking for would be something similar to what is described https://discourse.chef.io/t/test-kitchen-1-10-0-released/8721 with provisioning configuration.  Basically a way to be able to retry testing.  Is this something that is possible?  If its currently possible, can you send me to the documentation?

## Kitchen Version

Test Kitchen version 1.16.0

**Comment by coderanger** [comment]
InSpec does not actually use RSpec, it just looks kind of similar. You could do this but you would have to implement it yourself in your test code.

**Comment by pantocrator27** [comment]
@coderanger I think you need to re-examine the issue I am submitting.  Maybe the rspec example was not the right one.  Why not have retry options like the provisioning piece?

**Comment by coderanger** [comment]
Because it comes up so rarely. Retries for provisioning were added specifically as a workaround for system reboots, not flaky code.

**Comment by pantocrator27** [comment]
@coderanger the code in question is not necessarily flaky ... the test in question is running on AWS and is occasionally subject to AWS API rate limiting errors of which a retry is appropriate.

**Comment by coderanger** [comment]
That is the definition of flaky :) This is easy to build as needed though, so just go do it. For example:

```ruby
describe 'something' do
  subject do
    5.times do
      cmd = command('something')
      return cmd if cmd.stderr.empty?
    end
    raise "boom"
  end

  its(:stdout) { is_expected.to ... }
end
```

**Comment by pantocrator27** [comment]
@coderanger, thank you for your sage advice.  I will try this ...
