### ISSUE TITLE
Improve 'Test Summary" Coloring; especially "0 Failures" being in Red

### ISSUE THREAD

**Issue by polobo** [test-kitchen/test-kitchen#1222]
The following output, when in color, is alarming.  The failures show up as a nice bright red (using bash shell on Windows 10 presently).  Might I suggest that "0 failures" be output in grey instead.  In a similar fashion a non-zero skipped might warrant something like a cyan output to flag its non-zero presence while leaving the existing grey for '0 skipped'.  This later item being less bothersome than seeing red on a test output and having to read the result to realize that it isn't actually a problem.

`kitchen verify`
(lots of stuff...working...)
Test Summary: 1 successful, 0 failures, 0 skipped

Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0

**Comment by smurawski** [comment]
@polobo Are you referring the results of an inspec verifier (which I have seen positive results return in red) or the actual results output from Test-Kitchen?  Test-Kitchen doesn't necessarily manage the output of the various plugins.

If so, that feedback may be more appropriate for https://github.com/chef/kitchen-inspec or https://github.com/chef/inspec

**Comment by polobo** [comment]
In all probability its an inspec thing.  Its just the single "Test Summary: ..." line I listed above.
