### ISSUE TITLE
Switching Test-Kitchen Configuration

### ISSUE THREAD

**Issue by pantocrator27** [test-kitchen/test-kitchen#1223]
## Description

When switching test-kitchen configurations by modifying the `KITCHEN_YAML` variable to different configurations, I am noticing that the previous state of test-kitchen is reflected in the new test-kitchen configuration when I perform a `kitchen list`.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.16.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 1.3.40
chef-client version: 12.19.36
delivery version: master (69bfa4a76959a8d093511a90fddd7a1f7e43e354)
berks version: 5.6.4
kitchen version: 1.16.0
```

## Platform Version

Mac OS X

## Replication Case

```
kitchen converge
export KITCHEN_YAML=.kitchen.dokken.yml
kitchen list
```

The `kitchen list` from the `.kitchen.dokken.yml` example will be reflective of what was run before.

**Comment by coderanger** [comment]
You need to `kitchen destroy` whenever you change settings, otherwise the state files in `.kitchen/` are still present.

**Comment by pantocrator27** [comment]
@coderanger that is what I have been doing.  I guess the question is whether or not the state files in .kitchen/ could be namespaced by the config file name so that this would not happen?  It's not a huge deal but just curious.

**Comment by coderanger** [comment]
I don't think it would be worth the inconsistency given how pervasive this issue is. Changing `$KITCHEN_YAML` is the least of our worries, the bigger issues are stuff like "what if you edit the file to change the active driver while there are still running instances" :)

**Comment by coderanger** [comment]
If we end up solving that second problem, the first will probably come along for free.

**Comment by pantocrator27** [comment]
You are correct as always.  I will close the issue.
