### ISSUE TITLE
::Kitchen::Configurable#finalize_config! expands expandable attributes before validating their values

### ISSUE THREAD

**Issue by ncs-alane** [test-kitchen/test-kitchen#1229]
## Description

[`::Kitchen::Configurable#finalize_config!` calls `::Kitchen::Configurable#expand_paths!` before `::Kitchen::Configurable::#validate_config!`](https://github.com/test-kitchen/test-kitchen/blob/v1.16.0/lib/kitchen/configurable.rb#L50), which means that an unvalidated attribute value that can't be expanded by `::File.expand_path` can cause an error to be raised that may be surprising to the user. Calling `#validate_config!` before `#expand_paths!` would allow plugins to validate config attributes marked for expansion and raise unsurprising errors when appropriate.

## Kitchen Version

```ruby
Test Kitchen version 1.16.0
```

**Comment by cheeseplus** [comment]
Do you have an example of this breaking something that we can look at? It sounds reasonable enough but a repro/PR would also be great.

**Comment by ncs-alane** [comment]
```ruby
class ::ExampleDriver < ::Kitchen::Driver::Base
  required_config :example do |attribute, value, plugin|
    value.kind_of? ::String or raise ::Kitchen::UserError, ":example must be a string"
  end

  expand_path_for :example
end
```

If `:example` is associated with a value that is not valid for `File.expand_path`, `::Kitchen::Configurable#expand_paths!` will raise a core Ruby error before `::Kithen::Configurable#validate_config!` can raise an actionable plugin error.

**Comment by ncs-alane** [comment]
@cheeseplus is my example sufficient enough to explain the issue? I don't have a real world example of this causing an issue because the behaviour has already been monkey patched in the Test Kitchen plugin that I maintain.
