### ISSUE TITLE
Chef 13 Cookbook Root Aliases Not Found

### ISSUE THREAD

**Issue by jsmickey** [test-kitchen/test-kitchen#1230]
## Description

In Chef 13, root aliases can be used for cookbooks with a single attribute and recipe file

## Kitchen Version

```ruby
Test Kitchen version 1.16.0
```

## ChefDK Version

```ruby
Chef Development Kit Version: 1.3.40
chef-client version: 12.19.36
delivery version: master (69bfa4a76959a8d093511a90fddd7a1f7e43e354)
berks version: 5.6.4
kitchen version: 1.16.0
```

## Platform Version

Ubuntu 16.04 and Amazon Linux

## Replication Case

Move default recipe from recipes/default.rb to recipe.rb
Move default attributes from attributes/default.rb to attributes.rb

## Kitchen Output

Default recipe and/or attributes not found

**Comment by cheeseplus** [comment]
This should be a super easy fix, we just need to explicitly include `attributes.rb` and `recipe.rb`

https://github.com/test-kitchen/test-kitchen/blob/6a38203715c120b2e829948212d9becc9a562a2e/lib/kitchen/provisioner/chef_base.rb#L62-L66

**Comment by lizzabeth** [comment]
I'm experiencing the same issues using policy files, both in Test Kitchen and using `chef install` etc.

**ChefDK Version **

```
Chef Development Kit Version: 2.1.11
chef-client version: 13.2.20
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.0
kitchen version: 1.17.0
inspec version: 1.33.1
```

**Comment by cheeseplus** [comment]
Closed by https://github.com/test-kitchen/test-kitchen/pull/1446
