### ISSUE TITLE
kitchen login Connecting to Host Instead of Guest VM

### ISSUE THREAD

**Issue by MichaelStankiewicz** [test-kitchen/test-kitchen#1242]
## Description

The 'kitchen login' command is attempting to rdp to loopback IP, rather than the vm instance.

## Kitchen Version

Test Kitchen version 1.15.0

## ChefDK Version

Chef Development Kit Version: 1.2.22

## Platform Version

Windows 2012 R2 Standard

## Replication Case

Create a vagrant/virtualbox vm.
Update kitchen.yaml file to reflect proper environmental details.
Use the vagrant/vbox knife driver to instantiate an instance of the kitchen using 'knife create'.
Once kitchen vm is instantiated, execute 'kitchen login'.

## Kitchen Output

The results will be an RDP connection logon box that is attempting to connect to 127.0.0.1.  The connection attempt is essentially being made to the host instead of the underlying kitchen vm.  The command 'kitchen login %kitchen_instance%' (instance name derived from 'kitchen list') command also produces the same results.

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by cheeseplus** [comment]
This sounds like you're not using kitchen to create the machine itself so kitchen doesn't have the details it needs to login. `kitchen login` very specifically will rely on a yaml file in `.kitchen` to have the information it needs for connecting, it can't magically discover vagrant settings made outside it's control.
