### ISSUE TITLE
Test-kitchen without Berkshelf

### ISSUE THREAD

**Issue by dgreene-r7** [test-kitchen/test-kitchen#1251]
## Description
I'm interested in running test-kitchen without Berkshelf. We have our own vendoring system and rather than attempt to generate and shim in a Berksfile it would be better if I could just point test-kitchen to a directory containing all of the cookbooks.

Is this possible?

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.16.0
```

**Comment by coderanger** [comment]
Yes, the berks integration is only activated if `./Berksfile` exists.

**Comment by dgreene-r7** [comment]
Yes but that leaves me with no way of specifying my cookbook directory. Seems like an all or nothing proposition.

**Comment by coderanger** [comment]
If `./cookbooks` exists, it is used, otherwise it just transfers `.` as a cookbook. You can customize all this in your own driver, ex. https://github.com/poise/poise-boiler/blob/master/lib/poise_boiler/helpers/kitchen/provisioner.rb#L38-L43.

**Comment by dgreene-r7** [comment]
That's exactly what I wanted to hear. Thanks @coderanger!
