### ISSUE TITLE
Feature request - enabled: false for suite

### ISSUE THREAD

**Issue by robertlabrie** [test-kitchen/test-kitchen#1253]
I like having `kitchen all` in my CI pipeline, but sometimes I have suites in the .kitchen.yml for sandboxing and experiments. Currently I just comment out the whole block. Would be nice to have some sort of `enabled: false` or somesuch os that when test kitchen is enumerating the suites in an "all" run it just skips over it.

**Comment by cheeseplus** [comment]
You can use `excludes` on suite and/or ERB logic inside the `.kitchen.yml` for this purpose. Or just run specific suites or use a custom `.kitchen.yml` like `.kitchen.ci.yml` for CI. The `all` behaviour is the same as no argument `kitchen test` so we're unlikely to special case that given the other mechanisms mentioned.

**Comment by robertlabrie** [comment]
Closed as RTM. TYVM!
