### ISSUE TITLE
unable to load new/custom kitchen driver in my kitchen.yml

### ISSUE THREAD

**Issue by ighouri** [test-kitchen/test-kitchen#1256]
## Description
I have created a new kitchen driver (named as kitchen-oneops) and override create/destroy methods. Then I have build it as a gem and installed it successfully in my local MAC.
```
gem list kitchen-oneops
*** LOCAL GEMS ***

kitchen-oneops (0.1.0.dev)
```
But when I put the same driver (kitchen-oneops) in my kitchen.yml config file under my cookbook directory, I am not able to load it successfully. Even I have also tried the same gem driver through Gemfile by bundle install. Appreciate any help or clue what I am doing wrong. Thanks in advance.

## Kitchen Version
```
kitchen --version
Test Kitchen version 1.16.0
```

## Ruby Version
```
ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
```

## ChefDK Version
```
chef --version
Chef Development Kit Version: 2.0.28
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.31.1
````

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

## Kitchen Output
```kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'kitchen-oneops' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## Kitchen Diagnose
https://gist.github.com/ighouri/eb6393e84fccbff7a5ce4f6e62fb531b#file-kitchen-diagnose-all

**Comment by coderanger** [comment]
You need to install the gem into ChefDK's Ruby, use `chef gem install path/to/kitchen-oneops.gem`.

**Comment by ighouri** [comment]
@coderanger I did that as well but still seeing the same failure.
```
chef gem install ~/work/kitchen-oneops/kitchen-oneops-0.1.0.dev.gem 
Successfully installed kitchen-oneops-0.1.0.dev
1 gem installed
```
```
chef gem list kitchen-oneops

*** LOCAL GEMS ***

kitchen-oneops (0.1.0.dev)
```

**Comment by coderanger** [comment]
Ahh, reading the error more closely, I think you put `name: kitchen-oneops`? If so, that should be `name: oneops`.

**Comment by ighouri** [comment]
@coderanger thanks much my bad. I have assumed driver name as 'kitchen-oneops' as I have built the gem with the same name. Anyway, changing driver name has fixed the problem. Thanks much for the help.

**Comment by coderanger** [comment]
Technically the gem name doesn't matter, we just all use `kitchen-whatever` because it helps with user expectations. The API that Kitchen itself cares about is the `name: foo` will match to `require 'kitche/driver/foo'` and a class named `Kitchen::Driver::Foo`. How you meet that API is up to you.

**Comment by ighouri** [comment]
ahh I see. Let me dig in. thanks
