### ISSUE TITLE
Setting require_chef_omnibus to false results in an error

### ISSUE THREAD

**Issue by wrightp** [test-kitchen/test-kitchen#1261]
## Description

Setting `require_chef_omnibus: false` in the kitchen.yml results in a `Kitchen::ActionFailed` exception.

According to the docs setting require_chef_omnibus to false should "not install chef-client".

> Use to install the latest version of the chef-client in a node. Set to true to install the latest version, false to not install chef-client (assumes the box already has it installed), or a version specifier like 12.19.36 to install a particular version, or simply 12 to install the latest 12.x package. When set to true or a version number, the chef_omnibus_url may be used to specify the URL of the install.sh that installs the specified version of chef-client. Default value: true.

## Kitchen Version

Verified error with versions `1.17.0` and `1.16.0`

## ChefDK Version

N/A

## Ruby Version

2.3

## Platform Version

OSX 10.12

# Replication Case

1. Execute a converge to install chef

2. Update kitchen.yml provisioner options as so:

```yml
    provisioner:
      require_chef_omnibus: false
```

3. Execute a converge

### stdout
```
-----> Starting Kitchen (v1.17.0)
-----> Converging <default-ubuntu-1604>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <default-ubuntu-1604>
       sudo: /bin/chef-client: command not found
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-1604>.  Please see .kitchen/logs/default-ubuntu-1604.log for more details
>>>>>> ----------------------
```

[Kitchen log](https://gist.github.com/wrightp/d86373c4a83a228376b058142a6d8ac3#file-kitchen-log)

## Kitchen Diagnose

[Diag](https://gist.github.com/wrightp/d86373c4a83a228376b058142a6d8ac3#file-diag-all)

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by coderanger** [comment]
Yes, that is correct. You can see the error in your output, `sudo: /bin/chef-client: command not found`. You told it to not install chef-client, so it didn't.

**Comment by wrightp** [comment]
@coderanger Ok. I was expecting converge to finish without error. The part I missed in the steps is to run converge without provisioner options where require_chef_omnibus is true. This installs chef-client. Then by setting require_chef_omnibus to false it seems reasonable that converge would finish since chef had been previously installed. If this is correct then how is this setting intended to be used. Running a converge just to raise an error doesn't seem correct.

**Comment by coderanger** [comment]
You would have to specify the path to the previously installed chef-client executable: `chef_client_path: /usr/bin/chef-client` for the default case.

**Comment by wrightp** [comment]
Thank you.
