### ISSUE TITLE
Retry chef run after receiving WSMAN ERROR CODE: 995 in test-kitchen

### ISSUE THREAD

**Issue by jhtech2000** [test-kitchen/test-kitchen#1272]
## Description

I'm trying to deploy a Microsoft JEA (Just Enough Administration) endpoint and during the run, the WinRM service needs to restart. Under the chef_zero provisioner, I am using the retry_on_exit_code option to capture the error code and allow the chef run to try again. I've tried using error codes 1, 2, 3, 20 and it continues to error out and not retry the run.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

Test Kitchen version 1.16.0

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

Chef Development Kit Version: 1.5.0
chef-client version: 12.21.2
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
# Copy-paste your results here
```

## Platform Version

Windows 10 1703

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

[WinRM] 500 returned in cleanup with error: Bad HTTP response returned from server. Body(if present): (500).
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [[WSMAN ERROR CODE: 995]: <f:WSManFault Code='995' Machine='127.0.0.1' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The I/
O operation has been aborted because of either a thread exit or an application request. </f:Message></f:WSManFault>] on default-gnf-windows-2012-r2-std
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

Kitchen Log Gist: https://gist.github.com/jhtech2000/db0ebd748c15cfcbd48c9055be8e4ba8
Converge Log Gist: https://gist.github.com/jhtech2000/17872589bd59a6dfa189ecc96e06ecf9

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

Kitchen Diagnose Log Gist: https://gist.github.com/jhtech2000/32121ded7b8dbc88b02249e2aeae811e

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by cheeseplus** [comment]
In order to troubleshoot this one we'd actually need the `.kitchen.yml` as usually it's one of a few settings that is incorrect. Presently you can check https://github.com/test-kitchen/kitchen-docs/issues/65 for more information as to reboot tuning.

**Comment by cheeseplus** [comment]
Not enough information provided to diagnose so closing after a month of non-response.
