### ISSUE TITLE
:paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.

### ISSUE THREAD

**Issue by aw230012** [test-kitchen/test-kitchen#1277]
## Description

I'm trying to setup test kitchen to begin testing Chef recipes.  When I try to create a virtualbox with Kitchen, I receive the following error, ":paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed."   Kitchen then endlessly retries.  Even though the VirtualBox creates, Kitchen thinks the create failed so I can no longer run any Kitchen commands against the VirtualBox.  My Oracle VirtualBox version is 5.1.28 r117968 (Qt5.6.2).

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
1.17.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
2.3.1
```
## Platform Version

Microsoft Windows 10 Version 1703 (OS Build 15063.608)

## Replication Case

Install the recent versions of ChefDK, Vagrant, and Oracle VirtualBox.  
Open ChefDK to run an instance of PowerShell.
Create a new directory named Kitchen and cd to it.
Run kitchen init --create-gemfile
Run bundle install
Run kitchen create default-ubuntu-1404
You can also run kitchen converge default-ubuntu-1404 as well.  You'll see similar results.
## Kitchen Output

```ruby
-----> Starting Kitchen (v1.17.0)
-----> Creating <default-ubuntu-1404>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Box 'bento/ubuntu-14.04' could not be found. Attempting to find and install...
           default: Box Provider: virtualbox
           default: Box Version: >= 0
       ==> default: Loading metadata for box 'bento/ubuntu-14.04'
           default: URL: https://vagrantcloud.com/bento/ubuntu-14.04
       ==> default: Adding box 'bento/ubuntu-14.04' (v201708.22.0) for provider: virtualbox
           default: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-14.04/versions/201708.22.0/providers/virtualbox.box
    default:
       ==> default: Successfully added box 'bento/ubuntu-14.04' (v201708.22.0) for 'virtualbox'!
       ==> default: Importing base box 'bento/ubuntu-14.04'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'bento/ubuntu-14.04' is up to date...
       ==> default: Setting the name of the VM: default-ubuntu-1404_default_1505841234622_58304
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default:
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default:
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Mounting shared folders...
           default: /tmp/omnibus/cache => C:/Users/ajwood/.kitchen/cache
       ==> default: Machine not provisioned because `--no-provision` is specified.
:paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.
       Waiting for SSH service on 127.0.0.1:2222, retrying in 3 seconds
```
**Please note the retries appear to be endless.  They will not stop until the batch is terminated.**

## Kitchen Diagnose

https://gist.github.com/aw230012/02309c4e05c6fe5d6d7555f8fd291ad0

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by cheeseplus** [comment]
It seems that net-ssh chose to rename a key in a minor release which while for decent reasons is not really a cool SemVer thing to do https://github.com/net-ssh/net-ssh/pull/524

**Comment by cheeseplus** [comment]
Looking at this though I'm not sure that is strictly the issue, at least as written their code should still let the deprecated option work so this could be something else.

**Comment by cheeseplus** [comment]
What version of ChefDK?

**Comment by cheeseplus** [comment]
Fixed by https://github.com/test-kitchen/test-kitchen/pull/1283 and in ChefDK by https://github.com/chef/chef-dk/pull/1406

**Comment by cheeseplus** [comment]
The above fix was temporary but in our investigation this warning likely had little to do with the actual error you are experiencing. We only thought it was related due to some issues with our builder that appeared the same but these are definitely

We've merged https://github.com/test-kitchen/test-kitchen/pull/1281 which updates the key and removes the warning. I'm going to close this issue out but please feel free to open a new one if you're experiencing issues with ChefDK 2.3.4+.
