### ISSUE TITLE
Question: Multiple Verifiers?

### ISSUE THREAD

**Issue by con5cience** [test-kitchen/test-kitchen#1288]
## Description

I'd like to run multiple verifiers on a single instance/suite. I have both `awspec` and `serverspec` verifiers installed and would like to run two sets of tests on the same instance (one for server attributes and another for AWS attributes). I can't find any documentation on how to pull this off, and it also looks like `verifer` in `.kitchen.yml` doesn't accept a list/array. I would love it if someone could drop a big fat knowledge bomb on my face. Thanks in advance!

## Kitchen Version

```
Test Kitchen version 1.15.0
```

## Ruby Version

```
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

## Platform Version

Fedora 26.

**Comment by lamont-granquist** [comment]
probably a dup of #329 which covers multiple provisioners, and should cover multiple verifiers

**Comment by cheeseplus** [comment]
There is no way to do multiple verifiers in a single test at this time. You can setup two suites, each using a different verifier but as mentioned this is a dup of #329 and more generally https://github.com/chef/chef-rfc/blob/master/rfc084-test-kitchen-multi.md
