### ISSUE TITLE
Test-kitchen should not `require berkshelf` and should use berks as a CLI tool and not a ruby library

### ISSUE THREAD

**Issue by lamont-granquist** [test-kitchen/test-kitchen#1307]
Using external code as a ruby library is correct for the 80% case, but entirely fails with berkshelf.

By requiring berkshelf it produces a hard dep on all the dependencies of berkshelf and pulls all of them into the project.  By shelling out another ruby process will be fired up which decouples the dependencies.

It also simplifies the berkshelf API to the public CLI rather than anything someone can poke in the Berkshelf namespace (and for example, we're ripping all of the Ridley namespace out of berkshelf in a minor release).

**Comment by lamont-granquist** [comment]
Also note that berkshelf declares in its README that it should be used as a CLI and not as a ruby library:

https://github.com/berkshelf/berkshelf#cli-usage

**Comment by coderanger** [comment]
+INT_MAX, we did this right for Policyfiles, just need to go back and fix the berks integration.

**Comment by danielcbright** [comment]
I know this is an older issue, but wanted to check-in and see if there has been anything done/planned to fix the underlying problem, which as I understand it is the way `berks` is called is as a library instead of as a shell-out, causing conflicts when multiple suites are used that may depend on different versions of a cookbook

**Comment by stevenoneill** [comment]
For instance, here is a sample/cleansed summary output from running `kitchen converge -c` against a cookbook with 8 test suites.
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 2 actions failed.
>>>>>>     Failed to complete #converge action: [An error occurred while reading the Berksfile:

  No such file or directory @ rb_sysopen - Enterprise_Root_CA.crt] on default-rhel-7-stable
>>>>>>     Failed to complete #converge action: [An error occurred while reading the Berksfile:

  No such file or directory @ rb_sysopen - Enterprise_Root_CA.crt] on default-windows-2016-legacy
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

user@host MINGW64 ~/acme_cookbook ((3527526...))
$ kitchen list
Instance                       Driver  Provisioner  Verifier  Transport  Last Action  Last Error
default-windows-2012r2-legacy  Ec2     ChefZero     Inspec    Winrm      Converged    <None>
default-windows-2012r2-stable  Ec2     ChefZero     Inspec    Winrm      Converged    <None>
default-windows-2016-legacy    Ec2     ChefZero     Inspec    Winrm      Created      Berkshelf::BerksfileReadError
default-windows-2016-stable    Ec2     ChefZero     Inspec    Winrm      Converged    <None>
default-rhel-7-legacy          Ec2     ChefZero     Inspec    Ssh        Converged    <None>
default-rhel-7-stable          Ec2     ChefZero     Inspec    Ssh        Created      Berkshelf::BerksfileReadError
default-rhel-6-legacy          Ec2     ChefZero     Inspec    Ssh        Converged    <None>
default-rhel-6-stable          Ec2     ChefZero     Inspec    Ssh        Converged    <None>
```

I'd be happy to provide a more detailed/less redacted log via Chef Support .

There is a different class of concurrency error after this as well during `kitchen verify -c`, but this is the first issue in the chain.

Ultimately, the expected outcome is to be able to run `kitchen test -c` without any workarounds, gimmicks, band-aids, hacky tricks, etc....

**Comment by lamont-granquist** [comment]
@stevenoneill i think you're missing a whole lot of context as to why that output was pasted in this issue.  if there's a zendesk support ticket associated with this issue or something, some of that context should get pasted in here.

**Comment by stevenoneill** [comment]
> @stevenoneill i think you're missing a whole lot of context as to why that output was pasted in this issue. if there's a zendesk support ticket associated with this issue or something, some of that context should get pasted in here.

@danielcbright asked me directly to drop that in there

**Comment by danielcbright** [comment]
@lamont-granquist, I asked @stevenoneill to update this issue with a relevant example of the results of this issue when run against multiple test suites to illustrate the problem one might run into when converging multiple nodes at the same time if there are conflicts within Berkshelf. I'll be looking through the code soon to see what would need to be updated to change the `berkshelf` library calls to actual `shell-out` commands in the near future too.

**Comment by lamont-granquist** [comment]
Right so that is coming from multiple internal Berkshelf operations stomping all over each other because berkshelf itself is not threadsafe.  So forking and exec'ing berkshelf would presumably fix it.  And https://github.com/berkshelf/berkshelf/issues/1798 is the background on that bug.

I have some reservations that it may not be end of fixing that particular bug since the operations could still stomp all over each others external state on the filesystem, but this is certainly the start of fixing that.  May still need to mutex around the shell outs or may need to make certain that everyone has private directories in the filesystem.

**Comment by stevenoneill-jmfamily** [comment]
It appears that, at least for our use cases, we can work around this issue by switching to a Policyfile strictly for testing in kitchen.  We create a Policyfile.rb, update kitchen.yml to use the policyfile instead of our typical run_list settings, and after a whole half day of usage we haven't experienced any issues with `kitchen converge -c` using this method.

**Comment by lamont-granquist** [comment]
+1 for recommending Policyfiles.  that is the way of the future.

**Comment by sean-nixon** [comment]
Is there any known workaround for this to enable concurrent testing? Not being able to test concurrently is pretty devastating for test times.

**Comment by lamont-granquist** [comment]
Not other than switching to Policyfiles (which is probably the right answer anyway).

**Comment by tas50** [comment]
I'm going to close this one out as a wont-fix since we're not investing further effort into Berkshelf at this point. Yes there are known problems, but the solution is really to move off Berkshelf and use Policyfiles instead which is being actively improved
