### ISSUE TITLE
Configuration data can't unzip to kitchen\configuration folder on target instance (Windows) 

### ISSUE THREAD

**Issue by gl40014001** [test-kitchen/test-kitchen#1311]
## Description
TK errors out on a kitchen converge.

Configuration data isn't being unzipped to kitchen\configuration folder on target instance (Windows) following a kitchen create and kitchen converge.

TK appears to zip up the files on source machine and transfer the zipped files to c:\users\vagrant\appdata\temp\winrm-upload on target instance..but doesn't seem to go any further.

Looking more closely with help from a nice guy on Powershell user group slack forum..
The zip files produced can't be unzipped in Windows File explorer on either the host or the target VM (SUT).   

## Kitchen Version
1.17.0

## ChefDK Version
2.3.4

## Platform Version
Windows 2016  build 1607

## Replication Case

Based on example here:
https://github.com/smurawski/xWebAdministration/blob/kitchen_test_example/.kitchen.yml

but targeting a Win 2016 vagrant instance,

On a Win 2016 server
1. Install Vagrant
2. Install  ChefDK
3. Install TK 1.17 with kitchen-dsc 
4. Create a Test Kitchen folder
2. Clone content of above link in TK folder
3. Amend kitchen.yml as below
4. type kitchen create 
5. type kitchen converge

kitchen.yml :
`---
driver:
  name: vagrant
  linked_clones: true
  gui: false
  communicator: winrm
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: dsc

transport:
  name: winrm

verifier:
  name: pester
  test_folder: Tests/Integration

platforms:
  - name: windows-2016
    driver:
      box: jacqinthebox/windowsserver2016
      network: 
        - ["forwarded_port", {guest: 80, host: 8081}]
    provisioner:
      dsc_local_configuration_manager_version: wmf5
      
suites:
  - name: MSFT_xWebsite
    provisioner: 
      configuration_script_folder: Tests/Integration/MSFT_xWebsite
      configuration_script: MSFT_xWebsite.config.ps1
      configuration_name: MSFT_xWebsite_Config
`

## Kitchen Output
Gist of kitchen.yaml and kitchen converge --log-level=diagnose
https://gist.github.com/gl40014001/8f4343a1de8cd84b85fa862434e92cd3

## Kitchen Diagnose
https://gist.github.com/gl40014001/8f4343a1de8cd84b85fa862434e92cd3#file-kitchen-diagnose-all

**Comment by cheeseplus** [comment]
This was resolved by #1284 and is in test-kitchen 1.18.0+
