### ISSUE TITLE
After reboot, client.rb missing?

### ISSUE THREAD

**Issue by lavahot** [test-kitchen/test-kitchen#1315]
## Description

After a reboot, TK gives an error that would seem to indicate that /tmp has been cleared.

## Kitchen Version

```ruby
Test Kitchen version 1.17.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1
```

## Platform Version

macOS 10.12.15

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

cookbook:
```ruby
reboot 'reboot system' do
  delay_mins 1
  retries 2
  action :reboot_now
  reason 'Reboot to receive bacon'
end
```

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```
*** System shutdown message from vagrant@macmini01 ***
System going down in 1 minute

<My reboot reason message here>

WARN: ********************************
WARN: Did not find config file: /tmp/kitchen/client.rb, using command line options.
WARN: ********************************
WARN: No cookbooks directory found at or above current directory. Assuming /Users/vagrant.
WARN: No cookbooks directory found at or above current directory. Assuming /Users/vagrant.
FATAL: Cannot load configuration from /tmp/kitchen/dna.json
FATAL: Cannot load configuration from /tmp/kitchen/dna.json
```

## Kitchen Diagnose

https://gist.github.com/anonymous/0fdb58787f7b6f32a67e4f1a2398efae

**Comment by coderanger** [comment]
Most Linux images these days use a RAM-baacked tmpfs for `/tmp`, meaning it will be gone after a reboot. You'll need to either use a different kitchen root or use an image that doesn't use a tmpfs for `/tmp`.

**Comment by lavahot** [comment]
It's a macOS image, but it must be the same issue. Thank you!

**Comment by coderanger** [comment]
The config snippet to fix it, since I'm not sure this is actually documented:

```yaml
provisioner:
  # whatever you have already
  root_path: /somewhere/else
```

Anywhere we can write to via SSH should work, though a few drivers like Dokken and K8s don't allow it.

**Comment by lavahot** [comment]
It's documented in the kitchen.yml documentation. Not sure about a good path though. /etc/kitchen and /opt/kitchen do not work as there's no access there. The permissions don't seem to be different between /tmp and these so I'm not sure how to identify a better candidate. I'm trying /var/tmp/kitchen right now and I'll let you know how that goes.

**Comment by coderanger** [comment]
I take a more liberal view on FHS when it comes to ephemeral testing stuff and would probably just use `/kitchen` because why not (barring perms issues) :)

**Comment by lavahot** [comment]
`/kitchen` did not work (permissions).  `/var/tmp/kitchen` _did_ work.
