### ISSUE TITLE
Rakefile is missing berkshelf gem

### ISSUE THREAD

**Issue by anniehedgpeth** [test-kitchen/test-kitchen#1316]
## Description

I want to run kitchen in a rakefile, and if a Berksfile is present, then I get the following error, and it will not run. It runs normally without a Berksfile.

```Kitchen error: Could not load or activate Berkshelf (Unable to activate chef-13.4.19, because chef-config-13.6.0 conflicts with chef-config (= 13.4.19))```

## Kitchen Version

kitchen version: 1.17.0

## ChefDK Version
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1

## Platform Version
MacOS 10.13.1

## Replication Case
[berkshelf_bug.zip](https://github.com/test-kitchen/test-kitchen/files/1469595/berkshelf_bug.zip)

I generated a generic cookbook with a `rakefile` that looks like this: 
```
namespace :test do
  begin
		require 'kitchen/rake_tasks'
		
    desc 'Run kitchen integration tests'
    Kitchen::RakeTasks.new
  rescue StandardError => e
    puts ">>> Kitchen error: #{e}, omitting #{task.name}" unless ENV['CI']
	end
	task all: ['test:kitchen:all']
end
```
I get the same error when running `/opt/chefdk/embedded/bin/rake -T`

## Kitchen Output

Kitchen is working normally, but when I run rake, I get this (reproduced on another machine, too):

```
➜  berkshelf_bug git:(master) chef exec rake -T
!!!!!! The `berkshelf' gem is missing and must be installed or cannot be properly activated. Run `gem install berkshelf` or add the following to your Gemfile if you are using Bundler: `gem 'berkshelf'`.
>>> Kitchen error: Could not load or activate Berkshelf (Unable to activate chef-13.4.19, because chef-config-13.6.0 conflicts with chef-config (= 13.4.19)), omitting test:
rake test:  # Run kitchen integration tests
```

**Comment by coderanger** [comment]
Please use the standard way of running Kitchen, not the RakeTasks helper. It should be removed most likely.

```ruby
task 'test:kitchen' do
  sh 'kitchen test -d always'
end
```

**Comment by cheeseplus** [comment]
Closing this one but tracking the work to remove these helpers as part of https://github.com/test-kitchen/test-kitchen/issues/1307
