### ISSUE TITLE
Support reverse port forwarding when connecting via SSH transport

### ISSUE THREAD

**Issue by thomasriley** [test-kitchen/test-kitchen#1322]
## Description

Would be interested on your thoughts of an improvement I have been thinking about. It would be useful when calling SSH if it was possible to configure SSH to allow a `-R` port forward from the host system to the guest system.

For example, I am developing from my laptop a cookbook that installs Kibana and I have a Elasticsearch instance running on my laptop via docker compose. The Elasticsearch endpoint is available on the host system at localhost:9200 as configure in my docker-compose yml.

If you then set `-R 9200:localhost:9200` as an SSH option when connecting to the test kitchen provisioned VM, the elasticsearch endpoint becomes available at localhost:9200 on the guess system too. 

I feel this would be useful for launching and connecting to dependancies running outside of test kitchen that are required during development & testing via test kitchen provisioned systems.

Would be interested to hear your thoughts on this. Would also be interested to hear if there is a better way to do what I am trying to achieve! 

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.17.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.18.0
inspec version: 1.36.1
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```

## Platform Version

```ruby
Developing on Mac OX 10.12.6
```

**Comment by coderanger** [comment]
Kitchen is only built for fully self-contained testing. We do not recommend it for the use cases you mention. Unless @cheeseplus disagrees, I think this is out of scope for Kitchen.

**Comment by thomasriley** [comment]
@coderanger That is what I am trying to achieve in this instance, I do not want test-kitchen provisioned services to communicate with a dependancy outside of my self-contained testing environment (my laptop). 

For example, writing the cookbook for Kibana it must connect to an Elasticsearch instance when starting the service. I do not want to point it at an actual non-prod/production Elasticsearch node, but instead at a disposable node that is launched as part of my tests (such as with docker-compose on my development laptop alongside test-kitchen). 

Appreciate this may go against the principles of what test-kitchen does, in which case can anyone suggest an alternative way of achieving this?

ps. thanks for the amazing fast reply @coderanger !

**Comment by coderanger** [comment]
The current way to handle that is to launch both components in the same test instance. We are looking at improving that but it's a _very_ long term project.

**Comment by thomasriley** [comment]
I had been using this apporach, however unless I am missing something you have to set unnecessary cookbook dependancies in the cookbook metadata that you are developing for it to work.

For example, Kibana depends on using an Elasticsearch instances for testing purposes, but I do not want my Kibana cookbook to actually depend on the Elasticsearch cookbook and beyond the realms of testing these are two separate systems that do not depend on each other within the chef code.

Hence why I started exploring other options and was wondering how I could gain connectivity from my test-kitchen vagrant instance to a docker container on the same laptop, which was provisioned via docker-compose.

**Comment by coderanger** [comment]
Test-only dependencies go only in the `Berksfile` for exactly that reason :) Usually something like this:

```ruby
group :test do
  cookbook 'kibana'
end
```

**Comment by thomasriley** [comment]
Thanks for the advice! This certainly helps with my testing however not a massive fan of the test-only dependancies affecting the test environment in a way that would not occur when deploying Chef to an actual production system.

Look forward to hearing the improvements that are coming in the future on this :) have you shared any details around this yet? :)

**Comment by coderanger** [comment]
This is all under the general banner of "multi-system testing" and has been on everyone's want list for pretty much as long as TK has existed. We wrote up a plan over at https://github.com/chef/chef-rfc/blob/master/rfc084-test-kitchen-multi.md but it's mostly there in the hopes that when we do get some cycles to implement it, we're slightly more sure it will cover the use cases. So check that out and see if it does what you need, and maybe someday it will be an option. For now though, either do it all on one VM, or just accept that multi-server stuff with be pretty hacky and tied to one particular set of implementation requirements.

**Comment by cheeseplus** [comment]
This is well answered and I am in agreement with @coderanger here that the feature as requested initially is out of scope. Since we're already tracking multi-node I'm closing this for now but feel free to ask/suggest/re-open if need be.
