### ISSUE TITLE
No such cookbook error with kitchen 1.17.0

### ISSUE THREAD

**Issue by martinmosegaard** [test-kitchen/test-kitchen#1323]
## Description

When I run `kitchen converge`, I consistently get a `No such cookbook` error.

I have upgraded ChefDK from 1.2.22 to 2.3.4, which was an upgrade to Kitchen 1.17.0.

I use a Berksfile like this:

```
source 'https://myown.supermarket'
metadata
```

and vagrant / chef_zero in .kitchen.yml

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
kitchen version: 1.17.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (...)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1
```

## Platform Version

Windows 2012 R2

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
Missing Cookbooks:
-----------------
No such cookbook: mycookbook
```

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by cheeseplus** [comment]
You'll want to grab [ChefDK 2.4.17](https://downloads.chef.io/chefdk/2.4.17) - the bug you're hitting has to do with upstream winrm-fs dependencies that have been resolved already but wasn't in a 'stable' channel package until 2.4.17.

**Comment by martinmosegaard** [comment]
Thanks - Does it mean in practice that ChefDK 2.3.4 is not functional on Windows workstations or with Windows Kitchen VMs?

**Comment by cheeseplus** [comment]
The bug is specific to winrm-fs and the version packaged with test-kitchen pre-1.19.0 so it's not the whole ChefDK just that piece for that version.
