### ISSUE TITLE
Disk space is being used up by vmdk upon creation of suite

### ISSUE THREAD

**Issue by damm** [test-kitchen/test-kitchen#1326]
## Description

Briefly describe the issue

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.19.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

## Platform Version

Mac OS X, High Sierra 10.13.1
VirtualBox 5.1.30

## Replication Case

Occasionally when creating the suite it stalls and eventually a popup occurs telling me I have run out of disk space.
1. kitchen create `varnish-` in this case for me is all it takes.  1 out of say 5 tries it will fill up my disk space.  

## How I clean up from this

1. Remove the offending files on the disk.  This will not free up the space until VirtualBox is killed
```shell
Phlegethon :: VirtualBox VMs/varnish-apache-edge-ubuntu-1604_default_1512093491996_31575 » ls -lh
total 260786288
drwx------  3 slikens  staff    96B Nov 30 17:58 Logs
-rw-------  1 slikens  staff   663G Nov 30 17:58 ubuntu-16.04-amd64-disk001.vmdk
-rw-------  1 slikens  staff   3.0K Nov 30 17:58 varnish-apache-edge-ubuntu-1604_default_1512093491996_31575.vbox
-rw-------  1 slikens  staff   3.0K Nov 30 17:58 varnish-apache-edge-ubuntu-1604_default_1512093491996_31575.vbox-prev
Phlegethon :: VirtualBox VMs/varnish-apache-edge-ubuntu-1604_default_1512093491996_31575 » rm -rf *
```
2. Kill VirtualBox 
```shell
slikens          41781  99.9  5.3  5307348 886912   ??  R     5:58PM   2:11.14 /Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless --comment varnish-apache-edge-ubuntu-1604_default_1512093491996_31575 --startvm 545d44f9-3253-4e22-bd80-a30d316a7d4d --vrde config
slikens          42151   0.0  0.0  4287224   1048 s008  R+    6:02PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn Virt
slikens          40483   0.0  0.1  4423252  23924   ??  S     5:50PM   0:19.19 /Applications/VirtualBox.app/Contents/MacOS/VBoxSVC --auto-shutdown
slikens          40481   0.0  0.1  4290900  12292   ??  S     5:50PM   0:02.37 /Applications/VirtualBox.app/Contents/MacOS/VBoxXPCOMIPCD
kill -6 41781
kill -6 40481
kill -6 40483
Phlegethon :: VirtualBox VMs/varnish-apache-edge-ubuntu-1604_default_1512093491996_31575 » sync
Phlegethon :: ~ » cd ~
Phlegethon :: ~ » df -h
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   234Gi  108Gi  122Gi    47% 3073635 9223372036851702172    0%   /
devfs          378Ki  378Ki    0Bi   100%    1306                   0  100%   /dev
```

## Kitchen Output

```ruby
Phlegethon :: mubi/chef » kitchen create varnish-
-----> Starting Kitchen (v1.19.2)
-----> Creating <varnish-apache-edge-ubuntu-1604>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'bento/ubuntu-16.04'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
       ==> default: Setting the name of the VM: varnish-apache-edge-ubuntu-1604_default_1512093491996_31575
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Remote connection disconnect. Retrying...
           default:
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default:
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Mounting shared folders...
           default: /tmp/omnibus/cache => /Users/slikens/.kitchen/cache
^C^C^Z
```

## Kitchen Diagnose

This is a pretty good portion of my .kitchen.yml this started happening when I updated ChefDK recently.  If necessary I can reduce this to a smaller test case that I would be willing to share.  It's just very large and nothing secret just don't feel like sharing it.

## NOTE:

I suspect this is related to the vagrant plugin more than the core.  It could be because I am running too new of a VirtualBox? 

It's a sink on my time and I would hate to not report it; if others experience the same behavior.

**Comment by cheeseplus** [comment]
This has a lot more to do with the mechanics of Vagrant and Virtualbox less than kitchen.

```
-rw-------  1 slikens  staff   663G Nov 30 17:58 ubuntu-16.04-amd64-disk001.vmdk
```

The problem here appears to be how big you've grown the VMDK but that's not something kitchen is doing.

**Comment by damm** [comment]
@cheeseplus I agree it has to do with Vagrant and Virtualbox less than kitchen but I wasn't entirely sure where to start with this issue (where to post it).

It's an initial creation so I am not doing anything at all.  It's a pretty old Vagrant so I'm going to update it and see if the issue persists.

I've gotten pretty good at handling it; this happens during the initial `kitchen create` phase so if I can't create the box within a certain time period I can ^Z it and kill off the virtualbox processes and then nuke the files it leaves behind.

**Comment by cheeseplus** [comment]
If this is something that kitchen-vagrant is doing please feel free to open an issue over at https://github.com/test-kitchen/kitchen-vagrant but this is definitely not something core test-kitchen is capable of doing so I'm closing this here.

I suspect there's something wrong at another layer if these images are blowing out to that size but you could also check `~/.vagrant.d/boxes` to see if they are starting off oversized for whatever reason. If you can find something conclusive there please do open an issue on the other repo and we can dig into it.
