### ISSUE TITLE
kitchen create returns "remote user name not available"

### ISSUE THREAD

**Issue by nelsonjr** [test-kitchen/test-kitchen#1332]
## Description

When running `kitchen create` the run fails with `remote user name not available`.

Tried with both 'vagrant' and 'gce' drivers with same effects. VM gets created but SSH attempts fail with the above message.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
$ kitchen --version
Test Kitchen version 1.19.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
$ chef --version
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
$ ruby --version
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

1. Run 'kitchen create'
2. that's it

## Kitchen Output

https://gist.github.com/nelsonjr/77aae7f144f6545c3300e57994e7fad5

## Kitchen Diagnose

https://gist.github.com/nelsonjr/85ab012208c2583215560a7e5afe3fab

**Comment by cheeseplus** [comment]
I recall this was running on Debian unstable? Could we get the distro version information, `uname -a`, and the specific URL/installer that was used for ChefDK. I want to make sure this isn't a packaging or ABI related issue.

**Comment by nelsonjr** [comment]
```
$ uname -a
Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```

ChefDK was downloaded from https://packages.chef.io/files/current/chefdk/2.4.17/debian/8/chefdk_2.4.17-1_amd64.deb

**Comment by cheeseplus** [comment]
I setup a Debian 9 instance and was unable to reproduce the error. Given the location of `remote_user` in the Net:SSH code https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/proxy/command.rb#L45-L49  do you have anything configured in the ssh config (~/.ssh/config) with regard to ProxyCommand?

**Comment by nelsonjr** [comment]
JJ and I narrowed the problem down: kitchen create fails if the /etc/ssh/ssh_config has a ProxyCommand specified. Although the problem seems related to feature request #829, in our case the proxy is not required. If we delete the /etc/ssh/ssh_config file altogether it then works.

So Kitchen should either work with a ProxyCommand or completely ignore it.

Currently it fails with its presence.

**Comment by robbkidd** [comment]
@nelsonjr Was your `ProxyCommand` set under a `Host` entry with some restrictions on what domains or subnets ought to have SSH connections proxied?

I'm not sure what Test Kitchen itself can do about a local SSH proxy setting that is configured to match hosts broadly enough that it catches and proxies connections to localhost. We _might_ be able to catch the `remote user name not available` error bubbling up from Net::SSH and provide a warning "this error can be caused by SSH connections getting sent to a proxy host."

The change in #1208—adding the ability to set an alternate ssh_config file—might also be helpful as a workaround when a user's default ssh_config can't be modified to less-aggressively match hosts for proxying.

**Comment by nelsonjr** [comment]
Agree, in part. The problem is that the ProxyCommand works:

- Works on plain `ssh`
- Works on `gcloud compute ssh`

And most importantly:

- Works on `kitchen login` and `kitchen converge`

So the curious part here is why kitchen works for login and converge and not for create?

**Comment by cheeseplus** [comment]
Neither of those first two use Net::SSH however which is the crux of the issue, it's always lagged official clients and while it tries to be the same it often doesn't have the same coverage/support. 

I am interested in why `kitchen login` and `kitchen converge` don't work but would need a sample excerpt of the ssh config in question to validate any testing.

**Comment by nelsonjr** [comment]
@cheeseplus `kitchen login` and `kitchen converge` *always* work, with or without the ProxyCommand. If I delete the ssh_config file and run `kitchen create` then I can put the file back with ProxyCommand and run `kitchen converge` without issues.

The problem is limited to `kitchen create` only AFAIK.
