### ISSUE TITLE
kitchen "exec" transport: announce environment variables

### ISSUE THREAD

**Issue by guskovd** [test-kitchen/test-kitchen#1333]
It would be nice to provide an environment variables for "exec" transport,
just like it's done in shell verifier:
https://github.com/test-kitchen/test-kitchen/blob/a2939733cb6cc464c08dbd56416302e9016aa467/lib/kitchen/verifier/shell.rb#L87
--
otherwise, it is not very clear how the script of the transport should interact with the instance

**Comment by coderanger** [comment]
The `exec` transport doesn't have an instance to interact with, it is running everything locally.

**Comment by guskovd** [comment]
at the moment it is.
But why not pass the driver status information to the transport script?
--
If this is done, then it will be possible to understand transport as a script:
```bash
# scp /path/to/local/folder $KITCHEN_USERNAME@KITCHEN_HOST:/tmp/kitchen
# or
# rsync ...
# unison ...
```
--
perhaps worth it to call it as a "shell" transport. There is already a shell provisioner and a shell verifier. why not make a similar transport?

**Comment by coderanger** [comment]
Please explain what you are trying to accomplish that you currently cannot, I don't understand the question.

**Comment by guskovd** [comment]
for some reason I'm not satisfied with plug-ins such as kitchen-sync, kithchen-transport-rsync.
Many entities in them are hardcoded, they are poorly configurable. I can not use them (for example) with windows guest, although rsync on windows works fine.
--
With a similar one I encountered, for example, when I used verifier kitchen-inspec. After searching the test-kitchen code, I found a shell-verifier.
And frankly, I can not understand why you need a kitchen-inspec. I can send all possible options to inspec

**Comment by guskovd** [comment]
The first thing I thought about when there were problems: "Is there a shell transport?"

**Comment by coderanger** [comment]
I think maybe you are assuming that the `exec` transport allows some kind of arbitrary scripting for the transport commands? If so, that is not what it does. It literally uses the local machine as the test target instance.

**Comment by coderanger** [comment]
Also AFAIK the SFTP mode of kitchen-sync works fine on Windows, you just need an SFTP server.

**Comment by guskovd** [comment]
> perhaps worth it to call it as a "shell" transport. There is already a shell provisioner and a shell verifier. why not make a similar transport?

**Comment by guskovd** [comment]
> Also AFAIK the SFTP mode of kitchen-sync works fine on Windows, you just need an SFTP server.
it was just an example.
Many people use the cifs mounts + rsync to synchronize. 
There are many things you can do to optimize the configuration testing. But I'm not sure that all these entities need to be stitched into a ruby code

**Comment by coderanger** [comment]
Okay, but still, I don't think this transport is what you are looking for :) It sounds like what you want is to write your own transport plugin.

**Comment by guskovd** [comment]
Well, if you are not inspired by my idea, I can try to write my own plugin

**Comment by coderanger** [comment]
I'm still unclear what you are actually suggesting, and I am pretty sure you are mixing up the shell provisioner/verifier and the exec transport. They do very very different things.

**Comment by guskovd** [comment]
the main thing that did not suit me in exec transport is that I could not get the ip address of the instance from the script.
Of course, this can be a ruby script, from which you can get the name of the instance via ppid, and then through the call to the ruby library, find out the state of the instance.
But it's somehow stupid :)

**Comment by guskovd** [comment]
can you suggest something better?

**Comment by coderanger** [comment]
The `exec` transport does not have "a script". That is not a thing. As I said, I think you want to build your own custom transport and are trying to use some kind of a simple script instead, but that is not a thing Test Kitchen supports. You'll have to write an actual plugin.

**Comment by guskovd** [comment]
ok, I understand you
