### ISSUE TITLE
Memory Usage (Windows, vagrant-hyperv)

### ISSUE THREAD

**Issue by dmlb2000** [test-kitchen/test-kitchen#1334]
## Description

Kitchen memory usage through many suites

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.19.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
```

## Platform Version

I'm using Windows 10 and kitchen-vagrant backed by Hyper-V

## Replication Case

I've got a chef cookbook with 55 different suite/platform combinations. I'm trying to run them all serially to test them but it is unsuccessful and returns to a prompt after a time not completing all the runs. This is usually during the Berkself resolution of the cookbook dependencies. 

I've noticed that during this time it's taking up large amounts of memory (2+Gb) and every additional suite it runs takes up about 80-100Mb more memory. This seems bad to me...

## Kitchen Output

There's not much output when it fails. 

```ruby
-----> Converging <wrapper-policy-ubuntu-1604>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
PS C:\Users\dmlb2\git\dmlb2000\pacifica-cookbook>
```

## Kitchen Diagnose

I'm not sure this is relevant but I'll add it if requested.

## NOTE:

What I'd like to see is if anyone else has noticed the memory usage as kitchen is running especially on Windows 10 as I don't remember seeing these issues running on Linux. I'd like to know why it needs to keep so much in memory or if there's something going on at a lower level that needs to be fixed...

I've seen older versions of ChefDK ruby dump with `[can't create Thread: Not enough space]` which seems bad to me as well.

**Comment by coderanger** [comment]
What command line are you running when you test this? If you do `kitchen test --delete always`, it might help since that won't leave failed VMs running as it proceeds.

**Comment by dmlb2000** [comment]
I'm running `kitchen test -d always` yes...

**Comment by dmlb2000** [comment]
I've got a screen capture of the taskmgr output.

![memory usage kitchen](https://user-images.githubusercontent.com/1504962/34343333-bf3c71cc-e97f-11e7-8506-e01c313d7b8e.png)

**Comment by dmlb2000** [comment]
The issue to me really is, why is kitchen taking up so much memory. I wouldn't think it needs to, during the run it would only need to keep track of what suites failed vs succeeded to print them at the end. Even if you are using an internal Ruby threading model of some kind there should be minimal overhead for each thread. Should kitchen be cleaning up the relevant threads after a suite has finished?

**Comment by coderanger** [comment]
We only use one thread if you aren't running in concurrent mode IIRC, and even then, 40MB per instance is weirdly high. Can you reproduce this with another driver? Might be something wonky in the hyperv driver itself, since I'm less familiar with that one.

**Comment by dmlb2000** [comment]
That should be transparent to kitchen as I'm using Vagrant, but I could try a test using docker... might go faster anyway...

**Comment by coderanger** [comment]
Ahh, I missed that it was kitchen-vagrant+hyperv rather than kitchen-hyperv. The real way to debug it would be to locally modify your kitchen gem to use https://github.com/SamSaffron/memory_profiler to check what is taking up so much space. Might be easier to walk you through that on Slack rather than here though.

**Comment by dmlb2000** [comment]
Okay to prove this I'll do the following:

1. create empty directory
2. `kitchen init`
3. change `kitchen.yml`
```
---
driver:
  name: docker
provisioner:
  name: chef_zero
verifier:
  name: inspec
platforms:
  - name: ubuntu
    run_list:
      - recipe[apt]
      - recipe[apache2]
suites:
  - name: default
```
4. programatically add a lot of tests (about 100) `  - name: test$x`
5. create Berksfile
```
source 'https://supermarket.chef.io'
cookbook 'apt'
cookbook 'apache2'
```
6. verify testing default works
```
kitchen test default
```
7. run tests
```
kitchen test -d always test
```
8. watch ruby interpreter process in task mgr

Interestingly using either docker or vagrant driver and either shell or chef_zero provisioner the ruby interpreter doesn't use more than 100Mb total throughout the test of 100 suites. However, when adding the inspec verifier with a basic listen on port 80 test seems to gradually increase in memory usage per test.

**Comment by dmlb2000** [comment]
Also, seems to get worse when I add 100 test commands to verify for each of the 100 suites...

**Comment by coderanger** [comment]
Aha, that does give me something to go on to repro locally. Will try it out, thanks.

**Comment by cheeseplus** [comment]
What Vagrant version?
