### ISSUE TITLE
New product_version config doesn't behave as expected

### ISSUE THREAD

**Issue by tas50** [test-kitchen/test-kitchen#1342]
Previously we used require_chef_omnibus to set a specific version of chef to be used on the box. If the version installed was *newer* than the one specified test kitchen would reinstall the specified older version. With this new config option that no longer occurs. It makes it impossible to do multiple passes at any cookbook that involves chef updates and it makes it hard for those with baked in chef clients to test older releases.

**Comment by wrightp** [comment]
There is still work to be improved to get the word out. Docs have been updated: https://docs.chef.io/config_yml_kitchen.html

Add option `install_strategy: always` and see if it behaves as you expect.

**Comment by david-in-perth** [comment]
It's not clear from the docs what `install_strategy: always` means.
Does it mean that Chef Client is reinstalled on every kitchen run, or only when the version that is currently installed doesn't match `product_version`?

**Comment by pinterl** [comment]
**product_version** does not work as I would expect it.

I have Chef Client version 13.6.4 baked into the image. I want to test my cookbook with the old version of Chef Client, as the existing nodes still run that version.

My .kitchen.yml file has the following:
```
provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12.11.18
  install_strategy: always
```

Test kitchen downloads the old version of the Chef Client, but executes the baked-in new version:

>       ModuleType Version    Name                                ExportedCommands
>        ---------- -------    ----                                ----------------
>        Script     0.0        Omnitruck                           {Get-ProjectMetada...
>        Installing chef from C:\Users\umgadmin\AppData\Local\Temp\chef-client-12.11.18-1-x64.msi
>        Transferring files to <default-windows-2012r2>
>        Starting Chef Client, version 13.6.4
>

**Comment by Brantone** [comment]
Inverse also seems to occur as well:
VM baked with `12.20.3` , run kitchen with out `require_chef_omnibus`, but with:
```
product_name: chef
product_version: 13
```
Does not update to latest 13.9.1 (latest as of time of this writing) as it would have with `require_chef_omnibus` ; however ,  although I know I can also add:
```
install_strategy: true
```
It appears that on _every_ run, it re-downloads and re-installs 13.9.1.
Whereas if just had:
```
require_chef_omnibus: 13
```
It would do single upgrade and that's it, due to: https://github.com/test-kitchen/test-kitchen/blob/master/support/chef_base_install_command.ps1#L13

Obviously part of the change with RFC-091 is to consolidate the install paths, unfortunately the change as it currently exists doesn't leave much to compromise.

**Comment by pop** [comment]
How would one propose a change to `install_strategy`? Ideally we would have something like `install_strategy: mismatch` where it runs the install only if there is a version difference or Chef is not installed on the system.

**Comment by coderanger** [comment]
@pop The actual implementation (other than `skip`) of the methods is in https://github.com/chef/mixlib-install so that would be the place.

**Comment by cheeseplus** [comment]
@espoelstra that definitely wasn't known as a failure condition but I can add that to the list for re-architecting this functionality.

**Comment by mdunc** [comment]
@wrightp, ah, thank you!  I missed that in the documentation, but I see it now.

**Comment by mdunc** [comment]
Actually, I thought it was working, but I'm not sure it is.  

.kitchen.yml excerpt:
```
platforms:
  - name: ubuntu-16.04-chef-13.8.5
    driver:
      product_name: chef
      product_version: 13.8.5
      install_strategy: always
      box: bento/ubuntu-16.04
```

But in the log I still see it install the latest version of Chef:
```
-----> Creating <default-ubuntu-1604-chef-1385>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'bento/ubuntu-16.04'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
       ==> default: Setting the name of the VM: kitchen-test-default-ubuntu-1604-chef-1385
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default:
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default:
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Mounting shared folders...
           default: /tmp/omnibus/cache => /Users/mark/.kitchen/cache
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <default-ubuntu-1604-chef-1385> created.
       Finished creating <default-ubuntu-1604-chef-1385> (0m34.98s).
-----> Converging <default-ubuntu-1604-chef-1385>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.6...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       ubuntu 16.04 x86_64
       Getting information for chef stable  for ubuntu...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=16.04&m=x86_64
         to file /tmp/install.sh.1535/metadata.txt
       trying wget...
       sha1     bde0f07bbe17492ab56e2afa3794e8f4ac6f5f8b
       sha256   81dc8634609493a8e9c9dbcb027855027812c902db95e1884b18fe368acbd047
       url      https://packages.chef.io/files/stable/chef/14.6.47/ubuntu/16.04/chef_14.6.47-1_amd64.deb
       version  14.6.47
       downloaded metadata file looks valid...
       /tmp/omnibus/cache/chef_14.6.47-1_amd64.deb exists
       Comparing checksum with sha256sum...

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       You are installing an omnibus package without a version pin.  If you are installing
       on production servers via an automated process this is DANGEROUS and you will
       be upgraded without warning on new releases, even to new major releases.
       Letting the version float is only appropriate in desktop, test, development or
       CI/CD environments.

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       Installing chef
       installing with dpkg...
       Selecting previously unselected package chef.
(Reading database ... 38378 files and directories currently installed.)
       Preparing to unpack .../cache/chef_14.6.47-1_amd64.deb ...
       Unpacking chef (14.6.47-1) ...
       Setting up chef (14.6.47-1) ...
       Thank you for installing Chef!
```

**Comment by cheeseplus** [comment]
@mdunc these aren't _driver_ settings, they are _provisioner_ settings and need to be set under that key accordingly

**Comment by mdunc** [comment]
Thanks, that seemed to do the trick.  I was confused because the old `require_chef_omnibus` setting worked under the driver settings (I was following https://geekblood.wordpress.com/2015/03/27/test-kitchen-with-multiple-chef-client-versions/ as an example) and the documentation just mentions that the new settings replace it so I assumed that the new settings should work in the same spot.

**Comment by wrightp** [comment]
@mdunc No worries. These features are half-baked and only partial documented. We'll get back at it in the future.

**Comment by mcascone** [comment]
I am pretty sure I have the configuration correct but it doesn't work, on my VMs with v15 baked in:
```
provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12
  install_strategy: always
```

```
 Installing chef from C:\Users\ENGINE~1\AppData\Local\Temp\chef-client-12.22.5-1-x64.msi
       Transferring files to <remote-Windows>
       Starting Chef Infra Client, version 15.2.20
```

**Comment by mcascone** [comment]
I would just like to have an `upgrade` option as an install strategy. So kitchen will go and install the version you want on a box, and not do it again while that box is still up. Is there an existing way to do this? `always` seems like a waste of time.

**Comment by marcparadise** [comment]
When looking into this, it would be good if we could determine which scenarios do/don't work: 

- node already has chef installed that matches the specified version, what gets installed?
- node already has an older-than-specified version of chef-infra installed, what gets installed? 
- node already has a newer-than-specified version of chef-infra installed, what gets installed? 
- node has no chef-infra installed, what version gets installed when a version is specified in config?
I think 'always' is given here as a workaround, but when this is functioning correctly it will install the version configured only  only if it doesn't already match the installed version; in that context, I don't think we need a separate `upgrade` strategy.
