### ISSUE TITLE
kitchen doctor nothing found issue isn't very helpful

### ISSUE THREAD

**Issue by tas50** [test-kitchen/test-kitchen#1343]
With the new kitchen doctor feature is the yaml is OK you get the following message:

```
-----> The doctor is in
```

We should probably include a more useful message here stating what we even checked and that no issues were discovered.

**Comment by dwmarshall** [comment]
It would also be good to have an exit status of zero...

```
$ kitchen version; kitchen doctor; echo $?
Test Kitchen version 3.2.2
-----> The doctor is in
1
```
