### ISSUE TITLE
Kitchen converge fails on Windows - No such file or directory @ rb_sysope

### ISSUE THREAD

**Issue by vigri** [test-kitchen/test-kitchen#1349]
## Description

When running kitchen converge I get the following error
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [No such file or directory @ rb_sysopen - C:/Users/User/AppData/Local/Temp/default-debian-93-sandbox-20180122-17036-squdjq/cookbooks/apache2/.kitchen/kitchen-vagrant/default-debian-93/.vagrant/machines/default/vmware_workstation/f3026c58-c44d-4588-9df2-9a05ccf62af5/564d0231-6797-4826-06ed-e6b19037429b.vmem] on default-debian-93
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

This error happens even when trying with an empty cookbook.

## Kitchen Version

```ruby
Test Kitchen version 1.19.2
```

## ChefDK Version

```ruby
Chef Development Kit Version: 2.4.17
```

## Platform Version

Windows: Win 10x64, Version 1709
Vagrant: 2.0.1
VMware: 12.5

## Replication Case
```bash
chef generate cookbook cookbooks/apache2
cd .\cookbooks\apache2\
kitchen create # command succeeds without any errors
berks install # command succeeds without any errors
kitchen converge # problem (!)
```

## Kitchen Output

```ruby
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [No such file or directory @ rb_sysopen - C:/Users/User/AppData/Local/Temp/default-debian-93-sandbox-20180122-17036-squdjq/cookbooks/apache2/.kitchen/kitchen-vagrant/default-debian-93/.vagrant/machines/default/vmware_workstation/f3026c58-c44d-4588-9df2-9a05ccf62af5/564d0231-6797-4826-06ed-e6b19037429b.vmem] on default-debian-93
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

kitchen.log stays empty
default-debian-93.log stays empty too

## Kitchen Diagnose

[kitchen diagnose --all](https://gist.github.com/vigri/508f15ab12223044e9566be4e096be9c)

## Additional information:
- [.kitchen.yml](https://gist.github.com/vigri/2cb909f9eea640bab6c4fc1f212b551d)
- [chefignore](https://gist.github.com/vigri/1ac3317b5b7f6b3c3007b472f40f87f2)

**Comment by cheeseplus** [comment]
Given the path there looks suspicious I checked the `diagnose` output and it seems you've got these cookbooks and such stored on `D:\` which might be presenting an issue. Also could be something specific to the vmware setup that is causing extra long paths which Windows is known to have problems with.

First I'd try moving this to `C:\test` and trying again just to check to see if that's related.

**Comment by cheeseplus** [comment]
Were you able to get past this moving the dir to C:? If not a debug log `-l debug` would be great

**Comment by cheeseplus** [comment]
When we've seen this in other cases it's been a direct result of not having a chefignore entry for `.kitchen/*` - if the chefignore was added later that might also be problematic but that's definitely the root issue. Closing this given the above and since it's been nearly a month without response but feel free to re-open.
