### ISSUE TITLE
Query - Should passing the debug flag also set the debug of the chef-run?

### ISSUE THREAD

**Issue by willfish** [test-kitchen/test-kitchen#1354]
## Description

Been debugging using test-kitchen with the kitchen-vagrant plugin.

I noticed that when I enable debug mode I'm not outputting to the console any of the lines
using `Chef::Log.debug` on the run.

I am getting an awful lot of useful information from test-kitchen, though.

I haven't looked into the way we're passing the debug option in this codebase - happy to do that if answers aren't forthcoming :).

## Kitchen Version

1.19.2

## Chef 

```yaml
  require_chef_omnibus: 12.20.3
```

## ChefDK Version

```
~/R/m/m/c/e/cassandra-legacy-production production >: chef --version
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```
ruby 2.2.4p230 (2015-12-16 revision 53155)
```

## Platform Version
```bash
uname -a
Darwin Messier31 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

## Replication Case

converge any cookbook which has code driven which calls `Chef::Log.debug`

compare a converge with calls to `Chef::Log.info`

## Kitchen Output

Not applicable as there is no output.

**Comment by cheeseplus** [comment]
The log level for the provisioner can be set by the following
```
provisioner:
  name: chef_zero
  log_level: :debug
````

**Comment by willfish** [comment]
Apologies and thanks!
