### ISSUE TITLE
Domain Join, Reboot and continue with run-list with 'kitchen test'

### ISSUE THREAD

**Issue by ibprofin** [test-kitchen/test-kitchen#1357]
## Description

Need to find a way to execute a domain join and reboot and then continue to run the rest of the runlist without exiting chef-client. The domain join cookbook I have does work, I just can't get chef-client to continue afterwards. I have looked at other issues similar to this before but have not found a solution that was addressed in the last year at least. Thank you for your help.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
# Test Kitchen version 1.17.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
# Chef Development Kit Version: 2.1.11
chef-client version: 13.2.20
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.0
kitchen version: 1.17.0
inspec version: 1.33.1

```

## Platform Version

Windows Server 2012

## Replication Case

kitchen test runs run list, domain join needs to happen before some of the other recipes execute.
Domain-join runs and reboots, but chef-client does not continue its runlist, which is the problem.

```ruby
#     run_list:
      - role[default_role]
      - recipe[chef_win_reboot::domain_join] #where the reboot needs to occur
      - recipe[kitchen-test-helper]
      - recipe[java::jdk]
      - recipe[firefox]
      - recipe[google-chrome]
      - recipe[windows_firewall]
      # several other recipes with enterprise software
```

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
#        Recipe: domain-join::default
         * reboot[Restart Computer] action nothing (skipped due to action :nothing)
         * powershell_script[Join Domain and Reboot] action run
           - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20180214-1124-19zacy6.ps1"
         * reboot[Restart Computer] action reboot_now[2018-02-14T16:15:13+00:00] WARN: Rebooting system immediately, requested by 'Restart Computer'


           Running handlers:
           Running handlers complete

```

**Comment by coderanger** [comment]
This should already work by default. It won't pick up where it left off, but Test Kitchen should detect the reboot exit code and run Chef again.

**Comment by cheeseplus** [comment]
This doesn't exist in one canonical place yet but the details are https://github.com/test-kitchen/kitchen-docs/issues/65 which I'll be trying to write up this week as part of a larger doc pass on kitchen.ci.

**Comment by ibprofin** [comment]
Solved using 

https://github.com/chrisgit/test_kitchen-multiboot/issues/1
