### ISSUE TITLE
Error installing test-kitchen

### ISSUE THREAD

**Issue by ReenaAcharya** [test-kitchen/test-kitchen#1358]
Hi,

I am trying to install test-kitchen on chef-solo. I am using CentOS machine.
When I do "gem install test-kitchen", I get following error:-
"Error installing test-kitchen
Requires ruby >= 2.2"

Thanks.

**Comment by cheeseplus** [comment]
Closing this one due to lack of response. When installing test-kitchen as a gem it requires a Ruby greater than 2.2, we recommend 2.4.3 at present, or you can utilize this via ChefDK which ships with it's own embedded Ruby.
