### ISSUE TITLE
Error executing /tmp/chef-installer.sh

### ISSUE THREAD

**Issue by mlcooper** [test-kitchen/test-kitchen#1364]
## Description
Due to security standards for the OS images we use with Test Kitchen (and everywhere else) the `noexec` option is set for `tmpfs` in `/etc/fstab`.  This results in this error with Test Kitchen:
```
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       sudo: unable to execute /tmp/chef-installer.sh: Permission denied
```
The `root_path` provisioner option does not appear to change the location of `chef-installer.sh`.  It looks hard-coded here:
https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_base.rb#L506

## Kitchen Version
```ruby
Test Kitchen version 1.20.0
```

## ChefDK Version
```ruby
Chef Development Kit Version: 2.3.4
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.50.1
```
## Platform Version
Fedora 25

## Replication Case
Setup a server with the `noexec` option set on `tmpfs` and run `test kitchen <suite>`.  
Relevant line from our `/etc/fstab` file:
```
tmpfs /dev/shm tmpfs  defaults,nodev,nosuid,noexec,size=1g  0 0
```

## Kitchen Output
```ruby
Please see above
```

**Comment by cheeseplus** [comment]
This was something I've honestly been surprised hasn't bitten us earlier but we'll be looking into given it's pretty obvious _why_ this will be a problem.

**Comment by robbkidd** [comment]
@mlcooper Can you share more of the options you have passed to the Chef provisioner in your `kitchen.yml`?

**Comment by mlcooper** [comment]
`provisioner` options:
```
provisioner:
    product_version: <%= version %>
    root_path: /home/cloud/kitchen
    name: chef_zero
    product_name: chef
    data_bags_path: test/fixtures/data_bags
```

**Comment by cheeseplus** [comment]
Re-opening this issue as we've had to revert #1369 as it didn't work as intended.

**Comment by akashgoel92** [comment]
I am having the same issue with rhel 6.9:
`sudo: unable to execute /tmp/chef-installer.sh: Permission denied`

Are there any updates on this issue?

**Comment by predatorian3** [comment]
Is there an option to put that file in a different location like `/var/cache`, or some place like that?

**Comment by bdwyertech** [comment]
Could always work around that no execute from tmp thing by catting out first.
`"cat #{install_file} | #{sudo('/bin/sh')}"`

**Comment by akashgoel92** [comment]
Couldn't change the directory. But added `user_data` attribute with a script with following content:
`sudo mount -o remount,exec /tmp`

**Comment by varnav** [comment]
Workaround if you're using azure is to add this:

```
provisioner:
  root_path: /home/azure/test-kitchen # default /tmp has noexec on CIS hardened images
```
