### ISSUE TITLE
Host machine proxy environment variables overriding Chef client.rb proxy configs

### ISSUE THREAD

**Issue by jakauppila** [test-kitchen/test-kitchen#1366]
## Description

It appears that Kitchen pushes my host machine proxy environment variables when utilizing WinRM to execute the provisoner which is overriding the proxy configurations I have configured within my Chef client.rb. 

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.19.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

## Platform Version

Windows 10

## Replication Case

On my host machine, I have CNTLM configured to proxy requests against our corporate proxy, so my local `HTTP_PROXY` and `HTTPS_PROXY` environment variables are configured against localhost `http://127.0.0.1:3128`.

Within my machine-level `.kitchen.yml`, I have the following provisioner configuration configured so that my guests are able to talk back to the CNTLM instance configured on my host and thus able to authenticate to the proxy.

```
provisioner:
  name: chef_zero
  client_rb:
    http_proxy: http://10.0.2.2:3128
    https_proxy: http://10.0.2.2:3128
    no_proxy: localhost,127.0.0.1,.server.local,.contoso.com,.contosoextranet.com
```

The problem is that it appears that Kitchen interrogates my Host proxy configs and utilizes those values on the WinRM connection to the Windows guests.

https://github.com/test-kitchen/test-kitchen/blob/553106031b0045e95a771c3c4e2da7400a90b677/lib/kitchen/configurable.rb#L362

```
E, [2018-02-28T00:54:16.507735 #22872] ERROR -- iis-win2012r2-chef12203: ------Exception-------
E, [2018-02-28T00:54:16.507735 #22872] ERROR -- iis-win2012r2-chef12203: Class: Kitchen::ActionFailed
E, [2018-02-28T00:54:16.507735 #22872] ERROR -- iis-win2012r2-chef12203: Message: WinRM exited (1) for command: [$env:http_proxy = "http://127.0.0.1:3128"
$env:HTTP_PROXY = "http://127.0.0.1:3128"
$env:https_proxy = "http://127.0.0.1:3128"
$env:HTTPS_PROXY = "http://127.0.0.1:3128"
$env:no_proxy = "localhost,127.0.0.1,.server.local,.contoso.com,.contosoextranet.com"
$env:NO_PROXY = "localhost,127.0.0.1,.server.local,.contoso.com,.contosoextranet.com"
$env:TEST_KITCHEN = "1"
$env:PATH = try {
[System.Environment]::GetEnvironmentVariable('PATH','Machine')
} catch { $env:PATH }

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level auto --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889 ; exit $LastExitCode]
```

When this happens, it appears that those definitions are overriding the values I have specified via the provisioner which I see within `client.rb` are set appropriately to `http://10.0.2.2:3128`, so if I have a piece of code that references that environment variable, it's seeing the `http://127.0.0.1:3128` value instead of the value set within `client.rb`

```
Errno::ECONNREFUSED
I, [2018-02-28T00:54:15.220977 #22872]  INFO -- iis-win2012r2-chef12203:     -------------------
I, [2018-02-28T00:54:15.236673 #22872]  INFO -- iis-win2012r2-chef12203:     Failed to open TCP connection to 127.0.0.1:3128 (No connection could be made because the target machine actively refused it. - connect(2) for "127.0.0.1" port 3128)
```

## Kitchen Diagnose

https://gist.github.com/jakauppila/683b6975019738159d9f18861e809f4d

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by coderanger** [comment]
So the usual workaround here is to clear your ambient proxy configuration inside the kitchen.yml, something like:

```
<% %w{HTTP_PROXY http_proxy HTTPS_PROXY https_proxy NO_PROXY no_proxy}.each {|v| ENV.delete(v) } %>
```

It's gross, but it should help. The deeper issue is that Chef prefers the env vars for proxy config ahead of the config file, as you noted (https://github.com/chef/chef/blob/41d69e2a5b2ff23488441b82f019b77b243dbdf7/chef-config/lib/chef-config/config.rb#L982-L983).

**Comment by cheeseplus** [comment]
Closing this one out as this is really the upstream chef issue and I'm almost certain folks are relying on this behaviour by default. The workaround is the best way forward for this particular configuration.
