### ISSUE TITLE
kitchen init provides a kitchen-dokken friendly kitchen configuration

### ISSUE THREAD

**Issue by burtlo** [test-kitchen/test-kitchen#1374]
## Description

The `kitchen-dokken` approach to setting up Test Kitchen has been said by quite a few people it is the preferred way to go about using Test Kitchen and Docker. However, it is not a trivial task to convert a default vagrant version of the kitchen configuration to a dokken version of the kitchen configuration.

![vagrant vs dokken](https://user-images.githubusercontent.com/244426/36861720-5a17bfc8-1d4a-11e8-85d9-f847091004c4.png)

@robbkidd and I talked it seems as though we would want to solve for this in a large way with how plugins are involved in the kitchen configuration process. However, in the short term it feels like a first step would be to provide two different templates for the kitchen configuration and use the `dokken` version when the user performs the following:

```shell
$ kitchen init --driver=kitchen-dokken
    conflict  .kitchen.yml
Overwrite /Users/franklinwebber/scratch/apache/.kitchen.yml? (enter "h" for help) [Ynaqdh] Y
       force  .kitchen.yml
    conflict  chefignore
Overwrite /Users/franklinwebber/scratch/apache/chefignore? (enter "h" for help) [Ynaqdh] n
        skip  chefignore
      create  test/integration/default
Fetching: kitchen-dokken-2.6.6.gem (100%)
Successfully installed kitchen-dokken-2.6.6
1 gem installed

$ cat .kitchen.yml
---
driver:
  name: dokken

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
  - name: centos-7
    driver:
      image: dokken/centos-7

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
```

**Comment by burtlo** [comment]
Happy to implement. Looking for any comments.

**Comment by cheeseplus** [comment]
Pretty much identical feelings as https://github.com/test-kitchen/test-kitchen/pull/1380#issuecomment-371261767
