### ISSUE TITLE
`kitchen init` and `chef generate` set provider to `virtualbox` explicitly when driver is Vagrant

### ISSUE THREAD

**Issue by robbkidd** [test-kitchen/test-kitchen#1384]
Need to update `kitchen init` and `chef generate` to state explicitly the current default of `virtualbox` as the driver's provider.

e.g.

```diff
  driver:
    name: vagrant
+    provider: virtualbox
```

**Comment by tas50** [comment]
Kitchen init no longer does this. I'm also opening a PR to yank that bit from the simple docs example since there's no need to define that unless you know what you're doing and have multiple backends.
