### ISSUE TITLE
missing command : kitchen driver create [name]

### ISSUE THREAD

**Issue by osmanium** [test-kitchen/test-kitchen#1386]
## Description

Missing sub command : kitchen driver create [name]
This sub command is described in documentation but not available command list
<img width="599" alt="actualcommandlist" src="https://user-images.githubusercontent.com/8151650/37588243-174e7e72-2b7b-11e8-9baf-07243f67c4e7.PNG">

In documentation
<img width="283" alt="documentation" src="https://user-images.githubusercontent.com/8151650/37588281-3553f046-2b7b-11e8-8050-b14819cd8ed0.PNG">

## Kitchen Version

```ruby
Test Kitchen version 1.20.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 2.5.3
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
```

## Platform Version

Windows 10 Enterprise x64 Version 1709, Build 16299.125

## Replication Case

Command : kitchen help
It does not show 'kitchen driver create [name]' sub command

## Kitchen Diagnose

---
timestamp: 2018-03-19 09:47:11 UTC
kitchen_version: 1.20.0
plugins:
  error:
    exception: "#<Kitchen::UserError: Kitchen YAML file C:/WINDOWS/system32/.kitchen.yml
      does not exist.>"
    message: Kitchen YAML file C:/WINDOWS/system32/.kitchen.yml does not exist.
    backtrace:
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/loader/yaml.rb:65:in
      `read'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:152:in
      `data'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:131:in
      `suites'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:182:in
      `filter_instances'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:141:in
      `build_instances'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:117:in
      `instances'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:112:in
      `filtered_instances'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:142:in
      `parse_subcommand'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/diagnose.rb:53:in
      `load_instances'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/diagnose.rb:32:in
      `block in call'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/diagnose.rb:73:in
      `record_failure'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/diagnose.rb:32:in
      `call'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/cli.rb:52:in
      `perform'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/cli.rb:142:in
      `diagnose'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in
      `run'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in
      `invoke_command'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in
      `dispatch'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in
      `start'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/bin/kitchen:13:in
      `block in <top (required)>'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/errors.rb:171:in
      `with_friendly_errors'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/bin/kitchen:13:in
      `<top (required)>'
    - C:/opscode/chefdk/bin/kitchen:262:in `load'
    - C:/opscode/chefdk/bin/kitchen:262:in `<main>'
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
  local_config:
  combined_config:
    filename:
    raw_data: {}
instances:
  error:
    exception: "#<Kitchen::UserError: Kitchen YAML file C:/WINDOWS/system32/.kitchen.yml
      does not exist.>"
    message: Kitchen YAML file C:/WINDOWS/system32/.kitchen.yml does not exist.
    backtrace:
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/loader/yaml.rb:65:in
      `read'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:152:in
      `data'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:131:in
      `suites'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:182:in
      `filter_instances'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:141:in
      `build_instances'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:117:in
      `instances'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:112:in
      `filtered_instances'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:142:in
      `parse_subcommand'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/diagnose.rb:53:in
      `load_instances'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/diagnose.rb:32:in
      `block in call'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/diagnose.rb:73:in
      `record_failure'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/diagnose.rb:32:in
      `call'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/cli.rb:52:in
      `perform'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/cli.rb:142:in
      `diagnose'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in
      `run'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in
      `invoke_command'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in
      `dispatch'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in
      `start'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/bin/kitchen:13:in
      `block in <top (required)>'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/errors.rb:171:in
      `with_friendly_errors'
    - C:/Users/ogumus/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.20.0/bin/kitchen:13:in
      `<top (required)>'
    - C:/opscode/chefdk/bin/kitchen:262:in `load'
    - C:/opscode/chefdk/bin/kitchen:262:in `<main>'

**Comment by cheeseplus** [comment]
We ripped out the code in 1.19.0 https://github.com/test-kitchen/test-kitchen/blob/986a63904e5bdee26099a0d3bc1ac0fae75296a8/CHANGELOG.md#v1190-2017-11-1, specifically #1293

The docs were written earlier and don't reflect that in that snippet of output shared, they'll be fixed in the next push of https://github.com/test-kitchen/kitchen-docs
