### ISSUE TITLE
All files in gem has execute bit set

### ISSUE THREAD

**Issue by 375gnu** [test-kitchen/test-kitchen#1388]
## Description

All files in gem has execute bit set.

## Kitchen Version

1.20.0

## Replication Case

Install gem on any unix-like system or open it using mc.

**Comment by coderanger** [comment]
Sounds like maybe you had a funky umask when you installed the gem?

**Comment by coderanger** [comment]
Never mind, repro'd in a container. Thanks for the report.

**Comment by cheeseplus** [comment]
Fixed in 1.21.0
