### ISSUE TITLE
winrm-fs can't transfer files with special characters like `+`

### ISSUE THREAD

**Issue by grv87** [test-kitchen/test-kitchen#1391]
## Description
To converge Windows machine Kitchen packs cookbooks and other files in zip archives.
But produced zips are invalid, and can't be unpacked.

## Versions
Kitchen: `1.20.0`
winrm-fs: `1.1.1`
Ruby: `ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]`

Host Platform: Windows 7 SP1
Target Platform: Windows Server 2016 Base

## Kitchen Output
```
       Transferring files to <BuildToolset-WindowsServer-2016+amd64-amazon>
       Starting Chef Client, version 13.8.5
       resolving cookbooks for run list: ["fidata-build-toolset::default"]

       ================================================================================
       Error Resolving Cookbooks for Run List:
       ================================================================================

       Missing Cookbooks:
       ------------------
       No such cookbook: fidata-build-toolset
```

I partly investigated the issue and believe that the problem is in invalid paths in zip files.
Zip contain full paths including drive name, e.g. `q:/Temp/Basil/BuildToolset-WindowsServer-2016+amd64-amazon-sandbox-20180329-1179092-1y4xi5h/environments/production.json`.
Example file:
[tmpzip-1019288769ee745fc7bd94b27f9bffef05d12a5e.zip](https://github.com/test-kitchen/test-kitchen/files/1861862/tmpzip-1019288769ee745fc7bd94b27f9bffef05d12a5e.zip)

7-Zip and some other programs can open this file. But Windows built-in 'Zip as folder' feature can't.
I just don't know where the issue is exactly — in Test Kitchen or in winrm-fs gem.

**Comment by coderanger** [comment]
We don't support ChefDK on Windows 7, so how did you install it?

**Comment by grv87** [comment]
I believe I installed Win2008 version of ChefDK.
But right now I use Ruby gem version.

You think the problem is in host OS?
I believe the problem is somewhere with relativize. Maybe connected with the fact that on my PC system, temp and current working directories are all on different drives.

**Comment by coderanger** [comment]
If there was something globally broken, presumably more than you would have noticed, so the question become "what is special about your situation that might have lead to brokenness?".

**Comment by grv87** [comment]
The problem is in winrm-fs gem.
It arises whenever dir, i.e. temp directory and/or platform and/or suite name, contain regexp special characters, in my case it was `+`.
