### ISSUE TITLE
Attribute inclusion has an issue

### ISSUE THREAD

**Issue by scotthain** [test-kitchen/test-kitchen#1393]
## Description

I run into this error: https://gist.github.com/scotthain/203e3fc3837c608cdfc304328508349b

Here's the setup:

a `.kitchen.yml` with an include set up similar to:
```
default: &default
  includes:
    - ubuntu-16.04
  driver:
    vm_hostname: master-ubuntu-1604
    network:
<snip>
```
which is then used in some suites:
```
  - name: master
    <<: *default
    run_list:
      - my_cookbook::default
```
## Kitchen Version

1.20.0 (worked in 1.17.0)

## Version stuff

Chef Development Kit Version: 2.5.8
chef-client version: 13.8.5
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.51.21

## Platform Version

MacOS 10.13

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
# Copy-paste your results here
```

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by coderanger** [comment]
Yes, this was broken in 1.20 and will be fixed in 1.21. Sorry for the trouble.

**Comment by scotthain** [comment]
Sweet - thanks @coderanger

**Comment by robbkidd** [comment]
@scotthain I assume you are running test-kitchen 1.20.0 with the Chef DK environment you included in the PR information. In what environment at your running test-kitchen 1.17.0? Reverted to an older Chef DK? Or running a non-Chef DK Ruby install?
