### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by thedrow** [test-kitchen/test-kitchen#1394]
Just thought to let you know :)

**Comment by lamont-granquist** [comment]
reasonably certain that is intentional and the references to the website need to get updated with pointers to the TK docs, but don't quote me on that.

**Comment by cheeseplus** [comment]
Which website? https://kitchen.ci seems to be up at the moment and that's the only one that I am aware of.

**Comment by thedrow** [comment]
It was down. Now it isn't.
