### ISSUE TITLE
`kitchen test whatever -l debug` needs to show `chef-client -l debug` output

### ISSUE THREAD

**Issue by lamont-granquist** [test-kitchen/test-kitchen#1395]
There's a old thread where we had this argument and I lost the argument.

I think I'm now going to be stubborn until I get my way.

The 90% use case of needing debug logs isn't to debug test-kitchen itself but to want debug logging from the chef-client run.  I keep running into this issue talking to customers.

We need to support this case more intuitively directly from the command line, using exactly the same language as we use for chef-client.

I don't super care if it also gives test-kitchen debug output or if we swap it around so there's some other flag to get test-kitchen debug output.

**Comment by lamont-granquist** [comment]
Seriously...    talking to another CHEF EMPLOYEE in slack whose first thought was to throw "-l trace" on the end of a kitchen command to get chef-client -l trace output.

I rest my case, this is what everyone expects.

**Comment by jakauppila** [comment]
I've been hitting this recently too. I'd love if `-l trace` only showed the Chef output because as an end-user I usually don't care about the Kitchen logs

**Comment by coderanger** [comment]
We should continue to discuss this but for others that find this ticket, you can currently do `kitchen converge -D` to show debug logs from Chef (or any other provisioner/verifier that supports the flag). This doesn't get you `trace` logs (https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_base.rb#L53), but I would be happy to add that if someone has a UX sketch.

**Comment by cheeseplus** [comment]
I think we should make this easier and clearer but definitely need some UX thought above and beyond "this needs to be different".

**Comment by lamont-granquist** [comment]
So IMO this is fairly simple, `-l debug/trace/info` need to be wired up to chef-client.

I understand that this creates an issue where we have provisioners that have nothing to do with chef-client, but that means that we just need to move the existing test-kitchen `-l debug` output to some other flag.

This will indeed be considered a breaking change.

But right now we're inflicting UX punishment and suffering on the 80% use case, which is very backwards.

The user story is also simple:

As a Novice Chef Client / Test-Kitchen User,
I expect to get `chef-client -l debug` output out of `kitchen -l debug`
Because that is what everyone first guesses should be the right UX

**Comment by jjustice6** [comment]
Count me as another vote for `-l debug` passing through to chef-client.

**Comment by TechGuyChris** [comment]
Hi all, if you want to see output such as info, debug, or warns from chef client when running kitchen converge etc, you need to add this setting in your kitchen.yml or kitchen.openstack.yml file under provisioner.

`log_level :<value>

below is an example where wanting to get :info . Change to :debug if you want to get debug.

`
provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.0.202
  install_strategy: always
  log_level: :info 
`
