### ISSUE TITLE
Race condition: conflicting chdir during another chdir block

### ISSUE THREAD

**Issue by s-bernard** [test-kitchen/test-kitchen#1416]
## Description

Sometime, when doing kitchen actions like converge or verify in concurrent mode (ex: `kitchen verify -c`), I may have some:
```
~/.gem/ruby/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/util.rb:194: warning: conflicting chdir during another chdir block
~/.gem/ruby/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/util.rb:194: warning: conflicting chdir during another chdir block
~/.gem/ruby/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/util.rb:163: warning: conflicting chdir during another chdir block
~/.gem/ruby/2.5.0/gems/test-kitchen-1.21.1/lib/kitchen/util.rb:163: warning: conflicting chdir during another chdir block
```

and then, later the run failed with some file not found errors like:
```
LoadError:
  cannot load such file -- common_config
```

Re-running it may work or fail on another file, running it without `-c` works without problem.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.21.1
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

## Replication Case

Multiple suites run in concurrency,
```
driver name: docker_cli
transport name: docker_cli
provisioner name: chef_zero
serverspec for the tests
```

**Comment by coderanger** [comment]
Nothing in either TK or that driver mentions `common_config`. Do you get a stack trace for that LoadError?

**Comment by s-bernard** [comment]
Sorry I didn't mention it: it is a helper file located in `helpers/serverspec` next to `spec_helper.rb`.
BTW the error is random and could have been on `spec_helper.rb`. It can also be on the serverspec/busser files.

**Comment by coderanger** [comment]
How often does it happen? Are we talking like 1 in a million or 1 in 10?

**Comment by s-bernard** [comment]
More like 1 in 10. To be more reproducible, it is better to have a multi-core machine (more is better) and to converge all suites (to sync them) before running a `verify -c`.

I have made a simple project to show you: https://gitlab.com/chef-platform/test-cookbook/tree/racecondition (be sure to be on racecondition branch)

You can see the failure in action in this job (scroll near the end): https://gitlab.com/chef-platform/test-cookbook/-/jobs/71657209 (note: gitlab job status is not relevant in this test.)
While it working well on: https://gitlab.com/chef-platform/test-cookbook/-/jobs/71656577 (the same code, I just retried the job)

**Comment by coderanger** [comment]
Got it, thanks for the repro. Will try it out and see what I can discern.

**Comment by s-bernard** [comment]
From what I understand, the problem comes from the fact that `Dir.chdir` is not thread safe because the chdir is per process and not per thread.

A basic (not elegant) solution would be to synchronize each call to `Dir.chdir` as they are used only for file listing, so should be fast. A cleaner solution would be to not use `Dir.chdir` as all.

**Comment by s-bernard** [comment]
I've made a PR with the synchronize solution as it is very simple and solves this issue quickly.
