### ISSUE TITLE
Display download progress of VirtualBox images

### ISSUE THREAD

**Issue by Nowaker** [test-kitchen/test-kitchen#1417]
## Description

```
-----> Starting Kitchen (v1.21.2)
-----> Creating <default-ubuntu-1204>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Box 'bento/ubuntu-12.04' could not be found. Attempting to find and install...
           default: Box Provider: virtualbox
           default: Box Version: >= 0
       ==> default: Loading metadata for box 'bento/ubuntu-12.04'
           default: URL: https://vagrantcloud.com/bento/ubuntu-12.04
       ==> default: Adding box 'bento/ubuntu-12.04' (v2.3.5) for provider: virtualbox
           default: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-12.04/versions/2.3.5/providers/virtualbox.box
```

...now waiting for image to download without knowing how long it could possibly take. Coffee time or just 30 seconds? :thinking:  Who knows!

Solution: display download progress!

## Kitchen Version

`1.21.2`

**Comment by cheeseplus** [comment]
This is something that would only apply to kitchen-vagrant, not core. While there might be a way we can surface the progress bar it's not really something I'm keen to optimize for in our own code given we're merely abstracting Vagrant.
