### ISSUE TITLE
Runtime arguments

### ISSUE THREAD

**Issue by StuporHero** [test-kitchen/test-kitchen#1420]
I've been setting up an end-to-end CD pipeline for my organization which includes cookbooks and packer builds that I'm testing with kitchen, and it would be really nice if I could pass values in to kitchen. Currently, I'm trying to use kitchen to test an AMI from a packer build, and it is performing its job satisfactorily, but I'd really like to pass the name of the AMI to use for the test into it at runtime so I can include it in the packer build, itself, and so I can use the precise AMI name instead of using search criteria which leaves me open to the potential to grabbing the wrong AMI if I ever change the naming scheme and forget to update the search criteria.

**Comment by coderanger** [comment]
This is generally accomplished via environment variables and Erb interpolation in the kitchen.yml

**Comment by StuporHero** [comment]
@coderanger Is there an example you can point me to?

**Comment by StuporHero** [comment]
@coderanger I found [one of your answers](https://stackoverflow.com/a/26519320/1603791) on StackOverflow to help me out.

**Comment by cheeseplus** [comment]
@StuporHero it is https://kitchen.ci/docs/dynamic-configuration

**Comment by StuporHero** [comment]
@cheeseplus The docs need to be reorganized. I spent days looking for the information I needed and never once came across that screen.

**Comment by cheeseplus** [comment]
If you'd like to make PRs or actionable suggestion other than "make it better" then you are welcome to at https://github.com/test-kitchen/kitchen-docs - this is open source software and we don't have unlimited resources. Apologies for the inconvenience.
