### ISSUE TITLE
Operation already in progress - connect(2)

### ISSUE THREAD

**Issue by kais58** [test-kitchen/test-kitchen#1434]
## Description
test-kitchen exits with Operation already in progress - connect(2) for 54.229.120.37:22 when connecting to EC2 instance. I have a suspicion that this may be down to how WSL handles sockets but am not certain. Is there a way to test with a different transport that doesn't use connect?

## Kitchen Version

```ruby
kitchen-ec2 (2.2.2)
kitchen-inspec (0.23.1)
kitchen-puppet (3.3.2)
kitchen-sync (2.2.1)
kitchen-vagrant (1.3.2)
test-kitchen (1.22.0)
```

## Ruby Version

```ruby
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
```

## Platform Version

Debian 9 on WSL on Windows 10 1709

## Replication Case

I'm running a first converge it does this consistently

## Kitchen Output

```ruby
       EC2 instance <i-0279bbe3dcfa0f561> ready (hostname: ec2-54-229-120-37.eu-west-1.compute.amazonaws.com). 
       Removing automatic key pair kitchen-squidnatamzn-callummassey-LPT3281-2018-07-09T15:00:56Z-vs9jovi6
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Operation already in progress - connect(2) for 54.229.120.37:22] on test-amzn
>>>>>> ----------------------
```

## Config

```ruby
  - name: amzn
    driver:
      name: ec2
      aws_ssh_key_id: deployer
      security_group_ids: ["sg-875ca1fb"]
      region: eu-west-1
      subnet_id: subnet-a97f4ff2
      instance_type: m5.large
      associate_public_ip: true
      iam_profile_name: mgmt-packer
      image_search:
        owner-id: "137112412989"
        name: "*amzn-ami-hvm*"
      shared_credentials_profile: mgmt
    provisioner:
      custom_facts:
        environment: dev

transport:
  ssh_key: ~/.ssh/deployer
```

**Comment by cheeseplus** [comment]
This is WSL unfortunately - I hit this when experimenting earlier this year and it seemed to go away in newer WSL/ubuntu base image.

**Comment by kais58** [comment]
What version of windows are you running? Would it line up with going away in 1803? They seem to have made a bunch of improvements in that release but I haven’t got it yet.

**Comment by cheeseplus** [comment]
I've no longer, at least for a while while moving, have that machine available but I seem to recall it was 1803 at least.

**Comment by kais58** [comment]
Ok, will close for now then update if I get a definitive solution.
