### ISSUE TITLE
Question: Skip the initial "destroy" phase in "kitchen test"?

### ISSUE THREAD

**Issue by metmajer** [test-kitchen/test-kitchen#1436]
I was wondering if there was a way of skipping the initial *destroy* phase in the `kitchen test` command?  The reason for my question is that Terraform's lifecycle model is currently allergic to destroying some resources which haven't been created before (that's how I understood it).

Here's a link to a corresponding Terraform issue: https://github.com/hashicorp/terraform/issues/18424.

Cheers!

**Comment by metmajer** [comment]
I want to add that, in a Makefile context, the following line should do the trick to make sure `kitchen verify` is followed by a `kitchen destroy` in any case:

```
.PHONY: test
test:
  $(shell TF_WARN_OUTPUT_ERRORS=1 bundle exec kitchen verify; bundle exec kitchen destroy)
```

Now, I haven't had time to verify this yet, but the idea is that `shell` creates a sub-shell that executes these two commands. Without the sub-shell, `make` would fail with the first failing command.

**Comment by metmajer** [comment]
As a workaround, I was able to use a `kitchen validate; kitchen destroy`, which should be the same as `kitchen test --destroy=always` without the initial destroy. I can confirm that make doesn't stop the execution of the `test` target when `kitchen validate` fails.

```
.PHONY: test
test:
  bundle exec kitchen verify; bundle exec kitchen destroy
```

**Comment by coderanger** [comment]
This is a thing that should be handled in `kitchen-terraform`. How the driver implements the phases is up for the driver to decide, especially in the case of one as funky as Terraform.
