### ISSUE TITLE
Documentation for Shell Provisioner

### ISSUE THREAD

**Issue by darkn3rd** [test-kitchen/test-kitchen#1440]
## Description

Shell provisioner has no documentation.   I had to look at unit tests and source code to elicit the options for shell provisioner.  Currently, there's no documentation that documents the features available for the shell provisioner, other than the source code.  

Non-programmer users may likely be intimidated to dive to this level to figure out how to use the program.

## Kitchen Version

```ruby
Test Kitchen version 1.22.0
```

## ChefDK Version

```ruby
Chef Development Kit Version: 3.1.0
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.2.34
```

## Platform Version

any (win 8.1, fedora 28, maOS 10.13.5)

## Replication Case

1. Navigate to https://kitchen.ci/
2. look for documentation on shell provisioner

## Kitchen Output

n/a

## Kitchen Diagnose

n/a

**Comment by cheeseplus** [comment]
Opening this on the actual docs repo https://github.com/test-kitchen/kitchen-docs/issues/87
