### ISSUE TITLE
Running specific modules of puppet and testing for it

### ISSUE THREAD

**Issue by jpninanjohn** [test-kitchen/test-kitchen#1445]
I am not sure if this is the correct place to ask this question, but I'm not sure if this is implemented or not.

I am using the puppet-apply provisioner and kitchen vagrant to run tests on my puppet repository. Currently the entire catalogue is applied before the tests are run. 

I don't want to run the entire catalogue every single time I add a puppet module. Is there any way to run specific modules by specifying them as parameters or any other way? I want to run the appropriate tests for the same as well after the modules are applied. 

Test Kitchen version 1.22.0

**Comment by cheeseplus** [comment]
Hey @jpninanjohn you're probably better off checking/asking [here](https://github.com/neillturner/kitchen-puppet) as we (the core kitchen team) don't maintain or develop the puppet provisioner.

**Comment by jpninanjohn** [comment]
Thanks. I will take the question over there.
