### ISSUE TITLE
Vagrant ships with WinRM support builtin

### ISSUE THREAD

**Issue by safematix** [test-kitchen/test-kitchen#1460]
## Description

Vagrant has detected the `vagrant-winrm` plugin. Vagrant ships with
WinRM support builtin and no longer requires the `vagrant-winrm` plugin.

kitchen Version: 1.23.2
Chef Development Kit Version: 3.2.30
Vagrant Version: 2.1.4

## Platform Version

Ubuntu 18.04

## Replication Case

Install vagrant 2.1.4 and vagrant-winrm plugin.

## Kitchen Output

Kitchen/Vagrant output with vagrant-winrm plugin:

```ruby
STDERR: WARNING: Vagrant has detected the `vagrant-winrm` plugin. Vagrant ships with
WinRM support builtin and no longer requires the `vagrant-winrm` plugin. To
prevent unexpected errors please uninstall the `vagrant-winrm` plugin using
the command shown below:

  vagrant plugin uninstall vagrant-winrm

To disable this warning, set the environment variable `VAGRANT_IGNORE_WINRM_PLUGIN`
```

Kitchen output without vagrant-winrm plugin:

```ruby
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: WinRM Transport requires the vagrant-winrm Vagrant plugin to properly communicate with this Vagrant VM. Please install this plugin with: `vagrant plugin install vagrant-winrm' and try again.
>>>>>> ----------------------
```

**Comment by coderanger** [comment]
Test Kitchen doesn't touch your vagrant plugins so you do have to actually follow the instructions.

**Comment by safematix** [comment]
Kitchen should check the version and if it is smaller than the version which comes with winrm support, then the should show the exception.

**Comment by coderanger** [comment]
That error comes directly from Vagrant, Test Kitchen is not involved.

**Comment by cheeseplus** [comment]
The latter warning is coming from kitchen-vagrant and we can certainly adjust the check but this is the wrong repo for the issue/work.

https://github.com/test-kitchen/kitchen-vagrant/blob/d519b679abe8963bb68c897fd16370d2aeef95ca/lib/kitchen/driver/vagrant.rb#L547-L565

**Comment by cheeseplus** [comment]
Closing here and opening https://github.com/test-kitchen/kitchen-vagrant/issues/372
