### ISSUE TITLE
Passing alternative configs to Kitchen::ThorTasks

### ISSUE THREAD

**Issue by predatorian3** [test-kitchen/test-kitchen#1462]
## Description

Is it possible to pass an alternative .kitchen.local.yml file to Kitchen::ThorTasks in a Thorfile? 

* [Kitchen::ThorTasks](https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/thor_tasks.rb)
* 

## Kitchen Version

1.23.2

## ChefDK Version

> If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

Not using ChefDK

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

ruby-2.4.1/111

## Platform Version

> Tell us which Operating System distribution and version test-kitchen is running on.\

MacOS High Sierra 10.12.6

## Replication Case

> Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

N/A

## Kitchen Output

> The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

> The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

> Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

none available

## Kitchen Diagnose

> Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

N/A

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by cheeseplus** [comment]
Use the environment variables
- KITCHEN_YAML
- KITCHEN_LOCAL_YAML

**Comment by cheeseplus** [comment]
Closing this one as answered. Feel free to comment if this doesn't solve it for you but otherwise the Thor tasks shouldn't be overly leveraged.
