### ISSUE TITLE
"kitchen list --json" doesn't always output valid json

### ISSUE THREAD

**Issue by jayhendren** [test-kitchen/test-kitchen#1469]
## Description

Sometimes `kitchen list --json` may emit warnings in addition to normal JSON output; the warnings prevent output from being correctly parsed as JSON.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`). 

```
[birdsnest ~/Work/git/cookbooks/cub_policy_test](CF-785|✔)[I]% kitchen --version
Test Kitchen version 1.22.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```
[birdsnest ~/Work/git/cookbooks/cub_policy_test](CF-785|✔)[I]% chef --version
Chef Development Kit Version: 3.1.0
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.1.72
```

## Platform Version

Arch Linux

## Replication Case

Create a situation that causes kitchen to emit warnings.  For instance, use a deprecated configuration option in `.kitchen.yml`.  Run `kitchen list --json`.  The output will not be valid JSON and cannot be parsed by a JSON parser.

## Kitchen Output

```
[birdsnest ~/Work/git/cookbooks/cub_policy_test](CF-785|✔)[I]% kitchen list --json 2>/dev/null
$$$$$$ Deprecated configuration detected:
require_chef_omnibus
Run 'kitchen doctor' for details.

[
  {
    "instance": "default-cub-rh7",
    "driver": "Vagrant",
    "provisioner": "ChefZero",
    "verifier": "CubBusser",
    "transport": "Sftp",
    "last_action": null,
    "last_error": null
  }
]
```

The beginning of this output (`$$$$$$ Deprecated configuration detected: ...`) causes JSON parsers to error out.

**Comment by cheeseplus** [comment]
That is less than pleasant, will see what we can do there.

**Comment by marcparadise** [comment]
We should look at outputting deprecation and other warnings to stderr to prevent this.
