### ISSUE TITLE
RFC Unified attributes

### ISSUE THREAD

**Issue by rmoles** [test-kitchen/test-kitchen#1471]
## Description

This is to start a discussion on how attributes should be managed in the kitchen.yml. It would be nice to declare global attributes within the kitchen.yml file that can be used by inspec and/or chef-client.

Raising as a follow-on of a change made within inspec: https://github.com/inspec/inspec/issues/3176

**Comment by cheeseplus** [comment]
I'm not sure the purpose this serves - attributes for chef-client are wholly orthogonal to attributes in inspec and they are fed via completely different mechanisms. Moreover test-kitchen is more than just a chef-client provisioner.

Raising this doesn't serve as an RFC, there is an entire process for the chef community RFCs as per https://github.com/chef/chef-rfc and those are brought up at the weekly developer meetings.

**Comment by cheeseplus** [comment]
We totally understand _why_ people want this but this should be a clean interface/information passing between chef-client and inspec somehow, kitchen really shouldn't be involved or at the very least only nominally. Past efforts involve the chef run itself dropping off a file or doing something with say a handler to create a file that inspec could then look for during it's run.

Unifying attributes it in kitchen would be non-trivial given these things have been separate and purposefully so up until now. This isn't to say we aren't open to options but this discussion has happened a few times with no resolution.

**Comment by coderanger** [comment]
I'm with @cheeseplus on this. If kitchen-inspec wants to support something, that's cool, but it's not part of the abstraction of TK and I don't think we should add it. Specifically if kitchen-inspec wants to expose the instance attributes in some way, that is its prerogative.
