### ISSUE TITLE
test-kitchen does not support net-ssh > 5.0

### ISSUE THREAD

**Issue by Val** [test-kitchen/test-kitchen#1474]
## Description

`test-kitchen` cannot be included in a project using `net-ssh` with version > 5.0

## Kitchen Version

```Shell
$ bundle exec kitchen --version
Test Kitchen version 1.23.2
```

_I did not use **ChefDK**_.

## Ruby Version

```Shell
$ chruby
* ruby-2.5.1
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

## Platform Version

I'm running Debian stretch:

``Shell
$ cat /etc/debian_version 
9.5
``

## Replication Case

Try a `bundle` command with this `Gemfile`
```Ruby
gem 'test-kitchen', require: false
gem 'net-ssh', '>= 5.0', require: false
```

Result:
```Shell
Resolving dependencies...
Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a
line like this to your Gemfile:
source 'https://rubygems.org'
Bundler could not find compatible versions for gem "net-ssh":
  In Gemfile:
    net-ssh (>= 5.0)

    test-kitchen was resolved to 1.23.2, which depends on
      net-ssh (< 5.0, >= 2.9)
```

**Comment by coderanger** [comment]
That's not really a bug per se. Our dependencies are clearly stated in the gem metadata and bundler is correct to fail. If you would like to test out compat and fix any bugs with net-ssh 5.x, we welcome your contribution.

**Comment by Val** [comment]
@coderanger : could you please show my PR #1475 ?
