### ISSUE TITLE
Suites.Verifier.Inspec_tests

### ISSUE THREAD

**Issue by TheDigitalNinja** [test-kitchen/test-kitchen#1478]
## Description

Specifying different tests directories via suites.verifier.inspec_tests doesn't seem to be working. 

Given the .kitchen file below I would expect the tests in "test/smoke/default" to be executed but the output says its looking in the default location of "test/integration/default".

## Kitchen Version

```ruby
1.23.2
```

## Ruby Version

```ruby
ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
```

## Platform Version

Windows 10

## Replication Case
.kitchen.yml

```ruby
---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  - name: ubuntu

verifier:
  name: terraform
  systems:
    - name: default
      backend: aws

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/smoke/default
```

## Kitchen Output

```ruby
-----> Verifying <default-ubuntu>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [No such file or directory @ rb_sysopen - C:/Users/dswni/Projects/platform-taas/src/baseinfrastructure/test/integration/default] on default-ubuntu
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## Kitchen Diagnose

https://gist.github.com/TheDigitalNinja/9273de5a46de358c8817154f0b7ffd7a

**Comment by coderanger** [comment]
This is a feature of kitchen-inspec, which is not directly managed by the Test Kitchen team. You can raise any issues over on their repo :)
