### ISSUE TITLE
Remove dependency on mixlib-shellout. Ruby 1.9 has what we need.

### ISSUE THREAD

**Issue by reset** [test-kitchen/test-kitchen#148]
Ruby 1.9 has the cross platform and thread safe ability to shell out using `Process.spawn` and `Process.waitpid2`.

mixlib-shellout doesn't support JRuby and also requires in the win32-process gem which absolutely MURDERS the built-in Process module. This is causing some really weird issues in Berkshelf since Ridley + Test-Kitchen are a dependency of it and we are using the built-in Ruby 1.9 primitives.

More information here: https://github.com/RiotGames/ridley/issues/170

**Comment by smurawski** [comment]
Thanks for the discussion everyone, but there hasn't been any action on this for almost three years and I don't see us moving away from mixlib-shellout anytime soon, so I'm going to close this out.
