### ISSUE TITLE
Ubuntu guest hangs at "Preparing Client.rb"

### ISSUE THREAD

**Issue by sredne** [test-kitchen/test-kitchen#1482]
## Description

When running kitchen converge against my Ubuntu 16.04 VM, it hangs at the Preparing client.rb step.  SSH is available to the machine, and the username and password is both verifiable during the kitchen create process.  The only thing I can think of is the way it's passing the shell commands down using sudo.  I've ran the command in the output that it gets stuck on to install chef omnibus and it does nothing.  Any ideas?

## Kitchen Version

```ruby
Test Kitchen version 1.23.2
```

## ChefDK Version

```ruby
Chef Development Kit Version: 3.3.23
chef-client version: 14.5.33
```

## Platform Version

Windows 10 1709 w/ Hyper-V driver

## Replication Case

I'm able to ssh into the machine using admin-local, as well as directly console in.  The admin-local account is in the "sudo" group and can run sudo commands.

## Kitchen Output

https://gist.github.com/sredne/0d0dd0005243c81de4e6493f8603d4cf

## Kitchen Diagnose

https://gist.github.com/sredne/293f872c5e7b25cc34df393b61ba1817

**Comment by cheeseplus** [comment]
It'd be useful if we could also get the `.kitchen.yml` - not sure if this one belongs on core and not the driver but we can start here.

**Comment by sredne** [comment]
Here's my kitchen.yml:

```---
driver:
  name: hyperv
  parent_vhd_folder: ../../../VHDX
  parent_vhd_name: ubuntu-xenial.vhdx
  vm_switch: packer-hyperv-iso
  vm_generation: 2
  memory_startup_bytes: 2GB
  disable_secureboot: true

provisioner:
  name: chef_zero
  product_version: 14
  require_chef_omnibus: true
  attributes:
    authorization:
      sudo:
        passwordless: true

transport:
  name: ssh
  username: admin-local
  password: admin-local
    
platforms:
  - name: ubuntu-16.04

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[linux::default]
    verifier:
      inspec_tests:
        - test/smoke/default
```

I didn't think it was an issue with the Hyper-V driver since it's just trying to do the things with SSH.  I would think the Hyper-V part is out of the equation, but I could be wrong.

**Comment by cheeseplus** [comment]
If ssh were broken across the board with other drivers then we'd likely have noticed, hence why it feels driver specific at this juncture.

**Comment by cheeseplus** [comment]
These settings don't make sense either:
```
  product_version: 14
  require_chef_omnibus: true
```

If you want to use `porduct_version` you must also use `product_name` - both these directly conflict with `require_chef_omnibus`.

**Comment by sredne** [comment]
Yeah I was testing setting to see if that was the problem, I've removed the `product_version` and `require_chef_omnibus` settings and it still seems to hang.

**Comment by sredne** [comment]
So after some investigating, I added 
`admin-local ALL=(ALL) NOPASSWD:ALL`
to my `/etc/sudoers` file in the guest Ubuntu VM, and it was able to get past that step.  I'm now back to wondering if it's back to the SSH call and it's not sending the password down properly to run the omnibus install.  Is there any configuration requirements I need to have on the guest in order to make this work?

**Comment by cheeseplus** [comment]
As I don't maintain the hyper-v driver that is hard to say, I do believe there are some base level requirements (similar to Vagrant boxes) that are expected but not sure that is enumerated anywhere.

**Comment by sredne** [comment]
I'm still having a hard time believing it has anything to do with the driver because it's not actually running any hyper-v commands, it's doing standard SSH calls against the VM.

**Comment by cheeseplus** [comment]
Not saying it's the driver, I'm saying it's likely the base box not adhering to certain semantics that are expected.

**Comment by cheeseplus** [comment]
Closing this out - as stated the semantics of the base boxes as expected by the individual drivers are the responsibility of those drivers to either do on a users behalf or document. As a guide, the Vagrant base box instructions serve well for any local hypervisors https://www.vagrantup.com/docs/boxes/base.html
