### ISSUE TITLE
Kitchen::UserError: Unknown lifecycle hook target {}

### ISSUE THREAD

**Issue by benmullin333** [test-kitchen/test-kitchen#1498]
## Description

When running kitchen with two suites, at end of last suite, I get this error 
`Kitchen::UserError: Unknown lifecycle hook target {}`
seems to belong to this line:
https://github.com/test-kitchen/test-kitchen/blob/314fae60b3b4dddfc6296dacf672d4c2c46b80dd/lib/kitchen/lifecycle_hooks.rb#L75
If I comment out this raised exception, everything seems to work fine.

What are possible causes of this?  I'm probably munging something on my config, but can't figure out what.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.23.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
14.5.33
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
$ ruby --version
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin17]
```

## Platform Version

OSX

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Kitchen Output
```
       Finished verifying <default-amazonlinux-201709> (0m2.19s).
       Finished testing <default-amazonlinux-201709> (0m20.92s).
-----> Destroying <default-amazonlinux-201709>...
       b5c9e4645759
       b5c9e4645759e3f81616271bda1a465d61d078260cb3ecf0c40daa71459f5c01
       Finished destroying <default-amazonlinux-201709> (0m0.31s).
-----> Cleaning up any prior instances of <ruby-amazonlinux-201709>
-----> Destroying <ruby-amazonlinux-201709>...
       Finished destroying <ruby-amazonlinux-201709> (0m0.00s).
-----> Testing <ruby-amazonlinux-201709>
-----> Destroying <ruby-amazonlinux-201709>...
       Finished destroying <ruby-amazonlinux-201709> (0m0.00s).
rake aborted!
Kitchen::UserError: Unknown lifecycle hook target {}
/home/circleci/project/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:75:in `block in run'
/home/circleci/project/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:64:in `each'
/home/circleci/project/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:64:in `run'
/home/circleci/project/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
/home/circleci/project/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
/home/circleci/project/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
/home/circleci/project/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
/home/circleci/project/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:162:in `verify'
/home/circleci/project/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:191:in `block in test'
/home/circleci/project/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:187:in `test'
/home/circleci/project/lib/rake_tasks/kitchen_tasks.rb:31:in `block (4 levels) in define_tasks'
...
```

```ruby
# Copy-paste your results here
```

## Kitchen Diagnose
https://gist.github.com/benmullin333/b2c7547eaba5e784dfea754854b96585
https://gist.github.com/benmullin333/b610ba35c49a9eb6c31cba38fc812395

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by coderanger** [comment]
Please include your kitchen.yml

**Comment by benmullin333** [comment]
.kitchen.yml:
https://gist.github.com/benmullin333/ab3a884a15fab46e53d06e0cff953321

Thanks @coderanger !

**Comment by coderanger** [comment]
So probably something going funky with the data_munger as you're using the legacy pre_create_command option. Convert that to the new system and see if it helpers? The legacy munger shouldn't do this, but I no longer do much work on Chef stuff so if the new syntax fixes things, I'm unlikely to spend much time on it.

**Comment by benmullin333** [comment]
Thanks!  I’ll try it out.

**Comment by benmullin333** [comment]
Worth noting for future search that this is part of chef 12 to chef 14 upgrade.

**Comment by tigpas** [comment]
Hi,

looks like I have the same issue.

I use the feature from https://github.com/test-kitchen/test-kitchen/issues/598. It's working fine if I use kitchen for one suite, but `kitchen test` failed after the second suite.

If I comment the same line out in `test-kitchen/lib/kitchen/lifecycle_hooks.rb`, the `- local: sleep 10` is only running on the first suite, but `kitchen test` is working fine.

# Kitchen Version
Test Kitchen version 1.23.2
# Ruby Version
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
# Platform Version
Debian 9.5
# Kitchen File
https://github.com/tigpas/openvpn-formula/blob/add-kitchen-fix-log/.kitchen.yml

# Kitchen Output

```
> kitchen converge
-----> Starting Kitchen (v1.23.2)
-----> Converging <config-bento-debian-9>...
       Preparing files for transfer

       <SALT STUFF>
       
       Downloading files from <config-bento-debian-9>
       Finished converging <config-bento-debian-9> (0m6.89s).
       <SLEEP 10>
-----> Converging <config-bento-debian-8>...
       Preparing files for transfer
       
       <SALT STUFF>
       
       Downloading files from <config-bento-debian-8>
       Finished converging <config-bento-debian-8> (0m10.28s).
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Unknown lifecycle hook target {}
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

<EXIT 20>
```

# Kitchen Log
```
I, [2018-11-30T07:31:36.387100 #9944]  INFO -- Kitchen: -----> Starting Kitchen (v1.23.2)
I, [2018-11-30T07:31:36.597868 #9944]  INFO -- Kitchen: -----> Converging <config-bento-debian-9>...
I, [2018-11-30T07:31:53.573632 #9944]  INFO -- Kitchen: -----> Converging <config-bento-debian-8>...
E, [2018-11-30T07:32:03.993330 #9944] ERROR -- Kitchen: ------Exception-------
E, [2018-11-30T07:32:03.993417 #9944] ERROR -- Kitchen: Class: Kitchen::UserError
E, [2018-11-30T07:32:03.993472 #9944] ERROR -- Kitchen: Message: Unknown lifecycle hook target {}
E, [2018-11-30T07:32:03.993523 #9944] ERROR -- Kitchen: ----------------------
E, [2018-11-30T07:32:03.993561 #9944] ERROR -- Kitchen: ------Backtrace-------
E, [2018-11-30T07:32:03.993598 #9944] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:75:in `block in run'
E, [2018-11-30T07:32:03.993624 #9944] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:64:in `each'
E, [2018-11-30T07:32:03.993821 #9944] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:64:in `run'
E, [2018-11-30T07:32:03.993899 #9944] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:46:in `run_with_hooks'
E, [2018-11-30T07:32:03.993999 #9944] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2018-11-30T07:32:03.994063 #9944] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
E, [2018-11-30T07:32:03.994123 #9944] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2018-11-30T07:32:03.994203 #9944] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:140:in `converge'
E, [2018-11-30T07:32:03.994271 #9944] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
E, [2018-11-30T07:32:03.994299 #9944] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-11-30T07:32:03.994325 #9944] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-11-30T07:32:03.994394 #9944] ERROR -- Kitchen: ----End Backtrace-----
```

# Kitchen Diagnose
https://gist.github.com/tigpas/8d20b6bfb44559fe6f57a0082e2ba71a

**Comment by moofrank** [comment]
I'm seeing this as well. OSX, ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17], Test Kitchen version 1.23.2

In my case, I'm running a suite with two platforms. I have a pre-destroy to clean up a couple of things. The first succeeds, but the second fails with:

1usmbranham:puppet-env-1106_net-syslog branham$ kitchen destroy forwarder
-----> Starting Kitchen (v1.23.2)
       Could not set time -- leave may fail
       Left domain.
-----> Destroying <forwarder-c7>...
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <forwarder-c7> destroyed.
       Finished destroying <forwarder-c7> (0m4.43s).
#<Thread:0x00007fdb2b8e0018@/usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:167 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:173:in `destroy'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:64:in `run'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:64:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:75:in `block in run': Unknown lifecycle hook target {} (Kitchen::UserError)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Unknown lifecycle hook target {}
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

#But then if I explicitly destroy the second platform, it succeeds. 
1usmbranham:puppet-env-1106_net-syslog branham$ kitchen destroy forwarder-c6
-----> Starting Kitchen (v1.23.2)
       Could not set time -- leave may fail
       Left domain.
-----> Destroying <forwarder-c6>...
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <forwarder-c6> destroyed.
       Finished destroying <forwarder-c6> (0m4.22s).
-----> Kitchen is finished. (0m11.58s)

**Comment by moofrank** [comment]
I am using one legacy hook, but it is from the kitchen-puppet provisioner. I need it to happen between code push and puppet apply because of the way our code is structured / 3.x.x puppet version. 

  custom_pre_apply_command: |
    ln -s /tmp/kitchen/manifests/roles /tmp/kitchen/modules
    ln -s /tmp/kitchen/manifests/profiles /tmp/kitchen/modules

**Comment by PowerSchill** [comment]
I am not using the legacy hook but am still encountering this issue.

**Comment by cheeseplus** [comment]
As noted in https://github.com/test-kitchen/test-kitchen/issues/1498#issuecomment-439657512 almost all these are due to drivers that haven't updated their syntax to work with this feature. The core kitchen team is at best a skeleton crew and we can't hunt down and fix each misbehaving driver.

@PowerSchill could you open a new issue with your .kitchen.yml and other diagnostic information? I'm closing this one b/c all the rest lead back to semi-maintained drivers and want to separate the noise.
