### ISSUE TITLE
kitchen verify fails on amazonlinux (vagrant and docker drivers)

### ISSUE THREAD

**Issue by jkornblum** [test-kitchen/test-kitchen#1506]
## Description
I've tried running a simple cookbook using amazonlinux (both via a vagrant box and official Amazon docker image) and I'm getting the same error for both. `kitchen create` and `kitchen converge` work fine but `kitchen verify` fails with this error `Message: undefined method [] for nil:NilClass`

Can anyone help me understand whats happening? Works fine when I use say ubuntu-1604 platform.

## Kitchen Version
```
Chef Development Kit Version: 3.5.13
chef-client version: 14.7.17
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 3.0.52
```
## Platform Version

Elementary OS 5 (Ubuntu 18.04 fork) and Windows 10

## Replication Case

default.rb
```ruby
user 'user1' do
    action :create
    manage_home true
end
```

default_test.rb
```ruby
describe user('user1') do
	it { should exist }
end
```

kitchen.yml
```ruby
---
driver:
  name: docker
  #name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  # - name: amazon-linux
  #   driver_config:
  #     box: gbailey/amzn2
  - name: amazonlinux
    driver_config:
      image: amazonlinux
      platform: centos

suites:
  - name: default
    run_list:
      - recipe[mycookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
```

## Kitchen Output

Gist of full error log (from docker run)
[default-amazon-linux.log](https://gist.github.com/jkornblum/86ec8ae7b16dee2a6b4cbb9ba1b6ea28)

**Comment by cheeseplus** [comment]
Although it's working for you I'd highly advise against hacking in gem installs of pre-configured ChefDK/Workstation gems as it will lead you to a bad time very quickly, the options being to use a newer DK/Workstation that includes the fixes or running your own Ruby install a la chruby. It's one of those hacks that will work until it doesn't and then cause weirder errors down the line.

As this was a problem with train that is now resolved and not core test-kitchen, closing.
