### ISSUE TITLE
sudo: unable to execute /tmp/verifier/bin/busser: Permission denied

### ISSUE THREAD

**Issue by mccoyaoife** [test-kitchen/test-kitchen#1516]
-----> Verifying <default-rhel-7>...
--
01-Feb-2019 11:24:34 | Preparing files for transfer
01-Feb-2019 11:24:34 | -----> Installing Busser (busser)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem (  3%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem (  6%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem (  9%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 12%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 15%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 18%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 21%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 24%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 27%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 30%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 33%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 35%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 53%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 71%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem ( 89%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem (100%)
01-Feb-2019 11:24:35 | Fetching: thor-0.19.0.gem (100%)
01-Feb-2019 11:24:35 | Successfully installed thor-0.19.0
01-Feb-2019 11:24:35 | Fetching: busser-0.7.1.gem
01-Feb-2019 11:24:35 | Fetching: busser-0.7.1.gem ( 64%)
01-Feb-2019 11:24:35 | Fetching: busser-0.7.1.gem (100%)
01-Feb-2019 11:24:35 | Fetching: busser-0.7.1.gem (100%)
01-Feb-2019 11:24:35 | Successfully installed busser-0.7.1
01-Feb-2019 11:24:35 | 2 gems installed
01-Feb-2019 11:24:35 | -----> Installing Busser plugin: busser-serverspec

-----> Installing Busser plugin: busser-serverspec
--
01-Feb-2019 11:24:35 | sudo: unable to execute /tmp/verifier/bin/busser: Permission denied

Getting this error, how can I get round these permission errors?

**Comment by lamont-granquist** [comment]
would need a better repro, probably a better question for slack/discourse/stackoverflow
