### ISSUE TITLE
Feature Request: Support for PowerShell Core

### ISSUE THREAD

**Issue by glennsarti** [test-kitchen/test-kitchen#1533]
## Description

PowerShell Core is a cross platform scripting tool.  Unfortunately Test-Kitchen conflates Operating System with shell commands i.e. Windows == PowerShell, Linux == Bash

However this isn't true.  I would like to see Test-Kitchen support the use of PowerShell Core on non-Windows platforms.

This would also open up the ability to run Pester cross platform just like rspec/inspec/serverspec is.

Additionally (maybe not for this issue) But Windows also supports Bash commands.

## Kitchen Version

Any

## ChefDK Version

N/A 

## Ruby Version

Windows Ruby 2.5 x64 with DevKit

## Platform Version

Windows 10 1803

## Replication Case

N/A

## Kitchen Output

N/A

## Kitchen Diagnose

N/A

**Comment by gaelcolas** [comment]
I'd love to see that too!
