### ISSUE TITLE
Class: Kitchen::Transport::SshFailed

### ISSUE THREAD

**Issue by Karthick-Gopalakrishnan** [test-kitchen/test-kitchen#1540]
## Description

Am trying converge my cookbook to Azure VM's running with Centos & Readhat. My cookbook is failing with an error saying Class: Kitchen::Transport::SshFailed attaching logs for your reference.

This happens with only Centos & Readhat in Azure VM, I tried using Ubuntu VM in Azure with same recipe and Cookbook worked.  

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.24.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 3.8.14
chef-client version: 14.10.9
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.7
kitchen version: 1.24.0
inspec version: 3.6.6
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
```

## Platform Version

Chefdk is running on Windows 10 

## Replication Case

Try to converge a cookbook to azure centos vm 

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
[default-Centos.log](https://github.com/test-kitchen/test-kitchen/files/3068659/default-Centos.log)
[kitchen.log](https://github.com/test-kitchen/test-kitchen/files/3068660/kitchen.log)


```

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by tas50** [comment]
What version of centos are you trying to connect to?

**Comment by Karthick-Gopalakrishnan** [comment]
Centos VM was destroyed, I have deployed the same cookbook in RHEL and same issue occurred. 

Os Version:  Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Comment by rajesh2285** [comment]
I am also facing the same issue from last one and half month. I was able to ssh RHEL vm's from one machine to another RHEL vm. but getting this error `Kitchen::Transport::SshFailed -- SSH session could not be established` when I run kitchen.

### My  operating system specs:
`Linux ito17313 4.4.143-94.47-default`

### Chef Version

`chef-client version: 14.1.12
delivery version: master (7206afaf4cf29a17d2144bb39c55b7212cfafcc7)
berks version: 7.0.2
kitchen version: 1.21.2
inspec version: 2.1.72`

### Ruby Version 

`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]`

**Comment by tas50** [comment]
Chances are the keys on the guest are ed25519 which is not supported by the net-ssh release in Test Kitchen. You can try downloading the Chef-DK release from our "current" channel which includes Test Kitchen 2.0. That version has ed25519 support and this should just work without issues there. https://downloads.chef.io/chefdk/current
