### ISSUE TITLE
Multi node notes

### ISSUE THREAD

**Issue by lamont-granquist** [test-kitchen/test-kitchen#1563]
The RFC:

- https://github.com/chef-boneyard/chef-rfc/blob/master/rfc084-test-kitchen-multi.md

Problems:

- people want to analyze race conditions where machines come up out-of-order which is not captured in the RFC (e.g. createA/provisionA/createB/provisionB/verifyA/verifyB vs. createA/createB/provisionA/provisionB/verifyA/verifyB)
- terraform + inspec might be a better solution
- but people want to test on laptops with vagrant + virtualbox/fusion, no vagrant provider for terraform
- people want to orchestrate reboots (another kind of action)

Questions:

- are drivers/provisioners/verifiers/transports thread safe?
- can we eliminate the distinction between provisioners and verifiers (and drivers creating machines)?
- can we construct a collection of arbitrary step and then 'converge' it (with possible concurrency)?

Happy Accidents:

- we can solve the one-machine case of running the chef provisioner twice
- we can solve the one-machine case of that with a reboot in the middle

**Comment by marcparadise** [comment]
@lamont-granquist is this still something that should be on the radar? I don't think anything significant has changed since the write-up that makes it obsolete/irrelevant.
