### ISSUE TITLE
Where's the transport doc ?

### ISSUE THREAD

**Issue by rgarrigue** [test-kitchen/test-kitchen#1565]
## Description

I've been looking around, couldn't find the transport doc, with a list of available options, their description...

**Comment by Geogboe** [comment]
Just fyi, I just dug up this page which seems to have some transport config information: https://docs.chef.io/workstation/config_yml_kitchen/#transport-settings

**Comment by tas50** [comment]
I've added transport docs here: http://kitchen.ci/docs/transports/
