### ISSUE TITLE
Working SSH key types for version 1.25

### ISSUE THREAD

**Issue by wilhelmi** [test-kitchen/test-kitchen#1570]
## Description

Trying to run with chefdk 3, which has test-kitchen 1.25 and running into key errors, such as key was 257 bytes (expecting 32). What the best way around this at this point, without having to jump to chefdk 4?

- Is there a reliable way to update net-ssh to 5.2.0?
- What are the options with ssh-keygen to create compatible keys?

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
1.25.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 3.11.4
chef-client version: 14.13.11
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 1.25.0
```

**Comment by tas50** [comment]
ChefDK 3 is not going to have support for many modern keys that distros default to now. You're going to need to upgrade to Chef Workstation to pull in the latest Test Kitchen with newer releases of net-ssh.
