### ISSUE TITLE
prepare_chef_home doesn't work on Windows guests

### ISSUE THREAD

**Issue by dpetzel** [test-kitchen/test-kitchen#158]
I have Windows images which are running an sshd daemon (not cygwin) and when attempting to converge, I get the following exception
````
The syntax of the command is incorrect.
>>>>>> Converge failed on instance <w2k8r2>.
>>>>>> Please see .kitchen/logs/w2k8r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [rm -rf /tmp/kitchen-chef-solo && mkdir -p /tmp/kitchen-chef-solo/cache]
````

I believe this stems from this line: https://github.com/opscode/test-kitchen/blob/master/lib/kitchen/driver/ssh_base.rb#L135. It seems to be assumed that the guest will always be nix? 

Is it possible to somehow, guide test-kitchen into knowing its a windows guest, and not attempt to run commands specific to nix?

**Comment by tyler-ball** [comment]
Hey @athingisathing - @fnichol just pushed changes into the windows-guest-support branch (which is the upcoming 1.4 release) that should fix this issue.  If you encounter a specific error using this branch please file another bug with the details.  If you need general support using TK for windows guests (or host), let me know.  We have a regular standup for windows support that I would be happy to have you join!
