### ISSUE TITLE
Kitchen converge fails on Windows

### ISSUE THREAD

**Issue by brandonhawbaker** [test-kitchen/test-kitchen#1581]
## Description

When I perform a kitchen converge from Windows 10 host to Windows 10 Vagrant/VirtualBox Guest I get the following:

D      [WinRM] opening remote shell on http://127.0.0.1:1025/wsman
D      [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb

## Kitchen Version
Test Kitchen version 2.2.5

```ruby
ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
```

## ChefDK Version
ChefDK version: 4.2.0
Chef Infra Client version: 15.1.36
Chef InSpec version: 4.7.3
Test Kitchen version: 2.2.5
Foodcritic version: 16.1.1
Cookstyle version: 5.0.0

```ruby
ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
```

## Platform Version

Windows 10 Enterprise

## Replication Case

1.  Install ChefDK on Windows 10
2.  Install Vagrant
3.  Create custom Windows 10 box with packer
4.  kitchen converge

## Kitchen Output

D      [WinRM] opening remote shell on http://127.0.0.1:1025/wsman
D      [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb
D      [WinRM] opening remote shell on http://127.0.0.1:1025/wsman
D      [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb
D      [WinRM] opening remote shell on http://127.0.0.1:1025/wsman
D      [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb
D      [WinRM] opening remote shell on http://127.0.0.1:1025/wsman
D      [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb
D      [WinRM] opening remote shell on http://127.0.0.1:1025/wsman
D      [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb
D      Cleaning up local sandbox in C:/windows/Temp/default-BPA-TEST-sandbox-20190810-7492-1tswztc

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [Unable to parse authorization header. Headers: {"Content-Type"=>"text/html", "Server"=>"Zscaler/5.7", "Content-length"=>"16121", "Cache-Control"=>"no-cache, proxy-revalidate", "Proxy-Connection"=>"Keep-Alive", "Connection"=>"Keep-Alive", "Date"=>"Sat, 10 Aug 2019 21:56:49 GMT"}
Body: 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd">
<html>

## Kitchen Diagnose

instances:
  default-myapp-TEST:
    platform:
      os_type: windows
      shell_type: bourne
    state_file:
      hostname: 127.0.0.1
      last_action: converge
      last_error: WinRM::WinRMHTTPTransportError
      password: PASSWORD
      port: '1025'
      rdp_port: '1026'
      username: Tester
    driver:
      boot_timeout: 1200
      box: myapp-TEST
      box_check_update:
      box_download_ca_cert:
      box_download_insecure:
      box_url:
      box_version:
      cache_directory: C:\\omnibus\\cache
      cachier:
      communicator: winrm
      customize:
        memory: 4048
      gui: true
      kitchen_cache_directory: C:/Users/brandon.hawbaker/.kitchen/cache
      kitchen_root: C:/Dev/chef/cookbooks/myapp_test
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      password: PASSWORD
      port: 1025
      pre_create_command:
      provider: virtualbox
      provision: true
      ssh: {}
      synced_folders: []
      test_base_path: C:/Dev/chef/cookbooks/myapp_test/test/integration
      username: Tester
      vagrant_binary: vagrant
      vagrantfile_erb: C:/Dev/chef/cookbooks/myapp_test/templates/Vagrantfile.erb
      vagrantfiles: []
      vm_hostname: false
    provisioner:
      always_update_cookbooks: true
      architecture:
      attributes: {}
      channel: :stable
      checksum:
      chef_client_path: "\\bin\\chef-client.bat"
      chef_license:
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,VERSION,metadata.{json,rb},attributes.rb,recipe.rb,attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      debug:
      deprecations_as_errors: false
      download_url:
      downloads: {}
      encrypted_data_bag_secret_key_path:
      enforce_idempotency: false
      environments_path:
      ftp_proxy:
      http_proxy: http://proxy-am.shell.com:8080
      https_proxy: http://proxy-am.shell.com:8080
      install_strategy: once
      json_attributes: true
      kitchen_root: C:/Dev/chef/cookbooks/myapp_test
      log_file:
      log_level: info
      max_retries: 1
      multiple_converge: 1
      name: chef_zero
      named_run_list: {}
      no_proxy: 127.0.0.1
      nodes_path:
      platform:
      platform_version:
      policyfile:
      policyfile_path:
      product_name:
      product_version: :latest
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code:
      - 35
      - 213
      roles_path:
      root_path: "$env:TEMP\\kitchen"
      ruby_bindir: "\\embedded\\bin"
      run_list:
      - recipe[myapp_test::default]
      sudo:
      sudo_command:
      test_base_path: C:/Dev/chef/cookbooks/myapp_test/test/integration
      wait_for_retry: 30
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      elevated: true
      kitchen_root: C:/Dev/chef/cookbooks/myapp_test
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      operation_timeout: 60
      password: PASSWORD
      port: 1025
      rdp_port: 3389
      receive_timeout: 70
      scheme: http
      test_base_path: C:/Dev/chef/cookbooks/myapp_test/test/integration
      username: Tester
      winrm_transport: :negotiate
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      debug:
      ftp_proxy:
      http_proxy: http://proxy-am.shell.com:8080
      https_proxy: http://proxy-am.shell.com:8080
      inspec_tests:
      - test/integration/default
      kitchen_root: C:/Dev/chef/cookbooks/myapp_test
      log_level: :info
      name: inspec
      no_proxy: 127.0.0.1
      root_path: "$env:TEMP\\verifier"
      sudo:
      sudo_command:
      suite_name: default
      test_base_path: C:/Dev/chef/cookbooks/myapp_test/test/integration

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by brandonhawbaker** [comment]
One thing that is odd, is that it appears to be hitting the proxy for 127.0.0.1 even though I'm using the "no_proxy" setting for 127.0.0.1.

**Comment by tinar10** [comment]
have the same issue when running the kitchen converge.

```
D      [WinRM] opening remote shell on http://ec2-18-220-20-7.us-east-2.compute.amazonaws.com:5985/wsman
D      [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb
```

**Comment by softwool** [comment]
Any resolution around this? I got stuck in the same issue.

**Comment by brandonhawbaker** [comment]
If I remember correctly the issue was that the no_proxy setting was not being honored from the kitchen.yml file like it should have been.  Instead the setting from the c:\users\[user]\.chef\config.rb was being used.  I think I had to disable it from other places, including my environment variables.  Using config.rb was my work-around, I believe, but I still consider this a bug.  Kitchen.yml should trump other files.

**Comment by mbaitelman** [comment]
I had the same issue, found that the issue was the internal firewall blocking WinRM.
