### ISSUE TITLE
SSH transport appears to be running commands as foreground processes

### ISSUE THREAD

**Issue by terminalmage** [test-kitchen/test-kitchen#1586]
## Description

When a command is run using the SSH transport, that command shows up in the `ps` results as a member of the foreground process group, as do any other commands that are spawned by that process, including init scripts and the daemons that they start. As a result, when kitchen disconnects, these processes are SIGHUP'ed because their controlling TTY is no longer present.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
% kitchen version
Test Kitchen version 2.2.5
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
% ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

## Platform Version

Arch Linux

## Replication Case

I am using kitchen-salt's salt_solo provisioner. I've created [this gist](https://gist.github.com/terminalmage/74c01bf856238d8849d8daae67950023) with some files you should be able to use to get set up. Just create a new directory and download those three files into it, then create a subdirectory called "metricbeat" and move `init.sls` into it (sorry, gist won't let you make files in subdirectories). You can then run a `bundle install` to get test-kitchen, kitchen-salt, etc. installed.

Next, run `kitchen converge -l debug`. In a separate terminal you can `kitchen login` to get a shell on the container. Then just wait for the "sleep 30" to be run (you'll see it in Salt's debug logging). Now you'll have 30 seconds to run `ps` commands to confirm that the process for the daemon is in the foreground process group (as noted by the plus sign in the `STAT` column). Once the 30 second sleep is complete and kitchen disconnects, you can run `ps` again and you'll see that the daemon is no longer running. You can then run `sudo /sbin/service metricbeat start` and again run `ps` to see that the process does not have the `+` in the `STAT` column. If you logout, and repeat the `kitchen login` to log back in, you'll notice that the daemon is still running.

## Kitchen Output

The output is in a file called `kitchen_output.txt` in [this gist](https://gist.github.com/terminalmage/74c01bf856238d8849d8daae67950023). Note that this output is from before I stripped down the use case for this report.

## Kitchen Diagnose

The output is in a file called `kitchen_diagnose.txt` in the same gist mentioned above.

## Additional Details

I have already opened up an downstream issue with kitchen-salt (see [here](https://github.com/saltstack/kitchen-salt/issues/293)), but since kitchen-salt isn't establishing the SSH connection (this is happening at the test-kitchen level) I am opening this issue here. It's possible that this is a bug upstream in Net::SSH, but I'm not knowledgeable enough about Ruby to dig any further.

**Comment by marcparadise** [comment]
Thanks for reporting this @terminalmage.  What processes would you expect to continue running after kitchen disconnected?

**Comment by marcparadise** [comment]
This behavior is by design - nothing done over ssh transport is expected to have a lifespan beyond the connection to the node; this is consistent with the behavior of other supported transports.
