### ISSUE TITLE
grep pipe fails to return anything with `/bin/sh -c ss -tunl | grep -E -- :25001`

### ISSUE THREAD

**Issue by ghost** [test-kitchen/test-kitchen#1595]
## Description

When running the command `/bin/sh -c ss -tunl | grep -E -- :25001`, grep doesn't return anything. I suspect this is because it is executing in a different shell environment. When I run `/bin/sh -c "ss -tunl | grep -E -- :25001"` with quotes around both commands it returns the line with the port.

This occurs when using the following piece of code in my ServerSpec test:

```ruby
describe port(25001) do
    it { should be_listening }
end
```

## Kitchen Version

v1.20.0

## ChefDK Version

v2.5.3

## Platform Version

NAME="Oracle Linux Server"
VERSION="7.4"
ID="ol"

## Replication Case

Create a simple cookbook or use an existing one, and add the test case.  Note that you may need to change the port number.

```ruby
describe port(25001) do
    it { should be_listening }
end
```

## Kitchen Output

```bash
1) Port "25001" should be listening
            Failure/Error: it { should be_listening }
              expected Port "25001" to be listening
              /bin/sh -c ss\ -tunl\ \|\ grep\ -E\ --\ :25001\\\ 
              
            # /tmp/verifier/suites/serverspec/basic_spec.rb:9:in `block (2 levels) in <top (required)>'
```

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

### NOTE on the NOTE:

This seems more like a ServerSpec issue but they don't seem to be accepting any issues at the moment: https://github.com/mizzy/serverspec

**Comment by capriciousaton** [comment]
Since ServerSpec is dead in the water, my team is going to switch to InSpec.  In the mean time, can we determine if this is specific to ServerSpec, test-kitchen or Chef?

**Comment by marcparadise** [comment]
Thanks for taking the time to write this up @ghost.  This is a ServerSpec issue; a good next step here would be to try the same test under InSpec. Closing this issue, as it is not related to Test Kitchen.
