### ISSUE TITLE
data_path with an exclude regexp to transfer only useful files

### ISSUE THREAD

**Issue by arthurzenika** [test-kitchen/test-kitchen#1596]
## Description

Started off with issue https://github.com/test-kitchen/kitchen-ec2/issues/467

Given 

```
provisioner:
  name: shell
  data_path: .
```

And the path has a number of folders with git submodules and `.tox` environments (which can get quite big), the transfer time when using https://github.com/test-kitchen/kitchen-ec2 is too long and the files are not useful to the test. 

It would be nice to provide an exclude directive : 

```
provisioner:
  name: shell
  data_path: .
  data_path_excludes: 
     - .tox
     - .git
```
So that the transferred files is a subset of the designed folder. 

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
# Copy-paste your results here
/opt/chefdk/bin/kitchen --version
Test Kitchen version 2.3.3
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
# Copy-paste your results here
/opt/chefdk/bin/chef --version
ChefDK version: 4.4.27
Chef Infra Client version: 15.3.14
Chef InSpec version: 4.16.0
Test Kitchen version: 2.3.3
Foodcritic version: 16.1.1
Cookstyle version: 5.6.2

```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
# Copy-paste your results here
/opt/chefdk/embedded/bin/ruby --version
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux]

```

## Platform Version

Ubuntu 18.04

## Feature request

I'm not sure if this lack of documentation or  a feature missing.

**Comment by cheeseplus** [comment]
This is effectively a feature - kitchen is not designed for arbitrarily copying files, full stop. It's design is such that it pushes up your code/cookbook/playbook and then runs tests which is to say that any file transfer that happens is only in service of testing some "config as code". For the `chef` provisioners there is `cookbook_files_glob` which controls which files are considered _part_ of a cookbook but that is a provisioner specific feature and not general purpose.

Instead you could consider using lifecycle hooks to use some arbitrary copy mechanism (like rsync) https://kitchen.ci/docs/reference/lifecycle-hooks/.

I'm no longer a maintainer but I can speak to the low priority of this kind of feature as it's kind of shoehorning in features to accommodate patterns that are not encouraged in kitchen - ideally if you have that many files to transit up they are made a part of the base image (AMI) or you specifically put them in a folder for `data`. There are ways to accomplish this via these above methods without any fundamental changes to kitchen.

**Comment by arthurlogilab** [comment]
@cheeseplus thanks for taking the time for this explanation. 

We'll have to look into other options for shipping these files then.

**Comment by cheeseplus** [comment]
The easiest path is just moving these files that you want to transfer in to a folder, for example `data` (that's actually the default config) and then setting `data_path` accordingly.

**Comment by arthurlogilab** [comment]
@cheeseplus thanks for answering, is it possible to have multiple `data_path` ?

**Comment by cheeseplus** [comment]
Not with how it's written, it doesn't accept an array - https://github.com/test-kitchen/test-kitchen/blob/7ce894e74f828f9e36531cf2d74588dd74fbf240/lib/kitchen/provisioner/shell.rb#L46-L49

The above is for the Shell Provisioner as data_path is not universal and has to be explicitly supported by the provisioner (Chef or Shell do). I believe someone made data_bag_path accept arrays which might be a reasonable middle ground for enhancement and a pretty easy PR.
