### ISSUE TITLE
KITCHEN_NFS=1 fails on RHEL with subscriber model

### ISSUE THREAD

**Issue by arthurlogilab** [test-kitchen/test-kitchen#1597]
## Description

When using kitchen with RHEL RedHat with subscription-manager register, which requires a registration for basic packages such as nfs-utils or rsync, using the `KITCHEN_NFS=1 ` env which switched the `synced_folders` to NFS fails on 

```
==> default: Installing NFS client...
STDERR: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

if command -v dnf; then
  dnf -y install nfs-utils nfs-utils-lib portmap
else
  yum -y install nfs-utils nfs-utils-lib portmap
fi

if test $(ps -o comm= 1) == 'systemd'; then
  /bin/systemctl restart rpcbind nfs
else
  /etc/init.d/rpcbind restart
  /etc/init.d/nfs restart
fi

Stdout from the command:

Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
No package nfs-utils available.
No package nfs-utils-lib available.
No package portmap available.
```

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
# Copy-paste your results here
/opt/chefdk/bin/kitchen --version
Test Kitchen version 2.3.3
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
# Copy-paste your results here
/opt/chefdk/bin/chef --version
ChefDK version: 4.4.27
Chef Infra Client version: 15.3.14
Chef InSpec version: 4.16.0
Test Kitchen version: 2.3.3
Foodcritic version: 16.1.1
Cookstyle version: 5.6.2

```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
# Copy-paste your results here
/opt/chefdk/embedded/bin/ruby --version
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux]

```

## Platform Version

Ubuntu 18.04

**Comment by marcparadise** [comment]
Thanks for posting this @arthurlogilab; could you clarify what you're expecting KITCHEN_NFS to do that will prevent this? I am not able to find references to that environment variable as supported in either `test-kitchen` or `kitchen-vagrant`.

**Comment by arthurlogilab** [comment]
Sorry, I can't be more explicit, this is a bug I had on an environment I no longer have access to, for a client I no longer work with. I'll close the ticket. Thanks for taking the time to look into it.
