### ISSUE TITLE
Understanding Kitchen control flow - Deprecation warnings at start of kitchen run

### ISSUE THREAD

**Issue by cphoward** [test-kitchen/test-kitchen#1607]
## Description

I am looking for help understanding the control flow of test-kitchen. I am updating the kitchen driver [kitchen-opennebula](https://github.com/test-kitchen/kitchen-opennebula) to use the latest [fog-opennebula](https://github.com/fog/fog-opennebula) gem. When I run kitchen, I am getting the following warning:

```
[fog][DEPRECATION] Unable to load Fog::OpenNebula::Compute
[fog][DEPRECATION] The format Fog::Compute::OpenNebula is deprecated
Starting Test Kitchen (v1.16.0)
```

My problem is as follows. When test kitchen starts, where is it calling `Fog::Compute::OpenNebula` from? Test kitchen runs without error. The issue is just the deprecation warning. I have removed the obvious references to `Fog::Compute::OpenNebula` from the kitchen-driver, but I cannot figure out where `fog` would be referenced from in the test-kitchen program. We are using an old version of Chef/Kitchen, but as far as I can tell, the deprecation warning is not related to the old version.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).

```ruby
Test Kitchen version 1.16.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK or Chef Workstation, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 1.6.11
chef-client version: 12.21.26
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1
```

## Ruby Version

If you are not using test-kitchen via ChefDK or Chef Workstation, please provide the output of ruby --version.

```ruby
ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux]
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

Ubuntu 16

## Replication Case

I doubt this will be useful since I don't know of any public OpenNebula cluster to test this on. But the key change is that the kitchen-opennebula driver is using `fog/opennebula` instead of the `fog` gem.

Note that I am just wondering about how test kitchen loads third-party drivers. It is not clear how my deprecation warning above is occurring.

## Kitchen Output

Please note that kitchen runs as expected (no errors), the problem is the deprecation warning.

```ruby
[fog][DEPRECATION] Unable to load Fog::OpenNebula::Compute
[fog][DEPRECATION] The format Fog::Compute::OpenNebula is deprecated
Starting Test Kitchen (v1.16.0)
...
(truncated)
```

## Kitchen Diagnose

I will add if information would be helpful.

**Comment by marcparadise** [comment]
Thanks for raising this @cphoward.  This looks like it needs to be resolved in the [fog-opennebula](https://github.com/fog/fog-opennebula) repository , which hasn't been updated in some time. It is likely a reference that is occurring internal to that gem.
