### ISSUE TITLE
Add support for non-standard chef executables (OSS distributions)

### ISSUE THREAD

**Issue by tarcinil** [test-kitchen/test-kitchen#1609]
## Description

At present, test-kitchen is only building commands that support for chef-client.  As we can not guarantee that every distribution of Chef OSS will create the symlinks for wrapping chef-client.   We should create a provisioner attribute that defines the executables used for our various chef provisioners (chef-apply, chef-solo, chef-zero).

The defaults still should be the expected offical Chef executables.

chef-zero: https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_zero.rb#L39
chef-apply: https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_apply.rb#L62
chef-solo: https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_solo.rb#L35

This also is outlined in the distribution standards distributed by Chef. 

> Additionally, commands used to execute the distribution - if they include trademarks of Chef - must be different from those in Chef Software's distribution. For example, if you create a distribution of Chef, the command to use your distribution's binary cannot be "chef", though it can be something like "kitty" - the goal is prevent confusion about which distributions come from Chef Software and which come from another source.

> That said, it is ok to symlink a command to a distribution's equivalent command. If you have created a distribution of "chef" called "kitty", it is fine to symlink "chef-client" to call "kitty-client". In these cases. you do need to make it clear that the user is using "kitty" and not "chef". If someone uses "chef-client" and it calls "kitty-client" - the command output should display words to the user reminding them that they are using "kitty" and a symlinked command, rather that the official "chef" distribution.

Source: https://github.com/chef/chef-oss-practices/blob/510ccb2b1b9b046247be5f99083d0c2e30649dad/distributions/distribution-guidelines.md

## Kitchen Version

```ruby
$ kitchen --version
Test Kitchen version 2.3.4
```

## ChefDK Version
N/A

## Ruby Version

```ruby
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]
```

## Platform Version

MacOS 10.14.6

## Replication Case

If I use the Cinc client as an example, if they didn't have cinc-wrapper to symlink chef executables, then test-kitchen will not work for it.

https://gitlab.com/cinc-project/client/blob/master/patches/chef/0002-Cinc-omnibus-patches.patch#L299

**Comment by tas50** [comment]
This is something the community is going to need to tackle and I think that folks like @ramereth should probably provide input on how they think it could best be handled.

**Comment by ramereth** [comment]
Currently, if you use Cinc Workstation test-kitchen should work "out of the box" if you're testing against Linux or MacOS systems AFAIK. This is due to the fact that there is a wrapper in place which test-kitchen defaults to.

However I do know there is some issues with testing on Windows instances since that wrapper doesn't exist yet. I recall we created a ruby-based wrapper which should resolve this but I need to take a closer look.

**Comment by dbresson** [comment]
Not really. The provisioner installs chef instead of cinc, and it doesn't currently have a way to not accept the chef license agreement if you work around that to get cinc installed instead.

**Comment by artem-sidorenko** [comment]
One of related issues is because of https://github.com/test-kitchen/test-kitchen/blob/3c43f71c6c9cb7a6dd9095e19ab757e61cc1cac3/lib/kitchen/provisioner/chef/policyfile.rb#L81

If you have a blank system installation, have some kind of chef repo with Policyfiles and tries to run the kitchen: you get following:

```
-----> Starting Test Kitchen (v3.5.0)
-----> Converging <default-debian-12>...
$$$$$$ Running legacy converge for 'Digitalocean' Driver
       Preparing files for transfer
       Installing cookbooks for Policyfile PATH/Policyfile.rb using `/usr/local/bin/chef-cli install`
       Redirecting to cinc-cli
       ERROR: missing argument: --chef-license

       Usage: cinc install [ POLICY_FILE ] [options]

       `cinc install` evaluates a `Policyfile.rb` to find a compatible set of
       cookbooks for the policy's run_list and caches them locally. It emits a
       Policyfile.lock.json describing the locked cookbook set. You can use the
       lockfile to install the locked cookbooks on another machine. You can also push
       the lockfile to a "policy group" on a Cinc Infra Server and apply that exact set of
       cookbooks to nodes in your infrastructure.

       See our detailed README for more information:

       https://docs.chef.io/policyfile/

       Options:

        --chef-license ACCEPTANCE    Accept the license for this product and any contained products ('accept', 'accept-no-persist', or 'accept-silent')
           -c, --config CONFIG_FILE         Path to configuration file
           -D, --debug                      Enable stacktraces and other debug output
           -h, --help                       Show this message
           -v, --version                    Show Cinc Workstation version

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [Expected process to exit with [0], but received '1'
---- Begin output of /usr/local/bin/chef-cli install PATH/Policyfile.rb --chef-license  ----
STDOUT: ERROR: missing argument: --chef-license
```
