### ISSUE TITLE
Where's http://kitchen.ci ? TL/DR; it's here -> https://test-kitchen.chef.io/

### ISSUE THREAD

**Issue by rgarrigue** [test-kitchen/test-kitchen#1616]
Hi there

Where's the website ? 

**TL/DR; it's here -> https://test-kitchen.chef.io/**

Cheers,

**Comment by sblaisot** [comment]
The domain has not been renewed as you can see in whois :
```
$ whois kitchen.ci
Domain Name: kitchen.ci
[...]
Updated Date: 2020-01-14T05:00:06.101Z
Registry Expiry Date: 2019-11-14T14:30:00.0Z
Registrar Registration Expiration Date: 2019-11-14T14:30:00.0Z
Domain Status: serverHold https://icann.org/epp#serverHold
```

To temporarily acces the site, you can add in your hosts file:
```
13.225.38.86	kitchen.ci
13.225.38.69	kitchen.ci
13.225.38.128	kitchen.ci
13.225.38.84	kitchen.ci
```

That should do the trick waiting for the domain to be renewed

**Comment by epackorigan** [comment]
Also, you can build the static content yourself. see https://github.com/test-kitchen/test-kitchen/blob/master/docs/README.md for more info...

**Comment by patrickjahns** [comment]
@epackorigan 
I tried to follow the instructions however it doesn't work as expected.

Apparently the docs should have been migrated to hugo ? see: https://github.com/test-kitchen/test-kitchen/pull/1459

**Comment by nathanielhf** [comment]
Hi @patrickjahns, I reviewed the issue you linked to in your comment and came up with the following solution to get kitchen.ci running locally

`$ git clone https://github.com/test-kitchen/test-kitchen.git`

**Comment by nathanielhf** [comment]
Hi @patrickjahns, I reviewed the issue you linked to in your comment and came up with the following solution to get kitchen.ci running locally
 
```$ git clone https://github.com/test-kitchen/test-kitchen.git
$ cd test-kitchen
$ gem install bundler # (if you don't already have bundler installed)
$ bundle install
$ cd docs
$ hugo server -D
``` 
 
Then navigate to localhost:1313/docs
 
 
The hugo command is found here https://gohugo.io/getting-started/quick-start/

**Comment by es1o** [comment]
Any plans to renew domain?

**Comment by lxkm** [comment]
@fnichol looks like this domain is registered to you and is still expired / down ... any plans to renew?

(cc @tyler-ball as 'lieutenant')

**Comment by jzandbergen** [comment]
Is this project still being maintained? because I'm looking at kitchen to test our saltstack states but the all links pointing towards the dead website. So I'm not sure if kitchen is a safe choice for the future.

**Comment by jeremygaither** [comment]
+1 that the docs site being down makes the project seem unmaintained. It appears `kitchen.ci` expired on 2019-11-14, but may still be held by the original registrar. Does anyone know who has access to the domain registrar account?

**Comment by dijit** [comment]
Hi, I registered the domain and pointed it to the IPs listed in this thread.

I'll point the domain to your own nameservers if you tell me where they are, or transfer the registration to whatever provider you prefer. Please contact me.

**Comment by dijit** [comment]
nevermind, I spoke much too soon, my purchase was rejected. 

![2020-02-21-113235_grim](https://user-images.githubusercontent.com/667455/75026840-e95ce780-549d-11ea-9efc-25e81454d223.png)

**Comment by sblaisot** [comment]
Leaving this here for future reference:

```
Name Server: ns-359.awsdns-44.com
Name Server: ns-1500.awsdns-59.org
Name Server: ns-616.awsdns-13.net
Name Server: ns-1922.awsdns-48.co.uk
```

Domain status is still `serverHold` so no one can register it.

@fnichol is the legal owner. It appears to still be active on github.

@fnichol could you please at least respond to this thread?
Can you please renew the domain and/or transfer it to someone that can renew it?

I wil try reaching him through another channel if I can find one.

**Comment by sblaisot** [comment]
ping'ed @fnichol through twitter and linkedin.

**Comment by sblaisot** [comment]
Found on chef's slack: all docs can be found here: https://test-kitchen.chef.io/

**Comment by directionless** [comment]
Github appears active, but all the URLs point to a dead domain. I see there's content on  https://test-kitchen.chef.io/, and even a slack canned response, but, well, that github hasn't been updated isn't a good look. It makes this project look unmaintained.

**Comment by kmf** [comment]
bump

**Comment by sblaisot** [comment]
It seems kitchen.ci is back online
