### ISSUE TITLE
WinRm reconnection logic?

### ISSUE THREAD

**Issue by pryorda** [test-kitchen/test-kitchen#1618]
## Description

I've found that when using winrm and if you do any kind of network restart or "Add-Computer" it will leave the connection in a hung state and eventually expire resulting in a execution expired. Is there a way to have it retry to connect on disconnection so that you can continue provisioning?

**Comment by smurawski** [comment]
@pryorda You could use the reboot handling behavior in test-kitchen ( example: https://github.com/test-kitchen/kitchen-docs/issues/65#issue-239949111 )

If you close out whatever process before the network restart or system change with an particular exit code, you trigger a wait and attempt to reconnect.

**Comment by stevenoneill-jmfamily** [comment]
For example, we've (recently) set $LASTEXITCODE=35 in our custom user_data for kitchen-ec2.  Now when winrm bombs out, kitchen is happy to retry via the retry_on_exit_code feature.

Having some sensible defaults and options around windows user_data (extend in addition to override) for kitchen-ec2 would be helpful, imo.  Unfortunately, I don't see myself having cycles to work a PR around it any time soon.
