### ISSUE TITLE
Allow for "double-converges" on specific test suites

### ISSUE THREAD

**Issue by patcon** [test-kitchen/test-kitchen#162]
Context: http://community.opscode.com/chat/chef#id-391711

Working with a recipe that is particularly prone to failing on the second run, given some complex use of attribute load order.

Thinking it would be nice to be able to converge certain suites twice, before verifying. I believe that [the awesome chef-stage cookbook](https://github.com/ranjib/chef-stage) could probably be used for this as well, but it seemed something that test-kitchen might be able to easily implement, negating the need for specialized `test_mycookbook` support cookbooks.

cc: @ranjib

**Comment by tjnicholas** [comment]
+1

This would be really helpful. Especially in combination with windows support (where reboots are more commonplace). 

I think it would need to support whitelisting of 'failed' convergence runs as sometimes using 'raise' is needed to end the run when there is no point continuing prior to reboot (after upgrading powershell for example).

**Comment by emiddleton** [comment]
@tjnicholas the cleaner way is to set a flag and process the reboot at the end of the run.  You still need to handle killing the connecting service so you don't end up with a race condition.  I use this approach here https://github.com/emiddleton/cookbook-wakame-vdc to upgrade a kernel.

**Comment by tjnicholas** [comment]
@emiddleton Understood. Normally that's what I would do but in Windows land some time there really isn't any point in trying to continue. 

If you're upgrading from powershell 2 to powershell 4 (common) and use powershell from chef then there is little reason to think you'll get through the rest of the converge without an exception being thrown anyway. 

Certainly not ideal, but predictable and repeatable is worth an ugly exit code.

**Comment by TinaTina** [comment]
:+1:

**Comment by CpuID** [comment]
+1, this would be a really nice feature. The approach taken in https://github.com/test-kitchen/test-kitchen/pull/564 seems even more flexible again.

**Comment by TinaTina** [comment]
remember back then we I tried so hard to automate testing for idempotence! :joy:

**Comment by bdrust** [comment]
+1, would be nice.

**Comment by iiro** [comment]
+1 definitely

**Comment by cheeseplus** [comment]
Closing this issue (pruning a bunch of issues asking for the same thing) in favor of https://github.com/test-kitchen/test-kitchen/issues/329 and/or https://github.com/test-kitchen/test-kitchen/pull/564

**Comment by petere** [comment]
I don't think those will actually address this issue.
