### ISSUE TITLE
Failed to generate Policyfile.lock

### ISSUE THREAD

**Issue by softwool** [test-kitchen/test-kitchen#1620]
## Description
I am behind a proxy and trying to access supermarket for accessing a cookbook, 'kitchen converge' fails with the following error : STDERR: Error: Failed to generate Policyfile.lock

## Kitchen Version
Test Kitchen version 2.3.4

## ChefDK Version
ChefDK version: 4. 6. 35

## Platform Version
Ubuntu 16.04.6

This issue is quite similar to the one mentioned in https://github.com/chef/chef-dk/issues/2212 except the error is received while converging (kitchen converge).

**Comment by tas50** [comment]
If you're failing to generate the policyfile.lock the issue it actually further up the stack than Test Kitchen. We've made a lot of changes to how this works in Chef Workstation in the last year, so it would be great if you could upgrade to the latest Chef Workstation to see if this is still an issue.

**Comment by tas50** [comment]
I'm going to close this out since we haven't heard back at this point. If this is still an issue feel free to let us know.
