### ISSUE TITLE
Feature - Enable pushing in Environment variables

### ISSUE THREAD

**Issue by Xorima** [test-kitchen/test-kitchen#1622]
## Description

Currently the contents of the `CI` environment variable is pushed into the created virtual machine from the host, while this works well it is limiting in terms of what you can push in

I would like to propose that any environment variables that start with `KITCHEN_` is pushed into the created VM the same way the `CI` environment variable is today, but with the `KITCHEN_` stripped off, this would make handling the chef license easy for example, `KITCHEN_CHEF_LICENSE=accept` becomes `CHEF_LICENSE=accept` without having to update every kitchen file.

**Comment by tas50** [comment]
Closing this since we shipped it.
