### ISSUE TITLE
Missing Gemfile.lock

### ISSUE THREAD

**Issue by SMillerDev** [test-kitchen/test-kitchen#1631]
## Description

For packaging reasons it'd be nice if the repo contained a Gemfile.lock so each bundle install will only install the correct versions.

## Kitchen Version
2.4.0

## ChefDK Version
--

## Ruby Version
```ruby
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```

## Platform Version
macOS 10.15.3

## Replication Case
run `bundle install`, see a generated `Gemfile.lock`

## Kitchen Output
--

## Kitchen Diagnose
--

**Comment by tas50** [comment]
This repo is not designed to be used directly by the end user so we don't include a lockfile. This repo is for development only. For use we recommend either gem installing in your own environment where you manage particular plugin versions, or using Chef Workstation where Chef handles that work for you.

**Comment by SMillerDev** [comment]
You don't like reproducible builds from a development perspective?
