### ISSUE TITLE
Support running recipes in lifecycle hooks

### ISSUE THREAD

**Issue by Lasering** [test-kitchen/test-kitchen#1641]
## Feature Request
Lifecycle hooks could support running a recipe.

## Scenario
We are creating a chef recipe for a service which talks to a database. This recipe is presented with the necessary credentials to be able to create databases (with a specific name) in a database cluster elsewhere. However in production we don't want to create a new database, but rather connect to an existing one.

A test cookbook is created that depends on the mariadb supermarket cookbook and installs the mariadb clients locally and creates the database. With just this setup the database cluster would accumulate garbage databases over time. The lifecycle pre_destroy hook helps us to solve this problem, but since we can only run commands we will have to duplicate the logic already offered by the mariadb cookbook. A more maintainable approach would be to create a new recipe in the test cookbook that just destroys the database, then ask the pre_destroy hook to invoke that recipe.

**Comment by tas50** [comment]
I don't think this is a place we'd ever go with the lifecycle hooks. The point of the hooks is to provide a dead-simple shell execution that runs before/after. If we had to support a full recipe execution that would be a much more complex environment that would basically be a complete run of the chef-zero provisioner before running the provisioner.

**Comment by Lasering** [comment]
Running chef-zero ends up being invoking the transport (usually ssh) and running a command (usually chef-zero). Its not a dead-simple shell execution, but its also not that far from it.
