### ISSUE TITLE
Can't enable optional Ohai plugin in Test Kitchen

### ISSUE THREAD

**Issue by grdz** [test-kitchen/test-kitchen#1647]
## Description

I wanted to enable Ohai plugin "Passwd" on converged node, but nothing that I into .kitchen.yml enables this plugin. I tried:

```
provisioner:
  name: chef_zero
  client_rb:
    ohai.optional_plugins: [':Passwd']
```

This adds `ohai.optional_plugins [:Passwd]` to `/home/vagrant/.chef/client.rb`. But still I can't use attributes like this: `node['etc']['group']['SOME_USERNAME']['gid']` in templates. Even if I converge twice (because Ohai needs to run and collect attributes), or add to the beginning of the recipe resource "ohai" with action :reload to reload Ohai attributes. How can I verify if the plugin is enabled on the node? The templates that I am using are working on regular nodes with Passwd plugin enabled.

## Kitchen Version

Test Kitchen version 2.3.4

## ChefDK Version

ChefDK version: 4.7.73
Chef Infra Client version: 15.7.32
Ohai 16.1.0

If I remember correctly, Ohai plugin Passwd was enabled by default in earlier versions. Right now it has to be enabled.

## Platform Version

CentOS 7.7

## Replication Case

Enable Ohai plugin "Passwd" in .kitchen.yml file, then converge the node. Try using "Passwd" plugin attributes in some template file.

Is it a bug, or I am doing something wrong?

**Comment by scalp42** [comment]
@grdz any chance you could reopen the issue as I'm curious too

**Comment by grdz** [comment]
> @grdz any chance you could reopen the issue as I'm curious too

Ok, I edited my issue and reopened it.

**Comment by grdz** [comment]
Ok, someone on [StackOverflow](https://stackoverflow.com/a/65191742/7349932) pointed out, that this could not work because Test Kitchen does not save any node attributes to chef-server after a run, obviously. So, by this logic, even when I achieved `ohai.optional_plugins [:Passwd]` being present in `client.rb` on a test node, by doing this in `.kitchen.yml`:

```ruby
client_rb:
    ohai.optional_plugins: [':Passwd']
```

then still the test node had no attributes like `node['etc']['group']['SOME_USERNAME']['gid']`. Because Ohai on test node is not saving those attributes. So I am closing this issue, since it seems like it is because of the way that Test Kitchen works (attributes are not being saved after one kitchen verify).
