### ISSUE TITLE
[SPIKE] Customers can configure root directory for TK to work from

### ISSUE THREAD

**Issue by tyler-ball** [test-kitchen/test-kitchen#1661]
We want to perform a spike to help answer some of the questions from https://github.com/test-kitchen/test-kitchen/pull/1626 so that we can finish out that PR next sprint.

The expected outcome of this spike is:
1. Determine whether `root_path` is respected in either the `require_chef_omnibus` install path or the `product_name` install path
1. Understand why https://github.com/test-kitchen/test-kitchen/pull/1369 (a potential fix for the `require_chef_omnibus` path) was reverted
1. Update https://github.com/test-kitchen/test-kitchen/pull/1626 with a concrete list of TODOs remaining to solve the original customer issue - customers sometimes have a read-only `/tmp` dir and need to configure TK to write the installer files to a different directory.

Timebox this to 1 point (about 1 engineer for 1 day). If we find that we cannot answer these questions in that time we will continue this work into next sprint.

**Comment by clintoncwolfe** [comment]
I'm taking a look at this...

**Comment by clintoncwolfe** [comment]
PR that reverted #1369 was #1403

**Comment by clintoncwolfe** [comment]
There are at least three install paths:
* product_name is specified - not fixed by 1369 (yet).
* require_chef_omnibus is specified - Downloads to /tmp but does not execute the file directly. Installation is successful.
* neither is specified (ie only `name` is present) - the is the default as generated by `kitchen init`. Downloads to /tmp but does not execute the file directly. Installation succeeds.

**Comment by clintoncwolfe** [comment]
Code on branch msys/Nimesh/MSYS-1196_root_path_fixes currently fails when product_name is specified with the vagrant driver on a VM with a noexec /tmp and a root_path set to `/home/vagrant/kitchen` with errors:

```
Getting information for chef stable latest for ubuntu...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=latest&p=ubuntu&pv=20.04&m=x86_64
         to file /home/vagrant/kitchen/metadata.txt
       trying wget...
       environment: line 118: /home/vagrant/kitchen/stderr: Permission denied
       grep: /home/vagrant/kitchen/stderr: No such file or directory
       trying curl...
       environment: line 139: /home/vagrant/kitchen/metadata.txt: Permission denied
       grep: /home/vagrant/kitchen/stderr: No such file or directory
       trying perl...
       environment: line 169: /home/vagrant/kitchen/metadata.txt: Permission denied
       grep: /home/vagrant/kitchen/stderr: No such file or directory
       Unable to retrieve a valid package!
```

It also is noted that the passing of tmpdir to mixlib-install's install_command_options is possibly faulty. [Here](https://github.com/chef/mixlib-install/blob/4de48cc590d9cbcc7529c7327ac727d945b34eb7/lib/mixlib/install/generator/bourne/scripts/helpers.sh.erb#L324) it appears to only be an env variable, but it's not clear if that code is actually used, as that would not work on windows.

**Comment by clintoncwolfe** [comment]
Looks like there is an issue with the `sudo` wrapping of the install command. The command to create the temporary directory is executed as root, but the install script is running with an effective id of the vagrant user, so it cannot write to the temp directory (and would fail in other ways later on anyway).
