### ISSUE TITLE
WinRM elevated mode and reboot handling

### ISSUE THREAD

**Issue by gsreynolds** [test-kitchen/test-kitchen#1667]
## :ghost: Brief Description

When using WinRM elevated mode, it appears that Test Kitchen reboot handling isn't working. I'm able to reproduce this reliably in the below cookbook. This was tested in Azure so using the `kitchen-azurerm` driver, but is possibly common to all drivers.

## Version

2.5.1 and 2.5.2, in Chef Workstation 20.6.62 and 20.7.82

## Environment

Windows 2016 and Windows 2019

## Scenario

Testing a cookbook that includes a reboot

## Steps to Reproduce

https://github.com/gsreynolds/gr_reboot_test

Test Kitchen runs work correctly with reboots when `elevated: false` and break when `elevated: true`

## Expected Result

https://gist.github.com/gsreynolds/5d06d38b7648c82e1f101c13d7691b33 (this is with elevated: false, but expected to work with elevated: true)

## Actual Result

https://gist.github.com/gsreynolds/c10168c0cd315aa4a3892a04dc46874f

**Comment by damacus** [comment]
The Test Kitchen team is not planning any improvements at this time.
