### ISSUE TITLE
Suites that should fail

### ISSUE THREAD

**Issue by coderanger** [test-kitchen/test-kitchen#167]
There is not currently a great way to check that a given recipe fails, sometimes important to test that error detection is working.

**Comment by steversmith** [comment]
I have a similar need to perform verification tests after a convergence fails. As a workaround, I made a couple of changes to the test-kitchen.

In the kitchen.yml, I added a `ignore_convergence_failure` setting to the suite definition:
```
suites:
- name: should_fail
  ignore_convergence_failure: true
```

In the lib/kitchen/suite.rb, I added a `ignore_convergence_failure?` method
```
def initialize(options = {})
  ...
  option = options.fetch(:ignore_convergence_failure, false)
  @ignore_convergence_failure = option==true || option=="true"
end

# @return [Boolean] True if test suite should ignore convergence failures
def ignore_convergence_failure?
  @ignore_convergence_failure
end
```

In the lib/kitchen/instance.rb, I added a rescue block to the `converge_action` method:
```
def converge_action
  ...
      begin
        provisioner.call(state)
      rescue ActionFailed => e
        if suite.ignore_convergence_failure?
          # produce a backtrace in the instance's file logger
          # to aid in debugging
          log_failure(:converge, e)

          # produce a high level message on the console, the kitchen log,
          # and the instance's file logger to provide visibility that
          # the error is being ignored
          banner "ignore_convergence_failure on #{to_str}! " \
            "Please see .kitchen/logs/#{name}.log for more details"
        else
          raise e
        end
      end
  ...
end
```

In my serverspec, I added a test of the `chef-stacktrace.out` to confirm the expected error:
```
# validate the stack trace
describe file("/tmp/kitchen/cache/chef-stacktrace.out") do
  its(:content) { should match /my expected error/ }
end
```

***What do you think?  Should I create a pull request with my changes?***

Note that I have manually tested this, but I cannot get the automated tests to run at all, even without any edits to the code, so I have not added any unit tests...
