### ISSUE TITLE
Proxy configuration for Berkshelf during `kitchen converge`

### ISSUE THREAD

**Issue by jakauppila** [test-kitchen/test-kitchen#1682]
## :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

When I run `kitchen converge` for a cookbook execution, it attempts to resolve cookbook dependencies with Berkshelf and it appears to not respect my proxy configurations as it times out.

My workaround for years has just been to run `berks install` first prior to the `kitchen converge` but I'm guessing/hoping there's just an additional configuration I can put in place so it could be resolved during converge.

## Version

```
Cinc Workstation version: 20.9.136
Cinc Client version: 16.4.41
Cinc Auditor version: 4.22.22
Cinc CLI version: 3.0.27
Biome version: unknown
Test Kitchen version: 2.6.0
Cookstyle version: 6.16.10
```

## Environment

CentOS7 WSL on Windows 10.

I am running CNTLM on my workstation and point environment variables to that so I do not need to add username/pass on proxy configurations everywhere.

```
[jared@MYWORKSTATION tomcat]$ env | grep -i proxy
http_proxy=http://127.0.0.1:3128
https_proxy=http://127.0.0.1:3128
```

## Scenario

Execute `kitchen converge` and have it resolve cookbook dependencies via Berkshelf.

```
[jared@MYWORKSTATION tomcat]$ kitchen converge templated-service-centos-7
-----> Starting Test Kitchen (v2.6.0)
-----> Converging <templated-service-centos-7>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.1.0...
[2020-09-09T11:51:46-05:00] ERROR: Timeout connecting to https://supermarket.chef.io/universe, retry 1/5
```

Executing `berks install` works just fine and subsequent `kitchen converge` executions work

```
[jared@MYWORKSTATION tomcat]$ berks install
Resolving cookbook dependencies...
Fetching 'test' from source at test/cookbooks/test
Fetching 'tomcat' from source at .
Fetching cookbook index from https://supermarket.chef.io...
Using test (1.0.0) from source at test/cookbooks/test
Using tomcat (3.4.0) from source at .
Using homebrew (5.1.0)
Using java (6.0.0)
Using windows (7.0.0)
```

**Comment by marcparadise** [comment]
@jakuppila it looks like you can add `http_proxy` and `https_proxy` to the provisioner config, and have it work as  you would expect.  

If you run into troubles with this, please feel free to re-open this ticket so we can look further.
