### ISSUE TITLE
Re-opening Shell Provisoner Fails on Windows due to execute bit

### ISSUE THREAD

**Issue by nimDevOps** [test-kitchen/test-kitchen#1689]
## :ghost: Brief Description

This is additional attempt to fix **Shell Provisoner Fails on Windows due to execute bit** also known as  #1413,  #1381 and #442
The issue was declared as resolved few times but actually has never worked for me after.

## Version

    $ chef --version
    ChefDK version: 4.10.0
    Chef Infra Client version: 15.13.8
    Chef InSpec version: 4.22.1
    Test Kitchen version: 2.5.4
    Foodcritic version: 16.3.0
    Cookstyle version: 5.23.0

## Environment

  Windows + **chefdk** + [kitchen-vcenter](https://github.com/chef/kitchen-vcenter) driver on remote vmware VCenter

## Scenario

From windows  Run **kitchen converge** SomeSuite-linuxPlatform

## Steps to Reproduce

    On Windows host/vm do:
    1. install chefdk v 4.10.0
    2. chef gem install --no-user-install kitchen-vcenter -v 2.8.0
    3. use  kitchen-vcenter driver to provision linux vm on vmware VCenter

Run **kitchen converge BaseImage-CentOS**

Here is kitchen.yml file for reference:

		driver:
		  name: vcenter
		  vcenter_username: administrator@vsphere.local
		  vcenter_password: Passw0rd!
		  vcenter_host: vcenter.vsphere.local
		  vcenter_disable_ssl_verify: true
		transport:
		  name: ssh
		  elevated: true
		  username: vagrant
		  password: vagrant
		verifier:
		  name: inspec
		platforms:
		  - name: CentOS7
			os_type: linux
			driver_config:
			  datacenter: Datacenter
			  template: CentOS7Template
		suites:
		  - name: BaseImage
			provisioner:
			  name: shell
			  script: bootstrap.sh

## Expected Result
converged instance

## Actual Result

    kitchen converge --log-level=debug BaseImage-CentOS7
    -----> Starting Test Kitchen (v2.5.4)
    -----> Converging <BaseImage-CentOS7>...
           Preparing files for transfer
    D      Creating local sandbox in AppData/Local/Temp/1/BaseImage-CentOS7-sandbox-20201002-3492-34i5lb
           Preparing script
    D      Using script from BaseImage_Linux/bootstrap.sh
    D      [SSH] vagrant@172.32.128.7<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :keepalive_maxcount=>3, :timeout=>15, :password=>"vagrant", :verify_host_key=>:never}> (sh -c '
    TEST_KITCHEN="1"; export TEST_KITCHEN
    CHEF_LICENSE="accept"; export CHEF_LICENSE
    sudo -E rm -rf /tmp/kitchen/data ; mkdir -p /tmp/kitchen
    ')
    D      [SSH] opening connection to vagrant@172.32.128.7<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :keepalive_maxcount=>3, :timeout=>15, :password=>"vagrant", :verify_host_key=>:never}>
           Transferring files to <BaseImage-CentOS7>
    D      TIMING: scp async upload (Kitchen::Transport::Ssh)
    D      TIMING: scp async upload (Kitchen::Transport::Ssh) took (0m0.15s)
    D      Transfer complete
    D      Attempting to execute command - try 1 of 1.
    D      [SSH] vagrant@172.32.128.7<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :keepalive_maxcount=>3, :timeout=>15, :password=>"vagrant", :verify_host_key=>:never, :logger=>#<Logger:0x000000000872f620 @level=4, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000000872f558 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x000000000872f440 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mon_mutex=#<Thread::Mutex:0x000000000872f3a0>, @mon_mutex_owner_object_id=70875680, @mon_owner=nil, @mon_count=0>>, :password_prompt=>#<Net::SSH::Prompt:0x000000000872f350>, :user=>"vagrant"}> (sh -c '
    TEST_KITCHEN="1"; export TEST_KITCHEN
    CHEF_LICENSE="accept"; export CHEF_LICENSE
    sudo -E /tmp/kitchen/bootstrap.sh -h base-image -t Canada/Eastern -v 16.5.64
    ')
           sudo: /tmp/kitchen/bootstrap.sh: command not found
    D      Cleaning up local sandbox in AppData/Local/Temp/1/BaseImage-CentOS7-sandbox-20201002-3492-34i5lb

## :heavy_plus_sign: Additional context

Related issues: #1413, #1381 and #442

Resolution: 

Actually there is an existing framework for this but it does not work for os_type=linix:
**Existing code test-kitchen/lib/kitchen/configurable.rb:**

    # @return [TrueClass,FalseClass] true if `:os_type` is `"unix"` (or
    #   unset, for backwards compatibility)
    def unix_os?
      ["unix", nil].include?(instance.platform.os_type)
    end

**Working code test-kitchen/lib/kitchen/configurable.rb**:

    # @return [TrueClass,FalseClass] true if `:os_type` is `"unix"` (or
    #   unset, for backwards compatibility)
    def unix_os?
      debug "unix_os: instance.platform.os_type=#{instance.platform.os_type}"
      ["unix", "linux", nil].include?(instance.platform.os_type)
    end

**Comment by tas50** [comment]
@nimDevOps Can you confirm this with the latest Chef Workstation. It includes never versions of Test Kitchen and the plugins.

**Comment by nimDevOps** [comment]
Hi, @tas50 Sorry for the delay. I've checked  test-kitchen-2.7.0.gem test-kitchen-2.7.1.gem test-kitchen-2.7.2.gem test-kitchen-2.8.0.gem test-kitchen-2.9.0.gem gems and all of them have identical **lib/kitchen/configurable.rb** file.
I will try to install newest version and test.
