### ISSUE TITLE
/opt/chefdk/embedded/lib/ruby/2.6.0/openssl/digest.rb:40:in `initialize': Unsupported digest algorithm (SHA256). (RuntimeError)

### ISSUE THREAD

**Issue by LegacyTechnologie** [test-kitchen/test-kitchen#1692]
## Kitchen.yml
---
driver:
  name: docker

provisioner:
  name: chef_zero
  log_level: debug
  always_update_cookbooks: true
  product_name: chef
  product_version: 14

verifier:
  name: inspec

platforms:
  - name: debian-9

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

## :ghost: Brief Description

Here is my kitchen file whenever I run "sudo kitchen test" from jenkins pipeline it gives below error in output.

## Version

`ChefDK version: 4.12.0

Chef Infra Client version: 15.14.0

Chef InSpec version: 4.23.11

Test Kitchen version: 2.7.2

Foodcritic version: 16.3.0

Cookstyle version: 5.23.0

OpenSSL 1.1.0l `

## Environment

[VM cloud engine, debian 9]

## Output
`
+ sudo kitchen test
-----> Starting Test Kitchen (v2.7.2)
/opt/chefdk/embedded/lib/ruby/2.6.0/openssl/digest.rb:40:in 'initialize': Unsupported digest algorithm (SHA256). (RuntimeError)
        from /opt/chefdk/embedded/lib/ruby/2.6.0/openssl/digest.rb:40:in 'block (3 levels) in <class:Digest>'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/security.rb:357:in 'new'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/security.rb:357:in '<module:Security>'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/security.rb:332:in '<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/package.rb:44:in '<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/mixlib-archive-1.0.7/lib/mixlib/archive/tar.rb:1:in '<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/mixlib-archive-1.0.7/lib/mixlib/archive.rb:1:in 'require_relative'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/mixlib-archive-1.0.7/lib/mixlib/archive.rb:1:in '<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.1.0/lib/berkshelf/community_rest.rb:2:in '<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.1.0/lib/berkshelf.rb:226:in 'require_relative'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.1.0/lib/berkshelf.rb:226:in '<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/provisioner/chef/berkshelf.rb:96:in 'load_berkshelf!'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/provisioner/chef/berkshelf.rb:50:in 'load!'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/provisioner/chef_base.rb:487:in 'load_needed_dependencies!'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/configurable.rb:52:in 'finalize_config!'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/instance.rb:361:in 'setup_provisioner'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/instance.rb:107:in 'initialize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/config.rb:247:in 'new'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/config.rb:247:in 'new_instance'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/config.rb:143:in 'block in build_instances'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/config.rb:142:in 'map'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/config.rb:142:in 'with_index'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/config.rb:142:in 'build_instances'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/config.rb:116:in 'instances'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/command.rb:109:in 'filtered_instances'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/command.rb:139:in 'parse_subcommand'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/command/test.rb:39:in 'block in call'
        from /opt/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in 'measure'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/command/test.rb:37:in 'call'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/cli.rb:52:in 'perform'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/cli.rb:250:in 'test'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in 'run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in 'invoke_command'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in 'dispatch'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in 'start'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/bin/kitchen:11:in 'block in <top (required)>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/errors.rb:170:in 'with_friendly_errors'
        from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.7.2/bin/kitchen:11:in '<top (required)>'
        from /usr/bin/kitchen:347:in 'load'
        from /usr/bin/kitchen:347:in '<main>'
'

**Comment by tas50** [comment]
@LegacyTechnologie Can you try to reproduce this using the latest Chef Workstation please?

**Comment by tas50** [comment]
I'm going to close this out sincre we never heard back if this is still an issue with Workstation.
