### ISSUE TITLE
Deprecation Messages invalidate `kitchen diagnose` Output

### ISSUE THREAD

**Issue by tecracer-theinen** [test-kitchen/test-kitchen#1693]
## :ghost: Brief Description

As deprecation notices get printed out via STDOUT, they will invalidate the normally YAML formated output of `kitchen diagnose`. That creates problem on any occasion where the resulting YAML is supposed to be parsed for specific values (e.g. in pipelines).

## Version

2.7.2

## Environment

any environment, but I had this on Ubuntu

## Scenario

Parsing `kitchen diagnose` for some generated values

## Steps to Reproduce

I guess I am kind of partially guilty on that one ;)

Install `kitchen-vcenter` in version 2.9.0+ and use the `driver/customize` key. A deprecation warning will be shown that this section has been renamed.

If you run `kitchen diagnose` you will see:

```
$$$$$$ Deprecated configuration detected:
customize
Run 'kitchen doctor' for details.

---
timestamp: 2020-11-06 11:26:27 UTC
kitchen_version: 2.7.2
...
```

Which is no valid YAML anymore. :boom: 

## Expected Result

Getting the warning on `stderr` and the YAML on `stdout`. That way, parsing still works.

## Actual Result

```
 $ export test=$(kitchen diagnose | yq .instances)
 yq: Error running jq: ScannerError: while scanning a simple key
   in "<stdin>", line 2, column 1
 could not find expected ':'
   in "<stdin>", line 3, column 1.
```

## :heavy_plus_sign: Additional context

I am aware of the modularity of the kitchen logging system and that this might not be trivial. I didn't dig too much into it.

For anyone else running into this in the meantime, you can basically work around this like `kitchen diagnose | grep '^---$' --after-context 999 | ...` which will cut off anything preceding the YAML opening statement.

If you can live with reduced output, `kitchen diagnose --log-level=error` will also work, as deprecations are on `warn` level.

**Comment by tas50** [comment]
@tecracer-theinen Would you be ok with deprecation messages just writing to stderr instead?

**Comment by tecracer-theinen** [comment]
I think that would be the cleanest solution to show them but not invalidate YAML output etc, yes.
