### ISSUE TITLE
frozen log messages raise error "can't modify frozen String"

### ISSUE THREAD

**Issue by tbugfinder** [test-kitchen/test-kitchen#1694]
## :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

If a frozen string is passed to the logger (https://github.com/inspec/inspec-azure/blob/v1.33.2/libraries/backend/helpers.rb#L332), the error `can't modify frozen String` is raised.

```
Exception `FrozenError' at /.../vendor/bundle/ruby/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/logger.rb:300 - can't modify frozen String, created at libraries/backend/helpers.rb:340
```

## Version

2.7.2 (within kitchen-terraform 5.5.0 and inspec-azure)

## Environment

Linux
kitchen-terraform 5.5.0
inspec-azure profile > 1.28.0

## Scenario

[What you are trying to achieve and you can't?]

## Steps to Reproduce

[If you are filing an issue what are the things we need to do in order to repro your problem?]

example:

1. Create a kitchen-terraform project utilizing inspec-azure and a deprecated resource with prefix azurerm_*
2. run kitchen verifier on azure
3. error (`can't modify frozen String`) is raised

## Expected Result

[What are you expecting to happen as the consequence of above reproduction steps?]
If a frozen string is given, the logger has to either copy it or output it differently.

## Actual Result

[What actually happens after the reproduction steps?]

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.
inspec-azure: https://github.com/inspec/inspec-azure/issues/333
kitchen-terraform: https://github.com/newcontext-oss/kitchen-terraform/issues/424

**Comment by Fguhhla** [comment]
same failure with test-kitchen 2.10.0

**Comment by tas50** [comment]
I'm going to close this out from the Test Kitchen side since we need to ensure that inspec-azure is handling frozen strings.

**Comment by tbugfinder** [comment]
Hm, actually I thought it was traced down to the logger sitting in test-kitchen.

**Comment by tbugfinder** [comment]
The concat isn't applicable for frozen strings.

https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/logger.rb#L300

**Comment by tas50** [comment]
Nice catch. I added a dup on those: https://github.com/test-kitchen/test-kitchen/pull/1731

**Comment by tas50** [comment]
Closing this was fixed
