### ISSUE TITLE
Improve the speed of transferring files to nodes via SSH

### ISSUE THREAD

**Issue by gionn** [test-kitchen/test-kitchen#1696]
## :frowning_person: Problem Statement

Running `kitchen converge` with ssh transport takes a couple of minutes to copy files over ssh on my setup.

## :grey_question: Possible Solution

Make something like https://github.com/criteo/kitchen-transport-speedy the default implementation for the ssh transport (on my setup it takes 5 seconds for each converge).

## :arrow_heading_up: Describe alternatives you've considered

I continue to use the aforementioned project until it works, but it may broke in the future since the project looks unmaintained.
The solutions available in this external projects (there are many of them) are so clever and fast that I think should be integrated in the test-kitchen core.

There was a discussion about this topic in the past  #657

**Comment by matthewprenger** [comment]
+1, we run test-kitchen on EC2 and it takes forever to upload since each file is a separate operation out over the internet. Switching to kitchen-transport-speedy dropped our sync times from 10+ minutes to under 30s.

**Comment by damacus** [comment]
The Test Kitchen team is not planning any improvements at this time.

If Chef wishes to remove this provisioner in the future, please submit a patch.
