### ISSUE TITLE
Post Verification Hook Does Not Fire When Test Failures Occur

### ISSUE THREAD

**Issue by paulcalabro** [test-kitchen/test-kitchen#1703]
## :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

When one of my InSpec tests fail, the post verification hook will not execute.

## Version

4.24.8

## Environment

Running within a Docker container 

## Scenario

Trying to execute InSpec tests and using the post verification hook to upload data to Splunk and gather screenshots from Selenium.

## Steps to Reproduce

1. Create an InSpec test that will fail.
2. Create a post verification hook that does something simple, like creates a file.
3. Perform the test.
4. Notice that the hook does not fire.
5. Create an InSpec test that will pass.
6. Create a post verification hook that does something simple, like creates a file.
7. Perform the test.
8. Notice that the hook does fire.

## Expected Result

The post verification hook should fire.

## Actual Result

The post verification hook does not fire.

**Comment by tas50** [comment]
@paulcalabro I think this needs to get filed against the https://github.com/inspec/kitchen-inspec. I'd move it, but GitHub won't allow cross-org issue moving.
