### ISSUE TITLE
Remove the chef-apply provisioner

### ISSUE THREAD

**Issue by tas50** [test-kitchen/test-kitchen#1706]
## :frowning_person: Problem Statement

chef-apply is not a command in the Chef Infra kit that we'd like to continue. It is more than likely that this will be removed entirely and this little-used Test Kitchen provisioner should be removed to start that process off. 

## :grey_question: Possible Solution

- Add a deprecation warning now
- Remove it at some point in the future

**Comment by kagarmoe** [comment]
Related Docs:

**Workstation**:
ctl_chef_apply.md

**Chef Docs**:
glossary.md

**Shortcodes**:
knife_common_windwquotes_module.md
knife_common_windows_quotes_module.md

**Comment by damacus** [comment]
The Test Kitchen team are not planning any improvements for now.

If Chef wishes to remove this provisioner in the future, please submit a patch.
