### ISSUE TITLE
Remove chef-solo provisioner

### ISSUE THREAD

**Issue by tas50** [test-kitchen/test-kitchen#1707]
## :frowning_person: Problem Statement

Chef-solo legacy mode (non-chef-zero operation) is slated for removal in a future release of Chef Infra Client. We should start the process of removing this provisioner here in favor of chef-zero

## :grey_question: Possible Solution

- Add deprecation warning
- Remove the plugin at a yet to be determined time in the future

**Comment by kagarmoe** [comment]
List of `chef-solo` Related Docs: 

**Workstation**:
config_yml_kitchen.md
kitchen.md
chef_shell.md
chef_vault.md
chefspec.md
foodcritic.md

**Automate**:
data_collection.md
cfgmgmt.swagger.json

**Chef Infra Docs:**
chef_solo.md
config_rb_solo.md
ctl_chef_solo.md
ctl_automate_server.md
config_rb_client.md
data_bags.md
data_collection_without_server.md
debug.md
environments.md
handlers.md
recipes.md
roles.md
secrets.md
terraform.md

**Data files:**
chef_handler.yaml
template.yaml

**Shortcodes:**
chef_shell_config.md
chef_shell_example_hello_world.md
chef_shell_modes.md
chef_solo_environments.md
chef_solo_summary.md
config_rb_client_dot_d_directories.md
data_bag_chef_solo.md
handler_custom_example_error_report.md
handler_custom_example_json_file.md
test_kitchen_yml_syntax.md

**Comment by tas50** [comment]
I think for now we're just going to let this one fly
