### ISSUE TITLE
If we get an issue like SSH failed to connection while using kitchen create try to change the create a new workbook by removing the old  

### ISSUE THREAD

**Issue by mallikarjunagutta** [test-kitchen/test-kitchen#1720]
If we get an issue like SSH failed to connection while using kitchen create try to change the create a new workbook by removing the old  .

My work around is i ahve taken a new cookbook with same name and removed the old one worked fine

**Comment by marcparadise** [comment]
@mallikarjunagutta it's not clear what the described issue is.  Could you provide your kitchen.yml, kitchen log, and the output of your `kitchen create`command?
