### ISSUE TITLE
Test Kitchen Mac OS support

### ISSUE THREAD

**Issue by tdigangi** [test-kitchen/test-kitchen#1751]
## Brief Description
Test Kitchen  `local` backend does not support Big Sur Mac OS version 11.2.1

## Version
Test Kitchen version 2.11.2

## Environment
ruby '2.6.3'
kitchen-terraform 4.3
test-kitchen 2.11.2
mac os 11.2.1

## Steps to Reproduce

example:
`cd /path/of/.kitchen.yml`
`kitchen create`
`kitchen converge`
`kitchen verify` -> issue occurs when running controls

## Expected Result
local backend integration tests to run and report success/failure

## Actual Result

```
Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 1 successful, 0 failures, 0 skipped
$$$$$$ Finished verifying the 'inspec-gcp' system.
$$$$$$ Verifying the 'local' system...
Skipping profile: 'submodule_vpc_serverless_connector_beta' on unsupported platform: 'mac_os_x/20.3.0'.

Test Summary: 0 successful, 0 failures, 0 skipped
$$$$$$ Finished verifying the 'local' system.
$$$$$$ Finished verifying the systems.
       Finished verifying <submodule-vpc-serverless-connector-beta-local> (0m11.24s).
-----> Test Kitchen is finished. (0m12.68s)
```

**Comment by marcparadise** [comment]
The version number is reporting oddly there too (mac_osx/20.3.0), this is something we should look into further
