### ISSUE TITLE
Missing v3.0.0 tag in source code

### ISSUE THREAD

**Issue by glennsarti** [test-kitchen/test-kitchen#1789]
We can see that v3.0.0 of the Test-Kitchen gem has been release on rubygems, but there's no matching tag in this repository.  Is this a new release mechanism that is not documented or a bug in the 3.0.0 release process?

**Comment by glennsarti** [comment]
Also the link in the Changelog goes to 404 page

https://github.com/test-kitchen/test-kitchen/blob/master/CHANGELOG.md#300-2021-07-02

**Comment by damacus** [comment]
👍🏼 Thanks I've fixed that.
