### ISSUE TITLE
rsync support for syncing cookbook data

### ISSUE THREAD

**Issue by deeptshukla** [test-kitchen/test-kitchen#1802]
scp takes a lot of time with a big code base.
Kitchen converge takes more than 20 minutes as it copies everything everytime

**Comment by vkarve-chef** [comment]
@deeptshukla could you please share the logs here? typically, copying cookbooks shouldn't take as long.

**Comment by RomanKisilenko** [comment]
Could you revisit this issue. It is a well-known issue with kitchen since long time ago. In earlier versions of kitchen it was possible to use a third-party rsync transport to solve the issue and it is not available for latest versions anymore.
