### ISSUE TITLE
Add security headers to kitchen.ci page

### ISSUE THREAD

**Issue by tas50** [test-kitchen/test-kitchen#1810]
We can and should set additional security headers in the kitchen.ci page. This is controlled via the Hugo config at https://github.com/test-kitchen/test-kitchen/blob/master/docs/config.toml

Headers missing:

- [ ] Content-Security-Policy
- [x] X-Frame-Options
- [x] X-Content-Type-Options
- [x] Referrer-Policy
- [x] Permissions-Policy
- [x] Strict transport security

See https://securityheaders.com/?q=kitchen.ci&hide=on&followRedirects=on for more details

**Comment by tas50** [comment]
FYI: Some of these have been added, but not all.

**Comment by damacus** [comment]
Updated the list with the current status. Looks like we're just missing Content Security Policy

**Comment by sanjain-progress** [comment]
can we close this issue? PR for this fix is merged

**Comment by tas50** [comment]
All done now
