### ISSUE TITLE
Is this the right way to use test-kitchen with podman?

### ISSUE THREAD

**Issue by flman** [test-kitchen/test-kitchen#1856]
## Description

Although Podman is once mentioned in the documentation, using it with test-kitchen instead of Docker is not so straight forward. Could you please suggest some steps for this use case?

I've tried this:
$sudo systemctl start io.podman.socket
$sudo systemctl status io.podman.socket
● io.podman.socket - Podman Remote API Socket
   Loaded: loaded (/usr/lib/systemd/system/io.podman.socket; disabled; vendor preset: disabled)
   Active: active (listening) since Wed 2022-02-02 08:55:36 UTC; 25min ago
     Docs: man:podman-varlink(1)
   Listen: /run/podman/io.podman (Stream)
$sudo DOCKER_HOST=unix:///run/podman/io.podman kitchen test

I'm getting errors of this sort:
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker/connection.rb:91:in `rescue in request': read timeout reached (Docker::Error::TimeoutError)

I'm using dokken in the kitchen yml.

## Kitchen Version

Tell us which version of Test Kitchen you are using (`kitchen --version`).

```ruby
Test Kitchen version 3.2.2
```

## Chef Workstation Version

If you are running Test Kitchen via Chef Workstation, `chef --version` will provide additional relevent version details.

```ruby
Chef Workstation version: 22.1.745
Chef Infra Client version: 17.9.26
Chef InSpec version: 4.52.9
Chef CLI version: 5.5.0
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.26.1
```

## Ruby Version

If you are not using Test Kitchen via Chef Workstation, please provide the output of ruby --version.

```ruby
# Copy-paste your results here
```

## Platform Version

Tell us which operating system distribution and version Test Kitchen is running on.
Red Hat Enterprise Linux Server release 7.9 (Maipo)
## Replication Case

Tell us what steps to take to replicate your problem. See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/minimal-reproducible-example)
for information on how to create a good replication case.

Podman is installed:
$ sudo podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64

Docker is not installed:
$ sudo docker version
sudo: docker: command not found

$sudo systemctl start io.podman.socket
$sudo DOCKER_HOST=unix:///run/podman/io.podman kitchen test

## Kitchen Output

The relevant output of the Test Kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here. If the full output would be useful, link to it in a gist.

```ruby
$ sudo DOCKER_HOST=unix:///run/podman/io.podman kitchen test
-----> Starting Test Kitchen (v3.2.2)
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker/connection.rb:91:in `rescue in request': read timeout reached (Docker::Error::TimeoutError)
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/docker/connection.rb:44:in `request'
...
	from /bin/kitchen:380:in `load'
	from /bin/kitchen:380:in `<main>'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/excon-0.89.0/lib/excon/socket.rb:286:in `select_with_timeout': read timeout reached (Excon::Error::Timeout)
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/excon-0.89.0/lib/excon/socket.rb:196:in `rescue in read_nonblock'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/excon-0.89.0/lib/excon/socket.rb:177:in `read_nonblock'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/excon-0.89.0/lib/excon/socket.rb:65:in `readline'
...
	from /bin/kitchen:380:in `load'
	from /bin/kitchen:380:in `<main>'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/socket.rb:452:in `__read_nonblock': Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
...
```
The entire output is here:
https://gist.github.com/flman/f5777c2862e0f1684d0eb45dc966bde3.js

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed). This can be helpful in troubleshooting, so please include it in a gist.
https://gist.github.com/flman/6ba0f5de701d7135ef54475ca81c34d4.js
## NOTE

This repository is for core issues with the Test Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by vnaipaul** [comment]
@flman have you since retried with a newer version of podman ?  The Podman Compatibility API that docker-api would expose was only [introduced in podman v2.0.0](https://podman.io/blogs/2020/07/01/rest-versioning.html) apparently.
