### ISSUE TITLE
Getting uninitialized constant Dry::Container::DidYouMean

### ISSUE THREAD

**Issue by ssurendra549** [test-kitchen/test-kitchen#1906]
I, [2022-07-25T10:22:02.446335 #2076]  INFO -- Kitchen: -----> Starting Test Kitchen (v3.2.2)
E, [2022-07-25T10:22:02.640648 #2076] ERROR -- Kitchen: ------Exception-------
E, [2022-07-25T10:22:02.640701 #2076] ERROR -- Kitchen: Class: Kitchen::ClientError
E, [2022-07-25T10:22:02.640719 #2076] ERROR -- Kitchen: Message: Could not load the 'terraform' driver. Error: uninitialized constant Dry::Container::DidYouMean
E, [2022-07-25T10:22:02.640733 #2076] ERROR -- Kitchen: ----------------------
E, [2022-07-25T10:22:02.640747 #2076] ERROR -- Kitchen: ------Backtrace-------
E, [2022-07-25T10:22:02.640757 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/plugin.rb:45:in `rescue in load'
E, [2022-07-25T10:22:02.640770 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/plugin.rb:33:in `load'
E, [2022-07-25T10:22:02.640780 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/driver.rb:37:in `for_plugin'
E, [2022-07-25T10:22:02.640789 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:235:in `new_driver'
E, [2022-07-25T10:22:02.640797 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:250:in `new_instance'
E, [2022-07-25T10:22:02.640806 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:143:in `block in build_instances'
E, [2022-07-25T10:22:02.640815 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `map'
E, [2022-07-25T10:22:02.640829 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `with_index'
E, [2022-07-25T10:22:02.640844 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `build_instances'
E, [2022-07-25T10:22:02.640858 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:116:in `instances'
E, [2022-07-25T10:22:02.640872 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:109:in `filtered_instances'
E, [2022-07-25T10:22:02.640887 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:139:in `parse_subcommand'
E, [2022-07-25T10:22:02.640900 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/test.rb:39:in `block in call'
E, [2022-07-25T10:22:02.640913 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
E, [2022-07-25T10:22:02.640927 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/test.rb:37:in `call'
E, [2022-07-25T10:22:02.640940 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:52:in `perform'
E, [2022-07-25T10:22:02.640955 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:250:in `test'
E, [2022-07-25T10:22:02.640969 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
E, [2022-07-25T10:22:02.640982 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
E, [2022-07-25T10:22:02.640996 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
E, [2022-07-25T10:22:02.641010 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
E, [2022-07-25T10:22:02.641030 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `block in <top (required)>'
E, [2022-07-25T10:22:02.641043 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/errors.rb:183:in `with_friendly_errors'
E, [2022-07-25T10:22:02.641052 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `<top (required)>'
E, [2022-07-25T10:22:02.641060 #2076] ERROR -- Kitchen: /opt/chef-workstation/bin/kitchen:383:in `load'
E, [2022-07-25T10:22:02.641068 #2076] ERROR -- Kitchen: /opt/chef-workstation/bin/kitchen:383:in `<main>'
E, [2022-07-25T10:22:02.641076 #2076] ERROR -- Kitchen: ----End Backtrace-----
E, [2022-07-25T10:22:02.641084 #2076] ERROR -- Kitchen: ---Nested Exception---
E, [2022-07-25T10:22:02.641092 #2076] ERROR -- Kitchen: Class: NameError
E, [2022-07-25T10:22:02.641100 #2076] ERROR -- Kitchen: Message: uninitialized constant Dry::Container::DidYouMean
E, [2022-07-25T10:22:02.641109 #2076] ERROR -- Kitchen: ----------------------
E, [2022-07-25T10:22:02.641120 #2076] ERROR -- Kitchen: ------Backtrace-------
E, [2022-07-25T10:22:02.641129 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/plugin.rb:45:in `rescue in load'
E, [2022-07-25T10:22:02.641138 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/plugin.rb:33:in `load'
E, [2022-07-25T10:22:02.641150 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/driver.rb:37:in `for_plugin'
E, [2022-07-25T10:22:02.641159 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:235:in `new_driver'
E, [2022-07-25T10:22:02.641167 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:250:in `new_instance'
E, [2022-07-25T10:22:02.641176 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:143:in `block in build_instances'
E, [2022-07-25T10:22:02.641185 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `map'
E, [2022-07-25T10:22:02.641194 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `with_index'
E, [2022-07-25T10:22:02.641207 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:142:in `build_instances'
E, [2022-07-25T10:22:02.641217 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/config.rb:116:in `instances'
E, [2022-07-25T10:22:02.641229 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:109:in `filtered_instances'
E, [2022-07-25T10:22:02.641237 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:139:in `parse_subcommand'
E, [2022-07-25T10:22:02.641245 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/test.rb:39:in `block in call'
E, [2022-07-25T10:22:02.641253 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
E, [2022-07-25T10:22:02.641261 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/test.rb:37:in `call'
E, [2022-07-25T10:22:02.641269 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:52:in `perform'
E, [2022-07-25T10:22:02.641291 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:250:in `test'
E, [2022-07-25T10:22:02.641303 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
E, [2022-07-25T10:22:02.641312 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
E, [2022-07-25T10:22:02.641324 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
E, [2022-07-25T10:22:02.641333 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
E, [2022-07-25T10:22:02.641343 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `block in <top (required)>'
E, [2022-07-25T10:22:02.641353 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/errors.rb:183:in `with_friendly_errors'
E, [2022-07-25T10:22:02.641361 #2076] ERROR -- Kitchen: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `<top (required)>'
E, [2022-07-25T10:22:02.641372 #2076] ERROR -- Kitchen: /opt/chef-workstation/bin/kitchen:383:in `load'
E, [2022-07-25T10:22:02.641381 #2076] ERROR -- Kitchen: /opt/chef-workstation/bin/kitchen:383:in `<main>'
E, [2022-07-25T10:22:02.641393 #2076] ERROR -- Kitchen: ----End Backtrace-----

**Comment by vkarve-chef** [comment]
@ssurendra549 could you please describe the command you are executing? also, would you like to try out with a more recent version of test-kitchen included in latest [Chef Workstation](https://www.chef.io/downloads/tools/workstation)?
  it will help to see the `kitchen.yml` file for further analysis of the issue.
