### ISSUE TITLE
MacOS Ventura: SSH authentication failure

### ISSUE THREAD

**Issue by jweyer8** [test-kitchen/test-kitchen#1909]
## :ghost: Brief Description

I'm working on testing our cookbooks on macOS Ventura betas. Kitchen is failing to authenticate to the Ventura VM via public key. This quite possibly could be an issue with Net::SSH.

## Version

Chef Workstation version: 22.6.973
Chef Infra Client version: 17.10.0
Chef InSpec version: 4.56.20
Chef CLI version: 5.6.1
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.32.1

#### Local Machine

ProductName:    macOS
ProductVersion: 12.5
BuildVersion:   21G72

#### Vagrant box image

ProductName:    macOS
ProductVersion: 123.0
BuildVersion:   22A5321d

## Scenario

run `kitchen converge`

## Steps to Reproduce
run `kitchen converge` on macOS Ventura platform

## Actual Result

Failure to authenticate to the VM
```
default: Warning: Authentication failure. Retrying...
default: Warning: Authentication failure. Retrying...
default: Warning: Authentication failure. Retrying...
default: Warning: Authentication failure. Retrying...
```

#### Vagrant file contents
```
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "microsoft/macos-ventura"
  c.vm.box_version = "13.0-22A5321d"
  c.vm.hostname = "default-ventura.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :parallels do |p|
    p.customize ["set", :id, "--hypervisor-type", "apple"]
  end
end
```

#### `vagrant ssh-config` output
```
HostName 11.111.11.111 
User vagrant
Port 22
UserKnownHostsFile /dev/null
StrictHostKeyChecking no
PasswordAuthentication no
IdentityFile /Users/jweyer/.vagrant.d/insecure_private_key
IdentitiesOnly yes
LogLevel FATAL
```

`vagrant ssh` is successful ✅

**Comment by tas50** [comment]
Ventura disabled SHA-1 keys which Vagrant uses. This one is much bigger than just Test Kitchen and is something the larger community will need to work through

**Comment by jweyer8** [comment]
Thanks for the quick response @tas50, I guess I'm out of the loop.
