### ISSUE TITLE
ssh_key or password? - try both

### ISSUE THREAD

**Issue by nadtoka** [test-kitchen/test-kitchen#1936]
Hello everyone,

I have a request for fallback transport protocol. The case is that in some cases I need to ssh login using password and in some using ssh_key. 

I am using several suites and initial kitchen converge is using password, then it is being changed and key should be used. All is automated. When both (password and ssh_key) set then pass is used by default. But it would be great to switch to key auth then during same pipeline if password returned SSH Failed login error.  In different circumstances I have or password allowed or ssh_key only and there is no way to add condition in transport layer. 

transport:
  name: ssh
  username: "<%= ENV['SSH_USER'] %>"
  password: "<%= ENV['SSH_PWD'] %>"
  ssh_key:  "<%= ENV['SSH_KEY_PATH'] %>"
  port:     "<%= ENV['SSH_PORT'] %>"

**Comment by damacus** [comment]
We're not planning any improvements for now.

Please feel free to submit a patch to get this implemented.
