### ISSUE TITLE
Parameter connection_retry_sleep no respected - transport SSH delay hard-coded to 3 seconds

### ISSUE THREAD

**Issue by plaformsre** [test-kitchen/test-kitchen#1938]
## :ghost: Brief Description

Impact: No workaround available

We tried setting the `connection_retry_sleep` parameters as per documentation [1], however we can see that the `delay` within the Ruby source code is hardcoded to a value `3` [2]. 

Could you please revisit this and rectify to make the parameter configurable?

As of now, we have no way to delay the SSH transport and our user gets locked out as we have internal logic that requires many minutes to complete.

I can see that `connection_retry_sleep` is set to `120` in my `kitchen diagnose` output. But the code itself ignores the value

_ 

[1] https://docs.chef.io/workstation/config_yml_kitchen/#transport-settings

[2] https://github.com/test-kitchen/test-kitchen/blob/main/lib/kitchen/transport/ssh.rb#L225

## Version

Kitchen test 2.8.0

## Environment

Ubuntu 22.04 LTS

## Scenario

Delay SSH transport service after the AWS EC2 instance is provisioned.

## Steps to Reproduce

Set `connection_retry_sleep` to a value other than `3` and try a test with Kitchen EC2 provider and you can see that it takes the default 3 seconds retry interval.

## Expected Result

Delay set by `connection_retry_sleep` should be respected.

## Actual Result

The SSH delay is still showing 3 seconds.

## :heavy_plus_sign: Additional context

No workaround available after EC2 instance is provisioned to delay the testing through the SSH transport. We need at least 10 minutes delay.

**Comment by damacus** [comment]
This sounds like something that should be configurable. IT should probably default to 3 and then pull a value from whatever you've set in the EC2 driver. 

Happy to geta patch on this one and talk you through making any changes you need 👍🏼

**Comment by damacus** [comment]
The Test Kitchen team is not planning any improvements at this time.
