### ISSUE TITLE
Problem with no_proxy env variable and remote docker commands when testing with Vagrant and kitchen

### ISSUE THREAD

**Issue by rakopoul** [test-kitchen/test-kitchen#1970]
## :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

I am not sure what extra info i should give, if so please leave a comment and i will try to provide additional info.

I am testing with kitchen on Vagrant.
My Vagrant Box is behind http_proxy to access the internet. 
I am using almalinux 8 as vagrant box.
First part of the recipe installs some packets with dnf install. To do so i am setting http_proxy env variable in client.rb in kitchen.yml as following:

  client_rb:
    environment: kitchen
    chef_license: accept
    HTTP_PROXY: <%= ENV['kitchen_proxy'] || '' %>
    HTTPS_PROXY: <%= ENV['kitchen_proxy'] || '' %>
    http_proxy: <%= ENV['kitchen_proxy'] || '' %>
    https_proxy: <%= ENV['kitchen_proxy'] || '' %>

This works fine.
Later in the recipe i am trying to give remote docker commands like the following:

docker -H tcp://<ip>:2376 node inspect <node_name>

This goes through proxy (normal) and times out.
I tried to set no_proxy in the same way in kitchen.yml as following:
    no_proxy: <%= ENV['kitchen_no_proxy'] || '' %>
    NO_PROXY: <%= ENV['kitchen_no_proxy'] || '' %>
  
Though if i also have http_proxy settings in kitchen.yml command still goes through proxy and fails.
If i login into the vagrant box and try through shell commands, commands are succesful:

[root@leader ~]# export no_proxy=<ip>
[root@leader ~]# docker -H tcp://<ip>:2376 node inspect leader.cloud.com --format '{{ json .Spec.Labels }}'
**{} --> succesful if i have http_proxy and no_proxy set in env.**
[root@leader ~]# unset no_proxy
[root@leader ~]# docker -H tcp://<ip>:2376 node inspect leader.cloud.com --format '{{ json .Spec.Labels }}'
Timeout..

It seems somehow chef-client does not respect no_proxy if set in client.rb.
I checked /tmp/kitchen/client.rb and my settings are passed correctly there.

## Version

Test Kitchen version 2.8.0

## Environment

Vagrant Box: almalinux-8

## Scenario

Use no_proxy env variable in remote docker commands (docker -H) through kitchen converge run.

## Steps to Reproduce
Set http_proxy and no_proxy in client.rb in kitchen.yml
shell command "docker -H tcp://<ip>:2376" when run in chef-client run does not respect no_proxy

## Expected Result

Since my remote ip is in the no_proxy in client.rb i would expect to not use proxy.

## Actual Result

docker -H command uses proxy.
This happens only when chef uses it not from cmd line.

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by damacus** [comment]
The Test Kitchen team is not planning any improvements at this time.

Feel free to reopen when submitting a patch.
