### ISSUE TITLE
Pull suite data bags/roles/nodes from git repository/ies

### ISSUE THREAD

**Issue by lamont-granquist** [test-kitchen/test-kitchen#236]
I find myself copying around the same data bag content and same .kitchen.yml config across all my higher level role cookbooks and across all the suites in the .kitchen.yml file.

It should be possible to specify a single line in the .kitchen.yml to pull those artifacts from a git repo and apply them to all suites.

Ideally this should take an array of git repos and effectively merge all the artifacts from all of them.

**Comment by tas50** [comment]
I'm going to close this one out at in general we consider roles / environments to be a legacy pattern. It's not something we'll be developing further within Test Kitchen.
