### ISSUE TITLE
Add default value for encrypted_data_bag_secret_key_path

### ISSUE THREAD

**Issue by e0da** [test-kitchen/test-kitchen#248]
Similar to the way that the `data_bags_path` attribute is automatically resolved, it would be great to define a standard location for `encrypted_data_bag_secret_key_path`.

**Comment by rmoriz** [comment]
Just for reference if someone is coming to this page using search:

the default filename is `encrypted_data_bag_secret_key` not `encrypted_data_bag_secret` - which might be an inconsistency  (other chef tools/namings use/want `encrypted_data_bag_secret` by default)

see also https://github.com/test-kitchen/kitchen-ec2/issues/24 and the chef source
