### ISSUE TITLE
I would like to execute some tasks before chef-client run at `kitchen converge`.

### ISSUE THREAD

**Issue by sawanoboly** [test-kitchen/test-kitchen#251]
Is there a way this?

For Example:

```
1. kitchen create
2. add some file to platfrom
3. kitchen converge
```

**Comment by mrmarbury** [comment]
Sorry for commenting on closed issues but we are currently facing a problem that would make "hooks" an interesting feature for test-kitchen.

The company we are currently automating stuff for is relying on RHEL. With RHEL you have to register a system first, before you can use their repos. But you also have to unregister the system, before you delete it. For testing with kitchen that means that you have to do a `kitchen login` and then a manual unregister before you can do a `kitchen destroy`. A hook would for example enable us to configure the unregister command in `.kitchen.yml` and have it automagically be executed within the destroy run

Cheers,
Stefan

**Comment by carlosaya** [comment]
THIS!  Did you ever find a solution?  It's easy enough to run a cookbook to register, but we need to unregister as well.

**Comment by cheeseplus** [comment]
Currently fixture cookbooks that only execute are the best way to work around this and you can see the myqsql cookbook as one of many that use fixtures recipes/cookbooks. We also already have one, if not several, issues that fall under Lifecycle Stages which is already something that has been desired for quite some time.

**Comment by svmastersamurai** [comment]
An alternative I've explored is creating vagrant provisioning scripts and adding them into a custom `vagrantfile`. Not very ideal unfortunately :( It works *some* of the time, while others I get post provisioning errors that look to be more of vagrant's fault than test kitchen. Fixture cookbooks seem to be the way to go! I'll explore that once I get a chance to port over.
