### ISSUE TITLE
Document the newly introduced need to specify 'sudo: true'

### ISSUE THREAD

**Issue by eklein** [test-kitchen/test-kitchen#269]
This broke for me the first time I tried to run test-kitchen and only figured it out because I've been watching the commits.

I can submit a pull request, but I'm not sure if you're planning on doing a larger refactor of the readme.

**Comment by gsaslis** [comment]
thanks for this guys.. was having a very similar issue and even though the correct solution was [this one](https://github.com/test-kitchen/busser-serverspec/issues/20#issuecomment-119337660), setting sudo: false also helped to verify the issue...
