### ISSUE TITLE
Exception Handler does not always print out anything to stdout

### ISSUE THREAD

**Issue by damm** [test-kitchen/test-kitchen#281]
Perhaps i'm spoiled by Chef; but I really like being able to see the exception traces easily on the screen.

Started a new chef-repo and forgot about kitchen list -l debug and ended up tailing .kitchen/logs/kitchen.log because no meaningful information was emitted on the screen.  Now in hindsight I could use -l debug but I dismissed this notion.

```
Erebus :: scottmlikens/chef-repo » kitchen list -L debug
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Error parsing /Users/slikens/git/scottmlikens/chef-repo/.kitchen.yml
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
```

I can't say what the solution is; I can just tell *that* error message is not what I expect as a Chef user.

**Comment by smurawski** [comment]
Thanks for the feedback.
