### ISSUE TITLE
Use of sudo -E breaks compatibility with CentOS 5

### ISSUE THREAD

**Issue by nathwill** [test-kitchen/test-kitchen#307]
the version of sudo in CentOS 5 does not support the -E (preserve environment) flag, so omnibus installation fails.

ref: https://gist.github.com/nathwill/8137556

**Comment by fnichol** [comment]
Looking back at this one, I'm wondering if CentOS 5 is still a burning/relevant platform? I'm hoping no, but one never knows for sure…

**Comment by lamont-granquist** [comment]
It looks like its still a problem on ubuntu and anything else that does env_reset in sudoers will have the same problem, and at its root i think you need all the rigamarole that `su -` gets you for a login shell.

**Comment by jtimberman** [comment]
CentOS 5 will be supported long after we all retire :smile_cat:. Not really but it's not going anywhere anytime soon IMHO. As long as it's supported for Chef and other similar projects it should be supported by test kitchen.

**Comment by spheromak** [comment]
I know of cent4 still in the wild at some shops. Expect 5 to be around for a while.

**Comment by nathwill** [comment]
:clap:

**Comment by fnichol** [comment]
![675](https://cloud.githubusercontent.com/assets/261548/6853626/f247828c-d3b1-11e4-815e-b165a2e7d6ff.gif)
