### ISSUE TITLE
Kitchen doesn't cache chef packages during vm provision

### ISSUE THREAD

**Issue by sneak** [test-kitchen/test-kitchen#315]
Far and away the highest time spent running my tests is my fresh instances downloading the chef omnibus installer and then redownloading the chef package from Opscode.

It's done over https so I've found no easy way of caching this on my workstation to speed up subsequent test runs.

This is >80% of the wallclock time spent running my tests - can the chef provisioner be updated to perhaps cache the download on the host and copy it to the vm with the rest of the recipes and whatnot?

Apologies if I'm filing this bug in the wrong place or have some mistaken assumptions.

**Comment by tknerr** [comment]
@sneak @damm I'm currently using test-kitchen with the vagrant driver and vagrant cachier. It's a nice combo that even works with docker (via `VAGRANT_DEFAULT_PROVIDER=docker`).

* for caching the omnibus installer use the `-d` flag: https://github.com/tknerr/sample-toplevel-cookbook/blob/master/.kitchen.yml#L17
* for additionally caching bussers, add
   * this to your `~/.vagrant.d/Vagrantfile`: https://github.com/tknerr/bills-kitchen/blob/master/files/home/.vagrant.d/Vagrantfile#L9-L27
   * this to your `~/.kitchen/config.yml`: https://github.com/tknerr/bills-kitchen/blob/master/files/home/.kitchen/config.yml#L2-L5
* everything else that vagrant-cachier is caching will be cached too, e.g. apt packages, ruby gems, etc...
