### ISSUE TITLE
$HOME not set correctly during verify

### ISSUE THREAD

**Issue by coderanger** [test-kitchen/test-kitchen#321]
The verify phase and all busser stuff is run as root, but $HOME isn't reset so it still points at the home of the SSH user.

A workaround for serverspec is to add `ENV['HOME'] = Etc.getpwuid(Process.uid).dir` to your specs.

**Comment by cheeseplus** [comment]
Is this fixed by the above commit?

**Comment by cheeseplus** [comment]
This should have been resolved by the above referenced commits as we dropped sudo -E.
