### ISSUE TITLE
Add lifecycle hooks to various phases (including provisioners)

### ISSUE THREAD

**Issue by sethvargo** [test-kitchen/test-kitchen#329]
Example #257 

@fnichol is going to tack on some more information/whiteboard picture :smile:.

**Comment by CpuID** [comment]
*bump* any further updates to this one?

**Comment by lamont-granquist** [comment]
@fnichol @tyler-ball buuuuuump

**Comment by PurrBiscuit** [comment]
+1 for multi-provisioning

**Comment by lxhunter** [comment]
bump

**Comment by sochoa** [comment]
bump

**Comment by sawanoboly** [comment]
+1

**Comment by francoiskha** [comment]
+1

**Comment by habelson** [comment]
+1

**Comment by z0mi3ie** [comment]
+1 this would be very useful

**Comment by willejs** [comment]
+1000

**Comment by Chili-Man** [comment]
any updates on this ?

**Comment by cheeseplus** [comment]
Related https://github.com/test-kitchen/test-kitchen/pull/564

**Comment by pburkholder** [comment]
+1 on behalf of a commercial user I work with. (Thanks, @cheeseplus, for tagging for future release)

**Comment by chetanddesai** [comment]
+1 for `post_create_command` - anyone know of a work around to hack this until the `post_create_command` is available?  Trying to execute a command after vagrant is up, but before Chef starts.

**Comment by mwrock** [comment]
A hack would be to call `kitchen exec <command>` after `kitchen create` and before `kitchen converge`

**Comment by pietervogelaar** [comment]
+1 I would really like this!

**Comment by swimfrog** [comment]
+1

**Comment by darwin67** [comment]
+1

**Comment by netflash** [comment]
+1

**Comment by RamblingCookieMonster** [comment]
+1, for an implementation that would allow a run-multiple-provisioners-in-sequence scenario.

Cheers!

**Comment by anvarich** [comment]
+1

**Comment by gurumaia** [comment]
+1

**Comment by burythehammer** [comment]
+1, would love to run both a Terraform and Ansible provisioner in sequence. Found a workaround (trigger ansible within terraform), but it doesn't feel like the right way to do it at all.

**Comment by azazi-sa** [comment]
+1

**Comment by sputmayer** [comment]
+1

**Comment by rylarson** [comment]
+1

**Comment by jestallin** [comment]
+1

**Comment by DI-DaveGoodine** [comment]
+1

**Comment by seanguo** [comment]
+1

**Comment by thommay** [comment]
I've locked this since the stream of +1s are not adding anything; we understand that people would like this feature but right now it is not planned or specced. If someone wants to take a crack at designing and implementing it we'd be very happy to help and mentor them!

**Comment by cheeseplus** [comment]
Fixed by #1428
