### ISSUE TITLE
No way to disable colors

### ISSUE THREAD

**Issue by coderanger** [test-kitchen/test-kitchen#330]
For things like jenkins and travis, it would be nice to disable color. This could also be done as a default, to only output color if stdout (or whatever is passed in as the logdev) is a TTY.

**Comment by jujugrrr** [comment]
Hi,
Now that we have #481 . Is there a way to force to enable color even without tty ?
By example Jenkins with [ANSI plugin](https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin) can display colors.

 Thank you

**Comment by petere** [comment]
Yeah that would be nice.

**Comment by jujugrrr** [comment]
> Is there a way to force to enable color even without tty ?

do you think we could add a cli option?

**Comment by stormerider** [comment]
Yeah, having this be able to be specified explicitly would be helpful to me as well. I'm using Bamboo as my CI tool to run this and it's still sending the color codes, so it must have a TTY the way the Bamboo agent executes the job... perhaps Bamboo operates differently than Jenkins in that regard.

**Comment by gh2k** [comment]
@stormerider Just found this via a google search. I resorted to running `kitchen test all | cat`, which triggers the lack-of-tty detection. It's not pretty (--no-color would be much more preferable) but it works.

**Comment by jujugrrr** [comment]
> @stormerider Just found this via a google search. I resorted to running kitchen test all | cat, which triggers the lack-of-tty detection. It's not pretty (--no-color would be much more preferable) but it works.

Thanks for the workaround :+1:
