### ISSUE TITLE
Unable to set a chef environment for a node

### ISSUE THREAD

**Issue by jonathanq** [test-kitchen/test-kitchen#340]
There appears to be a race condition with test-kitchen (1.1.1) and chef_zero provider with environments.

I have the following in my kitchen.yml file:

```

---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: '/path/to/data_bags'
  roles_path: '/path/to/roles'
  environments_path: '/path/to/environments'

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[my-cookbook::default]
    attributes:
      vagrant:
    provisioner:
      client_rb:
        environment: Development
```

When I run this, it attempts to expand the nodes runlist and fetches the environment from the server.  However the environments (and cookbooks) have not yet been uploaded to the server.

```
Starting Chef Client, version 11.8.2
[2014-01-29T19:33:32+00:00] INFO: *** Chef 11.8.2 ***
[2014-01-29T19:33:32+00:00] INFO: Chef-client pid: 2406
Creating a new client identity for default-centos-65 using the validator key.
[2014-01-29T19:33:32+00:00] INFO: Client key /tmp/kitchen/client.pem is not present - registering
[2014-01-29T19:33:32+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: http://127.0.0.1:8889/nodes/default-centos-65
 [2014-01-29T19:33:32+00:00] INFO: Setting the run_list to ["recipe[my-cookbook::default]"] from JSON
[2014-01-29T19:33:32+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: http://127.0.0.1:8889/environments/Development

       ================================================================================
       Error expanding the run_list:
       ================================================================================


Unexpected API Request Failure:
-------------------------------
Object not found: http://127.0.0.1:8889/environments/Development


[2014-01-29T19:33:32+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated
[2014-01-29T19:33:32+00:00] ERROR: 404 "Not Found"
```

Am I defining my kitchen.yml file wrong?  Or is this an issue with chef-client's local mode and I need to open a ticket with Chef?  

I can log in to the node and confirm the environment files (and cookbooks, roles, databags) have all been copied to `/tmp/kitchen`.  Also if I remove the block: 

```
provisioner:
   client_rb:
      environment: Development
```

It starts running chef-client, but then fails early on because my recipe relies on the environment being set correctly.    I have also tried defining the environment file as both .rb and .json.

**Comment by srirammageswaran** [comment]
@howdoicomputer may be your environment file is not updated in chef-zero.

If you already have this environment in a chef-server better download it from the server. The below command worked for me. 

knife environment show qa -F json >> qa.json
