### ISSUE TITLE
Don't use generic descriptions for create, converge, setup, verify, and destroy

### ISSUE THREAD

**Issue by eherot** [test-kitchen/test-kitchen#344]
For example, it's actually pretty difficult to figure out (other than with trial and error) exactly what "kitchen verify" does, because the main Kitchen docs are not organized in a way that makes this easy to look up.  Thus, it would be super-useful, for example, if the help said something like:

"Re-runs unit tests on one or more instances"

rather than the generic:

"#{action.capitalize} one or more instances"

**Comment by cheeseplus** [comment]
Closed by https://github.com/test-kitchen/test-kitchen/pull/450
