### ISSUE TITLE
Add a way to execute arbitrary driver commands

### ISSUE THREAD

**Issue by Julian** [test-kitchen/test-kitchen#350]
Coming here from test-kitchen/kitchen-vagrant#69 –

It would be nice to be able to execute arbitrary commands on the underlying driver for cases where kitchen does not appropriately expose the underlying functionality. E.g. for vagrant kitchen vagrant does not currently expose nice ways to `halt`, `suspend`, `reload`, etc. and "hides" the VMs a bit which makes it non-obvious how to get to them.

Adding a `kitchen driver exec` command that just passed along what you asked could be one possible way to provide for this use case.

I am admittedly uninformed as to how other drivers than the vagrant one work, or the applicability of what I'm suggesting to them is with the proposed interface, but the concept seems extremely likely to be applicable.

**Comment by jmahowald** [comment]
So it's easy to imagine a general solution for the vagrant provider, as vagrant itself is a CLI tool.  Harder to imagine what driver exec <foo> <bar> would mean in the context of the fog drivers.  I'd feel comfortable with looking at the one for vagrant as mentioned, and could make it reasonable default behavior for the others, but would like input from @sethvargo on these details

**Comment by jmahowald** [comment]
One follow up point, is that while  I can't imagine kitchen driver exec for fog type drivers, the primitives of suspend/reload do make sense across the board

**Comment by jmahowald** [comment]
@fnichol care to comment, I've been having to do a lot of reloads recently on fat vms as you may know :) I can certainly do the trick of walking down to the vagrant directory and reload, and I had a wrapper to do it for me before I began cursing ruby gems and distribution, but I think halt/suspend/reload make more sense then execute arbitrary commands, as those make sense for virtually all of the drivers, whereas a driver-exec only makes sense in the context of vagrant as far as I can see

**Comment by fnichol** [comment]
@jmahowald We'll have to revisit this after the 1.4.0 release and see what we can do here and give this issue some time. Given the work for 1.4.0 with Drivers becoming slimmer (they only implement `#create(state)` and `#destroy(state)` and no longer own the `converge`, `setup`, `verify`, and `login` actions), we'll be in a better place to see what the use cases are outside of Vagrant commands, which seem to be the theme so far. Anyway, not punting on this, but shelving it for at least a few days :smile:

**Comment by jmahowald** [comment]
thanks.  From the sounds of it, what I was advocating works if there is a #suspend(state) and #reload/unsuspend(state) primitive as well.

**Comment by Sauraus** [comment]
Here is a more than nice to have use case for the ability to 'restart' a VM.

On OS X if you shutdown the Fusion Manager, it also suspends the VMs, and unfortunately you have to restart the Fusion Manager whenever you want to get a desktop to a new OS X VM. Which maybe needed for any number of reasons.

**Comment by ifeltsweet** [comment]
still nothing?

**Comment by coderanger** [comment]
I'm going to close this out. We should better document how to run arbitrary Vagrant commands in the readme for kitchen-vagrant and maybe in the new Kitchen docs site but there is no reasonable common interface where this makes sense for even a large subset of drivers.

**Comment by davidalpert** [comment]
@jtimberman @coderanger 

I took a spike at adding `kitchen suspend` and `kitchen resume` commands into the `instance` semantics, with a `supports_suspend?` method on the base driver that defaults to `false` to maintain backwards compatibility but enables individual drivers to opt-in as they get around to adding support.

I understand test-kitchen is not intended to expand to generic vm automation but felt that this pair of commands might be generic enough to make sense.

Reading through the comments on this and related issues, however, I'm not certain whether consensus landed on whether basic suspend/resume might fall in or out of scope.

If there is interest and it doesn't fall out of scope my spike is [available in my fork](https://github.com/test-kitchen/test-kitchen/compare/master...davidalpert:suspend?expand=1) for review and feedback.

**Comment by coderanger** [comment]
@davidalpert I am not interested in supporting that in Test Kitchen, it's not a verb(s) that makes sense in a testing-based view of the world. I can't speak for @cheeseplus though, so if you can convince him ... :)

**Comment by davidalpert** [comment]
k. I understand that, although it becomes useful when testing multiple node setups where that initial build and/or converge can take a long time.... then add some Windows box images to the mix... ;-)

**Comment by davidalpert** [comment]
to clarify further, my current scenario is that I have a pair of projects I'm contributing to, each of which has large VMs and my host sometimes struggles when they are up for an extended period of time, and I don't really want to try both of them up at the same time. one of them is a multi-node setup and the other one probably should be.

it becomes exceedingly useful to be able to "pause" (or suspend, if you will) and "resume" my testing cycle as I cycle in and out of supporting each of them.

I might submit that while pause/suspend and resume are not verbs which make sense in a testing-based view of the world for smaller projects, they certainly do make sense to me for larger projects with longer-running iteration and test cycles/processes.
