### ISSUE TITLE
Add Multi-provisioner support

### ISSUE THREAD

**Issue by schisamo** [test-kitchen/test-kitchen#36]
This feature would allow the community to implement support for provisioners other than Chef (ie chef-client, chef-solo).

Once the abstraction/plugin layer is in place it should be fairly easy to implement provisioners for:

* Generic Shell
* Puppet
* CFEngine

**Comment by fnichol** [comment]
Hey, look at that, we're supporting this now as of [1.2.0](https://github.com/test-kitchen/test-kitchen/releases/tag/v1.2.0)!

**Comment by ytsarev** [comment]
@fnichol sounds awesome, could you show exact PR implementing that ?

**Comment by ytsarev** [comment]
@fnichol sorry, i actually had https://github.com/test-kitchen/test-kitchen/issues/329 in mind...
