### ISSUE TITLE
kitchen login not working with plink

### ISSUE THREAD

**Issue by berniedurfee** [test-kitchen/test-kitchen#367]
So, I'm on Windows and it's common that plink is the ssh tool available. When I run 'kitchen login <server>' I get the following:

plink: unknown option "-o"

Because plink doesn't know what to do with "-o"

**Comment by TaylorMonacelli** [comment]
Sysinternals procmon helped me find 'kitchen login centos' was calling C:\Program Files (x86)\Gow\bin\ssh.bat.  Uninstalling Gow is my workaround.

**Comment by cheeseplus** [comment]
Given the lack of activity/age and non-ubiquity of plink (plus the workaround) I'm closing this one. If folks want to take up a PR in the future we'd happily review.
