### ISSUE TITLE
New option to change --parallel output to spool and not interleave

### ISSUE THREAD

**Issue by lamont-granquist** [test-kitchen/test-kitchen#372]
TK --parallel over travis is kind of terrible because of the interleaving.  It would be useful to be able to spool up all the output from a worker and then dump it all at once -- with locking or a single thread responsible for the output so that output interleaving did not happen at all.  Ideally have the output from the one(s) that failed come last and not be buried in the middle of it as well.

This probably shouldn't be the default behavior.  Since its travis, its difficult to get at the individual TK logs, so there's no good workaround.

**Comment by tas50** [comment]
If you want to code this one up @lamont-granquist we can merge it, but at this point, it's not going to be something we take on so I'm going to close this out.
