### ISSUE TITLE
Invoking Rake/Thor tasks with concurrency

### ISSUE THREAD

**Issue by dpetzel** [test-kitchen/test-kitchen#374]
Sorry if this a noob question, but I can't seem to get it to work...

Here is what I'm trying to do, but It doesn't seem to honor the concurrency settings:

```
class Default < Thor
  desc 'test_all', 'Run all tests on cookbook'
  def test_all
    invoke 'style:rubocop'
    invoke 'lint:foodcritic'
    invoke 'spec:rspec'
    invoke 'kitchen:c_l_i:test', 'all -c 8' # do no more than 8 at a time
  end
end
```

I reviewed https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/thor_tasks.rb, but its just not clicking for me. what is the righy way to pass arguments, so that I can tell test kitchen to use a concurrency value of 8 when invoking from my Thorfile?

**Comment by smurawski** [comment]
@dpetzel Sorry for the delayed response. Did you ever figure out a solution or is this no longer an issue?

**Comment by cheeseplus** [comment]
From reading the code it looks like we don't give a way to toggle this via rake task but we totally should. Considering this a new feature (maybe could be considered an improvement).

**Comment by edmachine** [comment]
I'd like to bump this issue as well. I am manually creating threads and joining them in the rakefile, but I'd rather use the concurrency built into test-kitchen.

**Comment by atheiman** [comment]
for anyone looking for a way to accomplish concurrency in a rake tasks (with a limit on the number of concurrent threads) I have implemented it here: https://github.com/zuazo/kitchen-in-travis/pull/5

```shell
$ bundle exec rake --rakefile Rakefile.concurrency --tasks
rake integration:docker[regexp,action,concurrency]   # Run integration tests with kitchen-docker
rake integration:vagrant[regexp,action,concurrency]  # Run integration tests with kitchen-vagrant
```
