### ISSUE TITLE
Long runs timeout

### ISSUE THREAD

**Issue by sethvargo** [test-kitchen/test-kitchen#380]
If Test Kitchen (and/or shellout) doesn't receive something in a certain about of time, it closes the connection. This very well may be vagrant, but I'm not sure.

Either way, we should persist the connection if output is being received. I personally experienced this while compiling a Ruby from source - TK just severed the connection to vagrant mid-build.

**Comment by dAnjou** [comment]
@lonniev It seems this has been fixed in >=11.14 https://github.com/test-kitchen/test-kitchen/issues/380#issuecomment-41359083

**Comment by cheeseplus** [comment]
This one is pretty old and not something we've seen in quite some time. Between vagrant, drivers, transport improvements all changing I'm closing this one but folks can always open a new issue (with lots of specific detail) should it present itself
