### ISSUE TITLE
Wrap mkdir in sudo() for init_command of chef_base provisioner?

### ISSUE THREAD

**Issue by hectcastro** [test-kitchen/test-kitchen#382]
In this method, `rm` is wrapped by `sudo()` but `mkdir` is not:

```ruby
def init_command
  dirs = %w{cookbooks data data_bags environments roles clients}.
    map { |dir| File.join(config[:root_path], dir) }.join(" ")
  "#{sudo('rm')} -rf #{dirs} ; mkdir -p #{config[:root_path]}"
end
```

(See also: https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_base.rb#L113)

Setting the `provisioner` `root_path` to something like `/var/cache/kitchen` fails because the directory cannot be created:

```
mkdir: cannot create directory ‘/var/cache/kitchen’: Permission denied
>>>>>> Converge failed on instance <default-fedora-19>.
>>>>>> Please see .kitchen/logs/default-fedora-19.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sudo -E rm -rf /var/cache/kitchen/cookbooks /var/cache/kitchen/data /var/cache/kitchen/data_bags /var/cache/kitchen/environments /var/cache/kitchen/roles /var/cache/kitchen/clients ; mkdir -p /var/cache/kitchen]
>>>>>> ----------------------
```

**Comment by smurawski** [comment]
@srenatus Sorry for the delayed respons, but is this still an issue for you?

**Comment by srenatus** [comment]
@smurawski: thanks, I'm fine with closing this. I'm not the reporter though :)

**Comment by srenatus** [comment]
Ping @hectcastro

**Comment by smurawski** [comment]
My bad.. @hectcastro is this still an issue for you?

**Comment by hectcastro** [comment]
Unfortunately, I have not used TK in while, but willing to close and reopen if I encounter it again.

**Comment by smurawski** [comment]
Thanks @hectcastro.  Please do re-open or file a new issue if you come across again.
