### ISSUE TITLE
Documentation for support for Encrypted Data Bags

### ISSUE THREAD

**Issue by mansona** [test-kitchen/test-kitchen#384]
I've been following this guide on how to use encrypted data bags with test-kitchen http://atomic-penguin.github.io/blog/2013/06/07/HOWTO-test-kitchen-and-encrypted-data-bags/ , and essentially it doesn't work. The line that breaks is this one

```
knife data bag show certificates test -Fj
```

and it just gives me this:

```
ERROR: Chef::EncryptedDataBagItem::DecryptionFailure: Error decrypting data bag value: 'bad decrypt'. Most likely the provided key is incorrect
```

I know that this isn't a test-kitchen issue but there is currently no documentation on how I should do this on the test-kitchen site. If we could figure out the correct way to get this to work I would love for this to be documented somewhere for other people to see. 

Any suggestion on what to try to resolve this would be much appreciated

**Comment by rhass-r7** [comment]
This feature appears to no longer work with Chef 12.x due to the option being deprecated from client configs in PR https://github.com/chef/chef/pull/1885

It now leverages the knife config, however I am not sure how this translates in the context of test-kitchen.
