### ISSUE TITLE
TestKitchen isn't using VAGRANT_HOME path

### ISSUE THREAD

**Issue by rich-murray** [test-kitchen/test-kitchen#398]
I'm running TestKitchen on a windows 7 pc and have kitchen.yml configured with a 'ubuntu-12.04' platform.  When running a kitchen converge I received the following error:
```
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not create the clone medium 'm:\VirtualBox VMs\packer-virtualbox\packer-virtualbox-disk1_2.vmdk'.
VBoxManage.exe: error: VMDK: cannot write allocated data block in 'm:\VirtualBox VMs\packer-virtualbox/packer-virtualbox-disk1_2.vmdk' (VERR_DISK
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Appliance, interface IAppliance
VBoxManage.exe: error: Context: "int __cdecl handleImportAppliance(struct HandlerArg *)" at line 779 of file VBoxManageAppliance.cpp
---- End output of vagrant up --no-provision --provider=virtualbox ----
Ran vagrant up --no-provision --provider=virtualbox returned 1]←[0m
```

The VM is being unpacked into my M drive (due to an environment variable HOMEDRIVE=M which is out of my control - a corporate standard).  My M drive is a network drive with very limited space so I don't want the VM's to be stored here.  

I hit the same issue when running Vagrant directly (without TestKitchen) but resolved the problem by setting a VAGRANT_HOME environment variable e.g.

VAGRANT_HOME=C:\Users\richardm\VagrantHome

However TestKitchen doesn't seem to be using the VAGRANT_HOME environment variable, is there a way I can set this in the kitchen.yml file or some other way?

**Comment by cheeseplus** [comment]
This is a kitchen-vagrant issue so I'm opening it there and referencing this for posterity.
