### ISSUE TITLE
Loading installed gem dependencies with busser plugins

### ISSUE THREAD

**Issue by patrick-wright** [test-kitchen/test-kitchen#406]
Summary:
Running busser tests (minitest, serverspec) is executing the provided ruby package included with chef-client, but gem paths reference /tmp/busser/...

I am trying to run a minitest by requiring a gem package that must be installed on the node.

I am having an issue figuring out how to get chef-client ruby, busser gem paths, and gem_package to work together. 

Here is a gist snippet from the kitchen log.  
https://gist.github.com/patrick-wright/10024301

**Comment by smurawski** [comment]
There are a couple of related questions in the Busser project itself:
* https://github.com/test-kitchen/busser/issues/9
* https://github.com/test-kitchen/busser/issues/18
* https://github.com/test-kitchen/busser/issues/27
