### ISSUE TITLE
Document includes/excludes kitchen.yml directives

### ISSUE THREAD

**Issue by eherot** [test-kitchen/test-kitchen#421]
The "excludes" directive is briefly discussed on this page: http://docs.opscode.com/config_yml_kitchen.html but is not mentioned at all (as far as I can tell) in the main Test Kitchen docs.  The "includes" directive isn't documented anywhere AFAIK.

Credit where credit's due @someara helped me find the right syntax and suggested I file this ticket.

**Comment by tas50** [comment]
Excludes is here: https://kitchen.ci/docs/getting-started/excluding-platforms/
