### ISSUE TITLE
Add Berksfile location config option

### ISSUE THREAD

**Issue by sonnysideup** [test-kitchen/test-kitchen#428]
The provisioner is hard-coded to read the Berksfile from the kitchen root (https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_base.rb#L290-L291). It would be nice to be able to use a different path in the `.kitchen.yml` file.

**Comment by chrisfarnham** [comment]
Without this feature we cannot use test-kitchen in our current environment

**Comment by mstyne** [comment]
:+1:

**Comment by gled-rs** [comment]
done here:
https://github.com/gled-rs/test-kitchen-ez/commit/514a43a483d227170a042c16f7b5d48f5b2e7e49

if you want a PR, just ask, the previous one on that subject was closed.

**Comment by cheeseplus** [comment]
I'd happily review/merge a PR for this!

**Comment by tas50** [comment]
This has already been shipped in with the berksfile_path config
