### ISSUE TITLE
Test Artifact Fetch Feature 

### ISSUE THREAD

**Issue by ehaselwanter** [test-kitchen/test-kitchen#434]
We started to use test-kitchen in a public open source security project. The goal is to provide chef and puppet automation to cover your bases.

In order to re-use integration tests it would be very helpful to be able to include integration tests from an specified artifact location.

- archive uri
- git uri

What do you think? Is there already a proposed solution I missed? kitchen should be aware I guess. Is there any hook we could use to trigger a pre verify action.

**Comment by smurawski** [comment]
@ehaselwanter Sorry for the delayed response on this issue.  Is this something you still want to accomplish or have you found other workarounds?

**Comment by ehaselwanter** [comment]
@smurawski well, you snapped up my former team mates @chris-rock @arlimus . So it is best to bring them in. As far as I know there is still the requirement to re-use tests throughout different kitchen projects.

Another thing comes to mind too were I do not know weather it is feasible or not: It would be really cool to add multiple testing libraries to one deployment. Like lets say you build an all-in-one machine with a web app + db in it. Then it would be super awesome to be able to reference https://github.com/hardening-io/tests-ssh-hardening https://github.com/hardening-io/tests-nginx-hardening https://github.com/hardening-io/tests-os-hardening und run them against the kitchen. 

but is never as easy as that ;-)

**Comment by chris-rock** [comment]
@ehaselwanter @smurawski We will implement such feature with kitchen-inspec. This allows you to load local tests and add additional remote `InSpec profiles`. 

@ehaselwanter This is funny, because the first real implementation was done by you :100:

**Comment by smurawski** [comment]
@ehanselwanter @chris-rock I think this definitely belongs in a verifier plugin (like the inspec one), and should be totally doable there, as you control building the sandbox for transfer to the system under test.

As this is more a concern of the individual verifier (each verifier is responsible for building its own sandbox to transfer), I'm going to close this out as an issue against test-kitchen.  If current verifiers (busser, inspec, pester) need this, please open an issue with them and we should be faster about responding (we've recently increased the pool of maintainers for test-kitchen).

**Comment by smurawski** [comment]
The mobile github app doesn't auto complete names, sorry for the mistype @ehaselwanter
