### ISSUE TITLE
Can test-kitchen work with mingw32 

### ISSUE THREAD

**Issue by rojomisin** [test-kitchen/test-kitchen#435]
I've been trying to get a local chef development working using git windows shell (mingw32).  I made my own .box using packer, and my latest hurdle is due to there being no 'sudo' in mingw32 or cygwin, the command for test-kitchen to deliver the cookbooks and run chef-solo fails.  

is test-kitchen meant to run on windows?  it seems like if it could detect the absence of sudo and not require sudo for running chef-solo it would work.

would the winrm method of talking to the box handle this better?

```
$ kitchen converge
-----> Starting Kitchen (v1.2.1)
←[36m-----> Converging <default-win2008r2sp1>...
←[0m←[36m       Preparing files for transfer
←[0m←[36m       Resolving cookbook dependencies with Berkshelf 3.1.1...
←[0mResolving cookbook dependencies...
Fetching 'nimsoft-windows' from source at .
Using nimsoft-windows (0.1.0) from source at .
Vendoring nimsoft-windows (0.1.0) to C:/Users/userdev1/AppData/Local/Temp/default-win2008r2sp1-sandbox-20140508-23104-1mgbu5e/cookbooks/nimsoft-windows
←[36m       Removing non-cookbook files before transfer
←[0m←[36m       Preparing environments
←[0m←[36m       /usr/bin/sudo: line 1: -E: command not found
←[0m←[36m       Transfering files to <default-win2008r2sp1>
←[0m←[36m       /usr/bin/sudo: line 1: -E: command not found
←[0m←[31m>>>>>> Converge failed on instance <default-win2008r2sp1>.←[0m
←[31m>>>>>> Please see .kitchen/logs/default-win2008r2sp1.log for more details←[0m
←[31m>>>>>> ------Exception-------←[0m
←[31m>>>>>> Class: Kitchen::ActionFailed←[0m
←[31m>>>>>> Message: SSH exited (127) for command: [sudo -E chef-solo --config /tmp/kitchen/solo.rb --json-attributes /tmp/kitchen/dna.json  --log_level info]←[0m
←[31m>>>>>> ----------------------←[0m
```

thanks!

**Comment by tyler-ball** [comment]
I'm going to close this because TK should fully support windows guests with the windows-guest-support branch now.  Let me know if you are still having issues!  

http://www.hurryupandwait.io/blog/help-test-the-future-of-windows-infrastructure-testing-on-test-kitchen has a full example of how to get running.
