### ISSUE TITLE
Create kitchen driver for Solaris/illumos Zones

### ISSUE THREAD

**Issue by schisamo** [test-kitchen/test-kitchen#44]

**Comment by schisamo** [comment]
This works is in progress by @scotthain.

**Comment by Atalanta** [comment]
Where is this?  Do you mean a driver that runs natively on Illumos derivatives?

**Comment by scotthain** [comment]
The driver will be open sourced early next month - it does not run natively on Illumos style, it remotely operates on a Solaris 10/Solaris 11 type system and spins up zones for testing.

Hopefully it'll be of use for you @Atalanta!

**Comment by fnichol** [comment]
I'm going to viciously close this as I know this Driver kicks ass :smile: Sound good? Hope so

![203](https://cloud.githubusercontent.com/assets/261548/6854666/4ffed78a-d3b8-11e4-88dc-546dfc8dee2b.gif)
