### ISSUE TITLE
Use vagrant-cachier, if available, for omnibus

### ISSUE THREAD

**Issue by docwhat** [test-kitchen/test-kitchen#440]
Downloading the chef-omnibus takes a while for each new converge.

To save time and bandwidth (both mine and opscode's) test-kitchen should cache the omnibus.

This can be done by:
1. detecting `vagrant-cachier`
2. passing `-d /tmp/vagrant-cache/vagrant_omnibus` (for linux systems) to the `https://www.getchef.com/chef/install.sh` script

That's it.  It'll download it if that file doesn't exist, otherwise it'll use the existing file.

For an example of this running (albeit as a vagrant plugin) see [this commit](https://github.com/schisamo/vagrant-omnibus/commit/9424a991c9d4abbd73513b291d30fe51db10c763) for [install_chef.rb](https://github.com/schisamo/vagrant-omnibus/blob/9424a991c9d4abbd73513b291d30fe51db10c763/lib/vagrant-omnibus/action/install_chef.rb) of vagrant-omnibus.

**Comment by tknerr** [comment]
fixed with test-kitchen 1.3.0

**Comment by tknerr** [comment]
affected by https://github.com/test-kitchen/test-kitchen/issues/580
