### ISSUE TITLE
Support Chef-DK

### ISSUE THREAD

**Issue by ringods** [test-kitchen/test-kitchen#443]
When running TK, the [busser integration code](https://github.com/test-kitchen/test-kitchen/blob/631a3d6cb6ef458305491ffb3000c51d33719397/lib/kitchen/busser.rb) tries to install the required tools in [``/opt/chef``](https://github.com/test-kitchen/test-kitchen/blob/631a3d6cb6ef458305491ffb3000c51d33719397/lib/kitchen/busser.rb#L160). It should detect either a Chef installation or a Chef Development Kit (Chef-DK) installation. The latter is installed under ``/opt/chefdk``.

**Comment by cheeseplus** [comment]
Looks like this should be supported based on the above merges. Closing but feel free to open for any further specific features or bugs related.
