### ISSUE TITLE
Support SOCKS proxy for post 'kitchen create' connectivity test

### ISSUE THREAD

**Issue by berniedurfee** [test-kitchen/test-kitchen#460]
The 'kitchen create' command uses a TCPSocket to test connectivity to the created host. If that host is hiding behind a firewall, you need to use a SOCKS proxy to reach it. So the 'kitchen create' fails, because there's no way to test the connection through a proxy.

This is a very common use case for users behind corporate firewalls spinning up instances in clouds, like AWS.

I don't mind fixing this, but I need a little guidance:

Option 1) Instead of doing a bare connection to port 22 on the host, why not just try to connect via SSH? This way the create would not only be sure the port is listening, but that a connection is possible.

Option 2) Add a socks_proxy parameter and use SOCKSSocket instead of TCPSocket if set.

Option 3) Something else?

**Comment by smurawski** [comment]
@berniedurfee now that kitchen create delegates the connection to the transport layer, is this still an issue for you?

**Comment by berniedurfee-ge** [comment]
This can probably be closed. No longer an issue, for me anyway.

**Comment by cheeseplus** [comment]
Thanks for following up!
