### ISSUE TITLE
Busser execution fails serverspec tests with command not found due to sbin not on PATH

### ISSUE THREAD

**Issue by daxroc** [test-kitchen/test-kitchen#469]
Issue
Working with a custom driver when I issue a kitchen verify using a simple serverspec test to verify a service is enabled. The test fails due to chkconfig not found.

Analysis
I've traced this back to the $PATH env not containing the sbin paths.

<pre><code>
$ ssh ...   sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CAC
HE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; sudo -E env'
</code></pre>

Result
<pre><code>
SHELL=/bin/bash
SSH_CLIENT=xxx.xxx.xxx.xxx 42496 22
USER=root
MAIL=/var/mail/kitchen
PATH=/usr/local/bin:/bin:/usr/bin:/opt/chef/bin
PWD=/vol_01/home/kitchen
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/kitchen
LOGNAME=root
SSH_CONNECTION=x.x.x.x 42496 x.x.x.x 22
LESSOPEN=|/usr/bin/lesspipe.sh %s
G_BROKEN_FILENAMES=1
_=/usr/bin/sudo
USERNAME=root
TERM=unknown
SUDO_COMMAND=/bin/env
SUDO_USER=kitchen
SUDO_UID=50737
SUDO_GID=50737
</code></pre>

<pre><code>
$ ssh ...   -t 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CAC
HE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; . /etc/profile; sudo -E env'
</code></pre>
Result
<pre><code>
HOSTNAME=localhost
TERM=xterm-256color
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=xxx.xxx.xxx.xxx 42497 22
SSH_TTY=/dev/pts/0
USER=root
VAR_ACE=/usr/local/etc
MAIL=/var/spool/mail/kitchen
PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/bin:/usr/bin:/opt/chef/bin:/opt/chef/bin
INPUTRC=/etc/inputrc
PWD=/vol_01/home/kitchen
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/kitchen
LOGNAME=root
SSH_CONNECTION=xxx.xxx.xxx.xxx 42497 xxx.xxx.xxx.xxx 4443
LESSOPEN=|/usr/bin/lesspipe.sh %s
G_BROKEN_FILENAMES=1
_=/usr/bin/sudo
USERNAME=root
SUDO_COMMAND=/bin/env
SUDO_USER=kitchen
SUDO_UID=50737
SUDO_GID=50737
</code></pre>

I'm not sure if this is a tk - bug or related to the custom driver 

This maybe caused by something weird in our environment so bare with me ... 

A question I have does the kitchen user require specifc environment setup on creation? 
Should I fix this command via the driver ?

**Comment by alliantist** [comment]
Hopefully this will help someone.  I manage sudo via chef using the https://github.com/opscode-cookbooks/sudo cookbook.  To allow serverspec to continue to work for tests where commands are called from /sbin, you need to override the node['authorization']['sudo']['sudoers_defaults'] attribute to set the secure path to include /sbin.  I do this as follows:
```
override['authorization']['sudo']['sudoers_defaults'] = [
  '!visiblepw',
  'env_reset',
  'env_keep =  "COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS"',
  'env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"',
  'env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"',
  'env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"',
  'env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"',
  'env_keep += "HOME"',
  'always_set_home',
  'secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
]
```
If you do the same be sure that vagrant user is not prevented from sudo'ing to root.

I do this using the sudo lwrp as follows in a recipe:
```
include_recipe 'sudo::default'

sudo 'vagrant' do
  user '%vagrant'
  runas 'ALL'
  variables :cmds => ['ALL']
  nopasswd true
end
```

**Comment by trilitheus** [comment]
Hopefully this will help someone.  I manage sudo via chef using the https://github.com/opscode-cookbooks/sudo cookbook.  To allow serverspec to continue to work for tests where commands are called from /sbin, you need to override the node['authorization']['sudo']['sudoers_defaults'] attribute to set the secure path to include /sbin.  I do this as follows:
```
override['authorization']['sudo']['sudoers_defaults'] = [
  '!visiblepw',
  'env_reset',
  'env_keep =  "COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS"',
  'env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"',
  'env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"',
  'env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"',
  'env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"',
  'env_keep += "HOME"',
  'always_set_home',
  'secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
]
```
If you do the same be sure that vagrant user is not prevented from sudo'ing to root.

I do this using the sudo lwrp as follows in a recipe:
```
include_recipe 'sudo::default'

sudo 'vagrant' do
  user '%vagrant'
  runas 'ALL'
  variables :cmds => ['ALL']
  nopasswd true
end
```

**Comment by Kasen** [comment]
You can add to your test:
```
set :path, '/sbin:/usr/local/sbin:$PATH'
```

**Comment by flaccid** [comment]
With serverspec/spec_helper.rb I did:

```
# encoding: UTF-8

require 'serverspec'

set :backend, :exec

RSpec.configure do |c|
  c.before :all do
    c.path = '/bin:/sbin:/usr/sbin:/usr/bin'
  end
end
```

In this case I was able to have serverspec check if a service was running on debian 7 via /usr/sbin/service.

**Comment by cheeseplus** [comment]
Closing this as answered (and not really a tk-core issue) - setting path in the spec_helper is the way to do this.
