### ISSUE TITLE
Multi-project chaining of shared CLI subcommands

### ISSUE THREAD

**Issue by schisamo** [test-kitchen/test-kitchen#47]
A concrete example of the problem this features aims to solve is the `init` subcommand Berkshelf and Test-Kitchen share.  Both projects make (sometimes competing) edits to the `Gemfile`, `Thorfile` and `Vagrantfile`.

Some sort of middleware convention would allow associated projects to share a command space.

**Comment by fnichol** [comment]
Agreed with @lamont-granquist; I think we can think about this in the context of ChefDK
