### ISSUE TITLE
Option to use internal gem server

### ISSUE THREAD

**Issue by amaltson** [test-kitchen/test-kitchen#474]
I'd love to have an option for test-kitchen's busser plugins to use our internal gem server instead of rubygems.org. Something like #438 or similar.

**Comment by aespinosa** [comment]
When I let busser use chef's embedded ruby (the default), I set the gemrc there in my omnibus installation scripts. I posted the same workaround in test-kitchen/busser#18

**Comment by cheeseplus** [comment]
Closing this as the issue belongs and already exists in test-kitchen/busser.
