### ISSUE TITLE
Missing vagrant-wrapper gem, update test-kitchen gem dependencies?

### ISSUE THREAD

**Issue by walterdolce** [test-kitchen/test-kitchen#488]
Hi there,

I just started using `test-kitchen` and I wanted to get quickly up-to-speed with the provided <a href="https://github.com/test-kitchen/test-kitchen#quick-start">Quick Start</a> guide.

I use the following bundle configuration on my projects as I like to isolate project's dependencies as much as I can (on that, I'd be more than pleased to receive recommendations from you guys, as I'm not a Ruby dev :) ).
```
# File {project_root_dir}/.bundle/config

BUNDLE_BIN: bin
BUNDLE_PATH: vendor/bundle
BUNDLE_DISABLE_SHARED_GEMS: '1'
```

Everything went fine for the initial steps: adding the gem to my `Gemfile`; running `bundle update`; running `kitchen init`;

When I ran `kitchen list` though, I received the error: `vagrant-wrapper is not part of the bundle. Add it to Gemfile.`

After doing that and re-running `bundle update` and `kitchen list` again, everything went fine.

So here's the question: should the gem `vagrant-wrapper` be added as a dependency to `test-kitchen`? 
If so, is <a href="https://github.com/test-kitchen/test-kitchen/blob/master/test-kitchen.gemspec">`test-kitchen.gemspec`</a> the right place to do so?

Thank you!

**Comment by grosser** [comment]
same here ... on rbenv too ...

**Comment by grosser** [comment]
solution is to `gem uninstall vagrant vagrant-wrapper` on every ruby you have -> rubygems no longer knows the executable -> works

**Comment by cheeseplus** [comment]
For the record, I'm pretty sure I'm not smarter than @sethvargo so I'm going to close this one for now. If this arises in the future we'll tackle it anew.
