### ISSUE TITLE
Upload files to test machine in parallel? 

### ISSUE THREAD

**Issue by robredpath** [test-kitchen/test-kitchen#491]
For various reasons, I use a private cloud on another continent to run VMs for Test Kitchen. I get approximately 130ms pings to the host that runs it, so I get really slow transfers when files are transferred in serial - kitchen seems to upload about 2-3 files a second (when I watch an strace). While I suspect that I'm at the extreme end of the spectrum, I think that anyone running VMs over the Internet would benefit from parallel file transfer. Would this be possible add?

**Comment by xmik** [comment]
Related to #657

**Comment by cheeseplus** [comment]
Closing this one as we have #657 and #35 before it for the same reason that https://github.com/coderanger/kitchen-sync exists and seems to solve this issue for the bulk of folks.
