### ISSUE TITLE
Need solution/best practice for installing gem in VM chef-client

### ISSUE THREAD

**Issue by kbruner** [test-kitchen/test-kitchen#495]
We have a site cookbook with a library that requires a gem be installed in the chef-client ruby environment.  There's a recipe that normally installs this gem (via chef_gem) before the library file is required, which works fine for a real-world chef-client.  However, because test-kitchen is trying to resolve all dependencies before anything gets run, it fails because it cannot load the library.

Is there a preferred way to handle this?  Would it make sense for test-kitchen to support multiple provisioners executed in order (in this case, a shell provisioner that uses /opt/chef/embedded/bin/gem to install the gem, then chef_zero to set up the environment).  Any other solutions?

**Comment by northrup** [comment]
What was the resolution to working with chef-vault in test kitchen?

**Comment by jezdikm** [comment]
Please can you share what was the solution for this problem? I face exactly same issue. Thank you.

**Comment by danieljimenez** [comment]
Same issue here I think...

**Comment by cheeseplus** [comment]
Please don't ressurect long dead issues. Closing this one and locking it.
