### ISSUE TITLE
test-kitchen exits if converge fails while there is still task to download a box

### ISSUE THREAD

**Issue by podwhitehawk** [test-kitchen/test-kitchen#496]
I'm trying to converge 2 boxes of 3 in parallel and if converge fail while downloading box - it will terminate download too.
It's not critical for sure, but can be painful while downloading from Amazon S3 (it's sometimes realy slooooow)

Steps to reproduce:
1. You need to have at least 2 boxes in converge process;
2. You should have 1 box already downloaded and another should download while previous is converging;
3. Start converging 2 boxes simultaneously with "-c 2" switch;
4. Get some exeption in first converge process while second is downloading;
5. See the exeption and test-kitchen stopping it's work while there is still data to download.
6. If you try to converge it again - test-kitchen will began downloading box from 0%

I'm using Xubuntu 14.04.1 x86_64 with latest updates, test-kitchen bundled in chefdk 0.2.1, Vagrant 1.6.3 and VirtualBox 4.3.14 r95030. 
If you need some more additional info - I'll try to collect it for you.
Thanks!

**Comment by smurawski** [comment]
Fixed by https://github.com/test-kitchen/test-kitchen/pull/1034
