### ISSUE TITLE
Need a mechanism to share tests between suites

### ISSUE THREAD

**Issue by bitwisekaizen** [test-kitchen/test-kitchen#503]
This has been raised a number of times on the IRC channel, yet the only recommendation to workaround the issue is to symlink common tests into each test suite directory.  Just like we can configure a path to data bags, we should be able to configure a path to additional tests that are common to multiple suites.

**Comment by L2G** [comment]
I, too, would like to be able to symlink to a directory of shared files and have Busser copy the files within it. Right now, for every place I want to use the shared files, I have to create a new directory and symlink each file individually, which is a pain in the ass.

**Comment by L2G** [comment]
I think I've worked out a fix for the symlinked-directory problem. See pull request #587.

**Comment by kbaltrinic** [comment]
+1

**Comment by acqant** [comment]
+1
I have a DEV and PROD chef server that I run tests for and I use the suites to point the same tests to the two different environments.  I'd like the same tests to be run on those suites.

I'll look at the different "helpers" for now.

**Comment by PierreRambaud** [comment]
:+1 Really need

**Comment by ChaitanyaChannella** [comment]
+1

**Comment by xmik** [comment]
Related to test-kitchen/pull/134

**Comment by Radagaisus** [comment]
###### Summary for people searching for this

https://github.com/test-kitchen/test-kitchen/pull/134 solves the issue, using shared RSpec examples ([here's an example implementation](https://github.com/coderanger/shared-spec-example)). It's not (yet) a documented feature of Test Kitchen.

**Comment by cheeseplus** [comment]
I'm closing this one out and locking as it's most "plus ones" when this belongs as a verifier specific issue and isn't a core issue.
