### ISSUE TITLE
difference between /tmp/kitchen/cache/cookbooks and /tmp/kitchen/cookbooks?

### ISSUE THREAD

**Issue by JeanMertz** [test-kitchen/test-kitchen#508]
While trying my hand at [vendoring gems inside a cookbook](https://sethvargo.com/using-gems-with-chef/) I am running into an issue where there is a difference between the contents of `/tmp/kitchen/cookbooks/transip` and `/tmp/kitchen/cache/cookbooks/transip`.

Namely, I am loading my vendored gem as followed:

``` ruby
$LOAD_PATH.unshift(
  *Dir[File.expand_path('../../files/default/vendor/gems/**/lib', __FILE__)])

require 'transip'
```

but am getting a `cannot load such file -- transip` error. When looking at the above two directories, I can see the `files/` path being present in the first (non-cache) path, but NOT in the cache path.

While printing `File.expand_path('../../files/default/vendor/gems/**/lib', __FILE__)` I get the following result:

`/tmp/kitchen/cache/cookbooks/transip/files/default/vendor/gems/**/lib`

Which means that the cookbook is being run from the cached path, but the `files` directory inside the cookbook only exists in the non-cached path.

What is the reasoning behind this, and is this a bug in Kitchen, or _am I doing it wrong_?

**Comment by iprudska** [comment]
Where have you added no_lazy_load setting?
I hit same issue and tried in .kitche.yml like this
suites: 
  - name: config
    run_list: 
      - "recipe[chefwkst::default]" 
    attributes: 
      chef_client: 
        config: 
          chef_server_url: ...
          log_level: ":info"
          no_lazy_load: true
          ohai: "Ohai::Config[:disabled_plugins] = [\"linux::filesystem\"]"
          validation_client_name: chef-validator

But I still can't see cookbook's files or templates uploaded.
