### ISSUE TITLE
enable multi YAML configuration support

### ISSUE THREAD

**Issue by odedpr** [test-kitchen/test-kitchen#514]
Hi, 
I know that YAML can support multiple configurations : 

name: SomeObject
attributes:
    - attr1
    - attr2
    - attr3
methods: [ getter, setter ]
\---
name: MyPrettyObject
attributes:
    - attr1
    - attr2
    - attr3
methods: [ getter, setter ]

Parses to:

{'attributes': ['attr1', 'attr2', 'attr3'],
 'methods': ['getter', 'setter'],
 'name': 'SomeObject'}
{'attributes': ['attr1', 'attr2', 'attr3'],
 'methods': ['getter', 'setter'],
 'name': 'MyPrettyObject’}

Can we have kitchen to support that functionality?

**Comment by smurawski** [comment]
This is a pretty general statement.  Feel free to re-open if you can be more specific with a use case.
