### ISSUE TITLE
Possibility to lock down versions of gems

### ISSUE THREAD

**Issue by ctapobep** [test-kitchen/test-kitchen#515]
Recently all the TestKitchen projects were failing because serverspec was updated. In order to escape this it's useful to be able to depend on particular version of busser, its plugins and libs like serverspec.

**Comment by cheeseplus** [comment]
This was fixed upstream https://github.com/test-kitchen/busser-serverspec/commit/a41a6da67872b1102fc7a33e7a8362bd17f8804e
