### ISSUE TITLE
Converge fails deleting non-cookbook files on Windows synced folder due to max path length

### ISSUE THREAD

**Issue by bravo-kernel** [test-kitchen/test-kitchen#522]
First of all, excuse me if this is not the right place to address this issue. Just let me know and I will re-create it elsewhere.

I stumbled across `kitchen converge` breaking the second time using Chef-DK on Windows against a Vagrant with synced local folder and it turns out the path length exceeded 255 chars.

Not sure if this is hitting the WIndows 255 character limitation or something else and if this could/should be fixed but having it noted here might actually benefit someone.

Described in detail with error here: [kitchen-converge-re-run-error-on-windows-against-vagrant-with-synced-folder](http://www.bravo-kernel.com/2014/10/kitchen-converge-re-run-error-on-windows-against-vagrant-with-synced-folder/)

**Comment by fnichol** [comment]
Hey there! Thankfully a lot has changed in the Test Kitchen codebase to make working with Windows Instances much easier. As we've worked hard to allow for uploading large files through WinRM, this issue should be resolved in the 1.4.0.beta.* releases. So, I'll close this issue out, but if you find that there is still an issue as described here, please reopen.

Thanks!

**Comment by bravo-kernel** [comment]
Thanks for responding, I will give 1.4 a go. Good job!
