### ISSUE TITLE
Provide ERB-variables in .kitchen.yml to get state of instances

### ISSUE THREAD

**Issue by jstriebel** [test-kitchen/test-kitchen#525]
It would be useful for dynamic configurations, to get the state of test-kitchen as ERB-variables. Currently I have to use this very implementation-dependent way to get this information:

```
state_file = Dir[".kitchen/#{role}-*.yml"][0]
if (state_file)
  state_config = SafeYAML.load_file(state_file)
  if ["converge", "setup", "verify"].include?(state_config['last_action'])
    # do something state-specific here
```

It would be nice to provide this information as a hash.

**Comment by gregsymons** [comment]
It would also be nice to have access to the instance's static config, so that I can do something like this (I haven't dug into what the actual structure is, so bear with me if it's wrong)

```
provisioner:
  name: ansible_playbook
  playbook: "test/integration/<%= config[:suite][:name] %>/playbook/main.yml
```

Or is there a better way to do this?

**Comment by cheeseplus** [comment]
Following up:
- Not entirely opposed to the feature but it's definitely outside the core use case
- the pathing is taken care of automatically for tests if they fit the `test/integration/SUITE` pattern but only for `verifiers`, so things (whether Chef or not) need to fit that model
- we really don't encourage this as this starts to get really clever and brittle, we may open this up more during a re-architect for 2.0 but depending on the state file is a recipe for edge case disasters

Going to close this one given the the isolate use case and interest. I've added this as a reference item on our roadmap as this request has come in a few different forms.
