### ISSUE TITLE
Auto creating nodes

### ISSUE THREAD

**Issue by mwrock** [test-kitchen/test-kitchen#528]
I know there have been a few issues filed in the past surrounding the notion of searching for other nodes and having those node populated with real data.

I too had this need and plumbed it into my custom driver that populates an IP and my custom provisioner that populates the run_list.

I'd be happy to submit a PR that puts this into the base driver and provisioner, but wanted to see if there is interest from the project owners before I do so.

**Comment by smurawski** [comment]
@mwrock searching for other nodes in the suite?  Or in some other pre-determined environment?  This might be a good thing to do in the provisioner when the chef ones are broken out.

**Comment by mwrock** [comment]
Oh blast from the past.  This is now[kitchen-nodes](https://github.com/mwrock/kitchen-nodes)
