### ISSUE TITLE
Cannot set log level to "info"

### ISSUE THREAD

**Issue by tyrken** [test-kitchen/test-kitchen#529]
As noticed in #478 & AFAIK, you cannot currently set log level to "info" as test-kitchen's chef solo and zero provisioners crowbar the setting to "auto" before forwarding to chef (see https://github.com/test-kitchen/test-kitchen/blob/a83398eba6d850971805447a42270925847acc08/lib/kitchen/provisioner/chef_solo.rb#L44), and chef interprets 'auto' as 'warn'.

This is currently more than "a bit annoying" as @danielsdeleo commented.  If you really wanted to trim down the log verbiage, change the default test-kitchen input from "info" to "warn", but please allow those of us who want it to get it rather than have to wade through debug.

Will happily submit a PR to remove the crow-baring in the line noted above & chef-zero if wanted.  Please advise on whether I should change the default TK log level to compensate at the same time or not.  Would suggest yes, as that would match Chef.

**Comment by mdhelgen** [comment]
Is there a workaround for this ? I'm using a chef handler which writes out to info at the end of the run and don't really want to go all the way down to debug in all of our jenkins logs.

**Comment by jeffbyrnes** [comment]
:+1: on fixing this up; it's frustrating that the `-l <loglevel>` CLI arg doesn't work.

**Comment by aaron-lane** [comment]
:+1:

**Comment by kevindickerson** [comment]
:point_up_2: Is there a reason for hijacking specific log levels?

**Comment by aaron-lane** [comment]
That really looks like you're flipping off this issue...

**Comment by kevindickerson** [comment]
@aaron-lane :hand: woah there

**Comment by fnichol** [comment]
@tyrken If I am understanding correctly, are you looking for a way to directly set the `--log_level` flag on a `chef-client` run inside of a Kitchen run, rather than Kitchen setting it for you? If so, we could create a new config option on the ChefZero Provisioner (maybe something like `:chef_log_level`) that would be used if set.

The one of the goals of #478 was to return the chef-client output to what a user would see running it directly on a node (defaults applying, of course).

@aaron-lane, @kevindickerson do I have a potential feature fix adequately captured, or still no quite on target?

Thanks all!

**Comment by aaron-lane** [comment]
@fnichol I think the sane solution would be to have kitchen and chef-client default to INFO level logs and default formatters, and possibly provide an option to tune each of those 4 parameters independently if it's desired by the community.

**Comment by danielsdeleo** [comment]
info is not the correct default for chef-client when output is to a terminal, 'warn' is the correct setting. Everything that gets sent to info is displayed in a more user friendly format via the formatters.

**Comment by alexpop** [comment]
I'm ok defaulting to 'auto' as long as it passes on to chef-client the log level specified for kitchen. Like this:

```
kitchen converge
/opt/chef/bin/chef-client ... --log_level auto
```

```
kitchen converge -l info
/opt/chef/bin/chef-client ... --log_level info
```

```
kitchen converge -l warn
/opt/chef/bin/chef-client ... --log_level warn
```

On top of this, a `:chef_log_level` provisioner option would be awesome

**Comment by tyrken** [comment]
Agree with @alexpop - we don't actually need a separate "chef log level" setting feature but that could be part of the fix.

The problem is the default log level for Kitchen is "info", but @fnichol says the goal of #478 was to tell Chef to log as it's default which is "auto" aka "warn" according to @danielsdeleo.  This circle has been squared with the mapping code in a couple of the Chef provisioners:

    level = config[:log_level] == :info ? :auto : config[:log_level]

... which means you cannot set chef to log in "info" _ever_.  Maybe you can with a custom formatter or such trickery - but this is a test system running a single converge of probably a single cookbook on a vanilla image.  Not a real node which might also have base cookbooks that use multiple passes to set & then use alterations of the client.rb to add such a formatter.

Like @alexpop, I'd also vote for the simplicity of changing the default Kitchen log level to auto/warn & removing the mapping code, but that might be regarded as too much of a breaking change by some.  If so, then I suspect you have to introduce an unmapped chef_log_level config.

**Comment by tknerr** [comment]
Apart from the log level, is there any way to control the formatter?

Right now it uses `doc` by default, but I have not found a way to use the `min` formatter yet

**Comment by hanskreuger** [comment]
@tknerr bit late here but the following works for me:
```yml
provisioner:
  client_rb: 
    add_formatter: min
```

**Comment by joegoggins** [comment]
:+1: , looking forward to a fix on this too

**Comment by tknerr** [comment]
@hanskreuger even way more later: thanks! Exactly what I was looking for :)

**Comment by jblaine** [comment]
Count me as a +1

```
2:35:37 PM - jblaine: Hi - does anyone know how to --force-formatter and use log_level :debug with the chef_zero provisioner + vagrant?
2:36:02 PM - jblaine: I'm not seeing the info in the docs.chef.io info or at kitchen.ci
2:36:36 PM - cheeseplus: there is an open issue on the repo has details iirc
2:42:42 PM - jblaine: Thanks. You're right.
```

**Comment by kquinsland** [comment]
Count me in a another +1; it's quite annoying that I can not set the log level i'd like for a given `chef-client` run in my `.kithcne.yaml` file.

**Comment by pc-fmarin** [comment]
+1 took me awhile to figure out I can't set the log_level to info since debug was working.

**Comment by keekdageek** [comment]
+1 I needed to set the log_level to 'info' this is a simple way to monkeypatch w/o changing too much.

Make your project a cookbook by adding metadata to your Berksfile and a metadata.rb.  In metadata.rb add a require statement
    
    require "./lib/kitchen/provisioner/chef_zero.rb"

Then in the chef_zero or chef_solo file, monkeypatch the chef_client_args method (keep in mind you only need to override the individual method and you can remove all the other methods from your monkeypatched filed)

    def chef_client_args
        level = config[:log_level] # == :info ? :auto : config[:log_level]
        args = [
          "--config #{remote_path_join(config[:root_path], "client.rb")}",
          "--log_level #{level}",
          "--force-formatter",
          "--no-color"
        ]
        add_optional_chef_client_args!(args)

        args
    end

Now info works just by changing your kitchen.yml !

    attributes:
      chef_client:
        config:
          log_level: ":info"

**Comment by b-dean** [comment]
@keekdageek the `metadata.rb` seems like a horrible place to monkey patch things from test kitchen. You could you probably do this inside the `.kitchen.yml` file since it can have ERB content.

```erb
---
platforms:
  - name: centos-7.1
suites:
  - name: default
    run_list:
      - recipe[foo]
<%
  # this will be evaluated when you run kitchen
  require 'kitchen/provisioner/chef_solo'
  class Kitchen::Provisioner::ChefSolo
    # whatever monkey patch you want
  end
%>
```

FWIW, I haven't actually tried this (although I have used ERB in `.kitchen.yml` files). I am just watching this issue waiting for some fix and using `-l debug` for times when I need to see more logs

**Comment by pc-fmarin** [comment]
@b-dean good idea, forgot about kitchen.yml erb, I agree w/ metadata.rb being a bad place.  I tried to put it in kitchen.yml though and it didn't work.  

This was the only place I could think of hooking into test-kitchen, open to any other ideas.

**Comment by iiro** [comment]
Bumped into this one again... +1 from me.

**Comment by vinyar** [comment]
:+1: +1

**Comment by carpnick** [comment]
+1

**Comment by carpnick** [comment]
I would agree we need an option to set kitchen log to debug, but chef to info/warn etc.  When debugging kitchen plugins, we might want debug, but not want to wade through chef-client debug.

**Comment by mwrock** [comment]
:+1:

**Comment by alexmanly** [comment]
:+1:

**Comment by axos88** [comment]
come on guys, it doesn't seem like such a hard fix, and it's been around for over a year now!

**Comment by cheeseplus** [comment]
@axos88 This project is volunteer open source for developers which all have full-time day jobs that aren't developing this project. We do our best but if you'd like to support the project then please submit a PR and we'd be happy to review it.

**Comment by axos88** [comment]
There ya go

**Comment by mwrock** [comment]
@axos88 are you planning on submitting that commit as a PR?

**Comment by cheeseplus** [comment]
If you can open the PR we can look at testing this and merging :+1:

**Comment by cheeseplus** [comment]
It also appears to only address this for chef-solo so we'd want to ensure parity between this and chef-zero/local-mode before merging this and also tests to validate the default levels. We are happy to assist with writing the tests but generally that is a pre-requisite for merging any changes in default behaviour.

**Comment by axos88** [comment]
Sorry, our enterprise github opens the PR automagically when editing a file on the web interface, it seems this one didn't.

https://github.com/test-kitchen/test-kitchen/pull/927

**Comment by sebfek** [comment]
+1

**Comment by alexpop** [comment]
Thank you all for the feedback.

A quick refresher. Independent of each other:
* kitchen default log level is `info`
* chef-client default log level is `auto`, where `auto` resolves to `warn` when a terminal is available or `info` when a terminal is not available. 

These are sensible defaults for every day human consumption. Without specifying the log level, you'll get this combination: kitchen on `info` and chef-client on `warn`

I've tested the recent PR( https://github.com/test-kitchen/test-kitchen/pull/927 ) opened for this issue.
Without specifying the log level, this change results in both kitchen and chef-client using `info`. I find chef-client `info` too verbose for everyday use and not a good default. I can make chef-client log `auto` by setting kitchen's log level to `warn`, but this produces very minimal output, as can be seen here:

* Successful converge output with https://github.com/test-kitchen/test-kitchen/pull/927:
```
$ bundle exec kitchen converge --log-level warn
$
```

* Failed converge output with https://github.com/test-kitchen/test-kitchen/pull/927:
```
$ bundle exec kitchen converge --log-level warn
>>>>>> Converge failed on instance <default-centos-6>.
>>>>>> Please see .kitchen/logs/default-centos-6.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

/opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889']
>>>>>> ----------------------
$
```

I've read all comments and two use-cases stand out:
* ability to set the provisioner(chef-client) log level to any of the supported values
* ability to change the chef-client log level independent from kitchen log level

My proposal is to have a new kitchen command line(and config) option for the provisioner log level. This will be the most flexible approach, as these examples show:

```
# kitchen info, chef-client info
kitchen converge --provisioner-log-level info

# kitchen warn, chef-client auto
kitchen converge --log-level warn

# kitchen info, FOO provisioner 7
kitchen converge --provisioner-log-level 7

# kitchen warn, chef-client fatal
kitchen converge --log-level debug --provisioner-log-level fatal
```

I can work on this the week of Feb 15 if we reach a consensus.

**Comment by carpnick** [comment]
Very good analysis from my perspective @alexpop .  As long as we can set the 2 values independently, we will be happy.  Keeping some sane defaults in .kitchen.yml and then having override on the CLI is just icing on the cake in my opinion

**Comment by drrk** [comment]
So in https://github.com/test-kitchen/test-kitchen/pull/950 I have created a possible route to fixing this.  I allow for the loglevel to be set under the provisioner section of the config file, rather than it being copied across from the base config.  I then for the chef-base set the default to auto.  

This allows for setting the two loglevel separately in the config file, but not on the commandline yet.  To do that an additional command line option is required to pass through to the provisioner.  I think perhaps having config options that starts --provisioner- being passed to the provisioner, with provisioner- stripped.  the same could be done for driver and other plugins.

**Comment by joegoggins** [comment]
Yay! Forward progress on this issue, hoping that ^^ commit can make it in soon.

**Comment by mfischer-zd** [comment]
Why not simply make the provisioner's log options settable under the provisioner definition in .kitchen.yml?  I was sort of surprised to find this doesn't work already.

**Comment by scottymarshall** [comment]
:+1:

**Comment by drrk** [comment]
This is what the current PR does, and I will have time on friday to fix the tests that currently fail due to the change in functionality.  I will also add documentation on how you can modify the setting with an environment variable if you are that way inclined.  Sorry for the delay I have been swamped getting ready for the conference I am running this week!

**Comment by vinyar** [comment]
@drrk this is great! Please post up when it's ready!

**Comment by drrk** [comment]
I've updated PR950 and i've got a kitchen-docs patch ready to go as soon as I know the version number of kitchen that it gets included into.

**Comment by acqant** [comment]
+1

**Comment by alisade** [comment]
+1

**Comment by cheeseplus** [comment]
So folks, this has been merged as per https://github.com/test-kitchen/test-kitchen/pull/950, adding +1's are meaningless and not helpful so I'm closing this one.
