### ISSUE TITLE
http(s)_proxy in test

### ISSUE THREAD

**Issue by obazoud** [test-kitchen/test-kitchen#533]
Hi folks,

Thanks for implementing http(s)_proxy #120 /cc @adamhjk 

My use case: Check that my web server is up and running via a http call

When I set http(s)_proxy in kitchen.yaml, 'busser test' includes 'env http_proxy=http://xxx.xxx.xxx https_proxy=http://xxx.xxx.xxx'. Each http call uses this proxy even in test that it misses my local web server (curl -iX GET http://localhost:8080)

Tested with bats/curl, serverspec/curl and serverspec/faraday.
The workaround is to force proxy to empty value.

My point of view is that "busser test" does not have to use proxy.
And no_proxy option is not available #414

Olivier.

**Comment by smurawski** [comment]
no_proxy is now supported as a configuration option.
