### ISSUE TITLE
Converge 2 suite runs on same node in Test-Kitchen

### ISSUE THREAD

**Issue by poliva83** [test-kitchen/test-kitchen#534]
I want to have integration test for testing that happens after a 2nd convergence on a node. I want to test an attribute driven recipe.

Right now I can only do this manually:

```
1. Do `test-kitchen converge` for default suite with json in .yml that adds 1st user.
2. `test-kitchen verify` 1st user exists on system. (Integration test 1)
3. Delete json in default suite relating to adding 1st user.
4. Add json in default suite relating to adding 2nd user
5. Do `test-kitchen converge` default suite again with 2nd user and original user's json removed.
6. `test-kitchen verify` that 1st user is removed from system and 2nd user is there. (Integration test 2)
```

I need a way to do a pre-converge step where I can modify platform after I create it for the 2nd ServerSpec test? Is this possible to do today?

**Comment by cheeseplus** [comment]
This already falls under the lifecycle support and #564 so closing as dupe.
