### ISSUE TITLE
How should one best test an application's response to configuration?

### ISSUE THREAD

**Issue by cdown** [test-kitchen/test-kitchen#541]
I have a cookbook that templatises a quite complex configuration for an application. I want to test that the configuration causes the application to do the right thing. In most cases I could just assume that the application author did the right testing, but in this case my concern is not about that, my concern is that the configuration is very complex and I want to run tests to make sure that the configuration does what is intended.

In this case, I want to provide a file in a certain location that the application will take action upon, and then I can write an integration test to make sure that the application did the right thing based on that input.

1. Is test-kitchen the right tool for this? If not, what is?
2. If test-kitchen is the right tool for this, how should one best go about placing a file in a particular location during the Kitchen run? Is there some way to get an arbitrary file to `kitchen_root`?

Thanks!

**Comment by cheeseplus** [comment]
Closing this as answered and lack of further response.
