### ISSUE TITLE
Test Kitchen setup issue

### ISSUE THREAD

**Issue by pavankumar222** [test-kitchen/test-kitchen#546]
Hi All,
I am trying to setup test kitchen to test few cookbooks. I am following the Learning chef Guide to do this.

All seems to have gone well till I edit the .kitchen.yml file to download centos machine. But when I try to spin up the VM I am facing below error.

-------------------------------------------------------------------------------------------------------------------------------

C:\Users\Pavan\Documents\kitchen>kitchen list
Instance Driver Provisioner Last Action
default-centos65 Vagrant ChefSolo <Not Created>

C:\Users\Pavan\Documents\kitchen>kitchen create default-centos65
-----> Starting Kitchen (v1.2.1)
-----> Creating <default-centos65>...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider=virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'learningchef/centos65' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
default: Adapter 1: nat
==> default: Forwarding ports...
default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
STDERR: The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.
---- End output of vagrant up --no-provision --provider=virtualbox ----
Ran vagrant up --no-provision --provider=virtualbox returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

--------------------------------------------------------------------------------------------------------------------------------

.kitchen.yml file contents.

*********************************************************************************************

---
driver:
name: vagrant

provisioner:
name: chef_solo

platforms:
- name: centos65
driver:
box: learningchef/centos65
box_url: learningchef/centos65

suites:
- name: default
run_list:
attributes:
---------------------------------------------------------------------------------------------------------------------------------

When I try to open the virtual box GUI and run the VM image.. my system crashes and reboots.. Kindly help me fix this issue.

**Comment by cheeseplus** [comment]
This is lack of vagrant which is explicitly required by the kitchen-vagrant install instructions. Closing.
