### ISSUE TITLE
chefzero integration test with several docker containers

### ISSUE THREAD

**Issue by reneix** [test-kitchen/test-kitchen#560]
I'm using kitchen-docker for integration test, while things become complicated on a new scenario:

I need test environment for solr cluster, say  2 solr server, 3 zookeeper server, and they need communicating. we already have this done with chef-server and multi vms.

My target is kitchen converge 5 docker container one by one, so that they can communicate. Not sure how to do this,  or I'm on the wrong way?

**Comment by DennyZhang** [comment]
Same question here: how use test kitchen to perform cluster deployment test.

**Comment by cheeseplus** [comment]
There is no way to currently use test-kitchen to test clusters, see #873 - closing as dupe.
