### ISSUE TITLE
recipe idempotence checking

### ISSUE THREAD

**Issue by petere** [test-kitchen/test-kitchen#561]
I'm looking for an automated way to test that recipes are idempotent.  This could be checked by hooking in a report handler and checking that it reports zero resources as updated.  (Maybe there is a better way.)  I see two main uses for this.  One are genuinely broken recipes, where for example a file is created and then deleted again two pages later, so that the resource flip-flops on every run.  The other is making report handling actually useful.  Currently, report handling is hardly useful because many cookbooks report resources as updated on every run because of bugs on all levels.  (Because of this, there would also have to be a way to opt out of testing this, initially.)

I was thinking that this could be implemented in Test Kitchen by adding another pass, like create, converge, *converge-again*, setup, verify, etc.  The second converge would just run converge again, and check the number of updated sources (or something else, see above).

So I started hacking around a bit, but I wasn't really sure if that approach made sense implementation-wise.  All the other passes are more or less passed through to the driver, whereas "converge-again" would be handled inside Test Kitchen.  So that led to some ugliness.

So what do you think?  Would this be useful?  And how should it be implemented?

**Comment by petere** [comment]
That's true, but that doesn't make it easy to apply this principle widely.  For example, there are quite a number of widely used cookbooks that fail this idempotence test, and if test-kitchen had an easy way to just turn this kind of test on, they could probably be fixed.  But if they all need to apply some cumbersome copy-and-paste snippets to their test definitions, very few will do it, and none will do it on their own.  So to succeed, this should really be built into test-kitchen.

**Comment by echohack** [comment]
+1 on this. Idempotent resources are incredibly important to well written cookbooks.

**Comment by cheeseplus** [comment]
This is being tracked in an existing issue and a PR #875 - closing this as dupe.
