### ISSUE TITLE
Existence of "/opt/chef" is not a sufficient condition for skipping Chef installation

### ISSUE THREAD

**Issue by ghost** [test-kitchen/test-kitchen#568]
[The existence of /opt/chef](https://github.com/test-kitchen/test-kitchen/blob/15b85bd9e99de299b9826e4919d51a6cac3ea62b/lib/kitchen/driver/ssh_base.rb#L109) should not be a sufficient condition for skipping Chef installation if `require_chef_omnibus` is set to `true`

If you uninstall the Chef RPM on Enterprise Linux and have had custom gems installed (like serverspec) the enclosing folder /opt/chef would not be removed by `yum purge chef`. This could happen if you provision your box with packer and remove the provisioner afterwards.

**Comment by cheeseplus** [comment]
A PR is welcome on this one but I agree in principle that the detection could be better.

**Comment by tas50** [comment]
We now remove the /opt/chef directory as part of the chef uninstall so this should no longer be an issue at the chef level. I'm going to close this out since we don't need to further expand the detection on the TK side.
