### ISSUE TITLE
.kitchen.yml configuration options 

### ISSUE THREAD

**Issue by kpettijohn** [test-kitchen/test-kitchen#574]
Hi all, 

I was wondering if we have a central list of all of the configuration options for the .ktichen.yml file. If not I would like to help create such a list. 

I have found each time I browse through the source code I find more and more valuable configuration options that I never new existed. If anyone has any interest in this please let me know!

**Comment by jeffbyrnes** [comment]
:+1: I'd definitely be interested in having a master list of the config options.

**Comment by kpettijohn** [comment]
I will attempt to put a list of config options together this weekend and post it here. Once things look good I will see about getting a pull request on https://github.com/test-kitchen/kitchen-docs.

**Comment by cheeseplus** [comment]
There is https://docs.chef.io/kitchen.html#kitchen-yml - happy to see more

**Comment by cheeseplus** [comment]
The place for these is now officially http://kitchen.ci/docs/kitchen-examples and PRs can be created on https://github.com/test-kitchen/kitchen-docs
