### ISSUE TITLE
Custom root_path permissions issues

### ISSUE THREAD

**Issue by kpettijohn** [test-kitchen/test-kitchen#576]
When using the `root_path` configuration kitchen will fail unless you have the permissions to create the directory. 

```
I, [2014-12-30T15:40:53.691830 #17560]  INFO -- api: Thank you for installing Chef!
I, [2014-12-30T15:40:54.174615 #17560]  INFO -- api: mkdir: cannot create directory `/var/chef': Permission denied
E, [2014-12-30T15:40:54.428643 #17560] ERROR -- api: Converge failed on instance <api>.
E, [2014-12-30T15:40:54.428777 #17560] ERROR -- api: ------Exception-------
E, [2014-12-30T15:40:54.428799 #17560] ERROR -- api: Class: Kitchen::ActionFailed
E, [2014-12-30T15:40:54.428813 #17560] ERROR -- api: Message: SSH exited (1) for command: [sh -c '
sudo -E rm -rf /var/chef/cookbooks /var/chef/data /var/chef/data_bags /var/chef/environments /var/chef/roles /var/chef/clients
mkdir -p /var/chef
']
```

I might not have the best use case in the world but when using test-kitchen I wanted to locate my chef files in the same location they would be located on my packer builds. 

For my use I modified the following:
https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_base.rb#L96

```
-        lines = ["#{sudo("rm")} -rf #{dirs}", "mkdir -p #{config[:root_path]}"]
+        lines = ["#{sudo("rm")} -rf #{dirs}", "#{sudo("mkdir")} -p #{config[:root_path]}", "#{sudo("chown")} #{config[:username]}:#{config[:username]} #{config[:root_path]}"]
```

If possible it would be awesome if we could get a similar change into test-kitchen. I can make a pull request if its something you guys would consider merging in. Any feedback on this would be appreciated!

**Comment by cheeseplus** [comment]
If this is still and issue we're happy to review a PR or close if it's already been addressed given the length of time.

**Comment by cheeseplus** [comment]
Closing due to age and lack of response but feel free to open a new one if this is still an issue in your environment.
