### ISSUE TITLE
Prefix console output with string (intsead/in lieu of colorizing)

### ISSUE THREAD

**Issue by robredpath** [test-kitchen/test-kitchen#583]
We use Jenkins for our internal CI. We try to keep our install as plugin-free as possible, so we don't get colour in CI. As a result of this, we have to run our tests in series, otherwise the output becomes completely unreadable. What I'd LOVE would be two things: 
- The option to disable colour 
- The option to replace coloured lines with a prepended string; maybe the name of the platform/suite that's being run. It then becomes trivial to extract a single suite's logs from the output with grep, while letting us use our beefy CI box to do parallel testing.

**Comment by robcoward** [comment]
+1

**Comment by ekrupnik** [comment]
:+1: Even with us having color in the Jenkins console output, it would be nice to have the ability to search for a specific platform/suite and even have the search results highlighted on the screen. Relying on the colors alone is not ideal in a concurrent run of 6 nodes!

**Comment by Igorshp** [comment]
+1 to above as well,

We run kitchen in jenkins as well, but there is no color output. 
I've traced it to the fact that kitchen thinks it's not running a tty:
https://github.com/test-kitchen/test-kitchen/blob/616c40cc3b2a764d6075dc7718ea316b0f528e6a/lib/kitchen.rb#L104

How do get it to output color when run from jenkins?

**Comment by chazzly** [comment]
+1

**Comment by Igorshp** [comment]
There is a PR open to fix this issue:
https://github.com/test-kitchen/test-kitchen/pull/1032#issuecomment-222834650

**Comment by mwrock** [comment]
and that is now merged and slated for release so while it does not prefix output, it does provide a means of forcing color/no-color.

**Comment by jorhett** [comment]
If you look at the diff for that merge, the option to add a prefix would be very very similar.

**Comment by koldrid** [comment]
👍 We use TeamCity and have the same problem.

**Comment by cheeseplus** [comment]
Renamed the issue to focus on the one issue of prefixing output as (no)colorization has been addressed.
