### ISSUE TITLE
Don't print extraneous equals signs to logs "================"

### ISSUE THREAD

**Issue by gdamiani** [test-kitchen/test-kitchen#586]
It's good practice to lint your repositories for cruft that can creep in during the course of normal business.  If you have merge conflicts in a git repository, that tool will print out a number of markers onto your code in order to mark them.  They look like this:

```
the number of planets are
<<<<<<< HEAD
nine
=======
eight
>>>>>>> branch-a
```

It's a developers responsibility to remove the markers before continuing the merge.  Most implementations of this SCM will be perfectly fine letting you commit `<<<<<<< HEAD` or `=======` back onto HEAD.  So it's a good idea to instruct your CI or git hooks to search for those strings and warn when found. 

test-kitchen as it's configured on my machine will print the following line to a log file as a matter of course:
```
================================================================================[0mI, [2014-12-18T18:51:29.724561 #85523]  INFO -- default-ubuntu-1204: 
```

I would venture a guess that this is to improve readability.  Changing that horizontal line to be a collection of hyphens would set off far fewer alarms for myself and for other people doing the same.

**Comment by tyler-ball** [comment]
@gdamiani What version of TK are you using?  Can you try this with the latest version (1.3.0) and see if you still get this output?

**Comment by fnichol** [comment]
I'm hoping that the 1.4.0 release of Test Kitchen has addressed this issue. If I'm wrong, please reopen and we will pick it up again. Thank you!
