### ISSUE TITLE
Idea: Driver-level hinting for Chef install

### ISSUE THREAD

**Issue by coderanger** [test-kitchen/test-kitchen#597]
I've been using a lot of kitchen-docker lately and it would be really nice if there was some way the driver could generate cached layers that has the requested Chef version the way it does with the other setup steps. This could be done by having a hinting layer that if a driver supports it, pass in the provisioner config. This would require some level of explicit coordination between the driver and provisioner so I thought it prudent to ask for public comment first. Installing Chef is a pretty decent chunk of the run time on most of my cookbooks (the other big one being cookbook transfer time) so it seems like it might be big enough win to be worth the messiness. For other drivers it could allow for things like picking an AMI or VBox file with the right version of Chef in it.

**Comment by xacaxulu** [comment]
+1 I could definitely use functionality like this.

**Comment by CpuID** [comment]
+1 definitely would love to see this. I did something in kitchen-docker to try and workaround this, see https://github.com/portertech/kitchen-docker/pull/133

**Comment by cheeseplus** [comment]
I'm cool with this - I mean at one point we pre-baked the bento boxes with Chef installed so this doesn't sound that out there. This could also fold in to the `package` command support for plugins we've added where one can generate the box file or AMI from a completed kitchen run.
