### ISSUE TITLE
Option to set delay between converge and verify on test

### ISSUE THREAD

**Issue by k6ps** [test-kitchen/test-kitchen#598]
For example:

```
kitchen test --verify-delay=30000
```

That would delay/sleep for 30000 milliseconds after a successful converge and before starting the tests. This would be useful when i'm smoke-testing a system that takes time to fully start up for the first time. Otherwise it would retain the normal behaviour of the test command, and it would work also when testing multiple suites in parallel.  

Just an idea..

**Comment by rbowlby** [comment]
+1, some of these resources take time to fully converge.

**Comment by TinaTina** [comment]
+1

**Comment by kisoku** [comment]
If you are using serverspec for smoke testing you can use rspec-wait to
have the test suite wait until certain conditions are met before executing
tests. I'm using this successfully in my environment

On Thu, Feb 12, 2015 at 2:49 AM, Ryan Bowlby <notifications@github.com>
wrote:

> +1, some of these resources take time to fully converge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/test-kitchen/test-kitchen/issues/598#issuecomment-73928086>
> .
>



-- 
Mathieu Sauve-Frankel

**Comment by bottkv488** [comment]
+1
also +1 for @kisoku, thx for sharing rspec-wait!

**Comment by pinterl** [comment]
@kisoku 
Can you help me with an example how to set up rspec-wait in test kitchen?

I have installed rspec-wait with
`gem install rspec-wait`

I have added the following to spec_helper.rb in the folder of the test file
`require 'rspec-wait'`

I have the following in the XXX_spec.rb test file
```
describe port(9090), wait: { timeout: 30 } do
  wait_for { should be_listening }
  it { should be_listening }
end
```

When I run `kitchen verify` I get:
`in `require': cannot load such file -- rspec-wait (LoadError)`

**Comment by cheeseplus** [comment]
If the resources take lots of time to startup I'd argue that the cookbook itself should be checking that before being done or the test itself use a mechanism similar to rspec-wait. Kitchen really shouldn't be responsible for this but if there was a PR I'd also be more amenable.

We already have so many timeouts all over the place I'm not keen to add another one if unneeded.

**Comment by joestump** [comment]
@pinterl Add it to a [Gemfile](https://github.com/test-kitchen/busser-serverspec#-usage) in your `test/integration/suite_name` directory. That fixed it for me.

**Comment by joestump** [comment]
@cheeseplus I'd be happy with closing this out with a `wait_for` example that'd work. I gave up and just added a `sleep 30 && /my/command` in the one area I needed it.

Elasticsearch takes a while to start up. Doing a `converge` and then `verify` works, but a `test` runs too fast and fails while checking for the alive server. Ironically, it shows up as `be_running` but the HTTP service isn't yet up and running when Busser runs.

**Comment by joestump** [comment]
@pinterl @cheeseplus Looks like `rspec-wait` requires Spec 3.5 or less. Seems v3.5 is what's used.

**Comment by coderanger** [comment]
@p0six You can now do this with a lifecycle hook if you must:

```yaml
lifecycle:
  post_converge:
  - local: sleep 30
```
