### ISSUE TITLE
Not correct URL for opensuse-13.1 platform

### ISSUE THREAD

**Issue by Y4Rv1K** [test-kitchen/test-kitchen#599]
In case of OpenSUSE 13.1 as platform for test-kitchen I add next line: 

    platforms:
         - name: ubuntu-14.04
         - name: opensuse-13.1

As result: 

        default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
        default: Box Version: >= 0
       ==> default: Adding box 'opscode-opensuse-13.1' (v0) for provider: vmware_desktop, vmware_fusion, vmware_workstation
       default: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_opensuse-13.1_chef-provisionerless.box

    STDERR: An error occurred while downloading the remote file. The error message, if any, is reproduced below. Please fix this error and try again.

    The requested URL returned error: 404 Not Found
    ---- End output of vagrant up --no-provision --provider=vmware_fusion ----
    Ran vagrant up --no-provision --provider=vmware_fusion returned 1]

After some investigation I found workaround how to use proper URL `https://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_opensuse-13.1-x86_64_chef-provisionerless.box`: 

     platforms:
        - name: ubuntu-14.04
        - name: opensuse-13.1-x86_64

Doesn't looks like a feature.

**Comment by cheeseplus** [comment]
The ssue here was corrected as of 13.3 when we set the naming to match the other boxes. Feel free to re-open under https://github.com/test-kitchen/kitchen-vagrant/ for further issues.
