### ISSUE TITLE
Detect and warn users about Powershell bug KB2842230 that causes Out of Memory Errors

### ISSUE THREAD

**Issue by robcoward** [test-kitchen/test-kitchen#604]
Powershell has a documented bug (http://support.microsoft.com/kb/2842230) that causes Powershell to ignore a customized MaxMemoryPerShellMB quota. This causes chef-client run via a WinRM session to fail with 'failed to allocate memory' errors when converging certain resources:

```
           ================================================================================
           Error executing action `install` on resource 'chef_gem[rest-client]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of C:/opscode/chef/embedded/bin/gem install rest-client -q --no-rdoc --no-ri -v "1.7.2" ----
           STDOUT: 
           STDERR: Invalid gemspec in [C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/specifications/diff-lcs-1.2.5.gemspec]: failed to allocate memory
```
There is a hotfix available to fix this powershell issue - http://hotfixv4.microsoft.com/Windows%208%20RTM/nosp/Fix452763/9200/free/463941_intl_x64_zip.exe . Could test-kitchen detect the absence of this hotfix and either download and install it, or at least warn users about the problem ?

**Comment by fnichol** [comment]
@robcoward Hi there! I was also bit by this issue and it seems to plague certain versions of Windows that don't yet have patches applied including Windows 8 (not 8.1) and Windows Server 2012 (not 2012r2).

After a lot of investigation into possible solutions, I think we'll need to leave this as a known issue that the base image needs to address--it's just too hard to detect and fix this. In looking for a solution, I found that most other projects (including CHEF-related projects) leave this to the end user to prepare their base image with the hotfix.

As I don't like to manually do what I can automate, I've sent contributed boxcutter/windows/pull/6 to the boxcutter project with a .bat script to install the hotfix when Windows is being installed. I'm reasonably sure that the hotfix script could be applied to other image-preparation setups which hopefully gets people closer to solving this "in the base", as it were.

I'm going to close this, if that's all right as I don't see an out-of-the-box solution which is rock solid. In the meantime, I hope this confirmation and a possible mitigation gets you closer to testing happiness.

Thank you!

**Comment by spuder** [comment]
I also ran into this on a test vm, however I'm running windows 2012 R2. 

![screenshot 2015-10-14 09 31 33](https://cloud.githubusercontent.com/assets/242382/10488552/6ac358ce-7256-11e5-9802-8134e722f6aa.png)

Running the latest patches as of September 2015 (currently is october)
