### ISSUE TITLE
Inconsistent default filename for encrypted_data_bag_secret?

### ISSUE THREAD

**Issue by rmoriz** [test-kitchen/test-kitchen#614]
As far as I understand the source, test-kitchen defaults to a file called `encrypted_data_bag_secret_key`, however most other chef-tools (and chef itself) just call the file `encrypted_data_bag_secret`.

see https://github.com/test-kitchen/test-kitchen/blob/72632ed74fcf945a8cbaf8e817496f118a8056e8/lib/kitchen/data_munger.rb#L280
and https://github.com/test-kitchen/test-kitchen/blob/72632ed74fcf945a8cbaf8e817496f118a8056e8/lib/kitchen/provisioner/chef_base.rb#L92

I'm confusing it all the time, and I'm not sure if this is intentional:

see:

https://github.com/test-kitchen/test-kitchen/issues/248#issuecomment-29361804
vs.
https://github.com/test-kitchen/kitchen-ec2/issues/24#issuecomment-29546657

**Comment by cheeseplus** [comment]
So the tricky bit is that `encrypted_data_bag_secret` is actually for a directory that the secrets live in vs the file in client.rb. In test-kitchen we are explicit between path vs key but it's definitely confusing as Chef docs use `encrypted_data_bag_secret` to reference the setting which is just the dir and then later for the file itself despite the two not (actually) being related: https://docs.chef.io/data_bags.html
