### ISSUE TITLE
Support Special Characters in SSH Passwords

### ISSUE THREAD

**Issue by kaizoku0506** [test-kitchen/test-kitchen#619]
I have noticed that Kitchen::SSH.new truncates passwords that contain a "?".  I assume this is happening for other characters as well.

---

**Given:**
VM Password => "pa55w0rd?"
Command => `Kitchen::SSH.new(config[:ip_address], config[:username], password: config[:password])`

---

**The result is:**

``` bash
[2015-02-23T12:27:19.618816 #58441] DEBUG -- : [SSH] opening connection to username@ip_address:22<{:password=>"pa55w0rd"}>
>>>>>> Converge failed on instance <server-centos-66>.
>>>>>> Please see .kitchen/logs/server-centos-66.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Authentication failed for user username@ip_address
>>>>>> ----------------------
```

**Comment by cheeseplus** [comment]
This was resolved a long while ago.
