### ISSUE TITLE
kitchen not detecting vagrant plugin `kitchen-vagrant`

### ISSUE THREAD

**Issue by xacaxulu** [test-kitchen/test-kitchen#622]
Ubuntu 14.10 fresh install

    chef@ubuntu:~/db2$ uname -a
    Linux ubuntu 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

    chef@ubuntu:~/db2$ vagrant -v
    Vagrant 1.4.3
    chef@ubuntu:~/db2$ vagrant plugin list
    kitchen-vagrant (0.15.0)
    chef@ubuntu:~/db2$ chef -v
    Chef Development Kit Version: 0.4.0
    chef@ubuntu:~/db2$ 

    chef@ubuntu:~/db2$ kitchen converge --parallel
    -----> Starting Kitchen (v1.3.1)
    -----> Creating <default-centos-511>...
    -----> Creating <default-fedora-20>...
       The plugin "kitchen-vagrant" could not be found. Please make sure that it is
       properly installed via `vagrant plugin`. Note that plugins made for
       Vagrant 1.0.x are not compatible with 1.1+ and this error will likely
       continue to show when you use `plugin install` with a 1.0.x plugin.

Running `chef exec kitchen test` & `kitchen test` return the same error message even though `gem list`, `chef gem list`, `vagrant plugin list` all show the `kitchen-vagrant` gem/plugin installed.

Why does `kitchen` not detect the vagrant plugin `kitchen-vagrant` even though it's listed as installed?

**Comment by cheeseplus** [comment]
This should have been resolved in Vagrant 1.5 I believe (it was an issue with internal ruby paths). If you're still experiencing feel free to open a fresh issue with current details.
