### ISSUE TITLE
kitchen hangs on converge

### ISSUE THREAD

**Issue by myspotontheweb** [test-kitchen/test-kitchen#624]
Chef client hangs when running a converge

    $ kitchen converge default-ubuntu-1204
    -----> Starting Kitchen (v1.3.1)
    -----> Converging <default-ubuntu-1204>...
           Preparing files for transfer
           Preparing dna.json
           Resolving cookbook dependencies with Berkshelf 3.2.3...
           Removing non-cookbook files before transfer
           Preparing validation.pem
           Preparing client.rb
    -----> Chef Omnibus installation detected (install only if missing)
           Transferring files to <default-ubuntu-1204>
           Starting Chef Client, version 12.0.3

Tracked down root cause to be a known issue with the [gce ohai plugin][1]

Problem is I cannot disable the plugin in order to work-around the issue. Here's my kitchen file

    ---
    driver:
      name: vagrant
    
    provisioner:
      name: chef_zero
      client_rb:
        "Ohai::Config[:disabled_plugins] =":
          - gce
    
    platforms:
      - name: ubuntu-12.04
      - name: centos-6.4
    
    suites:
      - name: default
        run_list:
          - recipe[my_java]

This generates the following expected entry in the client.rb file, which does not work:

    Ohai::Config[:disabled_plugins] = ["gce"]

The following setting does work:

    Ohai::Config[:disabled_plugins] = [:GCE]

Problem is kitchen insists on quoting the value fields and there does not appear to be a way to specify Ruby symbols. Alternative suggestions are very welcome.

Ohai 7 changes the way plugins are disabled and the [docs][2] are confusing. The example suggests string names are accepted... but I think that is only for Ohai 6 plugins.

Finally I discovered issue  https://github.com/test-kitchen/test-kitchen/issues/415 which might be the same problem.

Software:

- Chef Development Kit Version: 0.4.0
- Vagrant 1.7.2

[1]: https://github.com/chef/ohai/issues/382
[2]: https://docs.chef.io/ohai.html#ohai-settings-in-client-rb

**Comment by myspotontheweb** [comment]
My eventual work-around was to revert back to chef 11.

    ---
    driver:
      name: vagrant
      require_chef_omnibus: 11.16.4

Although the underlying root cause is the ohai version, it's a pity I was unable to disable the gce plugin.

**Comment by myspotontheweb** [comment]
Eventually discovered how to disable the ohai plugin

    provisioner:
      name: chef_zero
      client_rb:
        "Ohai::Config[:disabled_plugins] = [:GCE] #": 

This generates the following entry in the client.rb file

     Ohai::Config[:disabled_plugins] = [:GCE] # nil

**Comment by mikedodge04** [comment]
Thanks that worked !
