### ISSUE TITLE
Test-Kitchen Bats Test not showing description

### ISSUE THREAD

**Issue by mliedike** [test-kitchen/test-kitchen#628]
I am learning test-kitchen and am running into a small issue.  When I run kitchen verify or test I am able to get the test to complete successfully but I am not able to see a description of the test I am successfully completing.  I get this output:

-----> Running bats test suite
                                                                            1/1

```
   1 test, 0 failures
   Finished verifying <default-ubuntu-1204> (0m1.22s).
```

When I look at examples I should be seeing something similar to this:

----> Running bats test suite
 ✓ git binary is found in PATH

1 test, 0 failures
       Finished verifying <default-ubuntu-1204> (0m0.89s).

My test looks like this:
# !/usr/bin/env bats

@test "git binary is found in PATH" {
  run which git
  [ "$status" = 0 ]
}

Any idea why I am not getting the description output?

Thank you

**Comment by cheeseplus** [comment]
Was this ever resolved? I haven't been able to reproduce and given the age will close this if we don't get a reply within 30 days just for the sake of housekeeping.
