### ISSUE TITLE
Support multiple paths for data bags

### ISSUE THREAD

**Issue by garrypolley** [test-kitchen/test-kitchen#634]
In #161 some configuration options were given to specify the path to roles or data bags.  I would like to be able to specify an array of directories/paths.  

Basically doing something like: 

``` yml
data_bags_path: 
  - 'data_bags',
  - 'test/integrations/data_bags'
```

I want to do this so I can have two types of data bags in my tests.
- The ones I'm keeping in source control that I upload to my environments
- Other ones that I am dependent on in my given chef environment but are not in the control of my application (for example URLs that are shared between many applications).

If I could specify multiple paths this would make it easier to test the data bags I upload as well as my chef roles and environments.  I could see this same concept being expanded to roles and environments as well if desired.

**Comment by joonas** [comment]
I'm interested in this feature for similar reasons as well.

I'm also willing to look in to submitting a PR that implements this (and potentially adds support for other things like roles and/or environments) if the functionality is desirable to have.

**Comment by maximusfloydus** [comment]
I have the need for multiple role paths.

**Comment by iiro** [comment]
+1 for multiple role paths as well.

**Comment by cmgurba** [comment]
+1

**Comment by pwyliu** [comment]
+1 this feature would be super useful for me too.

**Comment by cheeseplus** [comment]
Definitely adding this to the backlog but if anyone feels up for a PR we'd be happy to review.

**Comment by ashmckenzie** [comment]
Plz to haz?! :)

**Comment by benallamar** [comment]
+1 will be a good way to mix real & fake data bags (for integration purpose)
