### ISSUE TITLE
client key is invalid or not found at: 'C:/chef/client.pem'

### ISSUE THREAD

**Issue by threezerous** [test-kitchen/test-kitchen#636]
I am using vagrant 1.7.2 and chefdk 0.4.0-1 on windows and seeing the error above each time when I try to run kitchen converge. Not sure where it is trying to pickup the path setting for c:/chef-client.pem. Anybody run into this before?

**Comment by fnichol** [comment]
@threezerous Hi there! Would you be able to attach a sample .kitchen.yml or better yet the output of `kitchen diagnose --all` (just be sure to check the contents for password, API secrets, etc.)? I'd also recommend that you try upgrading to the latest 1.4.0.beta.* (or later) releases to rule out anything that may have been resolved in the last week or so--there's a lot :wink: 

Thanks!

**Comment by fnichol** [comment]
Hopefully the 1.4.0 release of Test Kitchen, the 0.17.0 release of kitchen-vagrant fixed your issue. If I'm wrong, please don't hesitate to reopen this issue and we will pick it up. Thank you!

**Comment by threezerous** [comment]
Apologies for the late response. Just upgraded to Test Kitchen 1.4.0 and the issue got resolved. Thanks a bunch.

**Comment by jdmundrawala** [comment]
I had this issue once. Turned out, I had a cookbook that was deleting files. Any chance you have something like that going on?
You can paste your yaml file here, and long things in a [gist](https://gist.github.com) and paste the link here. Make sure to use markdown

**Comment by threezerous** [comment]
Thanks. I will check my cookbook again to confirm it is not deleting any files. Meanwhile, here is the kitchen.local.yml

---
use_vagrant_berkshelf_plugin: true
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: test/environments

platforms:
  - name: centos-6.5
    driver:
      box: opscode_centos-6.5
      network:
      - ["private_network", {ip: "33.33.33.10"}]

suites:
  - name: default
    run_list:
      - recipe[vagrant-yum-repo::client]
      - recipe[test-cookbook::default]

    attributes:
      mount_shares: true
      dev_mode: true

Here is the link to kitchen diagnose https://gist.github.com/threezerous/10d9d3ad7d768250a885

**Comment by jdmundrawala** [comment]
`kitchen_version: 1.3.1`

**Comment by jdmundrawala** [comment]
Also, you should paste the log that kitchen spits out when it fails

**Comment by threezerous** [comment]
Thank you very much for taking the time to look into this.
I did not update windows path so it again picked up 1.3.1......now corrected
The revised logs are attached
https://gist.github.com/threezerous/a5b48d99887ff9f8599d
https://gist.github.com/threezerous/a40097c4b5544885fad1

The message on console is
       Vagrant instance <default-centos-65> created.
       Finished creating <default-centos-65> (1m23.30s).
-----> Converging <default-centos-65>...
$$$$$$ Running legacy converge for 'Vagrant' Driver
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [client key is invalid or not found at: 'C:/chef/client.pem']
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by jdmundrawala** [comment]
What does your Berksfile look like

**Comment by threezerous** [comment]
source 'http://berkshelf-api.portal.webmd.com'
source 'https://supermarket.getchef.com'

metadata

if ENV['LOCAL_YUM'] == 'true'
  cookbook 'vagrant-yum-repo', path: '~/projects/vagrant-yum-repo/cookbooks/vagrant-yum-repo'
end

**Comment by threezerous** [comment]
This was resolved after I removed the line where it was sourcing to our internal berkshelf server - source 'http://berkshelf-api.company.com' Not sure why it was trying to access the client.pem
