### ISSUE TITLE
RubyZip is corrupting zip files on windows hosts

### ISSUE THREAD

**Issue by mwrock** [test-kitchen/test-kitchen#643]
This is related to #635 that @webframp, @fnichol and I were discussing earlier. Its the same cookbook, but i dont think the cookbook matters. After specifying a communicator and getting `kitchen create` to work, individual files were copied to `temp/kitchen` but not the cookbook directories. After troubleshooting, I found that the initial zip file created was corrupted. I couldn't open it. The same zip generated on a linux host is ~1k smaller and is just fine. I have a strong suspicion that this is related to line endings. In 2015 the type writer and its carriage return still haunts us.

I'll spend some time this weekend looking further into this.

**Comment by mwrock** [comment]
Also see http://stackoverflow.com/questions/25322704/opening-file-in-binary-mode-and-saving-it-adds-new-line about

**Comment by fnichol** [comment]
@mwrock what version of Windows were you creating?

**Comment by fnichol** [comment]
Also, is there I way I could run the same cookbook to repro?

**Comment by mwrock** [comment]
The cookbook is here: https://github.com/mwrock/chef-minecraft/tree/windows and the .kitchen-vagrant.yml file includes a box url to my win 2012R2 virtual box box that i am using. You will need to add `communicator: winrm` and keep the `transport: winrm` in the file. I had to do that on my linux machine. You might also need to manually change the generated kitchen state file and set the port to 55985. Thats another issue that I need to investigate further.

The problem occurs before he zips are transferred. I think the hot spot is somewhere in here:

```
        def produce_zip_entries(zos)
          entries.each do |entry|
            entry_path = entry.sub("#{dir_strip}/", "")
            debug { "+++ Adding #{entry_path}" }
            zos.put_next_entry(entry_path, nil, nil, method, compression)
            entry.open("rb") { |src| IO.copy_stream(src, zos) }
          end
          debug { "=== All files added." }
        end

        # Writes out a temporary Zip file.
        #
        # @api private
        def write_zip
          debug { "Populating files" }
          Zip::OutputStream.write_buffer(NoDupIO.new(zip_io)) do |zos|
            produce_zip_entries(zos)
          end
        end
```

So I think the only way to reproduce is to do this on a windows host. I was gonna try to extract this t oa small test program so it can be reproduced in a windows VM.

**Comment by fnichol** [comment]
@mwrock ah, running `kitchen` on a Windows workstation could be related here, something I haven't done enough direct testing with.

The good news is that you can test this part in isolation with pry (or irb), by calling `Kitchen::Transport::Winrm::TmpZip` directly (from the test-kitchen project root):

```
> bundle exec pry -Ilib -rkitchen -rkitchen/transport/winrm/tmp_zip
logger = ::Logger.new($stdout)
# zip the kitchen codebase
zip = Kitchen::Transport::Winrm::TmpZip.new(Dir.pwd, logger)
puts "My zipfile is at: #{zip.path}"
# look at it, then cleanup with:
zip.unlink
exit
```

**Comment by mwrock** [comment]
I was able to reproduce a corrupt zip by running this in `irb`:

```
require "kitchen"
require "kitchen/transport/winrm"
Kitchen::Transport::Winrm::TmpZip.new("c:/dev/chef-minecraft/recipes")
```

So if you have a ruby environment on a windows vm, this may result in a corrupt zip.

**Comment by mwrock** [comment]
just found a fix:

```
          @zip_io = Tempfile.open(["tmpzip-", ".zip"]).binmode
```

I'll send a pr

**Comment by mwrock** [comment]
ugh. not so fast. now the unlink fails. well get back to this but its progress.

**Comment by mwrock** [comment]
ok. this should do it.
