### ISSUE TITLE
Set Environment Variables on target machine

### ISSUE THREAD

**Issue by ArjunHariharan** [test-kitchen/test-kitchen#662]
I set the version of my package in .kitchen.yml as shown

```
attributes:
  my_pkg:
    version: '<%= ENV['MY_PKG_VERSION'] %>'
```

During chef-run, a file **/opt/app/<version>.war** is generated.
I want to write some server specs for this file

```
describe file('/opt/app/ENV['VERSION']>.war') do
  (expectations)
end
```

But since the environment variables are not set not the target machine, Servespec is unable to find such a file. Is there a way to set the environment variables on the target machine? If not, what is the ideal approach for such issues?

**Comment by fnichol** [comment]
@ArjunHariharan  Hi there! There isn't currently a way to expose arbitrary environment variables to the Chef Provisioners or Busser (I have some rough thoughts on this but it's parked at the moment), but we could attack this from a different angle. While it's not ideal, you could read the Chef JSON file back into your ServerSpec tests with a:

```ruby
require 'json'

let(:chef_data) { JSON.parse(IO.read("/tmp/kitchen/dna.json")) }

describe file("/opt/app/#{chef_data.fetch("my_pkg").fetch("version)}.war") do
  (expectations)
end
```

(note that the Hash#fetch will help throw a big error if the "my_pkg" or "version" keys aren't found).

Otherwise, is there a way you could inspect the version of the WAR by calling an HTTP endpoint, inspecting a config file, or other side effect?

**Comment by ArjunHariharan** [comment]
@fnichol - Reading Chef JSON as you said is not ideal but a good work around to approach the issue for the time being. I need the version no and few other environment attributes to check the content of the files also (regexp). 
What do you think about having the support to pass environment attributes to provisioner? Do you see any side effects of having such a feature? I feel this feature would be very helpful when you want to test the changes in a rapidly changing development phase.

**Comment by wlawbr** [comment]
Is there any thought to loading the configured attributes (e.g. dna.json) or even pulling in ohai information into testkitchen by default?  This would make a nice addition and get around some of the nasty hacks that are floating around (like a cookbook to dump ohai into a file to be read back into testkitchen).

**Comment by neillturner** [comment]
This would be very useful. In my kitchen-puppet and kitchen-ansible plugins you can get environment variables. If you pull out the code for chef into a kitchen-chef plugin you will be able to innovate ( and screw up -))  much faster than have the code in the core of test-kitchen. -)

**Comment by luckymike** [comment]
Could it at least support a `no_proxy` variable alongside the `http_proxy` and `https_proxy`? Right now additional variables defined in a `.kitchen.local.yml` are silently discarded, which makes for lots of head scratching.
