### ISSUE TITLE
platform centos-6.4, centos-6.5 cannot be downloaded

### ISSUE THREAD

**Issue by lloydde** [test-kitchen/test-kitchen#663]
platform centos-6.4, centos-6.5 cannot be downloaded

`kitchen init` populates `.kitchen.yml` with "centos-6.4"

http://kitchen.ci/ screenshot shows "centos-6.5"

Both of these images are not able to be downloaded.

~~~
$ kitchen verify 64
-----> Starting Kitchen (v1.3.1)
-----> Creating <default-centos-64>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Box 'centos-6.4' could not be found. Attempting to find and install...
           default: Box Provider: virtualbox
           default: Box Version: >= 0==> default: Adding box 'centos-6.4' (v0) for provider: virtualbox
           default: Downloading: centos-6.4
An error occurred while downloading the remote file. The error
       message, if any, is reproduced below. Please fix this error and try
       again.
       
       Couldn't open file /Users/ll/wrk/my-kitchen/.kitchen/kitchen-vagrant/kitchen-my-kitchen-default-centos-64/centos-6.4
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos-6.4' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'centos-6.4' (v0) for provider: virtualbox
    default: Downloading: centos-6.4

STDERR: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/ll/wrk/my-kitchen/.kitchen/kitchen-vagrant/kitchen-my-kitchen-default-centos-64/centos-6.4
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
~~~

ADDITIONAL DETAILS

If I update 6.5 to "chef/centos-6.5" that works, but there is no 6.4 listed at https://atlas.hashicorp.com/chef/ .

When I update it to 7.0, "centos-7.0", I see the URL is https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box

Oh, now, I've found https://github.com/chef/bento#virtualbox and see that 6.6 is the oldest 6.x image.
http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box

![welcome_to_test_kitchen_-_kitchenci_-_centos-6_5](https://cloud.githubusercontent.com/assets/962387/6876517/7510c4d4-d485-11e4-8bb9-e33711b7e88b.png)

This also makes me think that the cucumber tests in features/ have not been run for some time.

**Comment by aaron-lane** [comment]
Just today, I started seeing this same behavior with centos-7.1. It's still listed under VirtualBox on the Bento list, and specifying it as opscode-centos-7.1 works.

**Comment by wayoutmind** [comment]
+1

**Comment by johntdyer** [comment]
A better error message would be nice IMHO..... something along the lines of "hey jerk face, that box no longer exists, you should update your box URL"  ;)

**Comment by lloydde** [comment]
@johntdyer you had me at jerk face.

**Comment by fnichol** [comment]
@lloydde Thank you for resolving this and sorry it took so long. I'll follow this PR up with a further freshening of the platform list so that we can match chef/chef-dk#382.

**Comment by mokhan** [comment]
Is it possible to find a centos-6.4 vagrant box anywhere anymore? Sadly, we have a lot of cookbooks that are written in a way that are dependent on this specific version of CentOS.
