### ISSUE TITLE
Publicly expose winrm session

### ISSUE THREAD

**Issue by mwrock** [test-kitchen/test-kitchen#670]
I'm working on a `kitchen-nodes` provisioner plugin that sits on top of chef-zero and creates minimal node json files containing a test suite's name, IP and runlist. Tt scrapes the state file for IP, but I ran into a scenario with virtualbox/vagrant which only exposes the NAT NIC and thus the IP (127.0.0.1) is not useful. Here I found it useful to interrogate the IPs from inside the test instance to get the one publicly accessible from another instance. To make this work, I had to monkey patch the winrm connection class so I could access the session and the command executor.

I think this would be useful in many plugin/driver scenarios. At least for winrm, stdout gets flushed to tty and I think because of the way kitchen sets up logging, I was not able to hijack `$stdout` which would be a bad solution anyways.

I'll likely submit a PR for this later but wanted to open this issue in case I forget or if anyone thinks this might be a bad idea.

**Comment by fnichol** [comment]
Could you subclass the "chef_zero" Provisioner to have direct access to the connection? Sounds like we could huddle around a laptop next week at ChefConf :smile:

**Comment by mwrock** [comment]
Totally up for pairing. I actually am subclassing chef_zero and calling into the communicator but `execute` which is publicly accesible does not expose a friendly way to parse the stdout returned from the command. However, if the `session` method were public I could then use the much friendlier `run_powershell_script` method.

The class and my monkey patch are here: https://github.com/mwrock/kitchen-nodes/blob/master/lib/kitchen/provisioner/nodes.rb

**Comment by fnichol** [comment]
What if `Transport::Connection#execute` had an optional configuration to return its STDOUT stream rather than streaming to the logger? Or possibly another method all together that was an opt-in implementation for Transport authors?

That was you could rewrite your line as (something like):

```ruby
command = "Get-NetIPConfiguration | % { $_.ipv4address.IPAddress}"
ipaddress = instance.transport.connection(state).execute(command, :capture => true).chomp
```

If we can solve this without exposing the internal implementation details of WinRM (or other Transport internals), we should be better setup to future use cases like this that extend beyond WinRM.

**Comment by mwrock** [comment]
Totally. That would be way better. What if `execute` yielded stdout if given a block?

**Comment by mwrock** [comment]
closing this for now. I ended up monkey patching in my driver which worked fine but I would take this approach if that ever breaks.
