### ISSUE TITLE
avoid forwarding port 22 if a Windows guest?

### ISSUE THREAD

**Issue by juliandunn** [test-kitchen/test-kitchen#676]
I'm not sure if it's just me but the Windows guests I'm testing with 1.4.0.beta.2 still have port 22 forwarded by Test Kitchen. Is this necessary?

```
       ==> default: Fixed port collision for 22 => 2222. Now on port 2201.
       ==> default: Clearing any previously set network interfaces...
<snip>
           default: 22 => 2201 (adapter 1)
```

**Comment by jdmundrawala** [comment]
Does it forward the port if you just run this box with vagrant?
I think that might be set in the Vagrantfile for that box

**Comment by juliandunn** [comment]
Ah, good point, could be a box-cutter-ism

**Comment by fnichol** [comment]
Totally, it's specified in the underlying base box's Vagrantfile template. At the moment, most packer-based templates are still installing via SSH and some keep it around afterwards. Rest assured though, your Windows instances do **not** require SSH running to be Test Kitchen friendly :smile: 

Think we're good to close or would a properly placed sentence in some docs help clear this up?

**Comment by juliandunn** [comment]
Let's just close it then... If it comes up we can refer to this issue. Thanks folks!

**Comment by fnichol** [comment]
Okay!
