### ISSUE TITLE
Feature: 'vagrant reload' for kitchen

### ISSUE THREAD

**Issue by DI-DaveGoodine** [test-kitchen/test-kitchen#678]
Please add a feature to allow kitchen to do a 'vagrant reload', rather than a 'kitchen destroy && kitchen reate'.

This would save a lot of time, especially in cases where network bandwidth is limited, causing chef omnibus and other package downloads to take a long time.

**Comment by sawanoboly** [comment]
Hi,

F.Y.I. We can reload my available vagrant vm directly like below.

```
$ cd .kitchen/kitchen-vagrant/default-ubuntu-1204/   # suite-platform
$ vagrant reload
```

**Comment by DI-DaveGoodine** [comment]
Thank you @sawanoboly - that's a good workaround - I could make the changes to my dynamic Vagrantfile and do a vagrant reload.  

I would like the feature, though, so that the network changes can be made in .kitchen.yaml and then the dynamically generated Vagrantfile would be updated and the reload done, all through a single command, such as "kitchen reload".

**Comment by jlucasps** [comment]
Use the command ````vagrant global-status```` to get the machine id, then use it to reload.
something like:
````bash
$ vagrant global-status
42c66ec  default virtualbox poweroff /path/to/your/machine/kitchen-vagrant/webserver-ubuntu-1404 
1c135ae  default virtualbox running  /path/to/other/machine/.kitchen/kitchen-vagrant/kitchen-machines-webserver-ubuntu-1404
$ vagrant reload 1c135ae
````

**Comment by cheeseplus** [comment]
Closing this issue as this is something that would belong to the https://github.com/test-kitchen/kitchen-vagrant project driver not test-kitchen itself
