### ISSUE TITLE
Can we capture the output message of chef in test-kitchen?

### ISSUE THREAD

**Issue by nogayama** [test-kitchen/test-kitchen#679]
I would like to check and verify the output message of chef with test-kitchen.

For example, when we use a file resource with action=create and path=/tmp/foobar, then chef write "create /tmp/foobar" into stdout. I want to verify this message in rspec/minitest/serverspec.

**Comment by cheeseplus** [comment]
It would be much better to verify this information directly with serverspec or rspec rather than check a log message which doesn't necessarily mean the action happened. This kind of testing is a slippery slope to anti-patterns and not something I'm inclined to support.

**Comment by cheeseplus** [comment]
Closing this as this is a verifier specific feature or something outside kitchen and not something we want to cover in core.
