### ISSUE TITLE
Reference-Style Documentation for Kitchen file

### ISSUE THREAD

**Issue by clintoncwolfe** [test-kitchen/test-kitchen#682]
I often wish I could give someone a URL, or simply browse a page myself, to a _reference_ for the .kitchen.yml .  Not a guide or tutorial, but an exhaustive guide to what options are permitted or expected.

I've been told much of this information is available from 'kitchen diagnose', I'm looking to have it accessible on the web.

Granted, plugins may extend what may be permitted in many places.

**Comment by jtimberman** [comment]
This kind of documentation should definitely go on the [Chef docs](http://docs.chef.io/devkit/kitchen.html#kitchen-yml) site.

**Comment by cheeseplus** [comment]
http://kitchen.ci/docs/kitchen-examples
