### ISSUE TITLE
shell_type 'bourne' assumes that a user's default shell is actually Bourne

### ISSUE THREAD

**Issue by juliandunn** [test-kitchen/test-kitchen#683]
Non-Windows platforms (UNIX, Linux) assume that the kitchen's user actually has a Bourne-compatible shell (`bash`, `sh`, `ksh`) as the default shell. This is not always the case. For example, on FreeBSD, a non-root user's default shell is either `csh` or `tcsh`, even though Bourne shell is always available on the system in `/bin/sh`.

Reading Kitchen's source code, I can see that it assumes that it can simply issue Bourne-style commands like `foo=bar` to set environment variables. Thus, `kitchen` will fail on FreeBSD while attempting to set vars before running Chef's `install.sh`:

```
-----> Converging <default-freebsd-10-1-x64>...
$$$$$$ Running legacy converge for 'Digitalocean' Driver
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       Unmatched '.
       chef_omnibus_root=/opt/chef: Command not found.
       chef_omnibus_url=https://www.chef.io/chef/install.sh: Command not found.
       install_flags=: Command not found.
       pretty_version=always install latest version: Command not found.
       sudo_sh=sudo -E sh: Command not found.
       version=latest: Command not found.
       #: Command not found.
       Badly placed ()'s.
       Ambiguous output redirect.
       then: Command not found.
       return: Command not found.
       else: endif not found.
```

One possible solution is to make a third shell type in `lib/kitchen/configurable.rb`, let's say `c`, and add helper methods like `c_shell?`. That way, in [#shell_var](https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/configurable.rb#L272) we could use `setenv` instead of just blindly doing `a=b` which fails under csh.

Let me know what you think.

**Comment by tyler-ball** [comment]
I'm hoping we don't have to support `c_shell` - the idea with the shell script was to use Bourne if it is available (which is is on FreeBSD, as you point out).  It should be using `/bin/sh` instead of the default shell.

https://github.com/test-kitchen/test-kitchen/blob/adb0eb9733e8af4da412041fd647111ca6778c94/lib/kitchen/util.rb#L115

**Comment by tyler-ball** [comment]
I'm tagging this as 1.4 so we investigate this now, but we may decide to push it to later after investigation.

**Comment by fnichol** [comment]
I've spun up a FreeBSD instance with the Vagrant Driver using our Bento box, and the bourne script seems to be invoking [properly](https://gist.github.com/anonymous/96b711e03eb4b2a4d680#file-kitchen-converge-output-txt-L79-L343).

I'm going to try the Digital Ocean Driver next and see if there's a hidden regression in here somewhere.

**Comment by fnichol** [comment]
After looking at the Digitalocean driver, there's currently a [version pin](https://github.com/test-kitchen/kitchen-digitalocean/blob/dea3810770bdd719a01310c984b8b857cb11248e/kitchen-digitalocean.gemspec#L21) to test-kitchen `"~> 1.2"`.

@juliandunn did you happen to have an existing project I could clone and repro? I'm becoming increasingly convinced that the above behavior is circa Test Kitchen 1.2.x.

**Comment by juliandunn** [comment]
@fnichol Yeah. Check this out: https://github.com/juliandunn/freebsd/tree/freebsd-do-kitchen (that branch)

I was using Test Kitchen 1.4.0.rc.1 on my laptop while attempting to do this.

**Comment by juliandunn** [comment]
@tyler-ball I should point out that the FreeBSD bento boxes are not a good repro case because the vagrant user's shell is [explicitly set up](https://github.com/chef/bento/blob/master/packer/http/freebsd-10.1/install.sh#L91) to use `/bin/sh` due to Vagrantisms

**Comment by fnichol** [comment]
Oh dear, this will involve more work FreeBSD-side. Looks like even interactively, running `/bin/sh` still runs `tcsh` on Digital Ocean droplets:

```
> be kitchen login
$$$$$$ Running legacy login for 'Digitalocean' Driver
FreeBSD 10.1-RELEASE (GENERIC) #0 r274401: Tue Nov 11 21:02:49 UTC 2014

Welcome to FreeBSD!

Release Notes, Errata: https://www.FreeBSD.org/releases/
Security Advisories:   https://www.FreeBSD.org/security/
FreeBSD Handbook:      https://www.FreeBSD.org/handbook/
FreeBSD FAQ:           https://www.FreeBSD.org/faq/
Questions List: https://lists.FreeBSD.org/mailman/listinfo/freebsd-questions/
FreeBSD Forums:        https://forums.FreeBSD.org/

Documents installed with the system are in the /usr/local/share/doc/freebsd/
directory, or can be installed later with:  pkg install en-freebsd-doc
For other languages, replace "en" with a language code like de or fr.

Show the version of FreeBSD installed:  freebsd-version ; uname -a
Please include that output and any error messages when posting questions.
Introduction to manual pages:  man man
FreeBSD directory layout:      man hier

Edit /etc/motd to change this login announcement.
> whoami
freebsd
> echo $SHELL
/bin/tcsh
> sh -c 'echo $SHELL'
/bin/tcsh
> /bin/sh
$ echo $SHELL
/bin/tcsh
$ exit
```

However our Bento boxes use `/bin/sh` as the shell for the vagrant user:

```
> be kitchen login
$$$$$$ Running legacy login for 'Vagrant' Driver
FreeBSD 10.1-RELEASE (GENERIC) #0 r274401: Tue Nov 11 21:02:49 UTC 2014

Welcome to FreeBSD!

Release Notes, Errata: https://www.FreeBSD.org/releases/
Security Advisories:   https://www.FreeBSD.org/security/
FreeBSD Handbook:      https://www.FreeBSD.org/handbook/
FreeBSD FAQ:           https://www.FreeBSD.org/faq/
Questions List: https://lists.FreeBSD.org/mailman/listinfo/freebsd-questions/
FreeBSD Forums:        https://forums.FreeBSD.org/

Documents installed with the system are in the /usr/local/share/doc/freebsd/
directory, or can be installed later with:  pkg install en-freebsd-doc
For other languages, replace "en" with a language code like de or fr.

Show the version of FreeBSD installed:  freebsd-version ; uname -a
Please include that output and any error messages when posting questions.
Introduction to manual pages:  man man
FreeBSD directory layout:      man hier

Edit /etc/motd to change this login announcement.
$ whoami
vagrant
$ echo $SHELL
/bin/sh
$ sh -c 'echo $SHELL'
/bin/sh
$ /bin/sh
$ echo $SHELL
/bin/sh
$ exit
```

I'm going to slide this into the next release and we can figure out what to do (if anything) in Bento to try and harmonize FreeBSD's defaults knowing that we need to also make Vagrant's boot process happy.

Anyway, interesting results… :cry:

**Comment by juliandunn** [comment]
Thanks @fnichol. I think if you run `/bin/sh` on FreeBSD (when the default shell is `tcsh`) actually does get you Bourne shell, it's just that maybe `$SHELL` isn't reset unless it's a login shell? I dunno.

**Comment by RoboticCheese** [comment]
FWIW, I ran into this today and it seems to have to do with tcsh not accepting multi-line commands like Kitchen is using...

```
% sh -c 'echo hi'
hi

% sh -c '
Unmatched '.

% sh -c '\
? echo hi\
? '
hi
```

`Unmatched '.` is also the first line in the Kitchen output when things start going off the rails. If I dump the Chef install script into a file and run it from there instead, it works fine. Presumably escaping the end of each line or making it one giant line with semi-colons would work too.

**Comment by fnichol** [comment]
Thanks @RoboticCheese, that could be the underlying reason. I have one last idea before turning all these commands into a "write a file, then execute" strategy.

Also, I found the following in the [FreeBSD documentation](https://www.freebsd.org/doc/en_US.ISO8859-1/articles/linux-users/shells.html):

> "Instead, FreeBSD uses tcsh(1) as the default root shell, and the Bourne shell-compatible sh(1) as the default user shell."

As I interpret that, we'd normally expect a non-root default shell to be sh, but in Digital Ocean's case, it's really tcsh. Anyway, we'll need to accommodate both in any case.

**Comment by routelastresort** [comment]
Relevant to my interests, as I had to accommodate for the same thing in vagrant-junos (not elegantly).  I want to release a kitchen driver, but this is what I rammed my head against.

**Comment by gregf** [comment]
Were in the process of moving some of our servers to FreeBSD on DigitalOcean and running into this same issue trying to test our cookbooks. Has there been any progress on this?
