### ISSUE TITLE
If Berksfile is present, kitchen never finds Cheffile

### ISSUE THREAD

**Issue by luckymike** [test-kitchen/test-kitchen#686]
On a system with Librarian installed, but no Berkshelf, if a cookbook has both a Berksfile and a Cheffile kitchen will see the Berskfile, attempt to resolve dependencies, and then fail. 

This is especially problematic due to ChefDK, since Berks is rarely included in the Gemfile any longer. 

```
$ be kitchen test service-ubuntu-1204
-----> Starting Kitchen (v1.3.1)
!!!!!! The `berkshelf' gem is missing and must be installed or cannot be properly activated. Run `gem install berkshelf` or add the following to your Gemfile if you are using Bundler: `gem 'berkshelf'`.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Could not load or activate Berkshelf (cannot load such file -- berkshelf)
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

$ ls
Berksfile       CONTRIBUTING.md Gemfile         README.md       attributes      metadata.rb     test
Berksfile.lock  Cheffile        Gemfile.lock    Rakefile        files           recipes
CHANGELOG.md    Cheffile.lock   LICENSE         TESTING.md      libraries       templates

$ cat Gemfile
source 'https://rubygems.org'

gem 'chefspec',   '~> 3.0'
gem 'foodcritic', '~> 3.0'
gem 'rubocop'

group :integration do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'librarian-chef'
end

group :release do
  gem 'emeril'
  gem 'rake'
end
```

**Comment by tyler-ball** [comment]
@fnichol has an idea to introduce a new `resolver` plugin type.  This resolver could be Berkshelf, or Librarian or policy files.  Late loading of these plugins should resolve these load issues, as well as allowing users to specify whether they want to use Berkshelf or Librarian.

I'm marking this as 'later' because we want to finish up the current (1.4) release before tackling new work.

**Comment by luckymike** [comment]
FWIW, if you go a `resolver` plugin route, I think that should be totally open, rather than a supported list.

**Comment by cheeseplus** [comment]
Given that this one is over 2 years old and librarian is effectively no longer maintained closing.
