### ISSUE TITLE
Support `:no_proxy` in Provisioners and Verifiers

### ISSUE THREAD

**Issue by fnichol** [test-kitchen/test-kitchen#687]
This is a matter of symmetry when supporting `http_proxy` and `https_proxy` and is very useful in corporate environments as well as small networks (like my house) where assets might be locally fetched.

**Comment by jmassara** [comment]
What's the status of this? There's also an old PR, #414, that attempts to address this. Would be great to finally have `no_proxy` support included!

**Comment by codereflection** [comment]
+1

**Comment by Maniacal** [comment]
+1

This is very important for us.  Very restrictive corporate environment.

**Comment by acqant** [comment]
+1

**Comment by smurawski** [comment]
As long as the provisioners and verifiers use `wrap_shell_command` for their actions, we make proxy and no_proxy settings available either from the host machine or from configuration.

As of v1.5.0 we've had support for no_proxy, but the latest version have contained a few bug fixes on how those settings were resolved.
