### ISSUE TITLE
Windows guest doesn't update serverspec files

### ISSUE THREAD

**Issue by stonith** [test-kitchen/test-kitchen#693]
Hi,

Using test-kitchen v1.4.0rc1 (windows host/guest), when updating serverspec test files and running `kitchen verify` kitchen doesn't seem to update the files on the guest VM. If the file is removed from the guest and `kitchen verify` is run again, the new file is copied over.

Thanks.

**Comment by DPD-30** [comment]
busser 0.7.1 resolves this. See bug https://github.com/test-kitchen/test-kitchen/issues/684

**Comment by fnichol** [comment]
I believe that Busser [0.7.1](https://github.com/test-kitchen/busser/blob/master/CHANGELOG.md#071--2015-04-20) fixes this issue.

If you're finding that the issue remains can you please reopen? Thanks!
