### ISSUE TITLE
Chef::Log.warn never print out

### ISSUE THREAD

**Issue by chrisduong** [test-kitchen/test-kitchen#694]
Hi,

Please let me have a silly question.
I'm writing a recipe, and I want to print out some messages on terminal during Chef run.
Even though i export KITCHEN_LOG='INFO', the message still not shown up.

```ruby
Chef::Log.warn("never print out")
Chef::Log.info("never print out")
```

The only way I can do is to use `puts` method.
Thanks for reading

**Comment by daxgames** [comment]
I have seen this as well.  The Chef::Log.error alway shows though.

**Comment by mconigliaro** [comment]
Same problem here on 1.4.0 with ChefDK 0.5.1.

**Comment by jkleinlercher** [comment]
I have the same problem - any ideas?

**Comment by LevonBecker** [comment]
I kind of have the same issue. I can't get Log.info to output even with -l info argument.  Debug is a nightmare to filter through. 

The one different is I can get Log.warn to show without giving a log level.

Chef::Log.warn('################################################')   [Works]

When I give it the -l debug such as ```kitchen converge suitename -l debug``` I only get Debug messages... no WARN or INFO.

I also tried this .kitchen.yml setting for the chef_client and it didn't change anything.
https://docs.chef.io/config_yml_kitchen.html 

I'm using Chef_Zero latest client 12.3.x

**Comment by s-bernard** [comment]
I guess I have the same problem. Chef::Log.info is not printed in -l info, only in debug. Warn and error are printed in info but not in warn or error. Debug is OK.

**Comment by zoran** [comment]
same here

**Comment by matthew-churcher** [comment]
:-(

**Comment by cheeseplus** [comment]
Hey folks, this is a dupe of https://github.com/test-kitchen/test-kitchen/issues/694 and I'm closing it so we can keep it focused on one issue.

There is also a PR, #950, that addresses this.

**Comment by scottymarshall** [comment]
This is #694.  Did you mean a different one?

**Comment by cheeseplus** [comment]
Edited for https://github.com/test-kitchen/test-kitchen/issues/529
