### ISSUE TITLE
default-centos-64 is not available

### ISSUE THREAD

**Issue by yohei1126** [test-kitchen/test-kitchen#707]
I am using Chef DK 0.4.0 on MacOSX 10.10.3. I got this message when I run "kitchen create default-centos-64" right after I installed Chef-DK.

default-centos-64 is not available now. The default platforms on .kitchen.yml should be ones on the list here: https://github.com/chef/bento.

```
-----> Creating <default-centos-64>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Box 'centos-6.4' could not be found. Attempting to find and install...
           default: Box Provider: virtualbox
           default: Box Version: >= 0
       ==> default: Adding box 'centos-6.4' (v0) for provider: virtualbox
           default: Downloading: centos-6.4
An error occurred while downloading the remote file. The error
       message, if any, is reproduced below. Please fix this error and try
       again.
       
       Couldn't open file /Users/yohei/work/test-kitchan-sample/.kitchen/kitchen-vagrant/kitchen-test-kitchan-sample-default-centos-64/centos-6.4
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos-6.4' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'centos-6.4' (v0) for provider: virtualbox
    default: Downloading: centos-6.4

STDERR: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/yohei/work/test-kitchan-sample/.kitchen/kitchen-vagrant/kitchen-test-kitchan-sample-default-centos-64/centos-6.4
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1]
```

**Comment by yohei1126** [comment]
centos should be "centos-66" or "centos-71".

**Comment by tyler-ball** [comment]
@yohei1126 Can you update to the latest ChefDK and try this again?  Also, did you run `chef generate` to create a cookbook that you are using `kitchen create` with?

**Comment by tyler-ball** [comment]
If you used `chef generate`, there is a PR for updating this: https://github.com/chef/chef-dk/pull/382

**Comment by tyler-ball** [comment]
@fnichol is also working on an update to the TK code base which will look for bento boxes using a looser algorithm than it is now.  That should help with this specific issue.

**Comment by yohei1126** [comment]
It works with the latest chef-dk. Thanks.

**Comment by rylectro** [comment]
I'm encountering this error still with latest ChefDK, Mac 10.10.5, kitchen 1.4.2.

kitchen converge 65
-----> Starting Kitchen (v1.4.2)
-----> Creating <default-centos-65>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Box 'opscode-centos-6.5' could not be found. Attempting to find and install...
           default: Box Provider: virtualbox
           default: Box Version: >= 0
       ==> default: Box file was not detected as metadata. Adding it directly...
       ==> default: Adding box 'opscode-centos-6.5' (v0) for provider: virtualbox
           default: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
An error occurred while downloading the remote file. The error
       message, if any, is reproduced below. Please fix this error and try
       again.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'opscode-centos-6.5' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'opscode-centos-6.5' (v0) for provider: virtualbox
    default: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

STDERR: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

I have set the variable export DYLD_INSERT_LIBRARIES=

I can wget the file from this location. Any other suggestions?
