### ISSUE TITLE
Override automatic attributes

### ISSUE THREAD

**Issue by dgoradia** [test-kitchen/test-kitchen#713]
I have a recipe that checks the `virtualization` attribute from Ohai. 

```
if node['virtualization'].key?('role') && node['virtualization']['role'] == 'host' && node['virtualization']['system'] == 'kvm'
  package qemu-kvm do
    action :install
  end

  ...
end
```

Now this obviously won't pass in Vagrant so is there a way to mock or override this when verifying using test-kitchen?

**Comment by balajijegan** [comment]
Where you able to find a work around for this?

-balaji

**Comment by dgoradia** [comment]
@balajijegan I took the json output of the hardware/systems that we use to provide the basis of the "mocks". This was back in May so I can't remember the exact resources I consulted but I just found this which pretty much has your answer. 

https://github.com/test-kitchen/test-kitchen/issues/337

**Comment by cheeseplus** [comment]
Closing this one but generally speaking overriding automatic attributes is a slippery slope and something that we'd rather try to avoid with the mocks above as it's clear. We may re-examine this after we split out the chef provisioner into it's own plugin.
