### ISSUE TITLE
TK attempts to download install.sh every converge

### ISSUE THREAD

**Issue by vinyar** [test-kitchen/test-kitchen#714]
__Scenario:__
When a cookbook makes network changes to the DNS/hostname, the subsequent TK converges fail because the node can't find locate www.chef.io/install.sh

__Expectation:__
Since the node is already converged, subsequent converges should not attempt to download and install chef.

**Comment by tfitch** [comment]
@vinyar In the .kitchen.yml file, is the provisioner setup to pull down the `latest` chef-client?  Changing it to `require_chef_omnibus: true` can skip the chef-client install when the client is already there.

Some more info/options are here.  https://docs.chef.io/config_yml_kitchen.html#chef-client-specific-settings

**Comment by cheeseplus** [comment]
As @tfitch points out if you have latest it will always grab latest no matter what - setting it to true or a version should not result in an error.

**Comment by vinyar** [comment]
thanks!
