### ISSUE TITLE
run with specific version of the chef-client

### ISSUE THREAD

**Issue by ror6ax** [test-kitchen/test-kitchen#715]
Currently latest version gets pulled from chef.io

I'd like to test against specific versions available in my production servers.

Maybe can be coupled with option to set download source elsewhere from chef.io, for those behind firewall, etc.

**Comment by nogayama** [comment]
Use `provisoner/require_chef_omnibus` key to specify chef's version.

```
provisioner:
  name: chef_solo
  require_chef_omnibus: "11.16.4"
```

**Comment by fnichol** [comment]
@nogayama You got it! You can also pass partial versions to `:require_chef_omnibus` such as:

* `12` (i.e. the latest version of 12.x.x)
* `11.16` (i.e. the latest patch release of 11.16.x)

@ror6ax Does this help with the first part of your comment?

**Comment by walterdolce** [comment]
Being able to run specific versions of Chef is great :+1:
Maybe this could be added to the documentation somewhere so that people are aware of this feature straight away?

**Comment by tyler-ball** [comment]
I'm going to mark this as a documentation issue - https://docs.chef.io/config_yml_kitchen.html should be updated to explain about using `11` or `11.18`.

**Comment by walterdolce** [comment]
@tyler-ball 
Maybe I was wrong, from the page above, on the Provisioner Settings near the `require_chef_omnibus` option:
> Use to install the latest version of the chef-client in a node. Set to true to install the latest version, false to not install chef-client (assumes the box already has it installed), or a version specifier like 11.8.0 to install a particular version. When set to true or a version number, the chef_omnibus_url may be used to specify the URL of the install.sh that installs the specified version of chef-client. Default value: false.

**Comment by tyler-ball** [comment]
@walterdolce that helps some, but its not complete so I'm leaving this bug open until we finish it

**Comment by walterdolce** [comment]
:+1:

**Comment by cheeseplus** [comment]
This was fixed in docs a bit ago.
