### ISSUE TITLE
kitchen exec fails to show text content without linebreak

### ISSUE THREAD

**Issue by nogayama** [test-kitchen/test-kitchen#717]
When I tried to see a file content in vagrant box, I faced this issue.

To reproduce, first we just make a file which end with ASCII character not line break.

```
$ kitchen login default
   > echo -n "hello" > /tmp/bar
   > exit
```

Then print it with "exec" command.
```
$ kitchen exec default -c "cat /tmp/bar"
-----> Execute command on default-centos65.
$
```

After several trial and error, I finally found that the following command works.
```
$ kitchen exec default -c "cat /tmp/bar; echo"
-----> Execute command on default-centos65.
hello
$
```

That is, the kitchen exec does not show an ASCII character only String to console. I guess this is not intended behavior.

**Comment by sawanoboly** [comment]
I don't think that data transferring between host and vm via stdout is better way.

Having said that, it seems kitchen-logger's bug that ignoring last line of output without line break. I'll try fix it.

**Comment by nogayama** [comment]
Thanks @sawanoboly.

I also agree with that using this to transfer file is not the correct way. But we are usually recording stdout to save the result of command execution. So I hope this will be fixed near future because `kitchen exec` is very useful and adds significant flexibility to test-kitchen.
