### ISSUE TITLE
expose trusted_certs_dir

### ISSUE THREAD

**Issue by acqant** [test-kitchen/test-kitchen#727]
Any resource that requires intermediate SSL certs fail with test-kitchen unless trusted_certs_dir is exposed and certs are installed.

Long discussion around this issue over here:
https://github.com/opscode-cookbooks/chef-client/pull/187#issuecomment-105679538
@danielsdeleo said it best, " I definitely think we may have forgotten to add trusted certs support to kitchen...."

**Comment by bcg62** [comment]
+1 - has anyone looked at this?

**Comment by cheeseplus** [comment]
Not until just now but we're slowly triaging the lot of issues anyway so no better time than the present. If I can get an easily testable validation (and even better a PR) this would greatly speed up efforts.

**Comment by bcg62** [comment]
thanks, maybe I can try to take a look.

My issue specifically isn't an intermediate cert but a corporate network that does ssl inspection. I need a way to move our CA into the test instance outside of chef.

**Comment by bcg62** [comment]
Came across this which helps get the system CA in a good state 
https://github.com/williambailey/vagrant-ca-certificates 

This doesn't help chef as it uses its own embedded bundle.

It would be ideal if test kitchen could operate the same way knife bootstrap supports copying trusted_certs prior to converging. I have my own cookbooks to configure systemwide proxies and root certs. Bit of a chicken and the egg issue as they cant run until the cert is in place.

**Comment by scottvidmar** [comment]
+1 on this one. Internal CA's are pretty common around the industry, and it would be good to support them in a bit easier method.
