### ISSUE TITLE
Possible bug in Getting Started Guide: 'could not settle on compression_client algorithm'

### ISSUE THREAD

**Issue by tjlahr** [test-kitchen/test-kitchen#729]
I'm following the instructions in [Getting Started Guide: Creating a Cookbook](http://kitchen.ci/docs/getting-started/creating-cookbook) and am getting errors while running ```kitchen create default-ubuntu-1204```, I receive the following error:

```
-----> Starting Kitchen (v1.4.0)
-----> Creating <default-ubuntu-1204>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: VirtualBox VM is already running.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [could not settle on compression_client algorithm]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I'm not sure what's happening exactly, but it seems that the guest machine isn't ready to use zlib compression on incoming ssh connections out of the box. When I changed the default compression from "zlib" to "none" in kitchen/transport/ssh.rb:55, the problem went away.

Since this is so early in the tutorial, and test-kitchen manages the setup of the vagrant guest, I'm assuming this is either a default configuration error, or there's a missing step in the guide.

**Comment by nictrix** [comment]
I ran into this problem on a new install of yosemite, I uninstalled all test kitchen gems, I had test-kitchen, kitchen-docker and kitchen-vagrant (`gem uninstall test-kitchen`). Then did a `brew install zlib`, then reinstall the test kitchen gems, `gem install test-kitchen`.  Once that was done I was able to run `kitchen setup` successfully

**Comment by DanielRedOak** [comment]
Having the same issue, for now I added the following to my .kitchen.yml

transport:
  compression: none

**Comment by geek4good** [comment]
Same here. Running without compression for now. Thanks @DanielRedOak!

**Comment by rlanore** [comment]
Same problem for me today to fix

```
gem list |grep net-ssh 
net-ssh (2.10.0.beta2)
```
```
gem uninstall net-ssh
gem install net-ssh -v 2.9.1
```

**Comment by coderanger** [comment]
For others finding this issue via Google, net-ssh released 2.10.0 today which is breaking for me at least. Still investigating if there is a better solution than globally disabling compression.

**Comment by nayena** [comment]
@coderanger I am seeing the same issue. I have forced usage of 2.9.1 and it is working for me

**Comment by coderanger** [comment]
The relevant commit is https://github.com/net-ssh/net-ssh/commit/c189f3e24f31393dc23edfae6320b1d4c2e47e2a

I'm guessing this means compression hasn't been working the whole time and we just didn't notice.

**Comment by coderanger** [comment]
Sigh, so the issue is that the correct compression mode is actually `"zlib@openssh.com"`. Pull request incoming.
