### ISSUE TITLE
'kitchen init' should create a chefignore file

### ISSUE THREAD

**Issue by tyler-ball** [test-kitchen/test-kitchen#732]
Reference: https://github.com/test-kitchen/test-kitchen/issues/699

Windows users run into issues when Berkshelf tries to inspect files in the `.kitchen` folder and it has suuuuuuper long paths.  This is fixed by adding a `chefignore` file that tells it to ignore the `.kitchen` folder because berkshelf will respect that.

Also update the `chef generate cookbook` command to add `.kitchen` to the list of ignored files.

There is a bigger issue here that we're going to have to continue updating the `chefignore` file as more utilities add extra folders to the cookbook directory.  As bonus points, create an RFC to start managing cookbook contents either 1) the same way the server does or 2) the way a gemspec file does.

**Comment by metadave** [comment]
The Chef client looks like it already generates a correct chefignore file with .kitchen: https://github.com/chef/chef-dk/blob/master/lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb#L21
https://github.com/chef/chef-dk/blob/master/lib/chef-dk/skeletons/code_generator/files/default/chefignore#L56

**Comment by tyler-ball** [comment]
Sweet, thanks @metadave
