### ISSUE TITLE
not able to force chef-client in local model even my .kitchen.yml said so. 

### ISSUE THREAD

**Issue by ellenshen** [test-kitchen/test-kitchen#739]
In the kitchen.yml, I specified that I use chef_zero, 
but when i do "kitchen converge instance", it failed because 
sudo -E /opt/chefdk/embedded/bin/ruby /tmp/kitchen/chef-client-zero.rb didn't start with option -z,  
if I login into instance and  manually run chef-client-zero.rb with  flag -z along with all other args, it works fine. 
how to enforce -z flag? 

#1 kitchen file 
Kitchen.yml file: 
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk
  require_chef_omnibus: 0.5.0

#2 run kitchen converge $instance
>>>>>> Converge failed on instance <default-oel-65>.
>>>>>> Please see .kitchen/logs/default-oel-65.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

CHEF_REPO_PATH="/tmp/kitchen"; export CHEF_REPO_PATH
GEM_HOME="/tmp/kitchen/chef-client-zero-gems"; export GEM_HOME
GEM_PATH="/tmp/kitchen/chef-client-zero-gems"; export GEM_PATH
GEM_CACHE="/tmp/kitchen/chef-client-zero-gems/cache"; export GEM_CACHE

sudo -E /opt/chefdk/embedded/bin/ruby /tmp/kitchen/chef-client-zero.rb --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json

**Comment by ellenshen** [comment]
in the vagrant,here is all the chef_zero.rb 
seems I have multiple test-kitchen, 1&2 are same, 3,4,5 are same. 
1./opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef_zero.rb
2./root/.chefdk/gem/ruby/2.1.0/gems/chef-zero-1.7.3/lib/chef_zero.rb
3./opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-1.5.6/lib/chef_zero.rb
4./opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.2.1/lib/chef_zero.rb
5. /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/provisioner/chef_zero.rb

**Comment by ellenshen** [comment]
seems that I should set 
require_chef_omnibus: true this will make the chef-client into the modern mode, therefore the local mode is supported. 
its strange that with 0.5.0, the chef-client is already latest mode supports local mode

**Comment by rmoriz** [comment]
- Why do you want to use chefdk inside the virtual machine?
- Please use markdown to format your issues https://guides.github.com/features/mastering-markdown/#syntax

**Comment by cheeseplus** [comment]
Given the confusion about the bits I'm not entirely sure this is even an issue. Please open a new issue with specifics if you're still having problems.
