### ISSUE TITLE
msiexec was not successful

### ISSUE THREAD

**Issue by asanramon** [test-kitchen/test-kitchen#742]
Hello,
I am having a problem converging. I created my own Windows 2008 R2 vagrant box. When I use this box in test-kitchen I get the error below. If I kitchen login, run powershell and execute '$p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i C:\Users\vagrant\AppData\Local\Temp\chef-true.msi" -Passthru -Wait' as vagrant user, $p.ExitCode is 0. What am I missing in my vagrant box?

Thanks,

Angelo

-----> Installing Chef Omnibus (install only if missing)
       Downloading package from https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-client-12.3.0-1.msi
       Download complete.
       Successfully verified C:\Users\vagrant\AppData\Local\Temp\chef-true.msi
       
       Installing Chef Omnibus package C:\Users\vagrant\AppData\Local\Temp\chef-true.msi
$$$$$$ msiexec was not successful. Received exit code
$$$$$$ At line:53 char:28
$$$$$$ +   if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit
$$$$$$ code ...
$$$$$$ +
$$$$$$ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : OperationStopped: (msiexec was not...ived exit c
$$$$$$    ode :String) [], RuntimeException
$$$$$$     + FullyQualifiedErrorId : msiexec was not successful. Received exit code
>>>>>> Converge failed on instance <default-windows-2k8r2>.
>>>>>> Please see .kitchen/logs/default-windows-2k8r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=latest"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-true.msi"
$pretty_version = "install only if missing"
$version = "true"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }

  Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
  Catch { $chef_version = "" }

  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}

Function Get-ChefMetadata($url) {
  Try { $response = ($c = Make-WebClient).DownloadString($url) }
  Finally { if ($c -ne $null) { $c.Dispose() } }

  $md = ConvertFrom-StringData $response.Replace("`t", "=")
  return @($md.url, $md.md5)
}

Function Get-MD5Sum($src) {
  Try {
    $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
  } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
}

Function Download-Chef($md_url, $dst) {
  $url, $md5 = Get-ChefMetadata $md_url

  Try {
    Log "Downloading package from $url"
    ($c = Make-WebClient).DownloadFile($url, $dst)
    Log "Download complete."
  } Finally { if ($c -ne $null) { $c.Dispose() } }

  if (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
  else { throw "MD5 for $dst $dmd5 does not match $md5" }
}

Function Install-Chef($msi) {
  Log "Installing Chef Omnibus package $msi"
  $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait

  if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }

  Remove-Item $msi -Force
  Log "Installation complete"
}

Function Log($m) { Write-Host "       $m`n" }

Function Make-WebClient {
  $proxy = New-Object -TypeName System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $client = New-Object -TypeName System.Net.WebClient
  $client.Proxy = $proxy
  return $client
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

$chef_omnibus_root = Unresolve-Path $chef_omnibus_root
$msi = Unresolve-Path $msi

if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
]
>>>>>> ----------------------

**Comment by zl4bv** [comment]
Seeing the exact same issue on Windows Server 2012 R2 with kitchen-ec2.

Build log when executed in CI: https://travis-ci.org/zl4bv/test-kitchen-examples/builds/68104440
Kitchen diagnose when replicated locally: https://gist.github.com/zl4bv/1516a7ffe727a0d38418

Strangely when I copy the PowerShell script from the error output and run it locally on the same EC2 instance it works fine.

**Comment by kbvincent** [comment]
@asanramon did you ever find a resolution to this issue?  I am having the exact same thing happen.

**Comment by smurawski** [comment]
@asanramon @zl4bv @kbvincent What versions of test-kitchen are you using?

**Comment by kbvincent** [comment]
Personally I am using: `v1.4.0`

From Chef Support:
> After some more digging I've found this: https://github.com/chef/chef-provisioning/pull/410#issuecomment-130450745

> Looks like there's a memory issue with powershell 3: http://webcache.googleusercontent.com/search?q=cache:UmawClMkuEgJ:stevenmurawski.com/powershell/2015/5/powershell-3-winrm-maxmemorypershellmb-is-wrong+&cd=1&hl=en&ct=clnk&gl=us

> After updating the 2008r2 box to use powershell 4, things were working again just fine.

> Will this work out for you? If upgrading powershell (or applying the hotfix) isn't feasible, it looks like there is still development related to this (see the last comment on that issue)

> -Josh

**Comment by smurawski** [comment]
@kbvincent what is the OS of the system under test?  What is the PowerShell version of that box?  And what are the winrm settings?

**Comment by kbvincent** [comment]
Windows2008r2, Powershell 3, WinRm Configuration per userdata below:

```
<powershell>

winrm quickconfig -q
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'
winrm set winrm/config '@{MaxTimeoutms="1800000"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
winrm set winrm/config/service/auth '@{Basic="true"}'

netsh advfirewall firewall add rule name="WinRM 5985" protocol=TCP dir=in localport=5985 action=allow
netsh advfirewall firewall add rule name="WinRM 5986" protocol=TCP dir=in localport=5986 action=allow

net stop winrm
sc config winrm start=auto
net start winrm

</powershell>
```

**Comment by smurawski** [comment]
@kbvincent You are likely hitting a memory limit in the WinRM process.  ```winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'``` is an antiquated value.  The default for PowerShell 3 is 1024 - though the bug referenced for PowerShell 3 means that setting is ignored and treated as 300 regardless of how high it is set unless you have a hotfix applied (which you have to request from MS).

**Comment by smurawski** [comment]
@kbvincent The only workarounds are to upgrade the WMF version on the client or apply the patch (and reset the MaxMemoryPerShellMB to 1024).

**Comment by cheeseplus** [comment]
Closing this as @smurawski has provided the solution :confetti_ball:
