### ISSUE TITLE
verify should display a warning when there are no tests

### ISSUE THREAD

**Issue by coderanger** [test-kitchen/test-kitchen#745]
If running the verify command directly (i.e. not via `kitchen test`), a warning should probably get shown if there are no tests. This would help with the common case of users not understanding how to lay out their test files, getting the folder hierarchy wrong, etc.

**Comment by nogayama** [comment]
I agree. Currently test just ignore verifications if the directory does not exist. Developer should be informed of missing test.

**Comment by rmoriz** [comment]
+1

It really bit me when I've upgraded our in-house cookbooks from chef 11 to chef 12: I changed the suite name from "default" to "default-chef11" and silenty the serverspec tests were not executed anymore, because of the implicit mapping of suite-name and directory name.

**Comment by cheeseplus** [comment]
+1 - if someone does a PR I'll review but I'm throwing this on the backlog.

**Comment by giant-atomic-monster** [comment]
+1
