### ISSUE TITLE
encrypted_data_bag_secret_key_path does not fully work with Chef 12.x

### ISSUE THREAD

**Issue by rhass-r7** [test-kitchen/test-kitchen#751]
Chef::Config[:encrypted_data_bag_secret] was deprecated in 12.x in favor of knife[:secret] and knife[:secret_file] -- as a result, the key is dropped onto the system by TK but it does not actually use the key.

This may be a misunderstanding on my part of how this should function with Chef 12, and if so, feel free to close this issue.

**Comment by rmoriz** [comment]
maybe related: https://github.com/test-kitchen/test-kitchen/issues/614

**Comment by cheeseplus** [comment]
Is this still an issue?

**Comment by rhass-r7** [comment]
I haven't encountered this issue in a while, so I suspect it may be resolved. Nevertheless, I will attempt to reproduce the issue in a test cookbook.

**Comment by rhass-r7** [comment]
This appears to be resolved with Kitchen 1.4.2 and Chef 12.6.0.

Here is the cookbook I created to validate this if you want to look:  
https://github.com/rhass/kitchen-issue-751
