### ISSUE TITLE
provisioner.calculate_path should fallback to :kitchen_root rather than PWD ?

### ISSUE THREAD

**Issue by jujugrrr** [test-kitchen/test-kitchen#755]
Hi,
I had an issue where `data_bags` couldn't be found because I was not running kitchen from my cookbook (I run multiple Kitchen from a Rakefile ) . Even if I specified a correct `:kitchen_root`, `calculate_path` fell back to `Dir.pwd` https://github.com/test-kitchen/test-kitchen/blob/v1.4.1/lib/kitchen/configurable.rb#L105.

Would it be better to fallback to `:kitchen_root` ?

https://github.com/test-kitchen/test-kitchen/blob/e89bf81d78b2f673bd8baac2926040adf8c04c6a/lib/kitchen/config.rb#L52-L54

**Comment by cheeseplus** [comment]
I think you're probably right here - is this still a present issue? If you could provider a PR that would be fantastic but we'll still add it to the backlog.
