### ISSUE TITLE
Error if ssh_key does not exist

### ISSUE THREAD

**Issue by tyler-ball** [test-kitchen/test-kitchen#757]
Original issue - https://github.com/test-kitchen/kitchen-ec2/issues/155

It would be nice if Test Kitchen would error when the `ssh_key` file doesn't actually exist.  Instead, it just tries to perform SSH auth (which will always fail).

``` yaml
transport:
  ssh_key: c:/dev/local-preprod-keypair-does-not-exist.pem
```

\cc @huntertj

**Comment by hunterj** [comment]
@tyler-ball, I think you meant to cc @huntertj

**Comment by tyler-ball** [comment]
@hunterj Thanks :smile:

**Comment by vinyar** [comment]
+1 I want this!!!
