### ISSUE TITLE
Kitchen init -D won't accept nil

### ISSUE THREAD

**Issue by tyler-ball** [test-kitchen/test-kitchen#764]
When running `kitchen init` the `-D` flag can supposedly [be set to nil](https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/generator/init.rb#L234) to prevent installing a gem, but I cannot make this work.  Passing `-D=` sets it to `[""]` which fails both the nil and empty array checks.

Lets fix this so `kitchen init` can be setup to not install drivers.

This may be another issue, but if the driver is already installed and there is no `Gemfile` present, Test Kitchen will keep trying to install the driver.  It should not install the driver if it is already present.

**Comment by tas50** [comment]
I'm going to close this one out as a wont-fix. Kitchen init is not really our target path for setting up new kitchen installs in 2021 and the current state of things is functional for nearly all users.
