### ISSUE TITLE
Can we get log level of kitchen from test code?

### ISSUE THREAD

**Issue by nogayama** [test-kitchen/test-kitchen#766]
Hi 

If code to extract the actual value from the system needs several steps, we usually want to see variables in each step. Fortunately we can set log level to kitchen by using ENV['KITCHEN_LOG'] or --log_level option. I think we should reuse this configuration in test code. If we set DEBUG to kitchen, then simply the log level of test code should be DEBUG.

I tried this below but it did not work because the ENV['KITCHEN_LOG'] is not copied from host to box. 

test/integration/default/serverspec/localhost/default_spec.rb

```
require 'logger'
LOGGER ||= Logger.new(STDERR)
log_level_str = ENV['KITCHEN_LOG']
LOGGER.level = Logger.const_get(log_level_str.upcase) rescue Logger::WARN

describe "foo" do
  it "bar" do

    if LOGGER.debug?
      LOGGER.debug "print debug message here."
    end

  end
end
```

Do you know how to transfer the log level of kitchen into box?

**Comment by cheeseplus** [comment]
I don't really think checking for the environmental variable like that is good practice (it's brittle and shouldn't be something tested) but I could support passing the environmental variable through if there was a PR for it.

**Comment by cheeseplus** [comment]
Given the lack of response or traction here, closing as this isn't something we intend to support unless a convincing PR came our way.
