### ISSUE TITLE
Rename `chef_zero` Provisioner to (something like) `chef_client_local_mode`

### ISSUE THREAD

**Issue by fnichol** [test-kitchen/test-kitchen#772]
Also worth considering is to make this Provisioner the default vs. `chef_solo`.

**Comment by cheeseplus** [comment]
We could add this in a minor and deprecate in a major - also this need to move to an external gem as per https://github.com/test-kitchen/test-kitchen/issues/754

**Comment by tas50** [comment]
Closing in favor of https://github.com/test-kitchen/test-kitchen/issues/1708
