### ISSUE TITLE
Serverspec `command` does not seem to be working... 

### ISSUE THREAD

**Issue by mattjmorrison** [test-kitchen/test-kitchen#773]
Hello Everyone,

I'm not sure what the issue is here and I wasn't sure what the best place to go for help was, so I figured I would start here.

I'm testing some chef recipes with test-kitchen and serverspec and I have two really simple tests that have been working for months that just started breaking this week. 

```ruby
describe command('/var/www/base_virtualenv/bin/python --version') do
  its(:stdout) { should match(/\APython 2.7.6\Z/) }
end
```
and 
```ruby
describe command('apache2ctl configtest') do
  its(:stdout) { should match(/\ASyntax OK\Z/) }
end
```
When I `kitchen login` to the machine and run those exact commands, I get the expected output, which is:
```
└──➤ kitchen login
Welcome to Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)
vagrant@default-ubuntu-1404:~$ /var/www/base_virtualenv/bin/python --version
Python 2.7.6
```
and
```
vagrant@default-ubuntu-1404:~$ apache2ctl configtest
Syntax OK
```
respectively (I also did the same commands as `root` and got the same results), but the tests fail with:
```
         3) Command "/var/www/base_virtualenv/bin/python --version" stdout should match /\APython 2.7.6\Z/
            Failure/Error: its(:stdout) { should match(/\APython 2.7.6\Z/) }
              expected "" to match /\APython 2.7.6\Z/
              Diff:
              @@ -1,2 +1,2 @@
              -/\APython 2.7.6\Z/
              +""
```
and
```
         2) Command "apache2ctl configtest" stdout should match /\ASyntax OK\Z/
            Failure/Error: its(:stdout) { should match(/\ASyntax OK\Z/) }
              expected "" to match /\ASyntax OK\Z/
              Diff:
              @@ -1,2 +1,2 @@
              -/\ASyntax OK\Z/
              +""
```
respectively.

Does anyone have any thoughts or ideas of what to try or where better to go for help?

Thanks!

**Comment by mattjmorrison** [comment]
I should also mention that I have other tests using serverspec's `command` that are working just fine...

This, for example, 
```ruby
describe command('/var/www/test_deploy/current/virtualenv/bin/pip freeze') do
  its(:stdout) { should contain 'Django==1.8' }
end
```
is passing.

**Comment by mehtanidhi0809** [comment]
Hi,

I am facing the same issue for java -version.

Did you get it resolved?

Thanks,
Nidhi

**Comment by mattjmorrison** [comment]
@mehtanidhi0809 Unfortunately, no.

**Comment by Sacsi** [comment]
I ran into the same problem when executing the test on centos 6.5 box after installing openjdk version 1.7.0. 

describe command('java -version') do
  its(:stdout) { should match /1.7.0_85/ }
end

Got error : 

 Failure/Error: its(:stdout) { should match /1.7.0_85/ }
              expected "" to match /1.7.0_85/

After a bit of troubleshooting found that 'java -version' command wasn't actually printing to output handler but it was printing to the error handler. So changing my test with below code gave me a successful test result -

describe command('java -version') do
  its(:stderr) { should match /1.7.0_85/ }
  its(:exit_status) { should eq 0 }
end

I have seen this quite often that some executable's print version to error handler.

Hope it works for you as well!

**Comment by cheeseplus** [comment]
@mattjmorrison like the above comment it's printing to stderr and not stdout hence why it appears to be a blank string. Closing.

**Comment by imechemi** [comment]
I have the same issue. The command gives blank (`expect "" to match 'something'`) message. Sometimes all the tests passes, sometimes one fails, sometimes two or three fails. stderr didn't help as well.

**Comment by cheeseplus** [comment]
@imechemi  Without any further detail this is impossible to troubleshoot - moreover this is not an issue with test-kitchen but one with ServerSpec itself.

**Comment by shunchu** [comment]
This is just how `java -version` [was implemented and will likely never change](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4380614).

[The same thing with Nginx](https://trac.nginx.org/nginx/ticket/592). Quirks of DevOps, I guess.

If you must make everything go to `:stdout` for some reason, the Nginx thread offers a solution which could probably be applied to `java -version` in a similar fashion.
