### ISSUE TITLE
reconverge with test-kitchen

### ISSUE THREAD

**Issue by pantocrator27** [test-kitchen/test-kitchen#780]
Hello.  I have tried to scour the documentation and the internet but could not find my answer.  I apologize in advance if it exists out there ....

I am trying to test to see what happens when I want to re-converge my recipe and instance.  How can I do this with test kitchen?  The best way I can see to do this is to list my recipe twice in .kitchen.yml.

Any thoughts and I appreciate your help in advance!!!

**Comment by CpuID** [comment]
```
kitchen destroy
kitchen converge target
kitchen converge target
```

Will run the converge twice. The first converge should run the create step, then the second converge will use the previously created instance.

**Comment by pantocrator27** [comment]
What about from the perspective of kitchen.yml and a rake task ...

**Comment by CpuID** [comment]
I think what you want is probably something like https://github.com/test-kitchen/test-kitchen/pull/564 - which isn't merged yet (I am actually looking for the same thing).

Previous discussion at https://github.com/test-kitchen/test-kitchen/issues/162

**Comment by pantocrator27** [comment]
Yes.  This is definitely what I was looking for.  My apologies for not seeing this previous in the issues list.  If you want you can either link the issues or just close this one at your discretion.

**Comment by cheeseplus** [comment]
Closing in favor of https://github.com/test-kitchen/test-kitchen/issues/329 and https://github.com/test-kitchen/test-kitchen/pull/564 (lots of dupe requests)
