### ISSUE TITLE
kitchen close (or stop) [INSTANCE|REGEXP|all]

### ISSUE THREAD

**Issue by walterdolce** [test-kitchen/test-kitchen#791]
Hi all. This is more a question (feature request?) rather than an issue.

I'm not sure whether `kitchen` is intended to `create -> converge -> verify -> destroy` only the instances during development, which would explain the absence of the command mentioned above, or if that the `kitchen [close|stop]` command "just slipped through".

Sometimes during development I tend to let the VMs created by test-kitchen live for a while before destroying them. When I do that, they stay up and running and that's not an issue as far as I can tell. 
On the other hand though, I also think that the tool should provide the ability to shut down the VMs created when the user wants to.

What's your opinion about this? Do you see reasons for the `close` or `stop` command to exists at all?

Note that I'm using the word "VM" and not i.e. "container" so there's a certain degree of specificity here (i.e. use of hypervisors).

**Comment by sdarwin** [comment]
+1 for "kitchen halt" or "kitchen stop"

**Comment by nakulpathak3** [comment]
Is anyone working on this?

**Comment by coderanger** [comment]
The fact that kitchen uses VMs at all is a driver implementation detail (and indeed some drivers _don't_ use VMs). Kitchen is also not a general purpose VM management suite. 👎 voting to close this as out of scope.

**Comment by ForestJay** [comment]
I'd like this feature too! If this were to be closed, could we at least discuss the workaround? I presume for a vagrant/virtual box instance people can run vagrant down. Is that accurate?

**Comment by cheeseplus** [comment]
People can run whatever VM tools outside of kitchen they want but that's effectively breaking the model and can cause all sorts of havoc. Kitchen isn't designed or intended for this purpose as mentioned, the workaround is to not use kitchen in as a VM management suite - if the runs are so long or spinning up a VM is that expensive then there are alternate drivers (proxy/ssh/etc) that are far better suited to not managing the creation/destruction.

This is definitely out of scope and anytime we've added a feature along these lines it's bitten us and had to be hastily reverted.
