### ISSUE TITLE
when adding an audit-mode recipe to a test-suite, the kitchen instance never converges

### ISSUE THREAD

**Issue by ricardolupo** [test-kitchen/test-kitchen#794]
Error from the kitchen run:

`>>>>>> Converge failed on instance <default-ubuntu-1404>.`
`>>>>>> Please see .kitchen/logs/default-ubuntu-1404.log for more details`
`>>>>>> ------Exception-------`
`>>>>>> Class: Kitchen::ActionFailed`
`>>>>>> Message: SSH exited (1) for command: [sh -c '`

`sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889`
`']`
`>>>>>> ----------------------`
`remrlupo01:audit-demo rlupo$ kitchen list`
`Instance             Driver  Provisioner  Verifier  Transport  Last Action``
`default-ubuntu-1404  Docker  ChefZero     Busser    Ssh        Created``

**Comment by ricardolupo** [comment]
so there's 2 main points with regards to the UX experience here:
1. As a user/developer, I can never get a full converge when there is an audit failure, which means I never run integration testing
2. the `kitchen converge` actually does what it's supposed to do, but the TK run gives a hard error. Since we allowed chef-client 12.4.1 to NOT bomb a converge with a failed audit-mode recipe, we should probably do the same for TK as well.

Note this issue also exists in chef-provisioning, as referenced by:
https://github.com/chef/chef-provisioning/issues/393
https://github.com/chef/chef-provisioning/issues/387

**Comment by cheeseplus** [comment]
+1

**Comment by cheeseplus** [comment]
With audit-mode being deprecated this isn't really an issue anymore.
