### ISSUE TITLE
Uploading Multiple version of Cookbook

### ISSUE THREAD

**Issue by srirammageswaran** [test-kitchen/test-kitchen#797]
Hi ,

I use chef-zero with kitchen. If there any way that chef-zero supports multiple version of cookbooks when used with kitchen. 

Thanks ,
Sriram

**Comment by cheeseplus** [comment]
It doesn't explicitly prevent it but since you'd only be applying one constraint what does this do for you?

**Comment by cheeseplus** [comment]
Closing this due to lack of response or clarification as to what is trying to be achieved - generally speaking you're not going to be able to make use of multiple versions in a single run so this is moot as an issue.
