### ISSUE TITLE
Appveyor CI not configured correctly

### ISSUE THREAD

**Issue by Annih** [test-kitchen/test-kitchen#803]
Hello

The appveyor CI seems to be incorrectly configured. There are 2 jobs, one for ruby 200 and one for ruby 215.
But appveyor doesn't support ruby 2.1.5 see: http://www.appveyor.com/docs/installed-software#ruby

Because the ruby215 folder does not exists on the builder, it fallback to ruby 1.9.3
https://ci.appveyor.com/project/test-kitchen/test-kitchen/build/master-21/job/0kwx7akxqluw5khh#L13

**Comment by tyler-ball** [comment]
Removed 215 in https://github.com/test-kitchen/test-kitchen/commit/9ac7ac085d6398b496abefe9fa9946b23673b00f
