### ISSUE TITLE
Drop Ruby 1.9 support

### ISSUE THREAD

**Issue by tyler-ball** [test-kitchen/test-kitchen#806]
Then we could merge https://github.com/test-kitchen/test-kitchen/pull/804 and we could use the latest version of net-ssh

Tentatively setting this with milestone 1.5 but it is arguably a 2.0 breaking change.

Opening this so we can discuss it.

**Comment by coderanger** [comment]
Overall :+1:

https://github.com/portertech/kitchen-docker/pull/146 is a related issue for kitchen-docker about what version of Ruby to support. ChefDK does give somewhat of a reasonable expectation.

**Comment by thommay** [comment]
:+1:

**Comment by jeffbyrnes** [comment]
:+1:
