### ISSUE TITLE
Test Kitchen should use omnitruck's -d option by default

### ISSUE THREAD

**Issue by lamont-granquist** [test-kitchen/test-kitchen#809]
The -d option to install.sh sets up a caching directory (something under /tmp/kitchen should get used) so that you can get 'latest' semantics while at the same time not re-pulling down artifacts that you already have on the image.

**Comment by edehde** [comment]
Any update on this?

We are currently using `chef_omnibus_install_options: -d /tmp/vagrant-cache/chef-omnibus` with kitchen-vagrant (and vagrant cachier).

**Comment by afiune** [comment]
We are starting to work on this feature. Stay tuned! 🎉
