### ISSUE TITLE
ability to change location of test/integration/default/

### ISSUE THREAD

**Issue by jcii** [test-kitchen/test-kitchen#814]
Hi,

I am looking for a way to change the location of the test/integration/default. I keep my chefspec tests in spec/unit/, and I want to keep my serverspec tests in spec/integration/. I have my dependencies downloaded into test/integration/* and have it filtered in .gitignore and .rubocup.yml and others.

So...am I using paths incorrectly? does it make sense to want to have my chefspecs and serverspecs in a similar directory tree?

Thanks

-Jimmy

**Comment by KensoDev** [comment]
@jcii you can configure `test_base_path`.

I see this in the `Kitchen::Config` class

```ruby
  @test_base_path = options.fetch(:test_base_path) { default_test_base_path }
```

**Comment by KensoDev** [comment]
Looking deeper into this, it seems that this does not come from the configuration file and you are only able to change this through the `options` being passed in.

**Comment by cheeseplus** [comment]
We've added this option which helps https://github.com/test-kitchen/test-kitchen/pull/857 - closing this out for now but feel free to re-open if the above doesn't address the issue.
