### ISSUE TITLE
Make value for delay configurable in the transport ssh's wait_until_ready method

### ISSUE THREAD

**Issue by tfitch** [test-kitchen/test-kitchen#815]
As a user I want to be able to modify the `delay` in the the ssh transports `wait_until_ready` method.  Currently located here - https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/ssh.rb#L151

One of my customers built a driver for their internal provisioner API for infrastructure.  And that provisioner isn't quite snappy enough to respond in the 
In the ssh transport the `wait_until_ready` method has a value of `delay=3` but it'd be better for some environments if that value could default to 3 but be changed in the kitchen configuration.

It is understood that the `max_wait_until_ready` is already exposed as a setting that can be changed and I asked about that.  But being able to adjust the value of `delay` better meets their needs.

**Comment by haidangwa** [comment]
The line number in question has changed due to updates, but it's now at https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/ssh.rb#L217. We'd really like this to work, as we are seeing a longer need to wait when we are using kitchen-ec2.

**Comment by mlcooper** [comment]
Hi @tas50, @haidangwa and I still have a need for this and it has been opened for quite some time.  We're not sure why the `Accepted` label was removed, but is this something that could be re-accepted and implemented?
