### ISSUE TITLE
Error in test kitchen exits shell

### ISSUE THREAD

**Issue by btomasini** [test-kitchen/test-kitchen#822]
I am not sure if this is an issue with test kitchen, but figured this would be a good place to start.

When I run test kitchen via bundler in my bash shell under Ubuntu 15.04, if there is any error, the shell exists.  As a consequence, I have to run test kitchen in nested bash shell so that, in the event of an error, I can see the results.

Has anyone seen such a thing?  Where could I start to look to debug the issue?

The only clue that I have is the following output coinciding with the shell exit:

```
zlib(finalizer): the stream was freed prematurely.
```

**Comment by patcon** [comment]
Yep, seeing the same thing with kitchen-digitalocean.

Also, see https://github.com/portertech/kitchen-docker/issues/162

**Comment by coderanger** [comment]
The zlib thing should have nothing to do with this. How are you running Test Kitchen? The only thing I would expect to cause this would be running `exec kitchen ...` when you mean `bundle exec kitchen ...` or similar?

**Comment by patcon** [comment]
Checked back through my history and this wasn't the case, at least for me.

`Gemfile.lock`, in case it's helpful:
https://gist.github.com/patcon/7f6c3a6503bd0d0694f5

**Comment by sh0hin** [comment]
I'm getting this too.

OS X 10.10.1
Chef Development Kit Version: 0.7.0
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.2
Vagrant 1.7.2

Chef Kitchen otherwise appears to exit normally

**Comment by coderanger** [comment]
Reminder: the `zlib(finalizer): the stream was freed prematurely.` warning is not the cause of any errors. If you are seeing that warning, please don't +1 this ticket because it isn't a problem.

**Comment by btomasini** [comment]
Turns out the main issue I was reporting, the shell exiting on error, was simply operator error.  I has sourced a configuration script into my shell which included the following line:

```
set -o errexit
```
The bash shell was doing exactly what I asked it to do, exit on any non-zero result.

I'm closing this.
