### ISSUE TITLE
Output is buffered until the end of the Chef run -> don't see what's going on

### ISSUE THREAD

**Issue by tknerr** [test-kitchen/test-kitchen#826]
Recently noticed that the output of the Chef run is buffered / held back until the run completes or fails, and then the output of the whole convergence phase is flushed at one.

That makes it really hard to see what's going on, especially with larger run lists / more resources in the resource collection.

Sample recipe for repro:

``` ruby
log "let's go!"

execute 'oh wait...' do
  command 'sleep 5'
  action :run
end

log "done!"
```

Now when I run `kitchen converge`, I don't see anything until the end of the run.

To reduce it a bit more to the core of the issue: 

If you trigger the provisioning via kitchen/ssh, it gets buffered:

```
kitchen exec -c 'sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889'
```

If you trigger it via ssh directly, you see the live output as expected:

```
ssh vagrant@localhost -p 2222 'sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889'
```

**Comment by tknerr** [comment]
Thought it was [CHEF-4725](https://tickets.opscode.com/browse/CHEF-4725) first, but actually the issue is in test-kitchen

Might be related to #478

**Comment by cheeseplus** [comment]
Is this still present - I haven't seen this at all so I'm wondering if it's already been resolved by another PR.
