### ISSUE TITLE
Test Kitchen does not detect ports listening to localhost on Windows

### ISSUE THREAD

**Issue by pfaffle** [test-kitchen/test-kitchen#828]
A simple test to check if a port is listening passes on Linux but fails on Windows, if the port is listening to 127.0.0.1 and not a public IP address.

```ruby
describe port(1169) do
  it { should be_listening }
end
```

netstat -an output:
```
C:\Users\vagrant>netstat -an | findstr 1169
  TCP    127.0.0.1:1169         0.0.0.0:0              LISTENING
```

Judging from the debug output, this seems to be because the way it's detected is by enumerating the networking adapters using the Win32_NetworkAdapterConfiguration WMI class and grabbing their IP addresses, but 127.0.0.1 isn't listed as an IP address on any of the adapters on my Windows 7 VM, (or on my host Windows 8.1 system for that matter).

**Comment by cheeseplus** [comment]
This sounds like an issue with Specinfra/Serverspec, not Test Kitchen.

**Comment by pfaffle** [comment]
Aha, thanks. I'll move this over there.
