### ISSUE TITLE
Support for proxying SSH (ProxyCommand)

### ISSUE THREAD

**Issue by iiro** [test-kitchen/test-kitchen#829]
Many of us needs to use a jump box to connect to remote hosts as there might not be VPN access - and using public addressing for just Kitchen does not feel the best.

There is a PR in here: https://github.com/test-kitchen/test-kitchen/pull/426 - not sure though what's the status of it...

**Comment by atheiman** [comment]
@iiro @cheeseplus it looks like this was added in #1091 ?

**Comment by coderanger** [comment]
Yep, this is done via the `ssh_gateway` and `ssh_gateway_user` options. Only works with non-legacy drivers though.
