### ISSUE TITLE
Produce a better error message when the underlying virtualization provider is missing

### ISSUE THREAD

**Issue by tpetchel** [test-kitchen/test-kitchen#831]
A Learn Chef user reported that he did not have VirtualBox installed, but tried commands like `kitchen create` and `kitchen converge` anyway. He reported parser errors while Test Kitchen was reading his `.kitchen.yml` file: 

https://learn.chef.io/local-development/rhel/get-started-with-test-kitchen/#comment-2254294383

This error doesn't point to the problem. My suggestion is to produce a better error message when the underlying virtualization provider is missing.

(I would rank the pri/sev of this issue low. But it might help out new users. I would fix only if it's easy to do so.)

**Comment by cheeseplus** [comment]
The link no longer works and if we take this one up we'll need to do so under kitchen-vagrant specifically and not in core.
