### ISSUE TITLE
Ability to pass commands for execution to kitchen login

### ISSUE THREAD

**Issue by StFS** [test-kitchen/test-kitchen#832]
I'm not sure whether this is possible due to some cross-platform difficulties but I would like to be able to pass commands to run into kitchen login, same as you can do with SSH:

ssh [user@]hostname [command]

The reason I want this is actually pretty silly, I've been having problems with test-kitchen where converging/testing hangs when a cookbook needs to download large files (such as the java cookbook when it downloads the Oracle JDK). The weird thing is that if I do a "kitchen login" into the VM that is hanging, it seems to jumpstart it and the test continues. If I don't do that, I have hit a download time limit and the cookbook test fails.

So my idea was that I could run the test and then in parallell I would run a loop that would do "kitchen login mytest-vm exit" every 60 seconds while the test was running. This would prevent the test from hanging.

**Comment by conorsch** [comment]
Perhaps `kitchen exec <instance> -c uptime` would help, rather than logging in to an interactive session.

**Comment by cheeseplus** [comment]
The answer provided is solid and as described doesn't seem like a feature we need over the provided `kitchen exec`. Feel free to open a new issue or PR if you feel strongly about this feature.
