### ISSUE TITLE
Kitchen : reconverge with another user

### ISSUE THREAD

**Issue by michikhi** [test-kitchen/test-kitchen#840]
Hi All,

I am trying to make a cookbook idempotent. This cookbook installs a package that deactivates all users and creates a new one.
Only the newly created has access to the VM via ssh, and belongs to sudoers group.

In that way, I cannot rerun a kitchen converge of my cookbook. Is it possible to pass a user as an argument ? If not, is there a workaround?

Thx

**Comment by cheeseplus** [comment]
This functionality doesn't exist but closing this in favor of https://github.com/test-kitchen/test-kitchen/issues/329
