### ISSUE TITLE
Reuse tests from dependent cookbooks

### ISSUE THREAD

**Issue by bdrust** [test-kitchen/test-kitchen#843]
I am looking for a way to include tests from a dependent cookbook.  For example, if I have cookbook A that has a set of tests and I have cookbook B that includes cookbook A.  How can I automatically run the tests from cookbook A when I run kitchen verify for Cookbook B?

**Comment by Poohblah** [comment]
@bdrust,

AFAIK there is currently no way to do this that is natively supported by Test Kitchen.  My coworkers & I have been working on developing a way to do this, as we also wish to run tests from multiple cookbooks simultaneously.  However, it's totally non-trivial - for instance, there are a lot of conflicts & contentions when attempting to run multiple sets of "clean-room" tests in the same cleanroom together.

I'd love to hear from the Test Kitchen devs on this subject.

**Comment by neillturner** [comment]
you can create your own busser plugins. take a look at busser-serverspec and then change the command to run the spec test from the dependent cookbooks.
I created one to implement tests in ansible-spec format at https://github.com/neillturner/busser-ansiblespec

**Comment by cheeseplus** [comment]
Closing this as answered - we may revisit this in the future but for now this is the best solution.
