### ISSUE TITLE
How to specify RubyGem source in .kitchen.yml for serverspec gems?

### ISSUE THREAD

**Issue by LevonBecker** [test-kitchen/test-kitchen#844]
How can I specific an internal Ruby gem source for when gems are downloaded with test kitchen? Specifically when the integration test framework gems are downloaded (busser). I'm hoping this is something simple I just haven't found how to do in my searches.  The downloads fail because there is no access to rubygems.org from this environment I'm working in and this client has an internal gem repo I'm supposed to point to.

Thanks,

-=Levon

**Comment by vinayakshinde92** [comment]
Any updates on this? Can anybody answer this question? I am also facing the same problem.

**Comment by MarkGibbons** [comment]
I use a cookbook that configures the root user's .gemrc file.  I add the cookbook to the end of the run list in .kitchen.yml.

**Comment by MarkGibbons** [comment]
See pull request #438 for a code snippet.  I had a pull request to add a solution to test kitchen but I changed my mind.

**Comment by LevonBecker** [comment]
Thanks Mark. I'll use your code logic for now. Hopefully they will add the option.

**Comment by cheeseplus** [comment]
This is a busser issue and being tracked here https://github.com/test-kitchen/busser/issues/18
