### ISSUE TITLE
Ability to set windows login screen resolution

### ISSUE THREAD

**Issue by TemporarilyOffline** [test-kitchen/test-kitchen#849]
It would be great if the `kitchen login` command for my windows instances didn't take over full screen mode on both of my screens.

Ideally I'd like to set the resolution in the .kitchen.yml file or in the .rdp file in the .kitchen folder.

If it makes any difference, I'm running `kitchen login` from my mac to an EC2 instance.

The parameters to add to the .rdp file are:

`desktopwidth:i:1280`
`desktopheight:i:720`

Thanks!

**Comment by cheeseplus** [comment]
This looks like a super easy thing to do and also won't break much outside itself (which is nice). It looks like all the logic is here: https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/winrm.rb#L220-L236

I would want to expose this via configuration options under the transport section. Also it occurs to me that the RDP file is not necessarily bound to WinRM being used and maybe we should abstract that somewhere else in the future.
