### ISSUE TITLE
Appears to freeze on second converge.

### ISSUE THREAD

**Issue by jeffmacdonald** [test-kitchen/test-kitchen#850]
Hi,

I'm running this against Vmware Fusion 8 on a Mac running 10.10. Kitchen 1.4.2

If i do an initial 'kitchen converge' everything works fine. If i do a subsequent converge it freezes. I ran with -l debug and here is where it freezes until i ctrl-c it...

# augment path in an attempt to find a download program
PATH="${PATH}:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/sfw/bin";
export PATH;

main
')
D      [SSH] opening connection to vagrant@172.16.81.133<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"22", :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/jmacdonald/www4.chef/cookbooks/www4/.kitchen/kitchen-vagrant/kitchen-www4-default-ubuntu-1404/.vagrant/machines/default/vmware_fusion/private_key"], :auth_methods=>["publickey"]}>
-----> Chef Omnibus installation detected (install only if missing)
D      [SSH] vagrant@172.16.81.133<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"22", :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/jmacdonald/www4.chef/cookbooks/www4/.kitchen/kitchen-vagrant/kitchen-www4-default-ubuntu-1404/.vagrant/machines/default/vmware_fusion/private_key"], :auth_methods=>["publickey"], :user=>"vagrant"}> (sh -c '

sudo_rm="sudo -E rm"
dirs="/tmp/kitchen/clients /tmp/kitchen/cookbooks /tmp/kitchen/data /tmp/kitchen/data_bags /tmp/kitchen/encrypted_data_bag_secret /tmp/kitchen/environments /tmp/kitchen/roles"
root_path="/tmp/kitchen"

$sudo_rm -rf $dirs
mkdir -p $root_path
')

Unsure of why, etc.. 

Here is my kitchen.yml file

---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04
      box_url: bento/ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[www4::default]
    attributes:

**Comment by jeffmacdonald** [comment]
Totally disregard this. Something in my run_list was preventing this from running. I am including the recipe "sudo" so perhaps I've removed vagrants abilty to sudo without a password.

**Comment by iiro** [comment]
I have had ohai on run list - causing this to happen. Removing it from runlist removes the problem. Might have something to do with Ohai hints - have not debugged what would it really be...

**Comment by cheeseplus** [comment]
This is very likely the sudo issue - just saw this today again in IRC and was reminded that we can close this one out.

**Comment by wiliamsouza** [comment]
This happens cause `vagrant` user are member of `admin` and `sudo` groups and by default sudo cookbook only enable `sysadmin`  group to sudo access. You can fix this using:

```ruby
node.default['authorization']['sudo']['passwordless'] = true                                                                                                               
node.default['authorization']['sudo']['groups'] = [ 'sysadmin', 'admin', 'sudo']                                                                              
include_recipe 'sudo' 
```
