### ISSUE TITLE
Ignore/blacklist files from transfer

### ISSUE THREAD

**Issue by wohlben** [test-kitchen/test-kitchen#852]
the reason seems to be access rights, as it works if i do a 
chmod -R g+w .git/ 

any chance of getting something like a .gitignore file for the converge command, with which anyone could blacklist files/folders from the converge?

**Comment by cheeseplus** [comment]
The `chefignore` file does this. Closing as this is the preferred mechanism but feel free to open a new one if this doesn't work for you.
