### ISSUE TITLE
kitchen converge error

### ISSUE THREAD

**Issue by ddharia1024** [test-kitchen/test-kitchen#853]
While running kitchen converge from chef cookbook, facing below error, not sure what is missing or need to set to make this work.

2015-10-13T15:38:42.407317 #35886] ERROR -- Kitchen: ------Exception-------
E, [2015-10-13T15:38:42.407381 #35886] ERROR -- Kitchen: Class: Kitchen::ClientError
E, [2015-10-13T15:38:42.407408 #35886] ERROR -- Kitchen: Message: Could not load the 'docker' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
E, [2015-10-13T15:38:42.407420 #35886] ERROR -- Kitchen: ---Nested Exception---
E, [2015-10-13T15:38:42.407430 #35886] ERROR -- Kitchen: Class: LoadError
E, [2015-10-13T15:38:42.407449 #35886] ERROR -- Kitchen: Message: cannot load such file -- kitchen/driver/docker
E, [2015-10-13T15:38:42.407458 #35886] ERROR -- Kitchen: ------Backtrace-------
E, [2015-10-13T15:38:42.407467 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver.rb:50:in `rescue in for_plugin'
E, [2015-10-13T15:38:42.407486 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver.rb:40:in `for_plugin'
E, [2015-10-13T15:38:42.407495 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:226:in `new_driver'
E, [2015-10-13T15:38:42.407521 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:239:in `new_instance'
E, [2015-10-13T15:38:42.407530 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:135:in `block in build_instances'
E, [2015-10-13T15:38:42.407540 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:134:in `map'
E, [2015-10-13T15:38:42.407549 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:134:in `with_index'
E, [2015-10-13T15:38:42.407558 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:134:in `build_instances'
E, [2015-10-13T15:38:42.407567 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/config.rb:110:in `instances'
E, [2015-10-13T15:38:42.407576 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:115:in `filtered_instances'
E, [2015-10-13T15:38:42.407588 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:145:in `parse_subcommand'
E, [2015-10-13T15:38:42.407597 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command/list.rb:32:in `call'
E, [2015-10-13T15:38:42.407607 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/cli.rb:56:in `perform'
E, [2015-10-13T15:38:42.407616 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/cli.rb:108:in `list'
E, [2015-10-13T15:38:42.407625 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2015-10-13T15:38:42.407634 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2015-10-13T15:38:42.407643 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/cli.rb:308:in `invoke_task'
E, [2015-10-13T15:38:42.407652 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2015-10-13T15:38:42.407661 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2015-10-13T15:38:42.407670 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/bin/kitchen:13:in `block in <top (required)>'
E, [2015-10-13T15:38:42.407679 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/errors.rb:154:in `with_friendly_errors'
E, [2015-10-13T15:38:42.407699 #35886] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/bin/kitchen:13:in `<top (required)>'
E, [2015-10-13T15:38:42.407708 #35886] ERROR -- Kitchen: /opt/chefdk/bin/kitchen:15:in `load'
E, [2015-10-13T15:38:42.407717 #35886] ERROR -- Kitchen: /opt/chefdk/bin/kitchen:15:in `<main>'
E, [2015-10-13T15:38:42.407725 #35886] ERROR -- Kitchen: ----------------------

--------------

Test Kitchen version 1.4.2
Chef Development Kit Version: 0.7.0
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.2
kitchen-vagrant (0.16.0)

bash-3.2$ echo $PATH
/usr/bin:/opt/vagrant/bin:/usr/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

**Comment by cheeseplus** [comment]
`Could not load the 'docker' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.`

Does the .kitchen.yml include docker?

**Comment by ddharia1024** [comment]
Yes it has docker
---
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1
    driver_config:
     image: artifactory.company.com/centos/kitchen-client
     platform: centos
     require_chef_omnibus: false
     remove_images: true
     memory: 4000000000
     forward:
      - 8080:8080
suites:
  - name: default
    run_list:
      - recipe[ntp::default]

**Comment by cheeseplus** [comment]
You'll need to have https://github.com/portertech/kitchen-docker installed
