### ISSUE TITLE
Errno::ETIMEDOUT needed in winrm transport

### ISSUE THREAD

**Issue by akemner** [test-kitchen/test-kitchen#855]
i can consistently reproduce a connection failure using kitchen-ec2 for win2012r2 standard image_id: ami-c9cea0ac

```
E, [2015-10-16T16:26:27.483915 #4756] ERROR -- default-windows-2012r2: Create failed on instance <default-windows-2012r2>.
E, [2015-10-16T16:26:27.483915 #4756] ERROR -- default-windows-2012r2: ------Exception-------
E, [2015-10-16T16:26:27.484897 #4756] ERROR -- default-windows-2012r2: Class: Errno::ETIMEDOUT
E, [2015-10-16T16:26:27.484897 #4756] ERROR -- default-windows-2012r2: Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) for "10.84.17.179" port 5985 (http://10.84.17.179:5985)
```

Errno::ETIMEDOUT is missing from RESCUE_EXCEPTIONS_ON_ESTABLISH
 https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/winrm.rb#L137 

i also found that the ssh transport already handles this error. https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/ssh.rb#L166

@fnichol @smurawski

**Comment by cheeseplus** [comment]
Seems like this was addressed and the issue just never got closed.
