### ISSUE TITLE
Best Solutions for Referencing Node Data In Test Kitchen Tests?

### ISSUE THREAD

**Issue by jcderose** [test-kitchen/test-kitchen#858]
I'm running serverspec tests on my cookbook (via test kitchen) but I need to reference node attributes in the tests (rather than hard-code the value into the test). What's the best solution for this? I've seen a number of articles and examples over the last few days pointing to Fauxhai, ChefSpec, Minitest, etc. but none seem to allow me to read node attribute values for my test kitchen tests.

Example 1: The `base_port` and `max_port` values are dynamically generated based on the VM's hardware profile, so I can't hard-code these values.
```
($node['base_port']..$node['max_port']).each do |port|
    describe port(port) do
      it { should be_listening.on('127.0.0.1').with('tcp') }
    end
end
```

Example 2: The server key lives in an encrypted data-bag and can't be baked into the test code for the obvious security reasons.
```
crypto = Thumbor::CryptoURL.new $node['thumbor']['key']
encrypted_url = crypto.generate :width => 300, :height => 200, :image => "#{ERB::Util.url_encode(url)}"
request_url = "http://127.0.0.1:9000#{encrypted_url}"
```

**Comment by xmik** [comment]
I use [export-node cookbook](https://github.com/mwrock/export-node) very often. 

### How to
1. Add in Berksfile: `cookbook 'export-node'`
2. Add `"recipe[export-node::default]"` to your runlist in `.kitchen.yml`
3. In `spec_helper.rb` add method:
```
def node
  JSON.parse(IO.read('/tmp/kitchen/chef_node.json'))
end
```
and you can use node atributes in integration tests. Also note, that when you set an attribute in cookbook: `default['my_cookbook']['sth']`, in test code, it will be accessible by: `node['default']['my_cookbook']['sth']`.

**Comment by jcderose** [comment]
Thanks @xmik ! That worked like a charm.

**Comment by cheeseplus** [comment]
Glad you found a solution but I'll also include the reminder that relying on the attributes in an integration test is brittle and in a strict interpretation violates the constraints of an integration test (it should be black box and not know about the inputs). As this is resolved I'm closing.

**Comment by rsjohnso** [comment]
And hard coding values into your test files isn't brittle?  Please, the examples given by the OP are real-world situations where it just isn't possible nor is it valid to hard code or otherwise rely on static inputs.  Allowing for node-specific, run-time input is a much more robust form of testing.  I think the paradigm of black-box testing is flawed and needs to be reevaluated.  But that is obviously beyond the scope of this issue.
