### ISSUE TITLE
Waiting for SSH service on 127.0.0.1:2222, retrying in 3 seconds

### ISSUE THREAD

**Issue by jasonatfleepio** [test-kitchen/test-kitchen#862]
3 commands
> gem install test-kitchen
> kitchen init
> kitchen test

Environment
> Mac El Caption / Vagrant 1.7.4 / vbox 5.0.8r103449 / gem 2.4.8 / ruby 2.0.0p645 / test-kitchen 1.4.2

Then I got only this showing my full screen. 

<img width="794" alt="2015-10-22 22 54 14" src="https://cloud.githubusercontent.com/assets/15030430/10668689/0cf9d1d0-7910-11e5-90f8-7cc6fedfaa27.png">

**Comment by Mierdin** [comment]
What was the resolution for this issue?

**Comment by ctchen** [comment]
AFAIK `.ssh/config` with wildcard settings that caused this issue. FYI
