### ISSUE TITLE
Profiling kitchen runs

### ISSUE THREAD

**Issue by mattkanwisher** [test-kitchen/test-kitchen#863]
We regularly have 30 min runs of kitchen on some of our cookbooks, is there any way to profile this? I see this gem that was abandoned however I'm not sure it would even work in kitchen. https://github.com/joemiller/chef-handler-profiler

**Comment by mwrock** [comment]
One thing you might try is running in debug and looking at the log in your `.kitchen` directory that should have timestamps for each line.

**Comment by smurawski** [comment]
While it doesn't help at the moment, the next version of Chef will have some ruby profiling built in per https://github.com/chef/chef/pull/4034

**Comment by mattkanwisher** [comment]
Not sure if ruby profiling is useful cause most of the time spent will be on the virtual machine not in ruby

**Comment by smurawski** [comment]
@mattkanwisher Sure, if the profiling ran on the client running the cookbook (this isn't profiling of test-kitchen code, but of the chef-client process).

**Comment by cheeseplus** [comment]
Just to close this loop https://github.com/test-kitchen/test-kitchen/pull/901

We are also looking at additional instrumentation as part of a broader vision.

**Comment by cheeseplus** [comment]
At this point we have the --ruby-profiling and https://github.com/poise/poise-profiler to help track down issues with the chef-client runs. Tracking down where _kitchen_ is spending it's time is getting into the weeds of VM/hypervisor/instance management which really is a side affect of how test-kitchen works and far out of scope for general purpose use.
