### ISSUE TITLE
Add `kitchen status` command

### ISSUE THREAD

**Issue by miketheman** [test-kitchen/test-kitchen#87]
kitchen status should be a little more than just the list of instances.

Possibly the creation time/date, any other metadata we have, such as last test status - pass/fail, etc.

**Comment by miketheman** [comment]
@cheeseplus This is an oldie. Is there any new thoughts on this? I'm happy to close, as I've learned to use `list` and `diagnose` by now.

**Comment by jjasghar** [comment]
Maybe alias status to list?
