### ISSUE TITLE
ssh transport needs openssh-clients installed on remote side

### ISSUE THREAD

**Issue by petere** [test-kitchen/test-kitchen#871]
On RHEL-ish platforms, the ssh transport needs the `openssh-clients` installed on the remote side, otherwise the converge fails with an error like this:

```
       ...
       Thank you for installing Chef!
       Transferring files to <default-amazon-201503>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [SCP did not finish successfully (127): ]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

First of all, that error message is super-cryptic, but it seems to be buried in the net-ssh/net-scp packages, so I don't know if test-kitchen can do anything about it. Maybe someone will find this issue report at least.

Then, if I log into the instance and install the `openssh-clients` manually, the converge can proceed.

The kitchen-docker provider addresses this by explicitly running appropriate yum commands before provisioning. But since this issue pertains to the transport, not the provisioner, it seems to me that this should be addressed by test-kitchen proper.

In the short term, is there some kind of hook that one can run between instance creation and provisioning?

**Comment by cheeseplus** [comment]
Is this still occurring? I've not seen this before with any amazon instances of the same age but I think working SSH/WinRM (including that package) is a pre-requisite for TK to function.

**Comment by petere** [comment]
Yes.

Were there any changes made that would address this?

**Comment by cheeseplus** [comment]
There aren't any changes that I am explicitly aware of - do you have an example AMI? 

We do kind if expect a certain minimum of configuration but I'm all for making the failure cleaner if not providing a fix.
