### ISSUE TITLE
kitchen starts linux machine with run level 2 by default

### ISSUE THREAD

**Issue by d4v3y0rk** [test-kitchen/test-kitchen#881]
the default run level of linux server is 3
as referenced [here](http://refspecs.linuxfoundation.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/runlevels.html)
why does test kitchen start linux boxes with the run level of 2?
this hampers testing of auto starting services that start on run level 3

**Comment by cheeseplus** [comment]
@d4v3y0rk test-kitchen just starts up the VMs you tell it to - run levels are still specified at the OS level so not sure _how_ kitchen would have any affect on this.

Also if you could provide some more details (logs, versions, box version, etc) we may be able to further troubleshoot.

**Comment by d4v3y0rk** [comment]
sorry, seems the default run level for the box is 2.
