### ISSUE TITLE
toggling attributes in kitchen.yml

### ISSUE THREAD

**Issue by sdarwin** [test-kitchen/test-kitchen#884]
It would be nice to be able to set attributes in kitchen.yml and then comment them out and "kitchen converge" yet again.   It appears this works with chef-solo, but not chef-zero.

Example kitchen.yml:

suites:  
  - name: default  
    attributes:  
      my_app:  
        variable1: 'a'  
        variable2: 'b'  
		 
run "kitchen converge".   variable1 and variable2 are set.   Then, change kitchen.yml to 

suites:  
  - name: default  
    attributes:  
      my_app:  
        #variable1: 'a'  
        #variable2: 'b'  

run "kitchen converge".  variable1 and variable2 are still set.   Is there a way to manually clear them?     Is this perhaps an expected result, or is it a bug?   

environment: test kitchen 1.4.2 , Windows 10 host, Ubuntu 14 guest vm's , chef_zero provisioner

**Comment by cheeseplus** [comment]
@sdarwin so kitchen sets the attributes at the normal level which means it persists between chef runs so this is expected behaviour.
