### ISSUE TITLE
kitchen init will modify Rakefile and cause RuboCop issues

### ISSUE THREAD

**Issue by kaltokri** [test-kitchen/test-kitchen#915]
If I run kitchen init in a cookbook where a Rakefile already exists some lines are added:

```ruby
begin
  require "kitchen/rake_tasks"
  Kitchen::RakeTasks.new
rescue LoadError
  puts ">>>>> Kitchen gem not loaded, omitting tasks" unless ENV["CI"]
end
```

But RuboCop doesn't like that code:

```
== Rakefile ==
C: 40: 11: Prefer single-quoted strings when you don't need string interpolation or special symbols.
C: 43:  8: Prefer single-quoted strings when you don't need string interpolation or special symbols.
C: 43: 66: Prefer single-quoted strings when you don't need string interpolation or special symbols.
```

Please replace double quotes by single quotes in the generation to create code which is conform to default RuboCop defenitions.

**Comment by cheeseplus** [comment]
Fixed https://github.com/test-kitchen/test-kitchen/commit/17797b7416547149ad7fd983524756ee8aa8dd72

**Comment by kaltokri** [comment]
Nice. Thank you for the fast fix!

**Comment by cheeseplus** [comment]
Thankfully there was already a PR fixing the same issue so very easy :D
