### ISSUE TITLE
Latest build in chef-dk failing in travis

### ISSUE THREAD

**Issue by tas50** [test-kitchen/test-kitchen#918]
I'm seeing this in both the ntp and openssh cookbooks:

0.48s$ KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
-----> Starting Kitchen (v1.5.0)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'ssh' transport from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
The command "KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}" exited with 20.

https://travis-ci.org/gmiranda23/ntp/jobs/103452790

**Comment by cheeseplus** [comment]
How are you getting kitchen 1.5.0? (I ask cause it's not released )

**Comment by tas50** [comment]
It's in ChefDK nightly builds right now.

**Comment by cheeseplus** [comment]
Fixed @919
