### ISSUE TITLE
Kubernetes driver

### ISSUE THREAD

**Issue by azimut** [test-kitchen/test-kitchen#920]
I am new to this tool, so I am not 100% sure if this makes sense. But I think adding a [kubernetes](https://github.com/kubernetes/kubernetes) driver would make a nice feature.

**Comment by smurawski** [comment]
@azimut That's an interesting idea, but would be implemented as a plugin, not as part of the core test-kitchen project.

**Comment by cheeseplus** [comment]
Moreover we don't even have the notion of clusters (multiple machines seeing each other as a cluster) in test-kitchen, thought there is an issue to track the feature so kubernetes is pretty far our of scope at this point.

Doable but a non-trivial task.

**Comment by neillturner** [comment]
I have built kitchen-ansible so it does multiple machine etc by have a 3 machine architecture. 
i suggest you could build something similar for kubernetes. 
basically you have a workstation and a kitchen-kubernetes plugin that installs kubernetes on another machine and then it runs and deploys code on a third and subsequent machine.  

see http://ec2dream.blogspot.co.uk/2015/12/automated-devops-with-test-kitchen.html

**Comment by coderanger** [comment]
This exists now https://github.com/coderanger/kitchen-kubernetes
