### ISSUE TITLE
Test Kitchen 1.5+ is no longer compatible with Chef before 12.5.1

### ISSUE THREAD

**Issue by coderanger** [test-kitchen/test-kitchen#922]
The dependency on `chef-config` blocks using Test Kitchen with older Chef, which makes testing with older Chef more annoying.

My vote is to remove the dependency and make the feature optional. If you have newer Chef you get the proxy loading feature, otherwise you don't.

**Comment by coderanger** [comment]
To narrow things, this only actually breaks with Chef 12.4.x, because earlier Chef doesn't specify it's own chef-config dependency.

**Comment by cheeseplus** [comment]
I think we fixed this?

**Comment by coderanger** [comment]
I think so, via https://github.com/test-kitchen/test-kitchen/pull/924
