### ISSUE TITLE
Shell provisioner fails on Windows host to Linux guest

### ISSUE THREAD

**Issue by b00ga** [test-kitchen/test-kitchen#931]
I have a mixed environment (Linux, Mac, Windows). I've been doing a lot of work with Test Kitchen on Mac and Linux. I'm getting a lot of my developer's on the Test Kitchen bandwagon.

Today I tried testing a basic kitchen config with virtualbox/vagrant/shell provisioner/bats test on a Windows machine to document it for my Windows developers.

The shell provisioner fails with "sudo: /tmp/kitchen/bootstrap.sh: command not found"
Windows7 / VirtualBox 5.0.14 / vagrant 1.8.1 / ruby 2.2.3 / Test Kitchen 1.5.0 running in a Git Bash shell (git version 2.7.0.windows.2). CentOS and Ubuntu LTS platforms from internally maintained vagrant box images. Same .kitchen.yml works fine on RHEL/CentOS & Mac OS X.

After doing some debugging, I've found the issue, but not sure what the right way to fix it is. The underlying issue is that the bootstrap script that is copied into the guest VM has 0644 permissions (no executable bit set).

The code path I'm looking at seems to start in lib/kitchen/provisioner/shell.rb. The host sets up a sandbox of files to copy over to the guest. Looking at the prepare_script() function, the bootstrap script gets copied to the host's sandbox dir and then FileUtils.chmod is called to make sure it is executable (0755). IIUC, FileUtils.chmod doesn't do anything on Windows (my host), so when the script is copied into the Linux guest, there is no Unix executable bit for Net::SCP (who is ultimately doing the copy) to send along with the file. (ls -l /tmp/kitchen/bootstrap.sh inside the guest confirms 0644 permissions).

After a failed converge, if I 'kitchen login' and then 'sudo chmod 755 /tmp/kitchen/bootstrap.sh' and rerun the converge, it succeeds (the scp overwrite the bootstrap, but doesn't change the file mode for what it copies over).

Maybe the chmod can be moved to be executed in the guest? Maybe the bootstrap can explicitly be called as "sh bootstrap.sh"? 

-Shawn

**Comment by b00ga** [comment]
Not sure if the solution is ideal, but I tried changing in provisioner/shell.rb in run_command,
`code = powershell_shell? ? %{& "#{script}"} : sudo(script)`
to
`code = powershell_shell? ? %{& "#{script}"} : sudo("sh #{script}")`
which seems fairly non-intrusive to the code and works on Windows. The caveat is that this does presume that all of your bootstrap scripts are Bourne shell compatible (and will ignore the shebang line at the top of your script).

-Shawn

**Comment by b00ga** [comment]
Sorry, stream of consciousness thinking about this issue....
Maybe make an option for the shell provisioner that is overridable in a .kitchen.yml of which shell to use. Defaults to "sh", but then would allow user's to specify alternative shells (bash, pdksh, dash, zsh, etc). Then the chmod becomes moot and the sudo command is always "#{selected_shell} #{script}"

-Shawn

**Comment by LukeCarrier** [comment]
@b00ga why not simply chmod +x the bootstrap on the guest side, thus allowing the `#!` line to specify the shell?

**Comment by b00ga** [comment]
@LukeCarrier As long as there's a check that the target guest OS is something non-Windows that has chmod, that's probably fine. This is what @ringods did in PR #442 
I implemented this PR basically for two reasons. I thought this might be more flexible and also because in the aforementioned PR, @cheeseplus asked if the bootstrap could be fixed without using a chmod.
I just did an internal training session on my use of test-kitchen in our build system with my users at $WORK a couple of weeks ago (shell provisioner, bats tests) so I'd love to see this get fixed one way or the other for my Windows (host OS) developers.

-Shawn

**Comment by darkn3rd** [comment]
I was able to get around this issue, but manually logging into vagrant system, and setting execute bit on the boostrap script inside the guest, then on the host, run kitchen verify.  What seems unusual, is that sh calls sudo, instead of sudo calling `sh bootstrap.sh`.

**Comment by b00ga** [comment]
With the recent merge, I've closed my referenced PR (#942) and should be able to close referenced PR #442 from @ringods as well.

Thanks!

**Comment by b00ga** [comment]
Oh, and the merge should allow closing of #1413 as well. 

Woot for closing issues/PRs! 👍 

Thanks again.
