### ISSUE TITLE
Kitchen Converge Argument Error

### ISSUE THREAD

**Issue by treyx** [test-kitchen/test-kitchen#940]
I'm running through the [get_started guide](http://kitchen.ci/docs/getting-started/) on the test-kitchen site I keep encountering this issue. I am at [the point](http://kitchen.ci/docs/getting-started/running-converge) where I need to run kitchen converge and I am getting argument errors. 

[Here is the repo](https://github.com/treyx/git-cookbook) with the cookbook I am working with.

Here is the output of `kitchen converge default-ubuntu-1204`
```
-----> Starting Kitchen (v1.5.0)
-----> Converging <default-ubuntu-1204>...
       Preparing files for transfer
       Preparing dna.json
       Preparing current project directory as a cookbook
       Removing non-cookbook files before transfer
       Preparing solo.rb
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [wrong number of arguments (3 for 0..1)]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

[Here is the output](https://gist.github.com/treyx/0a393a59b051cbda8fff) of `kitchen test -l debug`

**Comment by treyx** [comment]
Turns out that I should have been running `chef exec kitchen` instead of just `kitchen`. My mistake. Thanks everyone for the help on IRC / Slack

**Comment by ScriptAutomate** [comment]
I ran into this same issue when executing on my Ubuntu 15.10 host system. In the IRC, I discovered that the documentation is currently being updated.

I was using raw ruby gems, and I found that transitioning over to the ChefDK resolved my issue: https://downloads.chef.io/chef-dk/ubuntu/
