### ISSUE TITLE
Colored output on 4th test suite does not appear in PowerShell

### ISSUE THREAD

**Issue by mprahl** [test-kitchen/test-kitchen#947]
Hello,
When running Test Kitchen tests from PowerShell on my Windows 10 PC, the 4th test suite's colored output, which is purple, does not appear, but the new lines do. Instead of getting the expected output, I just get a console full of blank lines.

Thank you for your help.

**Comment by mwrock** [comment]
:100: While somethings are better left unseen, usually I'm better off being able to see TK output. I know the pain you speak of.

**Comment by cheeseplus** [comment]
Any more detail here? There isn't much to go on as far as a report.

**Comment by PrahlM93** [comment]
Hi @cheeseplus,
So my suites section looks something like this in my .kitchen.yml file:
```
suites:
  - name: kitchenSuiteOne
  - name: kitchenSuiteTwo
  - name: kitchenSuiteThree
  - name: kitchenHyperV
```
All of them work fine when using the command-prompt. The fourth suite, kitchenHyperV, does not display appropriately in PowerShell.

This is fourth test suite in the command-prompt (the converge section with colored output):
![image](https://cloud.githubusercontent.com/assets/11711106/13920070/6b200c72-ef47-11e5-98f6-8a1a750fd064.png)

This is fourth test suite in PowerShell (the converge section with colored output):
![image](https://cloud.githubusercontent.com/assets/11711106/13920248/6680a72a-ef48-11e5-816c-d8724611fa3b.png)

I have tested and the same behavior is present on Windows 7.

**Comment by rdean716** [comment]
I've seen this behavior as well.

**Comment by nhudacin** [comment]
Same here... Always the fourth suite. I'm on Windows 10, powershell v5. @cheeseplus need more info for repro? 

The fourth entry in `kitchen list` while in Powershell (seems it happens on windows 7 & Windows 10) appears blank in the console: 

![image](https://cloud.githubusercontent.com/assets/6682884/17227169/a1be9bc2-54d2-11e6-865c-2dd2459aacb0.png)

Here's the end of output:
![image](https://cloud.githubusercontent.com/assets/6682884/17227181/b40b2ae8-54d2-11e6-84c9-69f820cdcf52.png)

I have to check the .logs/ to see the output.

**Comment by mcascone** [comment]
I am having the exact same issue as well. Always the fourth suite. If I `tee` the output into a file, it outputs to the screen as regular white (or your default color) text.

**Comment by nhudacin** [comment]
Is there a way to change the console color in the .kitchen.yml file?

**Comment by roens** [comment]
While I'm instead using MacOS, I've experienced a variety of color outputs from Kitchen. Some of these colors are barely legible for lack of significant contrast from my nearly black terminal background color. (Dark blue on black) An uncomfortable hack might be to change my terminal settings. A better solution would be to have some way of setting and/or disabling Kitchen's color output.

**Comment by david-in-perth** [comment]
@roens : It turns out that the `--no-color` command-line option was added in v1.9.1 (since this issue was originally created). See #1032.

It's not ideal, but it works.

**Comment by mbaitelman** [comment]
One of the colors here doesnt show on powershell.
https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/color.rb#L34-L37
