### ISSUE TITLE
kitchen converge does not apply template changes

### ISSUE THREAD

**Issue by so0k** [test-kitchen/test-kitchen#948]
Please direct me to the correct way of reporting an issue I'm facing and where I should be posting it, if not here.

my workstation (a VPS) versions:
```bash
Linux 3.13.0
Ubuntu 14.04 x64
Chef Development Kit Version: 0.11.1
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0
# not sure how to show version of kitchen driver
# I installed everything yesterday so it should be the latest one...
kitchen-digitalocean 0.9.3
# cookbook dependencies
depends 'apt', '~> 2.9.2'
depends 'firewall', '~> 2.4.0'
depends 'httpd', '~>0.3.4'
```

I'm going through the https://learn.chef.io/manage-a-web-app/ubuntu/configure-apache/ guide and made some errors in my `templates/default/customers.conf.erb`

`kitchen converge` highlighted these errors, and I modified the template to correct the mistake.

running `kitchen converge` the second time however gives me the same error and when I `kitchen login` and `/etc/apache2-customers/conf-enabled/customers.conf` I notice the template changes are not applied.

If I `kitchen destroy && kitchen converge` it re-creates the droplet and everything works correctly...

Is it normal that changes in templates are not applied?
Is this an issue with the httpd cookbook?

**Comment by cheeseplus** [comment]
Kitchen will upload the changes, what happens in the Chef provisioner is it's own business but I'm betting it's something to do with the recipes/cookbooks themselves.

**Comment by cheeseplus** [comment]
@so0k were you able to resolve this problem? I can't seem to reproduce this issue.

**Comment by cheeseplus** [comment]
Closing this one given the lack of response and also it's very likely a cookbook related issue. If it were an issue of kitchen not uploading changes it'd be fairly significant impact to so many build pipelines we'd definitely have more folks yelling.
