### ISSUE TITLE
Error while executing jinja2 template

### ISSUE THREAD

**Issue by gvenka008c** [test-kitchen/test-kitchen#960]
Hi,

We have all our unusable playbook which runs against openstack dynamic inventory.

I have the below zk.j2 file under templates which gets mesos_masters from dynamic inventory. 

zk://
{%- for host in groups['mesos_masters'] -%}
{{ hostvars[host]['ansible_ssh_host'] }}:2181{% if not loop.last %},{% endif %}
{%- endfor -%}
/mesos

When I run this through test kitchen, i am seeing the below error. 
 TASK: [mesos_slave | update slave to point to zk nodes] ***********************
       <localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1456946091.66-70813072314814 && echo $HOME/.ansible/tmp/ansible-tmp-1456946091.66-70813072314814']
       fatal: [localhost] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'mesos_masters'", 'failed': True}

How can i fix this? Let me know if any details required. Thanks.

Thanks,
Govind

**Comment by cheeseplus** [comment]
Probably want to ask over here https://github.com/neillturner/kitchen-ansible

That's an ansible error in there even though TK is the harness in the example.
