### ISSUE TITLE
Unable to parse WinRM response: No close tag for /HTML

### ISSUE THREAD

**Issue by BenjiZombie** [test-kitchen/test-kitchen#962]
Hi,

Using kitchen v1.6.0 (also tried v1.5.0 and v1.4.1) on Windows 8.1, using vagrant and chef_zero_scheduled_task as a provisionner, I'm facing an error when trying to converge:

       -----> Starting Kitchen (v1.6.0)
       -----> Creating <default-win-2k12r2>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Checking if box 'win-2k12r2' is up to date...
       ==> default: There was a problem while downloading the metadata for your box
       ==> default: to check for updates. This is not an error, since it is usually due
       ==> default: to temporary network problems. This is just a warning. The problem
       ==> default: encountered was:
       ==> default:
       ==> default: The requested URL returned error: 404 Not Found
       ==> default:
       ==> default: If you want to check for box updates, verify your network connection
       ==> default: is valid and try again.
       ==> default: Clearing any previously set forwarded ports...
       ==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 3389 (guest) => 2200 (host) (adapter 1)
           default: 5985 (guest) => 5985 (host) (adapter 1)
           default: 5986 (guest) => 55986 (host) (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: WinRM address: 127.0.0.1:5985
           default: WinRM username: vagrant
           default: WinRM execution_time_limit: PT2H
           default: WinRM transport: plaintext
       An error occurred executing a remote WinRM command.

       Shell: powershell
       Command: $ProgressPreference='SilentlyContinue';
       hostname
       if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
       Message: Unable to parse WinRM response: No close tag for /HTML
       Line: 3
       Position: 81
       Last 80 unconsumed characters:
        (301).

Has anyone encountered this error before? Couldn't find anything on the interwebs...

Thanx

**Comment by smurawski** [comment]
@BenjiZombie Could you provide the result of an kitchen create (that fails) with `kitchen create default-win-2k12r2 -l debug` ?  That should provide more insight into what is happening.  Offhand, it looks to be something vagrant is trying to run, but the debug output should tell more.

**Comment by BenjiZombie** [comment]
Here's the output:

	-----> Starting Kitchen (v1.6.0)
	D      [Vagrant command] BEGIN (vagrant --version)
	D      [Vagrant command] END (0m0.00s)
	D      [Vagrant command] BEGIN (vagrant plugin list)
	D      [Vagrant command] END (0m0.00s)
	D      Berksfile found at C:/Projects/redacted/Berksfile, loading Berkshelf
	D      Berkshelf 4.2.1 library loaded
	D      winrm requested, loading winrm gem (["~> 1.6"])
	D      winrm is loaded.
	D      winrm-fs requested, loading winrm-fs gem (["~> 0.3"])
	D      winrm-fs is loaded.
	D      Berksfile found at C:/Projects/redacted/Berksfile, loading Berkshelf
	D      Berkshelf 4.2.1 previously loaded
	D      winrm requested, loading winrm gem (["~> 1.6"])
	D      winrm was already loaded.
	D      winrm-fs requested, loading winrm-fs gem (["~> 0.3"])
	D      winrm-fs was already loaded.
	-----> Creating <default-win-2k12r2>...
	D      <default-win-2k12r2> is synchronizing on Kitchen::Driver::Vagrant#create
	D      <default-win-2k12r2> is messaging Kitchen::Driver::Vagrant#create
	D      Creating Vagrantfile for <default-win-2k12r2> (C:/Projects/redacted/.kitchen/kitchen-vagrant/kitchen-chef-ju
	st_iis-default-win-2k12r2/Vagrantfile)
	D      ------------
	D      Vagrant.configure("2") do |c|
	D        c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
	D        c.vm.box = "win2k12r2"
	D        c.vm.communicator = "winrm"
	D        c.vm.guest = "windows"
	D        c.vm.synced_folder ".", "/vagrant", disabled: true
	D        c.vm.provider :virtualbox do |p|
	D          p.customize ["modifyvm", :id, "--memory", "3072"]
	D        end
	D      end
	D      ------------
	D      [Vagrant command] BEGIN (vagrant up --no-provision --provider virtualbox)
		   Bringing machine 'default' up with 'virtualbox' provider...
		   ==> default: Importing base box 'win2k12r2'...
	==> default: Matching MAC address for NAT networking...
		   ==> default: Checking if box 'win2k12r2' is up to date...
		   ==> default: There was a problem while downloading the metadata for your box
		   ==> default: to check for updates. This is not an error, since it is usually due
		   ==> default: to temporary network problems. This is just a warning. The problem
		   ==> default: encountered was:
		   ==> default:
		   ==> default: The requested URL returned error: 404 Not Found
		   ==> default:
		   ==> default: If you want to check for box updates, verify your network connection
		   ==> default: is valid and try again.
		   ==> default: Setting the name of the VM: kitchen-redacted-default-win-2k12r2_default_1457106482027_77169
		   ==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
		   ==> default: Clearing any previously set network interfaces...
		   ==> default: Preparing network interfaces based on configuration...
			   default: Adapter 1: nat
		   ==> default: Forwarding ports...
			   default: 3389 (guest) => 2200 (host) (adapter 1)
			   default: 5985 (guest) => 5985 (host) (adapter 1)
			   default: 5986 (guest) => 55986 (host) (adapter 1)
		   ==> default: Running 'pre-boot' VM customizations...
		   ==> default: Booting VM...
		   ==> default: Waiting for machine to boot. This may take a few minutes...
			   default: WinRM address: 127.0.0.1:5985
			   default: WinRM username: vagrant
			   default: WinRM execution_time_limit: PT2H
			   default: WinRM transport: plaintext
		   An error occurred executing a remote WinRM command.

		   Shell: powershell
		   Command: $ProgressPreference='SilentlyContinue';
		   hostname
		   if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
		   Message: Unable to parse WinRM response: No close tag for /HTML
		   Line: 3
		   Position: 81
		   Last 80 unconsumed characters:
			(301).
	D      [Vagrant command] END (0m0.00s)
	>>>>>> ------Exception-------
	>>>>>> Class: Kitchen::ActionFailed
	>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
	---- Begin output of vagrant up --no-provision --provider virtualbox ----
	STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
	==> default: Importing base box 'win2k12r2'...
	==> default: Matching MAC address for NAT networking...
	==> default: Checking if box 'win2k12r2' is up to date...
	==> default: There was a problem while downloading the metadata for your box
	==> default: to check for updates. This is not an error, since it is usually due
	==> default: to temporary network problems. This is just a warning. The problem
	==> default: encountered was:
	==> default:
	==> default: The requested URL returned error: 404 Not Found
	==> default:
	==> default: If you want to check for box updates, verify your network connection
	==> default: is valid and try again.
	==> default: Setting the name of the VM: kitchen-redacted-default-win-2k12r2_default_1457106482027_77169
	==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
	==> default: Clearing any previously set network interfaces...
	==> default: Preparing network interfaces based on configuration...
		default: Adapter 1: nat
	==> default: Forwarding ports...
		default: 3389 (guest) => 2200 (host) (adapter 1)
		default: 5985 (guest) => 5985 (host) (adapter 1)
		default: 5986 (guest) => 55986 (host) (adapter 1)
	==> default: Running 'pre-boot' VM customizations...
	==> default: Booting VM...
	==> default: Waiting for machine to boot. This may take a few minutes...
		default: WinRM address: 127.0.0.1:5985
		default: WinRM username: vagrant
		default: WinRM execution_time_limit: PT2H
		default: WinRM transport: plaintext
	STDERR: An error occurred executing a remote WinRM command.

	Shell: powershell
	Command: $ProgressPreference='SilentlyContinue';
	hostname
	if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
	Message: Unable to parse WinRM response: No close tag for /HTML
	Line: 3
	Position: 81
	Last 80 unconsumed characters:
	 (301).
	---- End output of vagrant up --no-provision --provider virtualbox ----
	Ran vagrant up --no-provision --provider virtualbox returned 1]
	>>>>>> ----------------------
	>>>>>> Please see .kitchen/logs/kitchen.log for more details
	>>>>>> Also try running `kitchen diagnose --all` for configuration

	D      ------Exception-------
	D      Class: Kitchen::ActionFailed
	D      Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
	---- Begin output of vagrant up --no-provision --provider virtualbox ----
	STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
	==> default: Importing base box 'win2k12r2'...
	==> default: Matching MAC address for NAT networking...
	==> default: Checking if box 'win2k12r2' is up to date...
	==> default: There was a problem while downloading the metadata for your box
	==> default: to check for updates. This is not an error, since it is usually due
	==> default: to temporary network problems. This is just a warning. The problem
	==> default: encountered was:
	==> default:
	==> default: The requested URL returned error: 404 Not Found
	==> default:
	==> default: If you want to check for box updates, verify your network connection
	==> default: is valid and try again.
	==> default: Setting the name of the VM: kitchen-redacted-default-win-2k12r2_default_1457106482027_77169
	==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
	==> default: Clearing any previously set network interfaces...
	==> default: Preparing network interfaces based on configuration...
		default: Adapter 1: nat
	==> default: Forwarding ports...
		default: 3389 (guest) => 2200 (host) (adapter 1)
		default: 5985 (guest) => 5985 (host) (adapter 1)
		default: 5986 (guest) => 55986 (host) (adapter 1)
	==> default: Running 'pre-boot' VM customizations...
	==> default: Booting VM...
	==> default: Waiting for machine to boot. This may take a few minutes...
		default: WinRM address: 127.0.0.1:5985
		default: WinRM username: vagrant
		default: WinRM execution_time_limit: PT2H
		default: WinRM transport: plaintext
	STDERR: An error occurred executing a remote WinRM command.

	Shell: powershell
	Command: $ProgressPreference='SilentlyContinue';
	hostname
	if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
	Message: Unable to parse WinRM response: No close tag for /HTML
	Line: 3
	Position: 81
	Last 80 unconsumed characters:
	 (301).
	---- End output of vagrant up --no-provision --provider virtualbox ----
	Ran vagrant up --no-provision --provider virtualbox returned 1]
	D      ---Nested Exception---
	D      Class: Kitchen::ShellOut::ShellCommandFailed
	D      Message: Expected process to exit with [0], but received '1'
	---- Begin output of vagrant up --no-provision --provider virtualbox ----
	STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
	==> default: Importing base box 'win2k12r2'...
	==> default: Matching MAC address for NAT networking...
	==> default: Checking if box 'win2k12r2' is up to date...
	==> default: There was a problem while downloading the metadata for your box
	==> default: to check for updates. This is not an error, since it is usually due
	==> default: to temporary network problems. This is just a warning. The problem
	==> default: encountered was:
	==> default:
	==> default: The requested URL returned error: 404 Not Found
	==> default:
	==> default: If you want to check for box updates, verify your network connection
	==> default: is valid and try again.
	==> default: Setting the name of the VM: kitchen-redacted-default-win-2k12r2_default_1457106482027_77169
	==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
	==> default: Clearing any previously set network interfaces...
	==> default: Preparing network interfaces based on configuration...
		default: Adapter 1: nat
	==> default: Forwarding ports...
		default: 3389 (guest) => 2200 (host) (adapter 1)
		default: 5985 (guest) => 5985 (host) (adapter 1)
		default: 5986 (guest) => 55986 (host) (adapter 1)
	==> default: Running 'pre-boot' VM customizations...
	==> default: Booting VM...
	==> default: Waiting for machine to boot. This may take a few minutes...
		default: WinRM address: 127.0.0.1:5985
		default: WinRM username: vagrant
		default: WinRM execution_time_limit: PT2H
		default: WinRM transport: plaintext
	STDERR: An error occurred executing a remote WinRM command.

	Shell: powershell
	Command: $ProgressPreference='SilentlyContinue';
	hostname
	if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
	Message: Unable to parse WinRM response: No close tag for /HTML
	Line: 3
	Position: 81
	Last 80 unconsumed characters:
	 (301).
	---- End output of vagrant up --no-provision --provider virtualbox ----
	Ran vagrant up --no-provision --provider virtualbox returned 1
	D      ------Backtrace-------
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/shell_out.rb:73:in `res
	cue in run_command'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/shell_out.rb:61:in `run
	_command'
	D      C:/Program Files (x86)/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.19.0/lib/kitchen/driver
	/vagrant.rb:343:in `run_command'
	D      C:/Program Files (x86)/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.19.0/lib/kitchen/driver
	/vagrant.rb:302:in `run'
	D      C:/Program Files (x86)/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.19.0/lib/kitchen/driver
	/vagrant.rb:373:in `run_vagrant_up'
	D      C:/Program Files (x86)/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.19.0/lib/kitchen/driver
	/vagrant.rb:88:in `create'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:449:in `pub
	lic_send'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:449:in `blo
	ck in perform_action'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:510:in `cal
	l'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:510:in `blo
	ck in synchronize_or_call'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:508:in `syn
	chronize'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:508:in `syn
	chronize_or_call'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:478:in `blo
	ck in action'
	D      C:/Program Files (x86)/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:477:in `act
	ion'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:449:in `per
	form_action'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:359:in `cre
	ate_action'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:348:in `blo
	ck in transition_to'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `eac
	h'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `tra
	nsition_to'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:127:in `cre
	ate'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `publ
	ic_send'
	D      C:/Users/redacted/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `bloc
	k (2 levels) in run_action'
	D      C:/Program Files (x86)/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.0.0/lib/logging/diagnostic_cont
	ext.rb:448:in `call'
	D      C:/Program Files (x86)/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.0.0/lib/logging/diagnostic_cont
	ext.rb:448:in `block in create_with_logging_context'
	D      ----------------------

Thanx for your support

**Comment by smurawski** [comment]
Looks like it is related to how vagrant deals with proxy settings - this may provide some more insight and a possible workaround - https://github.com/mitchellh/vagrant/issues/6273

**Comment by smurawski** [comment]
@BenjiZombie And if that doesn't get you going down the right path, I'd follow up with another issue against the kitchen-vagrant plugin, as that's a more appropriate location. https://github.com/test-kitchen/kitchen-vagrant/issues

Good luck and happy testing!

**Comment by mwrock** [comment]
I was thinking proxy too but the fact that this is a local vm on 127.0.0.1 does not makes that less likely.

Just to eliminate test-kitchen and vagrant noise, try to see if you can reach the box over plain winrm using:
```
knife winrm -m 127.0.0.1 ipconfig -x vagrant -P vagrant -VV
```
Lets see if that actually runs ipconfig.

**Comment by smurawski** [comment]
@mwrock yeah, the vagrant bug actually references that case and suggests making sure no_proxy is configured for 127.0.0.1

**Comment by BenjiZombie** [comment]
Putting no_proxy to 127.0.0.1 solved my issue!

Thanx

**Comment by smurawski** [comment]
Awesome @BenjiZombie!
