### ISSUE TITLE
Deadlock failure when trying to provision Windows guest policyfile_zero provisioner

### ISSUE THREAD

**Issue by emachnic** [test-kitchen/test-kitchen#969]
## Description

When trying to use TK with policyfile_zero provisioner on a Windows 2012 guest, I repeatedly get 
```
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/command.rb:181:in `join': No live threads left. Deadlock? (fatal)
```

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.5.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
$ chef --version 
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0
```

## Platform Version

Mac OS X 10.11.3

## Replication Case

- Install version 0.11.2 of ChefDK and set it as the default Ruby environment
- Set `policyfile_zero` as the provisioner in `.kitchen.yml`
- Grab a base windows server 2012R2 Vagrant box
- Run `kitchen converge` to create the box and try to converge it. This should fail with the previously mentioned error

## Kitchen Output

[Test Kitchen output](https://gist.github.com/emachnic/939c97aa9038768dcd30#file-output-md)

## Kitchen Diagnose

[Kitchen Diagnose](https://gist.github.com/emachnic/939c97aa9038768dcd30#file-kitchen_diagnose-md)

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by mwrock** [comment]
This is a tough one and I have hit it before without really getting to the bottom of things. Maybe someone else will have a better and more definitive answer but I have fund that the best way to get past this error is basically to blow away your user gem store. Of course that means losing non dk gems but they are easy to get back.

Again thats just my rinky dink solution for getting unblocked that has worked for me.

**Comment by emachnic** [comment]
Do you mean gems that are in RVM as well or just in embedded Ruby in DK?
Sent from Outlook Mobile




On Fri, Mar 11, 2016 at 3:59 PM -0800, "Matt Wrock" <notifications@github.com> wrote:












This is a tough one and I have hit it before without really getting to the bottom of things. Maybe someone else will have a better and more definitive answer but I have fund that the best way to get past this error is basically to blow away your user gem store. Of course that means losing non dk gems but they are easy to get back.



Again thats just my rinky dink solution for getting unblocked that has worked for me.

**Comment by mwrock** [comment]
Not the ruby dk. the user one. Not exactly sure where it would be in an RVM controlled environment

**Comment by emachnic** [comment]
Alright, so doing a bit more investigating, I tried using Bundler and installing the chef-dk gem and TK dependencies that way. I'm now able to successfully converge. It looks like this is probably more an issue with ChefDK conflicting with RVM. Going to go ahead and close this but feel free to reopen if it's actually an issue.

**Comment by mwrock** [comment]
yup. bundler is another way to get around this and what I usually use. It just sucks that you cant use plain kitchen in a chefdk environment. Glad you worked around it!
