### ISSUE TITLE
No live threads left. Deadlock? (fatal)

### ISSUE THREAD

**Issue by pmoosh** [test-kitchen/test-kitchen#978]
## Description
Looks this happened before.
After installing chef-DK 0.12.0 I am hitting this:
/Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:181:in `join': No live threads left. Deadlock? (fatal)

## Kitchen Version
```ruby
Test Kitchen version 1.6.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
chef --version
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
# Copy-paste your results here
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Kitchen Output

Used kitchen-dokken as well as kitchen-vagrant with similar results.
```ruby
 kitchen converge  installation-binary-222-ubuntu-1404
-----> Starting Kitchen (v1.6.0)
-----> Converging <installation-binary-222-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.0...
/Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:181:in `join': No live threads left. Deadlock? (fatal)
	from /Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:181:in `map'
	from /Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:181:in `run_action'
	from /Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command/action.rb:39:in `block in call'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
	from /Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command/action.rb:37:in `call'
	from /Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/cli.rb:56:in `perform'
	from /Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/cli.rb:180:in `block (2 levels) in <class:CLI>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/cli.rb:321:in `invoke_task'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/bin/kitchen:13:in `block in <top (required)>'
	from /Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/errors.rb:154:in `with_friendly_errors'
	from /Users/pmoosh/.chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.6.0/bin/kitchen:13:in `<top (required)>'
	from /opt/chefdk/bin/kitchen:15:in `load'
	from /opt/chefdk/bin/kitchen:15:in `<main>'
```

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by mwrock** [comment]
I have encountered this error before and the way I finally worked around it was to delete my user gems so that only the chefdk gems were in use. Using bundler can also work around the issue. This isn't ideal nd it may mean having to reinstall a plugin or two if you had some in your user gems.

**Comment by pmoosh** [comment]
@mwrock - I ended up removing chefdk as per instructions and then I deleted ~/.chefdk. Went back to an older version. Works again. Not sure if the cleanup fixed it or moving back to an older version. When I get to it I will try to figure it out and update the issue.

**Comment by mwrock** [comment]
I'd bet it was the ~/.chefdk cleanup

**Comment by cheeseplus** [comment]
It's almost always the cleanup of the local gems that fixes it

**Comment by cheeseplus** [comment]
Closing this one as this is the fix until further notice.

**Comment by nellshamrell** [comment]
I am also seeing this, and removing my ~/.chefdk did not clear it.  Will try downgrading to an earlier version of ChefDK

**Comment by nellshamrell** [comment]
Ah, I had to kitchen destroy the already converged ubuntu-1204 instance AFTER removing ~/.chefdk.  Now it's working again!

**Comment by nellshamrell** [comment]
Whoops - removing ~/.chefdk and destroying the ubuntu-1204 instance cleared that error on $kitchen create, but I AM still seeing it on $kitchen converge
