### ISSUE TITLE
Windows tests fail with Test Kitchen 1.6

### ISSUE THREAD

**Issue by FreakyDug** [test-kitchen/test-kitchen#987]
## Description

I upgraded to Chefdk 0.12.0 and test-kitchen 1.6 in order to work around https://github.com/test-kitchen/test-kitchen/issues/982. That introduced a problem that appeared to be https://github.com/WinRb/winrm-fs/issues/38 so I upgraded winrm-fs to 0.4.0. Now I get the following error when I try to run windows tests:

```
-----> Converging <py27-lxml-windows-2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.0...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing secret
       Preparing validation.pem
       Preparing client.rb
$$$$$$ The argument 'C:\Users\vagrant\AppData\Local\Temp/kitchen/py27-lxml-windows-2012r2-long_script.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
>>>>>> Converge failed on instance <py27-lxml-windows-2012r2>.
>>>>>> Please see .kitchen/logs/py27-lxml-windows-2012r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [powershell -ExecutionPolicy Bypass -File "$env:TEMP/kitchen/py27-lxml-windows-2012r2-long_script.ps1"]
```

I checked the VM and not only does the referenced ps1 file not exist, the directory that it's supposed to be in (C:\Users\vagrant\AppData\Local\Temp/kitchen) is actually a file containing what appears to be a modified version of this script: https://github.com/test-kitchen/test-kitchen/blob/master/support/chef_base_install_command.ps1

## Kitchen Version

```ruby
Test Kitchen version 1.6.0
```

## ChefDK Version

```ruby
Chef Development Kit Version: 0.12.0
```

## Platform Version

Host OS: Windows 7
Guest OS: Windows Server 2012 R2

**Comment by kamaradclimber** [comment]
I think #981 will solve your issue.

**Comment by FreakyDug** [comment]
That does indeed fix the problem, thanks.

**Comment by ditjhaba** [comment]
Hi,

I seem to have the same issue as raised above. Please note that Test Kitchen was working before I restarted my machine. I am using Mac OSx and running a Windows Server 2012 R2. The only thing that I noticed that had changed was the Berkshelf version that changed to 4.3.0 but I am not sure what impact it has.

The chef spec is as follows:

**Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.0.1
kitchen version: 1.6.0**

These is a grep of all the winrm gems that I have locally:

**winrm (1.7.2)
winrm-fs (0.4.0)
winrm-transport (1.0.3)**

And this is the kitchen logs:

`-----> Starting Kitchen (v1.6.0)
-----> Cleaning up any prior instances of <server-windows-2012r2>
-----> Destroying <server-windows-2012r2>...
       /Users/ditjhaba/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:338: warning: Insecure world writable dir /Users/ditjhaba/Documents/code in PATH, mode 040777
       /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /Users/ditjhaba/Documents/code in PATH, mode 040777
       /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /Users/ditjhaba/Documents/code in PATH, mode 040777
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <server-windows-2012r2> destroyed.
       Finished destroying <server-windows-2012r2> (0m5.87s).
-----> Testing <server-windows-2012r2>
-----> Creating <server-windows-2012r2>...
       /Users/ditjhaba/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:338: warning: Insecure world writable dir /Users/ditjhaba/Documents/code in PATH, mode 040777
       /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /Users/ditjhaba/Documents/code in PATH, mode 040777
       /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /Users/ditjhaba/Documents/code in PATH, mode 040777
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'windows-2012r2'...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: kitchen-dependencies-server-windows-2012r2_default_1459775365293_53994
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 3389 => 3389 (adapter 1)
           default: 5985 => 5985 (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: WinRM address: 127.0.0.1:5985
           default: WinRM username: vagrant
           default: WinRM transport: plaintext
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [WinRM] Established

       Vagrant instance <server-windows-2012r2> created.
       Finished creating <server-windows-2012r2> (1m52.85s).
-----> Converging <server-windows-2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
/Users/ditjhaba/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cpu_counter.rb:28: warning: Insecure world writable dir /Users/ditjhaba/Documents/code in PATH, mode 040777
       Removing non-cookbook files before transfer
       Preparing solo.rb
$$$$$$ The argument 'C:\Users\vagrant\AppData\Local\Temp/kitchen/server-windows-2012r2-long_script.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
>>>>>> Converge failed on instance <server-windows-2012r2>.
>>>>>> Please see .kitchen/logs/server-windows-2012r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [powershell -ExecutionPolicy Bypass -File "$env:TEMP/kitchen/server-windows-2012r2-long_script.ps1"]
>>>>>> ----------------------`
