### ISSUE TITLE
chef_zero: normal attributes removed if removed from .kitchen.yml

### ISSUE THREAD

**Issue by docwhat** [test-kitchen/test-kitchen#988]
## Description

`chef_zero` is persisting normal attributes between runs instead of only using the values in `.kitchen.yml`.
## ChefDK/Kitchen Version

```
$ chef --version
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0
```
## Platform Version

OS X 10.11.4
## Replication Case
1. Download https://github.com/docwhat/tkbug
2. `kitchen converge`
3. `kitchen login` and `cat /node.json` -- notice that `remove_me` is in there.
4. Edit `.kitchen.yml` and remove (or comment out) the line marked `remove_me`.
5. `kitchen converge`
6. `cat /node.json` again and notice that `remove_me` is still there.

I expected that `remove_me` would be gone.  This is because `chef_zero` is persisting its node attributes in `/tmp/kitchen/nodes/default-centos7.json`.  Removing this file and doing another `kitchen converge` will remove the `remove_me`.

I feel that `kitchen converge` should remove the `chef_zero` node data in `/tmp/kitchen/nodes`.

**Comment by cheeseplus** [comment]
While I can see how that would be confusing, that is in fact the behaviour of normal attributes as designed. We could potentially enhance the provisioner to be aware of the removal but that also diverges with default behaviour as mentioned above.

**Comment by docwhat** [comment]
> ...that is in fact the behaviour of normal attributes as designed.

That isn't how `chef_solo` works.  And on my production systems if I `knife node edit` and remove an attribute, it goes away as well.

I understand that's how `chef_zero` works, but if you're using `chef_zero` as a stand-in for a chef-server, it is unexpected.

**Comment by cheeseplus** [comment]
> That isn't how chef_solo works. 

The attribute persistence isn't supposed to work like `chef_solo`, that is a different code path and different set of restrictions that guide implementation detail.

> And on my production systems if I knife node edit and remove an attribute, it goes away as well. 

This is precisely my point - `knife edit` is a willful action (or modifying from the recipe) is how a chef-client would operate in a normal chef-server setup which is what `chef_zero` is emulating.

I'm still open to thinking about it but this is an issue of state and where it should be tracked - the implicit assumption with using `chef_zero`, at least as it was designed, was to emulate a chef server. Ergo that is the interface where node/role/data_bag state would be mutated inside a converged instance between runs.

The reason `chef_solo` is different is that there is no implied need for state tracking between executions as it's just going to use what ends up in dna.json each time.

Now I can see how removing an attribute from `.kitchen.yml` can just as sensibly be construed as a desire to remove said attribute. That said there isn't a direct mapping of semantics: with a normal chef-server one doesn't remove attributes by not specifying them but by directly removing them via recipe or administrative (knife) action.

**Comment by docwhat** [comment]
I have to admit that I equated editing `.kitchen.yml` with `knife node edit`. 

Losing the rest of the state would be bad if anyone depended on it (like counting converges or something). Can the normal attributes be overwritten or something?

It's funny I keep getting bitten by this; I filed a bug with the chef-server because it had this bug inside it. Its reconfigure mechanism use chef zero as well and I couldn't unset and attribute from the config files.

**Comment by cheeseplus** [comment]
I totally feel the pain myself as well but I'm not entirely sure what the _correct_ solution is either

**Comment by docwhat** [comment]
How about either `.kitchen.yml` option or a `kitchen converge` command line flag to reset the node attributes?

Or both. 

It's not perfect but it's better than remembering where the node JSON file is located. 

Another option would be to track the attributes set by the `.kitchen.yml` file to "unset" them. 

Dunno. Too bad there isn't a way to feed the default attributes into chef zero like `knife node edit` does for a real server.

**Comment by docwhat** [comment]
According to https://docs.chef.io/knife_node.html `knife node edit` only shows `normal` attributes by default. 

That makes me feel like replacing `/tmp/kitchen/nodes/fubar.json`'s `normal` attributes with `.kitchen.yml`s isn't as bad as an idea.

**Comment by alexderz** [comment]
Sounds like tracking the source of a variable would be a can a of worms. If a variable is set on .kitchen.yml and a recipe also later sets it, or changes it, which should be the true one? Maybe exporting the node data into the .kitchen directory so that there can be an equivalent 'willful' action of removal?

**Comment by docwhat** [comment]
With the idea editing the file in `.kitchen` acting like the `knife node edit`? I think I like that.

**Comment by isuftin** [comment]
Got caught by this today in my kitchen testing. Spent a ton of time tracking down whether it was me doing something wrong, a community cookbook or what.

 A flag for kitchen converge runs that would replace `/tmp/kitchen/nodes/<nodename>.json` would be pretty sweet

**Comment by mconigliaro** [comment]
Ah, so this is why when I delete attributes from `.kitchen.yml`, the node keeps using the old values. I didn't realize the point was to try to mimic "normal" attribute behavior. I've just been using `.kitchen.yml` as an obvious place to test attribute changes in my cookbooks. I imagine a lot of people are doing something similar.

**Comment by docwhat** [comment]
Does version 1.8's [Policyfile support](https://discourse.chef.io/t/released-test-kitchen-1-8-0/8421) have the same issue? Or is 1.8 an alternative solution?

**Comment by mwrock** [comment]
Not sure I follow @docwhat. The policyfile support does not impact attribute resolution.

**Comment by docwhat** [comment]
I haven't used Policyfiles yet. I thought they had attributes.

**Comment by mwrock** [comment]
Oh I see. Yeah the documentation says `The policy_name and policy_group settings for a node are stored as searchable attributes`. The 1.8 behavior replaces what was used in the `policyfile_zero` provisioner. I'm not sure how the behavior is nuanced in regards to this issue.

**Comment by spuder** [comment]
I too just ran into this in test kitchen. 

Interestingly I tried to reproduce it using chef-zero, and I found I could not reproduce it

Append "foo": "bar" to `chef-repo/environments/dev.json`

    chef-client -z -r 'role[web]' -E dev -c c:\client.rb

My recipe adds 'foo:bar' to my template. 
When I remove 'foo:bar' from my environment file, and run chef again, the template is regenerated without that config file. 

From my observation, I'm guessing normal attributes are persisting across converges with test kitchen, but not persisting with pure chef-zero. 

If thats the case, then wouldn't creating a new chef-zero instance clear out any normal attributes? 
The desired behavior could possibly be achieved with a flag

      kitchen converge -new

**Comment by mattlqx** [comment]
I ran into this today with the chef-solo provisioner and was about to open an issue for it. I agree with prior posts that a flag to wipe/regenerate the node JSON would help surface this as normal behavior and give an easy workaround.

**Comment by ls-brentsmith** [comment]
One work around, when I'm sure I don't need to persist any node data (and i don't care what my node name is) is to generate a new node name for each run.

ex: timestamp

```
provisioner:
  name: chef_zero
  client_rb:
    node_name: "<%= Time.now.to_i %>"
```

Every time I converge it creates a new node.

a flag for test-kitchen to clear the node would be a better solution, imo.

**Comment by robbkidd** [comment]
> node_name: "<%= Time.now.to_i %>"

They're good hacks, Brent.

![i'm not even mad](https://user-images.githubusercontent.com/517302/37228963-7c1dcfec-23b0-11e8-9c39-3f5e57842941.gif)

Thanks to @docwhat's excellent repro repo, we've determined that is it indeed because `chef-client -z` is reading in the JSON of the persisted node object from `/tmp/kitchen/nodes/[suite]_[platform].json`.

Deleting that JSON file and then converging got the expected attributes.

```
       Recipe: tkbug::default
         * file[/node.json] action create
           - update content in file /node.json from b48495 to b32f32
           --- /node.json	2018-03-09 20:31:31.451211500 +0000
           +++ /.chef-node20180309-12346-goxzr7.json	2018-03-09 20:37:43.503144500 +0000
           @@ -1,2 +1,2 @@
           -{"kitchen":true,"remove_me":123}
           +{"kitchen":true}
```

So, mmmmmaybe the `chef_zero` and `chef_solo` provisioners could use a config option `nuke_the_node` that would clear `/tmp/kitchen/nodes` out prior to the chef-client run in converge?

**Comment by lamont-granquist** [comment]
For chef-zero runs the state should probably be eliminated between runs -- by default, all of the time.  Really we need an efficient mode of operation where chef-zero reads the data from disk, operates on it in-memory and then never writes the data out again in order to speed up operation.
