### ISSUE TITLE
Kitchen Converge Fails

### ISSUE THREAD

**Issue by ditjhaba** [test-kitchen/test-kitchen#994]
Hi,

I seem to have the same issue as #987 . Please note that Test Kitchen was working before I restarted my machine. I am using Mac OSx and running a Windows Server 2012 R2. The only thing that I noticed that had changed was the Berkshelf version that changed to 4.3.0 but I am not sure what impact it has.

The chef spec is as follows:

**Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.0.1
kitchen version: 1.6.0**

These is a grep of all the winrm gems that I have locally:

**winrm (1.7.2)
winrm-fs (0.4.0)
winrm-transport (1.0.3)**

And this is the kitchen logs:

`
-----> Converging <server-windows-2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing solo.rb
$$$$$$ The argument 'C:\Users\vagrant\AppData\Local\Temp/kitchen/server-windows-2012r2-long_script.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
>>>>>> Converge failed on instance <server-windows-2012r2>.
>>>>>> Please see .kitchen/logs/server-windows-2012r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [powershell -ExecutionPolicy Bypass -File "$env:TEMP/kitchen/server-windows-2012r2-long_script.ps1"]
>>>>>> ----------------------`

**Comment by mwrock** [comment]
You need to either downgrade winrm-fs to 0.3.2 or upgrade Test-kitchen to 1.7.1. See https://discourse.chef.io/t/updating-to-test-kitchen-1-6-0-in-a-chefdk-0-11-2-or-lesser/7899 for instructions on how to upgrade test-kitchen in your current chefdk.

**Comment by cheeseplus** [comment]
Closing as answered.
